# ruff: noqa: N802
from __future__ import annotations

import enum
import typing

import fltk.fegen.pyrt.terminalsrc

if typing.TYPE_CHECKING:
    import fltk.fegen.pyrt.span_protocol
__all__ = [
    "AnchoredWord",
    "Arrow",
    "Atom",
    "CaseInsensitive",
    "Colour",
    "CstModule",
    "DecimalVal",
    "DigitSeq",
    "EscapedMetas",
    "ExactlyTwoDigits",
    "Expr",
    "Grouped",
    "Items",
    "KwLabels",
    "LatinRange",
    "LatinWord",
    "LeadingWs",
    "Lval",
    "MixedOpt",
    "Name",
    "NcGroupAlt",
    "Nest",
    "NestSum",
    "NodeKind",
    "Num",
    "OptItem",
    "OptWrapper",
    "Pair",
    "ParenExpr",
    "Quoted",
    "RecViaSub",
    "RepWrapper",
    "Rval",
    "Span",
    "Stmt",
    "SumChain",
    "Tagged",
    "ThreeToFiveDigits",
    "Trivia",
    "UuidVal",
    "Val",
    "WordSeq",
    "Wrapper",
    "WsSeq",
    "ZeroItems",
]


class NodeKind(enum.Enum):
    NUM = enum.auto()
    NAME = enum.auto()
    ATOM = enum.auto()
    PARENEXPR = enum.auto()
    STMT = enum.auto()
    ITEMS = enum.auto()
    OPTITEM = enum.auto()
    ZEROITEMS = enum.auto()
    EXPR = enum.auto()
    LVAL = enum.auto()
    RVAL = enum.auto()
    ARROW = enum.auto()
    LATINWORD = enum.auto()
    TAGGED = enum.auto()
    VAL = enum.auto()
    LEADINGWS = enum.auto()
    GROUPED = enum.auto()
    RECVIASUB = enum.auto()
    NEST = enum.auto()
    NESTSUM = enum.auto()
    DIGITSEQ = enum.auto()
    WORDSEQ = enum.auto()
    WSSEQ = enum.auto()
    THREETOFIVEDIGITS = enum.auto()
    EXACTLYTWODIGITS = enum.auto()
    ESCAPEDMETAS = enum.auto()
    LATINRANGE = enum.auto()
    NCGROUPALT = enum.auto()
    CASEINSENSITIVE = enum.auto()
    ANCHOREDWORD = enum.auto()
    PAIR = enum.auto()
    WRAPPER = enum.auto()
    OPTWRAPPER = enum.auto()
    REPWRAPPER = enum.auto()
    KWLABELS = enum.auto()
    QUOTED = enum.auto()
    MIXEDOPT = enum.auto()
    UUIDVAL = enum.auto()
    DECIMALVAL = enum.auto()
    COLOUR = enum.auto()
    SUMCHAIN = enum.auto()
    TRIVIA = enum.auto()
    _fltk_canonical_name: str

    def __eq__(self, other: object) -> bool:
        if other is self:
            return True
        if type(other) is type(self):
            return self.name == other.name
        cn = getattr(other, "_fltk_canonical_name", None)
        if cn is not None:
            return self._fltk_canonical_name == cn
        return NotImplemented

    def __hash__(self) -> int:
        return hash(self._fltk_canonical_name)


NodeKind.NUM._fltk_canonical_name = "NodeKind.NUM"
NodeKind.NAME._fltk_canonical_name = "NodeKind.NAME"
NodeKind.ATOM._fltk_canonical_name = "NodeKind.ATOM"
NodeKind.PARENEXPR._fltk_canonical_name = "NodeKind.PARENEXPR"
NodeKind.STMT._fltk_canonical_name = "NodeKind.STMT"
NodeKind.ITEMS._fltk_canonical_name = "NodeKind.ITEMS"
NodeKind.OPTITEM._fltk_canonical_name = "NodeKind.OPTITEM"
NodeKind.ZEROITEMS._fltk_canonical_name = "NodeKind.ZEROITEMS"
NodeKind.EXPR._fltk_canonical_name = "NodeKind.EXPR"
NodeKind.LVAL._fltk_canonical_name = "NodeKind.LVAL"
NodeKind.RVAL._fltk_canonical_name = "NodeKind.RVAL"
NodeKind.ARROW._fltk_canonical_name = "NodeKind.ARROW"
NodeKind.LATINWORD._fltk_canonical_name = "NodeKind.LATINWORD"
NodeKind.TAGGED._fltk_canonical_name = "NodeKind.TAGGED"
NodeKind.VAL._fltk_canonical_name = "NodeKind.VAL"
NodeKind.LEADINGWS._fltk_canonical_name = "NodeKind.LEADINGWS"
NodeKind.GROUPED._fltk_canonical_name = "NodeKind.GROUPED"
NodeKind.RECVIASUB._fltk_canonical_name = "NodeKind.RECVIASUB"
NodeKind.NEST._fltk_canonical_name = "NodeKind.NEST"
NodeKind.NESTSUM._fltk_canonical_name = "NodeKind.NESTSUM"
NodeKind.DIGITSEQ._fltk_canonical_name = "NodeKind.DIGITSEQ"
NodeKind.WORDSEQ._fltk_canonical_name = "NodeKind.WORDSEQ"
NodeKind.WSSEQ._fltk_canonical_name = "NodeKind.WSSEQ"
NodeKind.THREETOFIVEDIGITS._fltk_canonical_name = "NodeKind.THREETOFIVEDIGITS"
NodeKind.EXACTLYTWODIGITS._fltk_canonical_name = "NodeKind.EXACTLYTWODIGITS"
NodeKind.ESCAPEDMETAS._fltk_canonical_name = "NodeKind.ESCAPEDMETAS"
NodeKind.LATINRANGE._fltk_canonical_name = "NodeKind.LATINRANGE"
NodeKind.NCGROUPALT._fltk_canonical_name = "NodeKind.NCGROUPALT"
NodeKind.CASEINSENSITIVE._fltk_canonical_name = "NodeKind.CASEINSENSITIVE"
NodeKind.ANCHOREDWORD._fltk_canonical_name = "NodeKind.ANCHOREDWORD"
NodeKind.PAIR._fltk_canonical_name = "NodeKind.PAIR"
NodeKind.WRAPPER._fltk_canonical_name = "NodeKind.WRAPPER"
NodeKind.OPTWRAPPER._fltk_canonical_name = "NodeKind.OPTWRAPPER"
NodeKind.REPWRAPPER._fltk_canonical_name = "NodeKind.REPWRAPPER"
NodeKind.KWLABELS._fltk_canonical_name = "NodeKind.KWLABELS"
NodeKind.QUOTED._fltk_canonical_name = "NodeKind.QUOTED"
NodeKind.MIXEDOPT._fltk_canonical_name = "NodeKind.MIXEDOPT"
NodeKind.UUIDVAL._fltk_canonical_name = "NodeKind.UUIDVAL"
NodeKind.DECIMALVAL._fltk_canonical_name = "NodeKind.DECIMALVAL"
NodeKind.COLOUR._fltk_canonical_name = "NodeKind.COLOUR"
NodeKind.SUMCHAIN._fltk_canonical_name = "NodeKind.SUMCHAIN"
NodeKind.TRIVIA._fltk_canonical_name = "NodeKind.TRIVIA"


class _ProtocolLabelMember:
    _fltk_canonical_name: str

    def __init__(self, canonical_name: str) -> None:
        self._fltk_canonical_name = canonical_name

    def __eq__(self, other: object) -> bool:
        if other is self:
            return True
        if type(other) is type(self):
            return self._fltk_canonical_name == other._fltk_canonical_name
        cn = getattr(other, "_fltk_canonical_name", None)
        if cn is not None:
            return self._fltk_canonical_name == cn
        return NotImplemented

    def __hash__(self) -> int:
        return hash(self._fltk_canonical_name)

    def __repr__(self) -> str:
        return f"_ProtocolLabelMember({self._fltk_canonical_name!r})"


class Num(typing.Protocol):
    class Label:
        VALUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.NUM] = NodeKind.NUM
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: Num) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def value_text(self) -> str: ...

    def text(self) -> str: ...


Num.Label.VALUE = _ProtocolLabelMember("Num.Label.VALUE")


class Name(typing.Protocol):
    class Label:
        VALUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.NAME] = NodeKind.NAME
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: Name) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def value_text(self) -> str: ...

    def text(self) -> str: ...


Name.Label.VALUE = _ProtocolLabelMember("Name.Label.VALUE")


class Atom(typing.Protocol):
    class Label:
        NAME: typing.ClassVar[object]
        NUM: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.ATOM] = NodeKind.ATOM
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Name | Num]]

    def append(self, child: Name | Num, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Name | Num], label: Label | None = None) -> None: ...

    def extend_children(self, other: Atom) -> None: ...

    def child(self) -> tuple[Label | None, Name | Num]: ...

    def insert(self, index: int, child: Name | Num, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Name | Num]: ...

    def replace_at(self, index: int, child: Name | Num, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_name(self, child: Name) -> None: ...

    def extend_name(self, children: typing.Iterable[Name]) -> None: ...

    def children_name(self) -> typing.Iterator[Name]: ...

    def child_name(self) -> Name: ...

    def maybe_name(self) -> Name | None: ...

    def append_num(self, child: Num) -> None: ...

    def extend_num(self, children: typing.Iterable[Num]) -> None: ...

    def children_num(self) -> typing.Iterator[Num]: ...

    def child_num(self) -> Num: ...

    def maybe_num(self) -> Num | None: ...

    def name(self) -> Name | None: ...

    def num(self) -> Num | None: ...

    def variant(self) -> Label: ...


Atom.Label.NAME = _ProtocolLabelMember("Atom.Label.NAME")
Atom.Label.NUM = _ProtocolLabelMember("Atom.Label.NUM")


class ParenExpr(typing.Protocol):
    class Label:
        INNER: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.PARENEXPR] = NodeKind.PARENEXPR
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Atom | Trivia]]

    def append(self, child: Atom | Trivia, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Atom | Trivia], label: Label | None = None) -> None: ...

    def extend_children(self, other: ParenExpr) -> None: ...

    def child(self) -> tuple[Label | None, Atom | Trivia]: ...

    def insert(self, index: int, child: Atom | Trivia, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Atom | Trivia]: ...

    def replace_at(self, index: int, child: Atom | Trivia, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_inner(self, child: Atom) -> None: ...

    def extend_inner(self, children: typing.Iterable[Atom]) -> None: ...

    def children_inner(self) -> typing.Iterator[Atom]: ...

    def child_inner(self) -> Atom: ...

    def maybe_inner(self) -> Atom | None: ...

    def inner(self) -> Atom: ...


ParenExpr.Label.INNER = _ProtocolLabelMember("ParenExpr.Label.INNER")


class Stmt(typing.Protocol):
    class Label:
        LHS: typing.ClassVar[object]
        RHS: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.STMT] = NodeKind.STMT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Atom | Trivia]]

    def append(self, child: Atom | Trivia, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Atom | Trivia], label: Label | None = None) -> None: ...

    def extend_children(self, other: Stmt) -> None: ...

    def child(self) -> tuple[Label | None, Atom | Trivia]: ...

    def insert(self, index: int, child: Atom | Trivia, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Atom | Trivia]: ...

    def replace_at(self, index: int, child: Atom | Trivia, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_lhs(self, child: Atom) -> None: ...

    def extend_lhs(self, children: typing.Iterable[Atom]) -> None: ...

    def children_lhs(self) -> typing.Iterator[Atom]: ...

    def child_lhs(self) -> Atom: ...

    def maybe_lhs(self) -> Atom | None: ...

    def append_rhs(self, child: Atom) -> None: ...

    def extend_rhs(self, children: typing.Iterable[Atom]) -> None: ...

    def children_rhs(self) -> typing.Iterator[Atom]: ...

    def child_rhs(self) -> Atom: ...

    def maybe_rhs(self) -> Atom | None: ...

    def lhs(self) -> Atom: ...

    def rhs(self) -> Atom: ...


Stmt.Label.LHS = _ProtocolLabelMember("Stmt.Label.LHS")
Stmt.Label.RHS = _ProtocolLabelMember("Stmt.Label.RHS")


class Items(typing.Protocol):
    class Label:
        ITEM: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.ITEMS] = NodeKind.ITEMS
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Atom]]

    def append(self, child: Atom, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Atom], label: Label | None = None) -> None: ...

    def extend_children(self, other: Items) -> None: ...

    def child(self) -> tuple[Label | None, Atom]: ...

    def insert(self, index: int, child: Atom, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Atom]: ...

    def replace_at(self, index: int, child: Atom, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_item(self, child: Atom) -> None: ...

    def extend_item(self, children: typing.Iterable[Atom]) -> None: ...

    def children_item(self) -> typing.Iterator[Atom]: ...

    def child_item(self) -> Atom: ...

    def maybe_item(self) -> Atom | None: ...

    def item(self) -> list[Atom]: ...


Items.Label.ITEM = _ProtocolLabelMember("Items.Label.ITEM")


class OptItem(typing.Protocol):
    class Label:
        ITEM: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.OPTITEM] = NodeKind.OPTITEM
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Atom]]

    def append(self, child: Atom, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Atom], label: Label | None = None) -> None: ...

    def extend_children(self, other: OptItem) -> None: ...

    def child(self) -> tuple[Label | None, Atom]: ...

    def insert(self, index: int, child: Atom, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Atom]: ...

    def replace_at(self, index: int, child: Atom, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_item(self, child: Atom) -> None: ...

    def extend_item(self, children: typing.Iterable[Atom]) -> None: ...

    def children_item(self) -> typing.Iterator[Atom]: ...

    def child_item(self) -> Atom: ...

    def maybe_item(self) -> Atom | None: ...

    def item(self) -> Atom | None: ...


OptItem.Label.ITEM = _ProtocolLabelMember("OptItem.Label.ITEM")


class ZeroItems(typing.Protocol):
    class Label:
        ITEM: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.ZEROITEMS] = NodeKind.ZEROITEMS
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Atom]]

    def append(self, child: Atom, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Atom], label: Label | None = None) -> None: ...

    def extend_children(self, other: ZeroItems) -> None: ...

    def child(self) -> tuple[Label | None, Atom]: ...

    def insert(self, index: int, child: Atom, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Atom]: ...

    def replace_at(self, index: int, child: Atom, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_item(self, child: Atom) -> None: ...

    def extend_item(self, children: typing.Iterable[Atom]) -> None: ...

    def children_item(self) -> typing.Iterator[Atom]: ...

    def child_item(self) -> Atom: ...

    def maybe_item(self) -> Atom | None: ...

    def item(self) -> list[Atom]: ...


ZeroItems.Label.ITEM = _ProtocolLabelMember("ZeroItems.Label.ITEM")


class Expr(typing.Protocol):
    class Label:
        ATOM: typing.ClassVar[object]
        LHS: typing.ClassVar[object]
        RHS: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.EXPR] = NodeKind.EXPR
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Atom | Expr]]

    def append(self, child: Atom | Expr, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Atom | Expr], label: Label | None = None) -> None: ...

    def extend_children(self, other: Expr) -> None: ...

    def child(self) -> tuple[Label | None, Atom | Expr]: ...

    def insert(self, index: int, child: Atom | Expr, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Atom | Expr]: ...

    def replace_at(self, index: int, child: Atom | Expr, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_atom(self, child: Atom) -> None: ...

    def extend_atom(self, children: typing.Iterable[Atom]) -> None: ...

    def children_atom(self) -> typing.Iterator[Atom]: ...

    def child_atom(self) -> Atom: ...

    def maybe_atom(self) -> Atom | None: ...

    def append_lhs(self, child: Expr) -> None: ...

    def extend_lhs(self, children: typing.Iterable[Expr]) -> None: ...

    def children_lhs(self) -> typing.Iterator[Expr]: ...

    def child_lhs(self) -> Expr: ...

    def maybe_lhs(self) -> Expr | None: ...

    def append_rhs(self, child: Atom) -> None: ...

    def extend_rhs(self, children: typing.Iterable[Atom]) -> None: ...

    def children_rhs(self) -> typing.Iterator[Atom]: ...

    def child_rhs(self) -> Atom: ...

    def maybe_rhs(self) -> Atom | None: ...

    def atom(self) -> Atom | None: ...

    def lhs(self) -> Expr | None: ...

    def rhs(self) -> Atom | None: ...


Expr.Label.ATOM = _ProtocolLabelMember("Expr.Label.ATOM")
Expr.Label.LHS = _ProtocolLabelMember("Expr.Label.LHS")
Expr.Label.RHS = _ProtocolLabelMember("Expr.Label.RHS")


class Lval(typing.Protocol):
    class Label:
        BASE: typing.ClassVar[object]
        INNER: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.LVAL] = NodeKind.LVAL
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Name | Rval]]

    def append(self, child: Name | Rval, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Name | Rval], label: Label | None = None) -> None: ...

    def extend_children(self, other: Lval) -> None: ...

    def child(self) -> tuple[Label | None, Name | Rval]: ...

    def insert(self, index: int, child: Name | Rval, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Name | Rval]: ...

    def replace_at(self, index: int, child: Name | Rval, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_base(self, child: Name) -> None: ...

    def extend_base(self, children: typing.Iterable[Name]) -> None: ...

    def children_base(self) -> typing.Iterator[Name]: ...

    def child_base(self) -> Name: ...

    def maybe_base(self) -> Name | None: ...

    def append_inner(self, child: Rval) -> None: ...

    def extend_inner(self, children: typing.Iterable[Rval]) -> None: ...

    def children_inner(self) -> typing.Iterator[Rval]: ...

    def child_inner(self) -> Rval: ...

    def maybe_inner(self) -> Rval | None: ...

    def base(self) -> Name | None: ...

    def inner(self) -> Rval | None: ...


Lval.Label.BASE = _ProtocolLabelMember("Lval.Label.BASE")
Lval.Label.INNER = _ProtocolLabelMember("Lval.Label.INNER")


class Rval(typing.Protocol):
    class Label:
        BASE: typing.ClassVar[object]
        INNER: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.RVAL] = NodeKind.RVAL
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Lval | Num]]

    def append(self, child: Lval | Num, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Lval | Num], label: Label | None = None) -> None: ...

    def extend_children(self, other: Rval) -> None: ...

    def child(self) -> tuple[Label | None, Lval | Num]: ...

    def insert(self, index: int, child: Lval | Num, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Lval | Num]: ...

    def replace_at(self, index: int, child: Lval | Num, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_base(self, child: Num) -> None: ...

    def extend_base(self, children: typing.Iterable[Num]) -> None: ...

    def children_base(self) -> typing.Iterator[Num]: ...

    def child_base(self) -> Num: ...

    def maybe_base(self) -> Num | None: ...

    def append_inner(self, child: Lval) -> None: ...

    def extend_inner(self, children: typing.Iterable[Lval]) -> None: ...

    def children_inner(self) -> typing.Iterator[Lval]: ...

    def child_inner(self) -> Lval: ...

    def maybe_inner(self) -> Lval | None: ...

    def base(self) -> Num | None: ...

    def inner(self) -> Lval | None: ...


Rval.Label.BASE = _ProtocolLabelMember("Rval.Label.BASE")
Rval.Label.INNER = _ProtocolLabelMember("Rval.Label.INNER")


class Arrow(typing.Protocol):
    class Label:
        TARGET: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.ARROW] = NodeKind.ARROW
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Name]]

    def append(self, child: Name, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Name], label: Label | None = None) -> None: ...

    def extend_children(self, other: Arrow) -> None: ...

    def child(self) -> tuple[Label | None, Name]: ...

    def insert(self, index: int, child: Name, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Name]: ...

    def replace_at(self, index: int, child: Name, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_target(self, child: Name) -> None: ...

    def extend_target(self, children: typing.Iterable[Name]) -> None: ...

    def children_target(self) -> typing.Iterator[Name]: ...

    def child_target(self) -> Name: ...

    def maybe_target(self) -> Name | None: ...

    def target(self) -> Name: ...


Arrow.Label.TARGET = _ProtocolLabelMember("Arrow.Label.TARGET")


class LatinWord(typing.Protocol):
    class Label:
        VALUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.LATINWORD] = NodeKind.LATINWORD
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: LatinWord) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def value_text(self) -> str: ...

    def text(self) -> str: ...


LatinWord.Label.VALUE = _ProtocolLabelMember("LatinWord.Label.VALUE")


class Tagged(typing.Protocol):
    class Label:
        VALUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.TAGGED] = NodeKind.TAGGED
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: Tagged) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def value_text(self) -> str: ...

    def text(self) -> str: ...


Tagged.Label.VALUE = _ProtocolLabelMember("Tagged.Label.VALUE")


class Val(typing.Protocol):
    class Label:
        ITEM: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.VAL] = NodeKind.VAL
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Name | Num | fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(
        self, child: Name | Num | fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def extend(
        self,
        children: typing.Iterable[Name | Num | fltk.fegen.pyrt.span_protocol.SpanProtocol],
        label: Label | None = None,
    ) -> None: ...

    def extend_children(self, other: Val) -> None: ...

    def child(self) -> tuple[Label | None, Name | Num | fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: Name | Num | fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Name | Num | fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: Name | Num | fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_item(self, child: Name | Num | fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_item(
        self, children: typing.Iterable[Name | Num | fltk.fegen.pyrt.span_protocol.SpanProtocol]
    ) -> None: ...

    def children_item(self) -> typing.Iterator[Name | Num | fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_item(self) -> Name | Num | fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_item(self) -> Name | Num | fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def item(self) -> Name | Num | fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def variant(self) -> Label: ...


Val.Label.ITEM = _ProtocolLabelMember("Val.Label.ITEM")


class LeadingWs(typing.Protocol):
    class Label:
        NUM: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.LEADINGWS] = NodeKind.LEADINGWS
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Num | Trivia]]

    def append(self, child: Num | Trivia, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Num | Trivia], label: Label | None = None) -> None: ...

    def extend_children(self, other: LeadingWs) -> None: ...

    def child(self) -> tuple[Label | None, Num | Trivia]: ...

    def insert(self, index: int, child: Num | Trivia, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Num | Trivia]: ...

    def replace_at(self, index: int, child: Num | Trivia, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_num(self, child: Num) -> None: ...

    def extend_num(self, children: typing.Iterable[Num]) -> None: ...

    def children_num(self) -> typing.Iterator[Num]: ...

    def child_num(self) -> Num: ...

    def maybe_num(self) -> Num | None: ...

    def num(self) -> Num: ...


LeadingWs.Label.NUM = _ProtocolLabelMember("LeadingWs.Label.NUM")


class Grouped(typing.Protocol):
    class Label:
        LEFT: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.GROUPED] = NodeKind.GROUPED
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Name | Num | Trivia]]

    def append(self, child: Name | Num | Trivia, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Name | Num | Trivia], label: Label | None = None) -> None: ...

    def extend_children(self, other: Grouped) -> None: ...

    def child(self) -> tuple[Label | None, Name | Num | Trivia]: ...

    def insert(self, index: int, child: Name | Num | Trivia, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Name | Num | Trivia]: ...

    def replace_at(self, index: int, child: Name | Num | Trivia, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_left(self, child: Name | Num) -> None: ...

    def extend_left(self, children: typing.Iterable[Name | Num]) -> None: ...

    def children_left(self) -> typing.Iterator[Name | Num]: ...

    def child_left(self) -> Name | Num: ...

    def maybe_left(self) -> Name | Num | None: ...

    def left(self) -> Name | Num: ...


Grouped.Label.LEFT = _ProtocolLabelMember("Grouped.Label.LEFT")


class RecViaSub(typing.Protocol):
    class Label:
        INNER: typing.ClassVar[object]
        SUFFIX: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.RECVIASUB] = NodeKind.RECVIASUB
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Atom | Name | RecViaSub]]

    def append(self, child: Atom | Name | RecViaSub, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Atom | Name | RecViaSub], label: Label | None = None) -> None: ...

    def extend_children(self, other: RecViaSub) -> None: ...

    def child(self) -> tuple[Label | None, Atom | Name | RecViaSub]: ...

    def insert(self, index: int, child: Atom | Name | RecViaSub, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Atom | Name | RecViaSub]: ...

    def replace_at(self, index: int, child: Atom | Name | RecViaSub, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_inner(self, child: Atom | RecViaSub) -> None: ...

    def extend_inner(self, children: typing.Iterable[Atom | RecViaSub]) -> None: ...

    def children_inner(self) -> typing.Iterator[Atom | RecViaSub]: ...

    def child_inner(self) -> Atom | RecViaSub: ...

    def maybe_inner(self) -> Atom | RecViaSub | None: ...

    def append_suffix(self, child: Name) -> None: ...

    def extend_suffix(self, children: typing.Iterable[Name]) -> None: ...

    def children_suffix(self) -> typing.Iterator[Name]: ...

    def child_suffix(self) -> Name: ...

    def maybe_suffix(self) -> Name | None: ...

    def inner(self) -> Atom | RecViaSub: ...

    def suffix(self) -> Name: ...


RecViaSub.Label.INNER = _ProtocolLabelMember("RecViaSub.Label.INNER")
RecViaSub.Label.SUFFIX = _ProtocolLabelMember("RecViaSub.Label.SUFFIX")


class Nest(typing.Protocol):
    class Label:
        INNER: typing.ClassVar[object]
        LEAF: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.NEST] = NodeKind.NEST
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Nest | Num]]

    def append(self, child: Nest | Num, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Nest | Num], label: Label | None = None) -> None: ...

    def extend_children(self, other: Nest) -> None: ...

    def child(self) -> tuple[Label | None, Nest | Num]: ...

    def insert(self, index: int, child: Nest | Num, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Nest | Num]: ...

    def replace_at(self, index: int, child: Nest | Num, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_inner(self, child: Nest) -> None: ...

    def extend_inner(self, children: typing.Iterable[Nest]) -> None: ...

    def children_inner(self) -> typing.Iterator[Nest]: ...

    def child_inner(self) -> Nest: ...

    def maybe_inner(self) -> Nest | None: ...

    def append_leaf(self, child: Num) -> None: ...

    def extend_leaf(self, children: typing.Iterable[Num]) -> None: ...

    def children_leaf(self) -> typing.Iterator[Num]: ...

    def child_leaf(self) -> Num: ...

    def maybe_leaf(self) -> Num | None: ...

    def inner(self) -> Nest | None: ...

    def leaf(self) -> Num | None: ...


Nest.Label.INNER = _ProtocolLabelMember("Nest.Label.INNER")
Nest.Label.LEAF = _ProtocolLabelMember("Nest.Label.LEAF")


class NestSum(typing.Protocol):
    class Label:
        FIRST: typing.ClassVar[object]
        LHS: typing.ClassVar[object]
        RHS: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.NESTSUM] = NodeKind.NESTSUM
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Nest | NestSum]]

    def append(self, child: Nest | NestSum, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Nest | NestSum], label: Label | None = None) -> None: ...

    def extend_children(self, other: NestSum) -> None: ...

    def child(self) -> tuple[Label | None, Nest | NestSum]: ...

    def insert(self, index: int, child: Nest | NestSum, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Nest | NestSum]: ...

    def replace_at(self, index: int, child: Nest | NestSum, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_first(self, child: Nest) -> None: ...

    def extend_first(self, children: typing.Iterable[Nest]) -> None: ...

    def children_first(self) -> typing.Iterator[Nest]: ...

    def child_first(self) -> Nest: ...

    def maybe_first(self) -> Nest | None: ...

    def append_lhs(self, child: NestSum) -> None: ...

    def extend_lhs(self, children: typing.Iterable[NestSum]) -> None: ...

    def children_lhs(self) -> typing.Iterator[NestSum]: ...

    def child_lhs(self) -> NestSum: ...

    def maybe_lhs(self) -> NestSum | None: ...

    def append_rhs(self, child: Nest) -> None: ...

    def extend_rhs(self, children: typing.Iterable[Nest]) -> None: ...

    def children_rhs(self) -> typing.Iterator[Nest]: ...

    def child_rhs(self) -> Nest: ...

    def maybe_rhs(self) -> Nest | None: ...

    def first(self) -> Nest | None: ...

    def lhs(self) -> NestSum | None: ...

    def rhs(self) -> Nest | None: ...


NestSum.Label.FIRST = _ProtocolLabelMember("NestSum.Label.FIRST")
NestSum.Label.LHS = _ProtocolLabelMember("NestSum.Label.LHS")
NestSum.Label.RHS = _ProtocolLabelMember("NestSum.Label.RHS")


class DigitSeq(typing.Protocol):
    class Label:
        VALUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.DIGITSEQ] = NodeKind.DIGITSEQ
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: DigitSeq) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def value_text(self) -> str: ...

    def text(self) -> str: ...


DigitSeq.Label.VALUE = _ProtocolLabelMember("DigitSeq.Label.VALUE")


class WordSeq(typing.Protocol):
    class Label:
        VALUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.WORDSEQ] = NodeKind.WORDSEQ
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: WordSeq) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def value_text(self) -> str: ...

    def text(self) -> str: ...


WordSeq.Label.VALUE = _ProtocolLabelMember("WordSeq.Label.VALUE")


class WsSeq(typing.Protocol):
    class Label:
        VALUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.WSSEQ] = NodeKind.WSSEQ
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: WsSeq) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def value_text(self) -> str: ...

    def text(self) -> str: ...


WsSeq.Label.VALUE = _ProtocolLabelMember("WsSeq.Label.VALUE")


class ThreeToFiveDigits(typing.Protocol):
    class Label:
        VALUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.THREETOFIVEDIGITS] = NodeKind.THREETOFIVEDIGITS
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: ThreeToFiveDigits) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def value_text(self) -> str: ...

    def text(self) -> str: ...


ThreeToFiveDigits.Label.VALUE = _ProtocolLabelMember("ThreeToFiveDigits.Label.VALUE")


class ExactlyTwoDigits(typing.Protocol):
    class Label:
        VALUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.EXACTLYTWODIGITS] = NodeKind.EXACTLYTWODIGITS
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: ExactlyTwoDigits) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def value_text(self) -> str: ...

    def text(self) -> str: ...


ExactlyTwoDigits.Label.VALUE = _ProtocolLabelMember("ExactlyTwoDigits.Label.VALUE")


class EscapedMetas(typing.Protocol):
    class Label:
        VALUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.ESCAPEDMETAS] = NodeKind.ESCAPEDMETAS
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: EscapedMetas) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def value_text(self) -> str: ...

    def text(self) -> str: ...


EscapedMetas.Label.VALUE = _ProtocolLabelMember("EscapedMetas.Label.VALUE")


class LatinRange(typing.Protocol):
    class Label:
        VALUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.LATINRANGE] = NodeKind.LATINRANGE
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: LatinRange) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def value_text(self) -> str: ...

    def text(self) -> str: ...


LatinRange.Label.VALUE = _ProtocolLabelMember("LatinRange.Label.VALUE")


class NcGroupAlt(typing.Protocol):
    class Label:
        VALUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.NCGROUPALT] = NodeKind.NCGROUPALT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: NcGroupAlt) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def value_text(self) -> str: ...

    def text(self) -> str: ...


NcGroupAlt.Label.VALUE = _ProtocolLabelMember("NcGroupAlt.Label.VALUE")


class CaseInsensitive(typing.Protocol):
    class Label:
        VALUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.CASEINSENSITIVE] = NodeKind.CASEINSENSITIVE
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: CaseInsensitive) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def value_text(self) -> str: ...

    def text(self) -> str: ...


CaseInsensitive.Label.VALUE = _ProtocolLabelMember("CaseInsensitive.Label.VALUE")


class AnchoredWord(typing.Protocol):
    class Label:
        VALUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.ANCHOREDWORD] = NodeKind.ANCHOREDWORD
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: AnchoredWord) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def value_text(self) -> str: ...

    def text(self) -> str: ...


AnchoredWord.Label.VALUE = _ProtocolLabelMember("AnchoredWord.Label.VALUE")


class Pair(typing.Protocol):
    class Label:
        KEY: typing.ClassVar[object]
        VAL: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.PAIR] = NodeKind.PAIR
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Name | Num]]

    def append(self, child: Name | Num, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Name | Num], label: Label | None = None) -> None: ...

    def extend_children(self, other: Pair) -> None: ...

    def child(self) -> tuple[Label | None, Name | Num]: ...

    def insert(self, index: int, child: Name | Num, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Name | Num]: ...

    def replace_at(self, index: int, child: Name | Num, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_key(self, child: Name) -> None: ...

    def extend_key(self, children: typing.Iterable[Name]) -> None: ...

    def children_key(self) -> typing.Iterator[Name]: ...

    def child_key(self) -> Name: ...

    def maybe_key(self) -> Name | None: ...

    def append_val(self, child: Num) -> None: ...

    def extend_val(self, children: typing.Iterable[Num]) -> None: ...

    def children_val(self) -> typing.Iterator[Num]: ...

    def child_val(self) -> Num: ...

    def maybe_val(self) -> Num | None: ...

    def key(self) -> Name: ...

    def val(self) -> Num: ...


Pair.Label.KEY = _ProtocolLabelMember("Pair.Label.KEY")
Pair.Label.VAL = _ProtocolLabelMember("Pair.Label.VAL")


class Wrapper(typing.Protocol):
    class Label:
        KEY: typing.ClassVar[object]
        VAL: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.WRAPPER] = NodeKind.WRAPPER
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Name | Num]]

    def append(self, child: Name | Num, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Name | Num], label: Label | None = None) -> None: ...

    def extend_children(self, other: Wrapper) -> None: ...

    def child(self) -> tuple[Label | None, Name | Num]: ...

    def insert(self, index: int, child: Name | Num, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Name | Num]: ...

    def replace_at(self, index: int, child: Name | Num, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_key(self, child: Name) -> None: ...

    def extend_key(self, children: typing.Iterable[Name]) -> None: ...

    def children_key(self) -> typing.Iterator[Name]: ...

    def child_key(self) -> Name: ...

    def maybe_key(self) -> Name | None: ...

    def append_val(self, child: Num) -> None: ...

    def extend_val(self, children: typing.Iterable[Num]) -> None: ...

    def children_val(self) -> typing.Iterator[Num]: ...

    def child_val(self) -> Num: ...

    def maybe_val(self) -> Num | None: ...

    def key(self) -> Name: ...

    def val(self) -> Num: ...


Wrapper.Label.KEY = _ProtocolLabelMember("Wrapper.Label.KEY")
Wrapper.Label.VAL = _ProtocolLabelMember("Wrapper.Label.VAL")


class OptWrapper(typing.Protocol):
    class Label:
        KEY: typing.ClassVar[object]
        VAL: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.OPTWRAPPER] = NodeKind.OPTWRAPPER
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Name | Num]]

    def append(self, child: Name | Num, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Name | Num], label: Label | None = None) -> None: ...

    def extend_children(self, other: OptWrapper) -> None: ...

    def child(self) -> tuple[Label | None, Name | Num]: ...

    def insert(self, index: int, child: Name | Num, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Name | Num]: ...

    def replace_at(self, index: int, child: Name | Num, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_key(self, child: Name) -> None: ...

    def extend_key(self, children: typing.Iterable[Name]) -> None: ...

    def children_key(self) -> typing.Iterator[Name]: ...

    def child_key(self) -> Name: ...

    def maybe_key(self) -> Name | None: ...

    def append_val(self, child: Num) -> None: ...

    def extend_val(self, children: typing.Iterable[Num]) -> None: ...

    def children_val(self) -> typing.Iterator[Num]: ...

    def child_val(self) -> Num: ...

    def maybe_val(self) -> Num | None: ...

    def key(self) -> Name | None: ...

    def val(self) -> Num | None: ...


OptWrapper.Label.KEY = _ProtocolLabelMember("OptWrapper.Label.KEY")
OptWrapper.Label.VAL = _ProtocolLabelMember("OptWrapper.Label.VAL")


class RepWrapper(typing.Protocol):
    class Label:
        KEY: typing.ClassVar[object]
        VAL: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.REPWRAPPER] = NodeKind.REPWRAPPER
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Name | Num]]

    def append(self, child: Name | Num, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Name | Num], label: Label | None = None) -> None: ...

    def extend_children(self, other: RepWrapper) -> None: ...

    def child(self) -> tuple[Label | None, Name | Num]: ...

    def insert(self, index: int, child: Name | Num, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Name | Num]: ...

    def replace_at(self, index: int, child: Name | Num, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_key(self, child: Name) -> None: ...

    def extend_key(self, children: typing.Iterable[Name]) -> None: ...

    def children_key(self) -> typing.Iterator[Name]: ...

    def child_key(self) -> Name: ...

    def maybe_key(self) -> Name | None: ...

    def append_val(self, child: Num) -> None: ...

    def extend_val(self, children: typing.Iterable[Num]) -> None: ...

    def children_val(self) -> typing.Iterator[Num]: ...

    def child_val(self) -> Num: ...

    def maybe_val(self) -> Num | None: ...

    def key(self) -> list[Name]: ...

    def val(self) -> list[Num]: ...


RepWrapper.Label.KEY = _ProtocolLabelMember("RepWrapper.Label.KEY")
RepWrapper.Label.VAL = _ProtocolLabelMember("RepWrapper.Label.VAL")


class KwLabels(typing.Protocol):
    class Label:
        MATCH: typing.ClassVar[object]
        TYPE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.KWLABELS] = NodeKind.KWLABELS
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Num | fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: Num | fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[Num | fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: KwLabels) -> None: ...

    def child(self) -> tuple[Label | None, Num | fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: Num | fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Num | fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: Num | fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_match(self, child: Num) -> None: ...

    def extend_match(self, children: typing.Iterable[Num]) -> None: ...

    def children_match(self) -> typing.Iterator[Num]: ...

    def child_match(self) -> Num: ...

    def maybe_match(self) -> Num | None: ...

    def append_type(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_type(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_type(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_type(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_type(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def match(self) -> Num: ...

    def type(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def type_text(self) -> str: ...


KwLabels.Label.MATCH = _ProtocolLabelMember("KwLabels.Label.MATCH")
KwLabels.Label.TYPE = _ProtocolLabelMember("KwLabels.Label.TYPE")


class Quoted(typing.Protocol):
    class Label:
        TAIL: typing.ClassVar[object]
        VALUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.QUOTED] = NodeKind.QUOTED
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: Quoted) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_tail(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_tail(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_tail(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_tail(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_tail(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def tail(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def tail_text(self) -> str | None: ...

    def value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def value_text(self) -> str: ...

    def text(self) -> str: ...


Quoted.Label.TAIL = _ProtocolLabelMember("Quoted.Label.TAIL")
Quoted.Label.VALUE = _ProtocolLabelMember("Quoted.Label.VALUE")


class MixedOpt(typing.Protocol):
    class Label:
        KEY: typing.ClassVar[object]
        NODE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.MIXEDOPT] = NodeKind.MIXEDOPT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Num | fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: Num | fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[Num | fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: MixedOpt) -> None: ...

    def child(self) -> tuple[Label | None, Num | fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: Num | fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Num | fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: Num | fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_key(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_key(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_key(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_key(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_key(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def append_node(self, child: Num) -> None: ...

    def extend_node(self, children: typing.Iterable[Num]) -> None: ...

    def children_node(self) -> typing.Iterator[Num]: ...

    def child_node(self) -> Num: ...

    def maybe_node(self) -> Num | None: ...

    def key(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def key_text(self) -> str | None: ...

    def node(self) -> Num: ...


MixedOpt.Label.KEY = _ProtocolLabelMember("MixedOpt.Label.KEY")
MixedOpt.Label.NODE = _ProtocolLabelMember("MixedOpt.Label.NODE")


class UuidVal(typing.Protocol):
    class Label:
        VALUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.UUIDVAL] = NodeKind.UUIDVAL
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: UuidVal) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def value_text(self) -> str: ...

    def text(self) -> str: ...


UuidVal.Label.VALUE = _ProtocolLabelMember("UuidVal.Label.VALUE")


class DecimalVal(typing.Protocol):
    class Label:
        VALUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.DECIMALVAL] = NodeKind.DECIMALVAL
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: DecimalVal) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def value_text(self) -> str: ...

    def text(self) -> str: ...


DecimalVal.Label.VALUE = _ProtocolLabelMember("DecimalVal.Label.VALUE")


class Colour(typing.Protocol):
    class Label:
        DARK: typing.ClassVar[object]
        SHADE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.COLOUR] = NodeKind.COLOUR
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: Colour) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_dark(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_dark(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_dark(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_dark(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_dark(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def append_shade(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_shade(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_shade(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_shade(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_shade(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def dark(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def dark_text(self) -> str | None: ...

    def shade(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def shade_text(self) -> str | None: ...

    def text(self) -> str: ...

    def variant(self) -> Label: ...


Colour.Label.DARK = _ProtocolLabelMember("Colour.Label.DARK")
Colour.Label.SHADE = _ProtocolLabelMember("Colour.Label.SHADE")


class SumChain(typing.Protocol):
    class Label:
        OP: typing.ClassVar[object]
        TERM: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.SUMCHAIN] = NodeKind.SUMCHAIN
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Num | Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(
        self, child: Num | Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def extend(
        self,
        children: typing.Iterable[Num | Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol],
        label: Label | None = None,
    ) -> None: ...

    def extend_children(self, other: SumChain) -> None: ...

    def child(self) -> tuple[Label | None, Num | Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: Num | Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(
        self, index: int
    ) -> tuple[Label | None, Num | Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: Num | Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_op(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_op(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_op(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_op(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_op(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def append_term(self, child: Num) -> None: ...

    def extend_term(self, children: typing.Iterable[Num]) -> None: ...

    def children_term(self) -> typing.Iterator[Num]: ...

    def child_term(self) -> Num: ...

    def maybe_term(self) -> Num | None: ...

    def op(self) -> list[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def term(self) -> list[Num]: ...


SumChain.Label.OP = _ProtocolLabelMember("SumChain.Label.OP")
SumChain.Label.TERM = _ProtocolLabelMember("SumChain.Label.TERM")


class Trivia(typing.Protocol):
    class Label:
        CONTENT: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.TRIVIA] = NodeKind.TRIVIA
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: Trivia) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_content(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_content(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_content(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_content(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_content(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def content(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def content_text(self) -> str: ...

    def text(self) -> str: ...


Trivia.Label.CONTENT = _ProtocolLabelMember("Trivia.Label.CONTENT")


class Span(typing.Protocol):
    kind: typing.Literal[fltk.fegen.pyrt.terminalsrc.SpanKind.SPAN] = fltk.fegen.pyrt.terminalsrc.SpanKind.SPAN


class CstModule(typing.Protocol):
    @property
    def Num(self) -> type[Num]: ...

    @property
    def Name(self) -> type[Name]: ...

    @property
    def Atom(self) -> type[Atom]: ...

    @property
    def ParenExpr(self) -> type[ParenExpr]: ...

    @property
    def Stmt(self) -> type[Stmt]: ...

    @property
    def Items(self) -> type[Items]: ...

    @property
    def OptItem(self) -> type[OptItem]: ...

    @property
    def ZeroItems(self) -> type[ZeroItems]: ...

    @property
    def Expr(self) -> type[Expr]: ...

    @property
    def Lval(self) -> type[Lval]: ...

    @property
    def Rval(self) -> type[Rval]: ...

    @property
    def Arrow(self) -> type[Arrow]: ...

    @property
    def LatinWord(self) -> type[LatinWord]: ...

    @property
    def Tagged(self) -> type[Tagged]: ...

    @property
    def Val(self) -> type[Val]: ...

    @property
    def LeadingWs(self) -> type[LeadingWs]: ...

    @property
    def Grouped(self) -> type[Grouped]: ...

    @property
    def RecViaSub(self) -> type[RecViaSub]: ...

    @property
    def Nest(self) -> type[Nest]: ...

    @property
    def NestSum(self) -> type[NestSum]: ...

    @property
    def DigitSeq(self) -> type[DigitSeq]: ...

    @property
    def WordSeq(self) -> type[WordSeq]: ...

    @property
    def WsSeq(self) -> type[WsSeq]: ...

    @property
    def ThreeToFiveDigits(self) -> type[ThreeToFiveDigits]: ...

    @property
    def ExactlyTwoDigits(self) -> type[ExactlyTwoDigits]: ...

    @property
    def EscapedMetas(self) -> type[EscapedMetas]: ...

    @property
    def LatinRange(self) -> type[LatinRange]: ...

    @property
    def NcGroupAlt(self) -> type[NcGroupAlt]: ...

    @property
    def CaseInsensitive(self) -> type[CaseInsensitive]: ...

    @property
    def AnchoredWord(self) -> type[AnchoredWord]: ...

    @property
    def Pair(self) -> type[Pair]: ...

    @property
    def Wrapper(self) -> type[Wrapper]: ...

    @property
    def OptWrapper(self) -> type[OptWrapper]: ...

    @property
    def RepWrapper(self) -> type[RepWrapper]: ...

    @property
    def KwLabels(self) -> type[KwLabels]: ...

    @property
    def Quoted(self) -> type[Quoted]: ...

    @property
    def MixedOpt(self) -> type[MixedOpt]: ...

    @property
    def UuidVal(self) -> type[UuidVal]: ...

    @property
    def DecimalVal(self) -> type[DecimalVal]: ...

    @property
    def Colour(self) -> type[Colour]: ...

    @property
    def SumChain(self) -> type[SumChain]: ...

    @property
    def Trivia(self) -> type[Trivia]: ...
