"""Tests for the generated-code normalization pipeline (`fltk.fegen.gencode_format`).

Every generated `.py` in the tree passes through this module, and its failure modes are all
silent-by-default: a ruff that cannot be resolved, a ruff that errors out instead of
reformatting, or a ruff that reads a config from the working directory would each leave
generated bytes different from what the seed and parity gates expect, with nothing pointing at
the cause.  These tests pin the loud behavior that replaces each of those.
"""

from __future__ import annotations

import stat
import sys
from pathlib import Path

import pytest

from fltk.fegen import gencode_format

# A line the pinned config (line-length 120) leaves alone and a 40-column config would wrap.
_LONG_LINE_SOURCE = 'VALUES = {"alpha": 1, "beta": 2, "gamma": 3, "delta": 4, "epsilon": 5}\n'


def _fake_ruff(tmp_path: Path, name: str, exit_code: int, stderr: str = "") -> Path:
    """A stand-in ruff executable that prints `stderr` and exits with `exit_code`."""
    script = tmp_path / name
    script.write_text(f'#!/bin/sh\nprintf "%s" "{stderr}" >&2\nexit {exit_code}\n')
    script.chmod(script.stat().st_mode | stat.S_IXUSR)
    return script


@pytest.fixture
def generated_file(tmp_path: Path) -> Path:
    path = tmp_path / "sample_cst.py"
    path.write_text(_LONG_LINE_SOURCE)
    return path


# ---------------------------------------------------------------------------
# find_ruff / gencode_ruff_config
# ---------------------------------------------------------------------------


def test_find_ruff_honors_the_env_override(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    override = _fake_ruff(tmp_path, "ruff-override", 0)
    monkeypatch.setenv(gencode_format.RUFF_ENV_VAR, str(override))

    assert gencode_format.find_ruff() == override


def test_find_ruff_without_a_resolvable_ruff_raises(monkeypatch: pytest.MonkeyPatch) -> None:
    """The diagnostic naming what was searched is the only clue a user gets."""
    monkeypatch.delenv(gencode_format.RUFF_ENV_VAR, raising=False)
    # A None entry in sys.modules makes `import ruff` raise ImportError, which is the state of
    # an environment that never installed the wheel.
    monkeypatch.setitem(sys.modules, "ruff", None)

    with pytest.raises(gencode_format.NormalizationError) as excinfo:
        gencode_format.find_ruff()

    assert "no ruff executable found" in str(excinfo.value)
    assert "Searched:" in str(excinfo.value)


def test_gencode_ruff_config_honors_the_env_override(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    config = tmp_path / "custom-ruff.toml"
    config.write_text("line-length = 120\n")
    monkeypatch.setenv(gencode_format.CONFIG_ENV_VAR, str(config))

    assert gencode_format.gencode_ruff_config() == config


def test_gencode_ruff_config_missing_file_raises(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv(gencode_format.CONFIG_ENV_VAR, str(tmp_path / "absent.toml"))

    with pytest.raises(gencode_format.NormalizationError) as excinfo:
        gencode_format.gencode_ruff_config()

    assert gencode_format.CONFIG_BASENAME in str(excinfo.value)


def test_gencode_ruff_config_default_is_the_pinned_file() -> None:
    config = gencode_format.gencode_ruff_config()

    assert config.name == gencode_format.CONFIG_BASENAME
    assert config.is_file()


# ---------------------------------------------------------------------------
# Exit-code contract
# ---------------------------------------------------------------------------


def test_ruff_check_exit_2_is_a_hard_error(
    tmp_path: Path, generated_file: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Exit >1 means ruff itself failed; normalizing nothing must not pass silently."""
    monkeypatch.setenv(gencode_format.RUFF_ENV_VAR, str(_fake_ruff(tmp_path, "ruff-exit2", 2, "unknown option")))

    with pytest.raises(gencode_format.NormalizationError) as excinfo:
        gencode_format.normalize([generated_file])

    assert "exit 2" in str(excinfo.value)
    assert "unknown option" in str(excinfo.value), "the tool's stderr must reach the caller"


def test_ruff_check_exit_1_is_tolerated(tmp_path: Path, generated_file: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Exit 1 is residual unfixable findings, which generated code is allowed to carry."""
    script = tmp_path / "ruff-check-exit1"
    script.write_text('#!/bin/sh\nif [ "$1" = "check" ]; then printf "1 error found" >&2; exit 1; fi\nexit 0\n')
    script.chmod(script.stat().st_mode | stat.S_IXUSR)
    monkeypatch.setenv(gencode_format.RUFF_ENV_VAR, str(script))

    gencode_format.normalize([generated_file])


def test_ruff_format_failure_is_a_hard_error(
    tmp_path: Path, generated_file: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`format` has no tolerated non-zero exit: any failure is a real defect."""
    script = tmp_path / "ruff-format-fails"
    script.write_text('#!/bin/sh\nif [ "$1" = "format" ]; then printf "boom" >&2; exit 1; fi\nexit 0\n')
    script.chmod(script.stat().st_mode | stat.S_IXUSR)
    monkeypatch.setenv(gencode_format.RUFF_ENV_VAR, str(script))

    with pytest.raises(gencode_format.NormalizationError) as excinfo:
        gencode_format.normalize([generated_file])

    assert "ruff format failed" in str(excinfo.value)
    assert "boom" in str(excinfo.value)


def test_normalize_of_nothing_never_reaches_for_the_tool(monkeypatch: pytest.MonkeyPatch) -> None:
    def unreachable() -> Path:
        msg = "find_ruff must not be called when there are no files"
        raise AssertionError(msg)

    monkeypatch.setattr(gencode_format, "find_ruff", unreachable)

    gencode_format.normalize([])


# ---------------------------------------------------------------------------
# Config hermeticity
# ---------------------------------------------------------------------------


def test_normalization_ignores_a_config_in_the_working_directory(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Generated bytes are a function of (grammar, generator, pinned ruff, pinned config).

    A build action's execroot may hold an unrelated project's ruff settings — in a downstream
    consumer's build, the consumer's own.  Config discovery would let those reshape FLTK's
    generated modules, so every invocation passes `--config` explicitly.  Dropping that (or
    adding a `cwd=`) is invisible in-repo, where fltk's own config extends the pinned one.
    """
    clean_dir = tmp_path / "clean"
    hostile_dir = tmp_path / "hostile"
    clean_dir.mkdir()
    hostile_dir.mkdir()

    clean_file = clean_dir / "sample_cst.py"
    hostile_file = hostile_dir / "sample_cst.py"
    clean_file.write_text(_LONG_LINE_SOURCE)
    hostile_file.write_text(_LONG_LINE_SOURCE)

    # Both discovery routes ruff has: the working directory, and the file's own ancestors.
    (hostile_dir / "pyproject.toml").write_text(
        '[tool.ruff]\nline-length = 40\ntarget-version = "py310"\n\n[tool.ruff.format]\nquote-style = "single"\n'
    )

    monkeypatch.chdir(clean_dir)
    gencode_format.normalize([clean_file])
    monkeypatch.chdir(hostile_dir)
    gencode_format.normalize([hostile_file])

    assert hostile_file.read_text() == clean_file.read_text(), (
        "normalization must not read a ruff config out of the working directory or the file's ancestors"
    )
    assert hostile_file.read_text() == _LONG_LINE_SOURCE, (
        "the pinned config's line-length must be what shapes the output"
    )
