"""Generator tests for the Rust AST backend (``RustAstGenerator``).

These assert structural properties of the emitted ``ast.rs`` source string; they do not compile
it.  The model-side answers the emitted types rest on — which edges are boxed, which enums carry
a span — are tested in ``fltk/fegen/test_ast_model.py``.
"""

from __future__ import annotations

import pathlib

import pytest

from fltk.fegen import ast_config as ac
from fltk.fegen import ast_model as am
from fltk.fegen import ast_test_grammars as fixtures
from fltk.fegen import gsm2ast_rs
from fltk.plumbing import parse_grammar_file

_FLTK_ROOT = pathlib.Path(__file__).parents[1] / "fltk"

TREE_GRAMMAR = "tree := name:word , child:tree? , kids:tree* ;\nword := w:/[a-z]+/ ;\n"
"""A rule holding itself at every arity: the whole container matrix in one cycle."""

KEYED_TREE_GRAMMAR = "node := key:word , kid:node? , kids:node* ;\nword := w:/[a-z]+/ ;\n"
KEYED_TREE_SIDECAR = "rule word { transparent; }\nrule node { key: key; }\n"
"""``TREE_GRAMMAR`` with the repeated position keyed, so the recursive container is a map."""


def model_for(grammar_text: str, sidecar: str | None = None) -> am.AstModel:
    return fixtures.model_for(grammar_text, sidecar, ac.Backend.RUST)


def generate(grammar_text: str, sidecar: str | None = None, **kwargs: str) -> str:
    return gsm2ast_rs.generate_ast_rs(model_for(grammar_text, sidecar), **kwargs)


def block(src: str, header: str) -> str:
    """The emitted item starting with ``header``, through its own closing brace.

    The brace is the one at ``header``'s own indentation, so an item nested in a module can be
    read the same way a top-level one is.
    """
    start = src.index(header)
    closer = "\n" + " " * (len(header) - len(header.lstrip())) + "}"
    return src[start : src.index(closer + "\n", start) + len(closer)]


_SPAN_SIGNATURE = "    pub fn span(&self) -> &::fltk_cst_core::Span {"


def impl_blocks(src: str, type_name: str) -> list[str]:
    """Every ``impl <type_name> { ... }`` the module emits, in order.

    A type can get more than one — the span accessor and ``from_cst`` are separate blocks — so a
    question about one of them has to look at all of them.
    """
    header = f"impl {type_name} {{"
    blocks: list[str] = []
    start = src.find(header)
    while start != -1:
        end = src.index("\n}\n", start) + 2
        blocks.append(src[start:end])
        start = src.find(header, end)
    return blocks


def has_span_method(src: str, type_name: str) -> bool:
    """Whether the emitted module gives ``type_name`` the enum ``span()`` accessor.

    Keyed on the emitted signature, not on the doc comment above it: every use below is a
    negative assertion, which a reworded comment would satisfy while proving nothing.
    """
    return any(f"{_SPAN_SIGNATURE}\n" in body for body in impl_blocks(src, type_name))


@pytest.fixture(scope="module")
def config_src() -> str:
    return generate(fixtures.CONFIG_GRAMMAR, fixtures.KEYED_SIDECAR)


@pytest.fixture(scope="module")
def fold_src() -> str:
    return generate(fixtures.FOLD_GRAMMAR, fixtures.FOLD_SIDECAR)


@pytest.fixture(scope="module")
def task_src() -> str:
    return generate(fixtures.TASK_GRAMMAR, fixtures.TASK_SIDECAR)


@pytest.fixture(scope="module")
def leaf_src() -> str:
    return generate(fixtures.LEAF_GRAMMAR, fixtures.LEAF_SIDECAR)


class TestHeader:
    def test_the_header_names_the_generator_and_the_grammar(self) -> None:
        src = generate("word := w:/[a-z]+/ ;", source_name="mylang.fltkg")
        assert src.startswith("//! Generated by fltk gen-rust-ast from `mylang.fltkg`. Do not edit.\n")

    def test_the_header_states_the_equality_rule(self) -> None:
        """Spans out of equality is the one surprise a consumer of the module has to know."""
        assert "Spans never take part in equality" in generate("word := w:/[a-z]+/ ;")

    def test_a_grammar_needing_no_features_names_none(self) -> None:
        assert "fltk-ast-core` features" not in generate("word := w:/[a-z]+/ ;")

    def test_a_keyed_collection_names_the_container_feature(self, config_src: str) -> None:
        assert "//! Requires these `fltk-ast-core` features: indexmap." in config_src

    def test_the_opt_in_builtins_name_their_features(self) -> None:
        src = generate(
            "doc := id:ident , amount:money ;\nident := /[0-9a-f-]+/ ;\nmoney := /[0-9.]+/ ;\n",
            "rule ident { type: uuid; }\nrule money { type: decimal; }\n",
        )
        assert "//! Requires these `fltk-ast-core` features: uuid, decimal." in src

    def test_the_cst_module_is_always_imported(self) -> None:
        """Every converter's signature names a CST node type, so the `use` is never unused."""
        assert "use super::cst;" in generate("word := w:/[a-z]+/ ;")

    def test_generation_is_idempotent(self) -> None:
        generator = gsm2ast_rs.RustAstGenerator(model_for("word := w:/[a-z]+/ ;"))
        assert generator.generate() == generator.generate()


class TestConfigLanguage:
    """The Rust types emitted for the config language grammar."""

    def test_the_goal_product_holds_a_vec_of_its_sum(self, config_src: str) -> None:
        assert block(config_src, "pub struct Config") == (
            "pub struct Config {\n    pub stanzas: Vec<Stanza>,\n    pub span: ::fltk_cst_core::Span,\n}"
        )

    def test_a_keyed_collection_is_an_index_map(self, config_src: str) -> None:
        assert "pub settings: ::fltk_ast_core::IndexMap<String, Setting>," in block(config_src, "pub struct ServerDef")

    def test_an_erased_rule_leaves_its_payload_at_the_use_site(self, config_src: str) -> None:
        assert "pub name: String," in block(config_src, "pub struct ServerDef")
        assert "pub struct Identifier" not in config_src

    def test_an_optional_coerced_field_is_an_option_of_the_scalar(self, config_src: str) -> None:
        assert "pub interval: Option<i64>," in block(config_src, "pub struct MetricDef")

    def test_a_renamed_field_takes_the_new_name(self, config_src: str) -> None:
        assert "pub metric_kind: MetricTypeValue," in block(config_src, "pub struct MetricDef")

    def test_the_sum_is_an_enum_over_its_payloads(self, config_src: str) -> None:
        assert block(config_src, "pub enum Stanza") == (
            "pub enum Stanza {\n    ServerDef(ServerDef),\n    MetricDef(MetricDef),\n}"
        )

    def test_a_span_bearing_sum_delegates_its_span(self, config_src: str) -> None:
        assert block(config_src, "impl Stanza") == (
            "impl Stanza {\n"
            "    /// The span of whichever payload this value holds.\n"
            "    pub fn span(&self) -> &::fltk_cst_core::Span {\n"
            "        match self {\n"
            "            Self::ServerDef(payload) => &payload.span,\n"
            "            Self::MetricDef(payload) => &payload.span,\n"
            "        }\n"
            "    }\n"
            "}"
        )

    def test_a_sum_of_erased_payloads_is_fully_plain(self, config_src: str) -> None:
        """Erased payloads carry no span, so the enum has no ``span()`` accessor."""
        assert block(config_src, "pub enum Value") == (
            "pub enum Value {\n    String(String),\n    Number(i64),\n    Flag(bool),\n    List(List),\n}"
        )
        assert not has_span_method(config_src, "Value")
        # The same predicate on a sum that does have one, so a needle that stopped matching fails
        # here instead of making the assertion above pass vacuously.
        assert has_span_method(config_src, "Stanza")

    def test_the_value_enum_is_match_and_map_material(self, config_src: str) -> None:
        assert "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\npub enum MetricTypeValue {" in config_src
        assert block(config_src, "pub enum MetricTypeValue") == (
            "pub enum MetricTypeValue {\n    Counter,\n    Gauge,\n    Histogram,\n}"
        )

    def test_a_bool_rule_leaves_no_value_enum(self, config_src: str) -> None:
        assert "pub enum BooleanValue" not in config_src

    def test_every_node_type_derives_debug_and_clone(self, config_src: str) -> None:
        """No ``PartialEq`` derive: equality skips span-typed members, so it is written out."""
        lines = config_src.splitlines()
        declarations = [
            index
            for index, line in enumerate(lines)
            if line.startswith(("pub struct ", "pub enum ")) and not line.endswith("Value {")
        ]
        assert declarations
        assert {lines[index - 1] for index in declarations} == {"#[derive(Debug, Clone)]"}


class TestExpressionGrammar:
    """The fold and boxing shapes for the expression grammar."""

    def test_the_chain_link_holds_both_sides_boxed(self, fold_src: str) -> None:
        assert block(fold_src, "pub struct ExprBinary") == (
            "pub struct ExprBinary {\n"
            "    pub op: AddOpValue,\n"
            "    pub lhs: Box<Expr>,\n"
            "    pub rhs: Box<Expr>,\n"
            "    pub span: ::fltk_cst_core::Span,\n"
            "}"
        )

    def test_the_fold_enum_boxes_the_operand_inside_the_cycle(self, fold_src: str) -> None:
        assert (
            block(fold_src, "pub enum Expr") == "pub enum Expr {\n    Operand(Box<Term>),\n    Binary(ExprBinary),\n}"
        )

    def test_the_sum_closing_the_cycle_boxes_only_that_edge(self, fold_src: str) -> None:
        assert block(fold_src, "pub enum Factor") == "pub enum Factor {\n    Num(i64),\n    Paren(Box<Expr>),\n}"

    def test_a_fold_over_erased_operands_has_no_span_method(self, fold_src: str, config_src: str) -> None:
        assert not has_span_method(fold_src, "Expr")
        assert has_span_method(config_src, "Stanza"), "the predicate still finds one where there is one"

    def test_the_erased_operator_rules_leave_only_their_value_enums(self, fold_src: str) -> None:
        assert "pub struct AddOp" not in fold_src
        assert block(fold_src, "pub enum AddOpValue") == "pub enum AddOpValue {\n    Plus,\n    Minus,\n}"


class TestFieldTypes:
    def test_a_self_reference_is_boxed_at_its_own_arity(self) -> None:
        src = generate("tree := name:word , child:tree? , kids:tree* ;\nword := w:/[a-z]+/ ;\n")
        body = block(src, "pub struct Tree")
        assert "pub child: Option<Box<Tree>>," in body
        assert "pub kids: Vec<Tree>," in body

    def test_a_keyword_label_becomes_a_raw_identifier(self) -> None:
        src = generate('decl := type:word , pub:"pub"? ;\nword := w:/[a-z]+/ ;\n')
        assert "pub r#type: Word," in src
        assert "pub r#pub: bool," in src

    def test_a_labeled_literal_carries_position_only(self) -> None:
        src = generate('marks := bang:"!" , stars:"*"* ;')
        body = block(src, "pub struct Marks")
        assert "pub bang: ::fltk_cst_core::Span," in body
        assert "pub stars: Vec<::fltk_cst_core::Span>," in body

    def test_a_label_free_rule_is_a_marker(self) -> None:
        src = generate('marker := "!" . "?" ;')
        assert block(src, "pub struct Marker") == "pub struct Marker {\n    pub span: ::fltk_cst_core::Span,\n}"

    def test_a_terminal_rule_carries_its_text(self) -> None:
        src = generate("word := w:/[a-z]+/ ;")
        assert block(src, "pub struct Word") == (
            "pub struct Word {\n    pub text: String,\n    pub span: ::fltk_cst_core::Span,\n}"
        )

    def test_a_redirected_terminal_rule_says_where_its_text_comes_from(self) -> None:
        src = generate(
            'quoted := "\\"" . content:/[^"]*/ . "\\"" ;',
            "rule quoted { text_from: content; }\n",
        )
        assert "/// AST node for terminal-only rule `quoted`, over the text of its `content` child." in src

    def test_the_wide_builtins_are_named_through_the_runtime(self) -> None:
        """Naming ``uuid::Uuid`` directly would be a second version of the type in the graph."""
        src = generate(
            "doc := id:ident , amount:money ;\nident := /[0-9a-f-]+/ ;\nmoney := /[0-9.]+/ ;\n",
            "rule ident { type: uuid; }\nrule money { type: decimal; }\n",
        )
        assert "pub value: ::fltk_ast_core::Uuid," in src
        assert "pub value: ::fltk_ast_core::Decimal," in src

    def test_a_field_enum_is_an_enum_over_the_types_the_label_carries(self) -> None:
        src = generate('wrap := ( a:num | a:word ) . ";" ;\nnum := d:/[0-9]+/ ;\nword := w:/[a-z]+/ ;\n')
        assert "pub a: WrapA," in block(src, "pub struct Wrap")
        assert block(src, "pub enum WrapA") == "pub enum WrapA {\n    Num(Num),\n    Word(Word),\n}"

    def test_a_field_enum_whose_variants_all_bear_spans_delegates_its_span(self) -> None:
        src = generate('wrap := ( a:num | a:word ) . ";" ;\nnum := d:/[0-9]+/ ;\nword := w:/[a-z]+/ ;\n')
        assert block(src, "impl WrapA") == (
            "impl WrapA {\n"
            "    /// The span of whichever payload this value holds.\n"
            "    pub fn span(&self) -> &::fltk_cst_core::Span {\n"
            "        match self {\n"
            "            Self::Num(payload) => &payload.span,\n"
            "            Self::Word(payload) => &payload.span,\n"
            "        }\n"
            "    }\n"
            "}"
        )

    def test_a_field_enum_holding_text_has_no_span_to_delegate_to(self) -> None:
        src = generate("wrap := ( a:num | a:/[a-z]+/ ) ;\nnum := d:/[0-9]+/ ;\n")
        assert "Text(String)," in block(src, "pub enum WrapA")
        assert not has_span_method(src, "WrapA")

    def test_a_sum_over_a_span_bearing_field_enum_delegates_through_it(self) -> None:
        """The label's enum answers for its payload, so the sum carrying one keeps an accessor."""
        src = generate(
            "wrap := i:inner | b:num ;\ninner := ( a:num | a:word ) ;\nnum := d:/[0-9]+/ ;\nword := w:/[a-z]+/ ;\n",
            "rule inner { transparent; }\n",
        )
        assert "pub enum InnerA {" in src
        assert "Self::I(payload) => payload.span()," in block(src, "impl Wrap")


class TestCustomAndErasedRules:
    def test_a_custom_rule_is_named_by_its_rust_path(self) -> None:
        src = generate(
            "holder := amount:money ;\nmoney := d:/[0-9]+/ ;\n",
            'rule money { custom(rust: "crate::Money", python: "app.Money"); }\n',
        )
        assert "pub amount: crate::Money," in src
        assert "pub struct Money" not in src

    def test_a_custom_rule_without_a_rust_entry_cannot_be_emitted(self) -> None:
        """The validator refuses this when Rust is a target, so only a hand-built config reaches it."""
        grammar = fixtures.classified_grammar("holder := amount:money ;\nmoney := d:/[0-9]+/ ;\n")
        python_only = ac.load_ast_config('rule money { custom(python: "app.Money"); }\n', grammar, {ac.Backend.PYTHON})
        with pytest.raises(ValueError, match=r"names no `rust:` type"):
            gsm2ast_rs.generate_ast_rs(am.build_ast_model(grammar, python_only))

    def test_a_flattened_wrapper_has_no_type_of_its_own(self, task_src: str) -> None:
        assert "pub struct Schedule" not in task_src
        body = block(task_src, "pub struct TaskDef")
        assert "pub interval: Option<i64>," in body
        assert "pub unit: Option<TimeUnitValue>," in body


class TestCstBackpointers:
    def test_every_type_carries_the_cst_node_it_came_from(self) -> None:
        src = generate("word := w:/[a-z]+/ ;", "option cst = true;\n")
        assert "use super::cst;" in src
        assert "pub cst: Option<::fltk_cst_core::Shared<cst::Word>>," in block(src, "pub struct Word")

    def test_the_cst_module_path_is_the_caller_s(self) -> None:
        src = generate("word := w:/[a-z]+/ ;", "option cst = true;\n", cst_mod_path="crate::grammar::cst")
        assert "use crate::grammar::cst;" in src

    def test_a_differently_named_cst_module_is_aliased(self) -> None:
        src = generate("word := w:/[a-z]+/ ;", "option cst = true;\n", cst_mod_path="crate::tree")
        assert "use crate::tree as cst;" in src


class TestEquality:
    """``PartialEq`` over semantic data only, per node form."""

    def test_a_product_compares_every_semantic_member(self, config_src: str) -> None:
        assert block(config_src, "impl PartialEq for Setting") == (
            "impl PartialEq for Setting {\n"
            "    fn eq(&self, other: &Self) -> bool {\n"
            "        self.key == other.key && self.value == other.value\n"
            "    }\n"
            "}"
        )

    def test_a_marker_product_holds_no_semantic_data_at_all(self) -> None:
        src = generate('marker := "!" . "?" ;')
        assert block(src, "impl PartialEq for Marker") == (
            "impl PartialEq for Marker {\n"
            "    /// A marker node carries position only, so every value of it is equal to every other.\n"
            "    fn eq(&self, _other: &Self) -> bool {\n"
            "        true\n"
            "    }\n"
            "}"
        )

    def test_labeled_literal_members_carry_position_and_stay_out(self) -> None:
        """A literal's text is a grammar constant, so its member records an offset and nothing else."""
        src = generate('marks := name:word , bang:"!" , stars:"*"* ;\nword := w:/[a-z]+/ ;\n')
        assert block(src, "impl PartialEq for Marks") == (
            "impl PartialEq for Marks {\n"
            "    fn eq(&self, other: &Self) -> bool {\n"
            "        self.name == other.name\n"
            "    }\n"
            "}"
        )

    def test_a_presence_flag_is_semantic_data(self) -> None:
        """``pub:"pub"?`` records *whether* the keyword was written, which is a datum."""
        src = generate('decl := type:word , pub:"pub"? ;\nword := w:/[a-z]+/ ;\n')
        assert "self.r#type == other.r#type && self.r#pub == other.r#pub" in block(src, "impl PartialEq for Decl")

    def test_the_cst_backpointer_stays_out(self) -> None:
        src = generate("word := w:/[a-z]+/ ;", "option cst = true;\n")
        assert block(src, "impl PartialEq for Word") == (
            "impl PartialEq for Word {\n"
            "    fn eq(&self, other: &Self) -> bool {\n"
            "        self.text == other.text\n"
            "    }\n"
            "}"
        )

    def test_a_terminal_rule_compares_its_text(self) -> None:
        src = generate("word := w:/[a-z]+/ ;")
        assert "        self.text == other.text\n" in block(src, "impl PartialEq for Word")

    def test_a_coerced_terminal_rule_compares_its_value(self) -> None:
        src = generate("count := d:/[0-9]+/ ;", "rule count { type: u32; }\n")
        assert "        self.value == other.value\n" in block(src, "impl PartialEq for Count")

    def test_an_enum_shaped_node_compares_its_variant(self) -> None:
        src = generate('flag := yes:"yes" | no:"no" ;')
        assert "        self.value == other.value\n" in block(src, "impl PartialEq for Flag")

    def test_a_sum_compares_the_payload_of_the_matching_variant(self, config_src: str) -> None:
        assert block(config_src, "impl PartialEq for Stanza") == (
            "impl PartialEq for Stanza {\n"
            "    fn eq(&self, other: &Self) -> bool {\n"
            "        match (self, other) {\n"
            "            (Self::ServerDef(a), Self::ServerDef(b)) => a == b,\n"
            "            (Self::MetricDef(a), Self::MetricDef(b)) => a == b,\n"
            "            _ => false,\n"
            "        }\n"
            "    }\n"
            "}"
        )

    def test_a_field_enum_compares_within_one_variant(self) -> None:
        src = generate('wrap := ( a:num | a:word ) . ";" ;\nnum := d:/[0-9]+/ ;\nword := w:/[a-z]+/ ;\n')
        body = block(src, "impl PartialEq for WrapA")
        assert "            (Self::Num(a), Self::Num(b)) => a == b,\n" in body
        assert "            _ => false,\n" in body

    def test_a_value_enum_keeps_its_derive(self, config_src: str) -> None:
        """It is a bare discriminant, so there is nothing to skip and nothing to write out."""
        assert "impl PartialEq for MetricTypeValue" not in config_src

    def test_a_long_member_list_breaks_across_lines(self) -> None:
        src = generate(
            "record := first_component:word , second_component:word , third_component:word ;\nword := w:/[a-z]+/ ;\n"
        )
        assert block(src, "impl PartialEq for Record") == (
            "impl PartialEq for Record {\n"
            "    fn eq(&self, other: &Self) -> bool {\n"
            "        self.first_component == other.first_component\n"
            "            && self.second_component == other.second_component\n"
            "            && self.third_component == other.third_component\n"
            "    }\n"
            "}"
        )


class TestEqualityWalk:
    """Comparison of the types whose values nest past any bound the grammar sets."""

    def test_a_cycle_free_grammar_needs_no_walk(self, config_src: str) -> None:
        """``list`` holds its values in a ``Vec``, so no type nests without a bound."""
        assert "mod eq_walk" not in config_src

    def test_a_recursive_type_seeds_the_walk_with_its_own_pair(self, fold_src: str) -> None:
        assert block(fold_src, "impl PartialEq for Expr {") == (
            "impl PartialEq for Expr {\n"
            "    /// Bounded stack: the pending pairs live in a worklist, not in call frames.\n"
            "    fn eq(&self, other: &Self) -> bool {\n"
            "        eq_walk::run(eq_walk::Item::Expr(self, other))\n"
            "    }\n"
            "}"
        )

    def test_the_walk_lists_exactly_the_recursive_types(self, fold_src: str) -> None:
        """The five bounded-stack types: the two chains, their links, and the sum between them."""
        assert block(fold_src, "    pub(super) enum Item<'a> {") == (
            "    pub(super) enum Item<'a> {\n"
            "        ExprBinary(&'a super::ExprBinary, &'a super::ExprBinary),\n"
            "        Expr(&'a super::Expr, &'a super::Expr),\n"
            "        TermBinary(&'a super::TermBinary, &'a super::TermBinary),\n"
            "        Term(&'a super::Term, &'a super::Term),\n"
            "        Factor(&'a super::Factor, &'a super::Factor),\n"
            "    }"
        )

    def test_the_walk_is_emitted_once_and_dispatches_every_item(self, fold_src: str) -> None:
        assert fold_src.count("mod eq_walk {") == 1
        assert fold_src.count("pub(super) fn run(root: Item<'_>) -> bool {") == 1
        assert fold_src.count("Self::Factor(a, b) => a.eq_shallow(b, worklist),") == 1

    def test_a_chain_link_compares_its_operator_before_enqueueing_both_sides(self, fold_src: str) -> None:
        assert block(fold_src, "impl ExprBinary {") == (
            "impl ExprBinary {\n"
            "    /// Compare what cannot recurse, enqueueing the pairs that can.\n"
            "    fn eq_shallow<'a>(&'a self, other: &'a Self, worklist: &mut Vec<eq_walk::Item<'a>>) -> bool {\n"
            "        if self.op != other.op {\n"
            "            return false;\n"
            "        }\n"
            "        worklist.push(eq_walk::Item::Expr(&self.lhs, &other.lhs));\n"
            "        worklist.push(eq_walk::Item::Expr(&self.rhs, &other.rhs));\n"
            "        true\n"
            "    }\n"
            "}"
        )

    def test_a_walked_enum_enqueues_only_the_recursive_payloads(self, fold_src: str) -> None:
        assert block(fold_src, "impl Factor {") == (
            "impl Factor {\n"
            "    /// Compare what cannot recurse, enqueueing the pairs that can.\n"
            "    fn eq_shallow<'a>(&'a self, other: &'a Self, worklist: &mut Vec<eq_walk::Item<'a>>) -> bool {\n"
            "        match (self, other) {\n"
            "            (Self::Num(a), Self::Num(b)) => a == b,\n"
            "            (Self::Paren(a), Self::Paren(b)) => {\n"
            "                worklist.push(eq_walk::Item::Expr(a, b));\n"
            "                true\n"
            "            }\n"
            "            _ => false,\n"
            "        }\n"
            "    }\n"
            "}"
        )

    def test_a_type_outside_a_cycle_compares_on_the_spot(self) -> None:
        """Only the recursive types walk; a bounded one keeps the direct comparison."""
        src = generate(TREE_GRAMMAR)
        assert block(src, "impl PartialEq for Word") == (
            "impl PartialEq for Word {\n"
            "    fn eq(&self, other: &Self) -> bool {\n"
            "        self.text == other.text\n"
            "    }\n"
            "}"
        )
        assert "fn eq_shallow" not in block(src, "impl Word {")

    def test_an_optional_recursive_member_needs_both_sides_present(self) -> None:
        src = generate(TREE_GRAMMAR)
        assert block(src, "impl Tree {") == (
            "impl Tree {\n"
            "    /// Compare what cannot recurse, enqueueing the pairs that can.\n"
            "    fn eq_shallow<'a>(&'a self, other: &'a Self, worklist: &mut Vec<eq_walk::Item<'a>>) -> bool {\n"
            "        if self.name != other.name {\n"
            "            return false;\n"
            "        }\n"
            "        match (&self.child, &other.child) {\n"
            "            (Some(a), Some(b)) => worklist.push(eq_walk::Item::Tree(a, b)),\n"
            "            (None, None) => {}\n"
            "            _ => return false,\n"
            "        }\n"
            "        if self.kids.len() != other.kids.len() {\n"
            "            return false;\n"
            "        }\n"
            "        for (a, b) in self.kids.iter().zip(other.kids.iter()) {\n"
            "            worklist.push(eq_walk::Item::Tree(a, b));\n"
            "        }\n"
            "        true\n"
            "    }\n"
            "}"
        )

    def test_a_keyed_collection_of_a_recursive_element_compares_by_key(self) -> None:
        """``IndexMap``'s own equality ignores insertion order, so the walk looks each key up."""
        src = generate(KEYED_TREE_GRAMMAR, KEYED_TREE_SIDECAR)
        body = block(src, "impl Node {")
        assert "        for (key, a) in &self.kids {\n" in body
        assert "            let Some(b) = other.kids.get(key) else {\n" in body
        assert "            worklist.push(eq_walk::Item::Node(a, b));\n" in body


_WITNESS_HEADER = "fn _expr_drop_witness() -> Expr {"

STRUCT_OPERAND_GRAMMAR = (
    "expr := d:atom , ( , op:sign , d:atom)* ;\n"
    'sign := p:"+" | m:"-" ;\n'
    'atom := "{" , tags:tag* , "}" , note:word? , n:num ;\n'
    'tag := key:word , "=" , v:word ;\n'
    "word := w:/[a-z]+/ ;\nnum := d:/[0-9]+/ ;\n"
)
STRUCT_OPERAND_SIDECAR = (
    "rule expr { fold_left: op; }\nrule sign { transparent; }\nrule word { transparent; }\n"
    "rule num  { type: i64; transparent; }\nrule tag  { key: key; }\n"
)
"""A fold whose operand is a product carrying a map, an optional and a coerced scalar.

Every fold in the shared fixtures bottoms out in a bare ``i64``, so this is the only input that
reaches the struct-witness renderer and the empty-container spellings at all.
"""


class TestIterativeDrop:
    """A chain link tears the chain below it down through a worklist, not through call frames."""

    def test_the_witness_is_the_cheapest_operand_the_chain_bottoms_out_in(self, fold_src: str) -> None:
        assert block(fold_src, "fn _expr_drop_witness() -> Expr {") == (
            "fn _expr_drop_witness() -> Expr {\n    Expr::Operand(Box::new(Term::Operand(Box::new(Factor::Num(0)))))\n}"
        )

    def test_each_fold_rule_gets_one_witness_function(self, fold_src: str) -> None:
        assert fold_src.count("fn _expr_drop_witness() -> Expr {") == 1
        assert fold_src.count("fn _term_drop_witness() -> Term {") == 1

    def test_the_link_replaces_both_sides_and_drains_a_worklist(self, fold_src: str) -> None:
        assert block(fold_src, "impl Drop for ExprBinary {") == (
            "impl Drop for ExprBinary {\n"
            "    /// Take the chain below this link apart through a worklist rather than by recursion.\n"
            "    fn drop(&mut self) {\n"
            "        // A link holding two bare operands tears down by ordinary glue: their depth is the\n"
            "        // parse's own. This is also what ends the nested drops the loop below triggers.\n"
            "        if !matches!(&*self.lhs, Expr::Binary(_)) && !matches!(&*self.rhs, Expr::Binary(_)) {\n"
            "            return;\n"
            "        }\n"
            "        let mut stack: Vec<Expr> = vec![\n"
            "            ::std::mem::replace(&mut *self.lhs, _expr_drop_witness()),\n"
            "            ::std::mem::replace(&mut *self.rhs, _expr_drop_witness()),\n"
            "        ];\n"
            "        while let Some(below) = stack.pop() {\n"
            "            if let Expr::Binary(mut link) = below {\n"
            "                stack.push(::std::mem::replace(&mut *link.lhs, _expr_drop_witness()));\n"
            "                stack.push(::std::mem::replace(&mut *link.rhs, _expr_drop_witness()));\n"
            "            }\n"
            "            // The popped value drops here holding witnesses or bare operands, so its own\n"
            "            // teardown takes the fast path above.\n"
            "        }\n"
            "    }\n"
            "}"
        )

    def test_only_the_link_struct_carries_it_so_the_enum_stays_move_matchable(self, fold_src: str) -> None:
        assert "impl Drop for Expr {" not in fold_src
        assert "impl Drop for Term {" not in fold_src
        assert "impl Drop for Factor {" not in fold_src

    def test_a_renamed_link_variant_reaches_both_the_guard_and_the_loop(self) -> None:
        src = generate(
            fixtures.FOLD_GRAMMAR,
            fixtures.FOLD_SIDECAR.replace("fold_left: op;", "fold_left: op; variant Binary: Link;"),
        )
        body = block(src, "impl Drop for ExprLink {")
        assert "matches!(&*self.lhs, Expr::Link(_))" in body
        assert "if let Expr::Link(mut link) = below {" in body

    def test_a_grammar_with_no_fold_emits_neither(self, config_src: str) -> None:
        assert "impl Drop for" not in config_src
        assert "_drop_witness" not in config_src

    def test_a_chain_nothing_can_construct_an_operand_of_gets_no_drop(self) -> None:
        """The generator knows nothing about a `custom(...)` type, so it can name no sentinel."""
        src = generate(fixtures.CUSTOM_FOLD_GRAMMAR, fixtures.CUSTOM_FOLD_SIDECAR)
        assert "impl Drop for ExprBinary {" not in src
        assert "_expr_drop_witness" not in src

    def test_the_residual_is_recorded_where_the_consumer_reads_it(self) -> None:
        src = generate(fixtures.CUSTOM_FOLD_GRAMMAR, fixtures.CUSTOM_FOLD_SIDECAR)
        # The doc block the link struct carries: everything back to the blank line above it.
        declaration = src[: src.index("pub struct ExprBinary {")].rsplit("\n\n", 1)[1]
        assert declaration.startswith("/// One link of the left-nested chain rule `expr` folds into.")
        assert "/// Teardown recurses once per link:" in declaration

    def test_a_witness_bearing_chain_carries_no_residual_note(self, fold_src: str) -> None:
        assert "Teardown recurses once per link" not in fold_src

    def test_a_struct_operand_witness_names_every_member_and_empties_every_container(self) -> None:
        """The witness is code a consumer's compiler judges, so each member spelling has to be right."""
        assert block(generate(STRUCT_OPERAND_GRAMMAR, STRUCT_OPERAND_SIDECAR), _WITNESS_HEADER) == (
            "fn _expr_drop_witness() -> Expr {\n"
            "    Expr::Operand(Atom { tags: ::fltk_ast_core::IndexMap::new(), note: None, n: 0,"
            " span: ::fltk_cst_core::Span::unknown() })\n"
            "}"
        )

    def test_a_struct_operand_witness_carries_the_back_pointer_where_one_is_on(self) -> None:
        """``option cst = true;`` adds a member to every struct, so the witness has to fill it too."""
        src = generate(STRUCT_OPERAND_GRAMMAR, "option cst = true;\n" + STRUCT_OPERAND_SIDECAR)
        assert block(src, _WITNESS_HEADER).endswith(
            "span: ::fltk_cst_core::Span::unknown(), cst: None })\n}",
        )

    def test_a_wide_scalar_operand_witnesses_the_runtimes_own_zero(self) -> None:
        """Both spellings sit behind a `fltk-ast-core` feature, so nothing else in the tree names them."""
        src = generate(
            "expr := d:atom , ( , op:sign , d:atom)* ;\n"
            'sign := p:"+" | m:"-" ;\n'
            'atom := id:ident . "@" . amount:money ;\n'
            "ident := $/[0-9a-f-]+/ ;\nmoney := $/[0-9.]+/ ;\n",
            "rule expr  { fold_left: op; }\nrule sign  { transparent; }\n"
            "rule ident { type: uuid; transparent; }\nrule money { type: decimal; transparent; }\n",
        )
        assert block(src, _WITNESS_HEADER) == (
            "fn _expr_drop_witness() -> Expr {\n"
            "    Expr::Operand(Atom { id: ::fltk_ast_core::Uuid::nil(),"
            " amount: ::fltk_ast_core::Decimal::ZERO, span: ::fltk_cst_core::Span::unknown() })\n"
            "}"
        )

    def test_an_erased_enum_shaped_operand_witnesses_its_first_variant(self) -> None:
        src = generate(
            'expr := d:pick , ( , op:sign , d:pick)* ;\nsign := p:"+" | m:"-" ;\npick := a:"a" | b:"b" ;\n',
            "rule expr { fold_left: op; }\nrule sign { transparent; }\nrule pick { transparent; }\n",
        )
        assert block(src, _WITNESS_HEADER) == ("fn _expr_drop_witness() -> Expr {\n    Expr::Operand(PickValue::A)\n}")


class TestConverters:
    """The forward direction: ``from_cst`` per node form, and the helpers behind it.

    These assert the emitted source; that it compiles and converts is what the fixture crate
    will pin.
    """

    def test_a_product_reads_each_field_out_of_its_own_block(self, config_src: str) -> None:
        """Only `cst_node` and the buckets are bound, so no label can shadow what the body reads."""
        body = block(config_src, "impl Setting {")
        assert "pub fn from_cst(node: &::fltk_cst_core::Shared<cst::Setting>)" in body
        assert "let cst_node = node.read();" in body
        assert (
            '                let child = ::fltk_ast_core::one(&children_key, "setting", "key", cst_node.span())?;\n'
            in body
        )
        assert "                _erased_identifier_from_cst(child_node)?\n" in body
        assert "            span: cst_node.span().clone(),\n" in body

    def test_a_body_reading_several_labels_walks_the_children_once(self, config_src: str) -> None:
        """One pass, one bucket per label: a scan per field would be a pass and an allocation each."""
        body = block(config_src, "impl Setting {")
        assert (
            "        let mut children_key: Vec<&cst::SettingChild> = Vec::new();\n"
            "        let mut children_value: Vec<&cst::SettingChild> = Vec::new();\n"
            "        for (label, child) in cst_node.children() {\n"
            "            match label {\n"
            "                Some(cst::SettingLabel::Key) => children_key.push(child),\n"
            "                Some(cst::SettingLabel::Value) => children_value.push(child),\n"
            "                _ => {}\n"
            "            }\n"
            "        }\n"
        ) in body
        assert body.count("for (label, child) in cst_node.children()") == 1

    def test_a_body_reading_one_label_collects_it_directly(self, config_src: str) -> None:
        """A single label needs no dispatch, and a one-armed `match` is a clippy complaint."""
        body = block(config_src, "impl Config {")
        assert "        let children_stanza: Vec<&cst::ConfigChild> = cst_node\n" in body
        assert "            .filter(|(label, _)| matches!(label, Some(cst::ConfigLabel::Stanza)))\n" in body

    def test_a_collection_field_converts_every_child(self, config_src: str) -> None:
        body = block(config_src, "impl Config {")
        assert "let mut values = Vec::with_capacity(children_stanza.len());" in body
        assert "values.push(Stanza::from_cst(child_node)?);" in body

    def test_a_keyed_collection_rejects_a_repeated_key(self, config_src: str) -> None:
        body = block(config_src, "impl ServerDef {")
        assert "let mut keyed: ::fltk_ast_core::IndexMap<String, Setting> = ::fltk_ast_core::IndexMap::new();" in body
        assert "let key = element.key.clone();" in body
        assert '::fltk_ast_core::duplicate_key("setting", &key, &element.span, &previous.span)' in body, (
            "the two-span diagnostic is the point of a keyed collection"
        )

    def test_an_optional_field_stays_absent_when_no_child_carries_it(self, config_src: str) -> None:
        body = block(config_src, "impl MetricDef {")
        assert 'if let Some(child) = ::fltk_ast_core::optional(&children_interval, "metric_def", "interval"' in body
        assert "value = Some(_erased_number_from_cst(child_node)?);" in body

    def test_a_terminal_rule_reads_the_text_its_own_span_covers(self) -> None:
        src = generate("word := w:/[a-z]+/ ;")
        assert block(src, "impl Word {") == (
            "impl Word {\n"
            "    /// Convert a `word` CST node.\n"
            "    pub fn from_cst(node: &::fltk_cst_core::Shared<cst::Word>)"
            " -> Result<Self, ::fltk_ast_core::AstError> {\n"
            "        let cst_node = node.read();\n"
            "        Ok(Self {\n"
            '            text: ::fltk_ast_core::node_text(cst_node.span(), "word")?,\n'
            "            span: cst_node.span().clone(),\n"
            "        })\n"
            "    }\n"
            "}"
        )

    def test_a_redirected_terminal_rule_reads_the_named_child(self) -> None:
        src = generate(
            'quoted := "\\"" . content:/[^"]*/ . "\\"" ;',
            "rule quoted { text_from: content; }\n",
        )
        body = block(src, "impl Quoted {")
        assert "let cst::QuotedChild::Span(span_child) = child;" in body, "one kind of child needs no test"
        assert 'text: ::fltk_ast_core::text(span_child, "quoted", "content", cst_node.span())?,' in body

    def test_a_coerced_terminal_rule_parses_through_the_shared_helper(self) -> None:
        src = generate("count := d:/[0-9]+/ ;", "rule count { type: u32; }\n")
        assert 'value: ::fltk_ast_core::scalar::parse_u32(&text, "count", cst_node.span())?,' in src

    def test_a_custom_coercion_goes_through_the_sidecar_s_own_function(self) -> None:
        src = generate(
            "doc := amount:money ;\nmoney := d:/[0-9]+/ ;\n",
            'rule money { type: custom(rust_type: "crate::Money", rust_parse: "crate::parse_money", '
            'rust_unparse: "crate::render_money"); }\n',
        )
        assert (
            'value: ::fltk_ast_core::scalar::parse_custom(crate::parse_money, &text, "money", cst_node.span())?,' in src
        )

    def test_an_enum_shaped_rule_dispatches_on_the_label_never_the_text(self) -> None:
        src = generate('flag := yes:"yes" | no:"no" ;')
        body = block(src, "impl Flag {")
        assert "if cst_node.children().iter().any(|(label, _)| matches!(label, Some(cst::FlagLabel::Yes))) {" in body, (
            "the label is the datum; two spellings of one label are equivalent by construction"
        )
        assert "return Ok(Self { value: FlagValue::Yes, span: cst_node.span().clone() });" in body
        assert '"rule \\"flag\\": no alternative label is present"' in body

    def test_a_bool_rule_carries_the_plain_boolean(self) -> None:
        src = generate('boolean := true:"true" | false:"false" ;', "rule boolean { bool: true; }\n")
        body = block(src, "impl Boolean {")
        assert "return Ok(Self { value: true, span: cst_node.span().clone() });" in body
        assert "return Ok(Self { value: false, span: cst_node.span().clone() });" in body

    def test_a_sum_counts_its_children_and_takes_the_first_alternative_that_fits(self, config_src: str) -> None:
        assert block(config_src, "fn _stanza_alternative") == (
            "fn _stanza_alternative(node: &cst::Stanza) -> Option<usize> {\n"
            "    let mut counts = [0usize; 2];\n"
            "    for (label, child) in node.children() {\n"
            "        if matches!(label, Some(cst::StanzaLabel::ServerDef)) {\n"
            "            if matches!(child, cst::StanzaChild::ServerDef(_)) {\n"
            "                counts[0] += 1;\n"
            "            } else {\n"
            "                return None;\n"
            "            }\n"
            "        } else if matches!(label, Some(cst::StanzaLabel::MetricDef)) {\n"
            "            if matches!(child, cst::StanzaChild::MetricDef(_)) {\n"
            "                counts[1] += 1;\n"
            "            } else {\n"
            "                return None;\n"
            "            }\n"
            "        } else if label.is_some() {\n"
            "            return None;\n"
            "        }\n"
            "    }\n"
            "    if counts[0] == 1 && counts[1] == 0 {\n"
            "        return Some(0);\n"
            "    }\n"
            "    if counts[1] == 1 && counts[0] == 0 {\n"
            "        return Some(1);\n"
            "    }\n"
            "    None\n"
            "}"
        )

    def test_a_sum_variant_delegates_to_its_payload(self, config_src: str) -> None:
        body = block(config_src, "impl Stanza {\n    /// Convert")
        assert "(_stanza_alternative(&cst_node), cst_node.span().clone())" in body
        assert "Ok(Self::ServerDef(ServerDef::from_cst(child_node)?))" in body
        assert '"rule \\"stanza\\": no alternative matches the node\'s labeled children"' in body

    def test_a_generated_payload_converts_the_sum_s_own_node(self) -> None:
        src = generate("val := a:word , b:word | c:word ;\nword := w:/[a-z]+/ ;\n")
        assert "/// Convert the `Alt1` alternative of a `val` CST node." in src
        assert "pub fn from_cst(node: &::fltk_cst_core::Shared<cst::Val>)" in block(src, "impl ValAlt1 {")
        assert "Ok(Self::Alt1(ValAlt1::from_cst(node)?))" in src

    def test_a_generated_payload_the_variant_boxes_is_boxed_on_the_way_in(self) -> None:
        """The alternative closes a cycle back onto the sum, so the variant holds it through a `Box`.

        A converter handing the payload over unboxed is an E0308 in every consumer's build, which
        an emitted-source assertion is the cheapest place to notice.
        """
        src = generate('sum := lhs:sum . "+" . rhs:num | first:num ;\nnum := d:/[0-9]+/ ;\n')
        assert "    Alt1(Box<SumAlt1>),\n" in block(src, "pub enum Sum")
        assert "Ok(Self::Alt1(Box::new(SumAlt1::from_cst(node)?)))" in block(src, "impl Sum {\n    /// Convert")

    def test_a_field_enum_converter_dispatches_on_the_child_s_kind(self) -> None:
        src = generate('wrap := ( a:num | a:word ) . ";" ;\nnum := d:/[0-9]+/ ;\nword := w:/[a-z]+/ ;\n')
        assert block(src, "fn _wrap_a_from_cst") == (
            "fn _wrap_a_from_cst(child: &cst::WrapChild, _span: &::fltk_cst_core::Span)"
            " -> Result<WrapA, ::fltk_ast_core::AstError> {\n"
            "    match child {\n"
            "        cst::WrapChild::Num(child_node) => Ok(WrapA::Num(Num::from_cst(child_node)?)),\n"
            "        cst::WrapChild::Word(child_node) => Ok(WrapA::Word(Word::from_cst(child_node)?)),\n"
            "    }\n"
            "}"
        )
        assert "_wrap_a_from_cst(child, cst_node.span())?" in block(src, "impl Wrap {")

    def test_a_field_enum_that_cannot_hold_every_child_kind_refuses_the_rest(self) -> None:
        """The label carries two of the rule's three kinds, so the third takes the error arm.

        That arm is what ``fltk_ast_core::unexpected_child`` exists for, and the live ``span``
        parameter it needs is the difference between a clean build and an unused-variable
        warning under ``-D warnings``.
        """
        src = generate(
            'wrap := ( a:num | a:word ) . b:other . ";" ;\n'
            "num := d:/[0-9]+/ ;\nword := w:/[a-z]+/ ;\nother := o:/[A-Z]+/ ;\n"
        )
        assert block(src, "fn _wrap_a_from_cst") == (
            "fn _wrap_a_from_cst(child: &cst::WrapChild, span: &::fltk_cst_core::Span)"
            " -> Result<WrapA, ::fltk_ast_core::AstError> {\n"
            "    match child {\n"
            "        cst::WrapChild::Num(child_node) => Ok(WrapA::Num(Num::from_cst(child_node)?)),\n"
            "        cst::WrapChild::Word(child_node) => Ok(WrapA::Word(Word::from_cst(child_node)?)),\n"
            '        _ => Err(::fltk_ast_core::unexpected_child("wrap", "a", span)),\n'
            "    }\n"
            "}"
        )

    def test_a_field_enum_holding_text_reads_the_span_it_was_handed(self) -> None:
        """A scalar variant reports against the owner's span, so the parameter is live here too."""
        src = generate('wrap := ( a:num | a:/[A-Z]+/ ) . ";" ;\nnum := d:/[0-9]+/ ;\n')
        assert block(src, "fn _wrap_a_from_cst") == (
            "fn _wrap_a_from_cst(child: &cst::WrapChild, span: &::fltk_cst_core::Span)"
            " -> Result<WrapA, ::fltk_ast_core::AstError> {\n"
            "    match child {\n"
            "        cst::WrapChild::Num(child_node) => Ok(WrapA::Num(Num::from_cst(child_node)?)),\n"
            "        cst::WrapChild::Span(span_child) =>"
            ' Ok(WrapA::Text(::fltk_ast_core::text(span_child, "wrap", "a", span)?)),\n'
            "    }\n"
            "}"
        )

    def test_a_presence_flag_asks_whether_the_keyword_is_there(self) -> None:
        src = generate('decl := type:word , pub:"pub"? ;\nword := w:/[a-z]+/ ;\n')
        assert '::fltk_ast_core::presence(&children_pub, "decl", "pub", cst_node.span())?' in src

    def test_a_labeled_literal_field_takes_the_span_and_nothing_else(self) -> None:
        src = generate('marks := bang:"!" , stars:"*"* ;')
        body = block(src, "impl Marks {")
        assert (
            "                let cst::MarksChild::Span(span_child) = child else {\n"
            '                    return Err(::fltk_ast_core::unexpected_child("marks", "bang", cst_node.span()));\n'
            "                };\n"
        ) in body, "a trivia child is not a literal, and the refusal is the whole point of the `else`"
        assert "values.push(span_child.clone());" in body

    def test_a_marker_product_carries_only_its_span(self) -> None:
        src = generate('marker := "!" . "?" ;')
        assert block(src, "impl Marker {") == (
            "impl Marker {\n"
            "    /// Convert a `marker` CST node.\n"
            "    pub fn from_cst(node: &::fltk_cst_core::Shared<cst::Marker>)"
            " -> Result<Self, ::fltk_ast_core::AstError> {\n"
            "        let cst_node = node.read();\n"
            "        Ok(Self {\n"
            "            span: cst_node.span().clone(),\n"
            "        })\n"
            "    }\n"
            "}"
        )

    def test_an_erased_rule_hands_back_its_payload(self, config_src: str) -> None:
        assert block(config_src, "fn _erased_number_from_cst") == (
            "fn _erased_number_from_cst(node: &::fltk_cst_core::Shared<cst::Number>)"
            " -> Result<i64, ::fltk_ast_core::AstError> {\n"
            "    let cst_node = node.read();\n"
            '    let text = ::fltk_ast_core::node_text(cst_node.span(), "number")?;\n'
            '    ::fltk_ast_core::scalar::parse_i64(&text, "number", cst_node.span())\n'
            "}"
        )

    def test_a_custom_rule_is_reached_through_the_trait(self) -> None:
        src = generate(
            "holder := amount:money ;\nmoney := d:/[0-9]+/ ;\n",
            'rule money { custom(rust: "crate::Money", python: "app.Money"); }\n',
        )
        assert (
            "<crate::Money as ::fltk_ast_core::FromCst<::fltk_cst_core::Shared<cst::Money>>>::from_cst(child_node)?"
            in src
        )

    def test_a_flattened_wrapper_hands_its_fields_to_its_use_site(self, task_src: str) -> None:
        assert (
            "fn _flat_schedule_from_cst(node: &::fltk_cst_core::Shared<cst::Schedule>)"
            " -> Result<(i64, TimeUnitValue)," in task_src
        )
        body = block(task_src, "impl TaskDef {")
        assert "let hoisted_schedule = {" in body
        assert "let (v0, v1) = _flat_schedule_from_cst(child_node)?;" in body
        assert "(Some(v0), Some(v1))" in body, "an optional use site degrades the hoisted fields"
        assert "None => (None, None)," in body
        assert "interval: hoisted_schedule.0," in body

    def test_a_recursive_field_is_boxed_on_the_way_in(self) -> None:
        src = generate(TREE_GRAMMAR)
        body = block(src, "impl Tree {\n    /// Convert")
        assert "value = Some(Box::new(Tree::from_cst(child_node)?));" in body
        assert "values.push(Tree::from_cst(child_node)?);" in body, "a collection is already an indirection"

    def test_the_back_pointer_is_the_node_the_value_came_from(self) -> None:
        src = generate("word := w:/[a-z]+/ ;", "option cst = true;\n")
        assert "cst: Some(node.clone())," in block(src, "impl Word {")


class TestFoldConverters:
    """A fold rule's ``from_cst``: two runs of children, then the runtime's fold.

    What the emitted source has to get right is the split of work — the nesting order, the span
    merging and the arity diagnostic belong to the runtime, and only the two closures name
    generated types.  That the chain comes out nested the right way round is pinned by the
    compile-and-run gate (``tests/test_generated_rust_gate.py``).
    """

    RIGHT_SIDECAR = fixtures.FOLD_SIDECAR.replace("fold_left: op", "fold_right: op")

    @staticmethod
    def renamed(member: str) -> str:
        """``FOLD_SIDECAR`` with ``expr``'s operator member renamed, in its own single block."""
        return fixtures.FOLD_SIDECAR.replace(
            "rule expr       { fold_left: op; }",
            f"rule expr {{ fold_left: op; field op {{ name: {member}; }} }}",
        )

    def test_the_operands_and_operators_are_bucketed_and_counted(self, fold_src: str) -> None:
        body = block(fold_src, "impl Expr {\n    /// Convert")
        assert "pub fn from_cst(node: &::fltk_cst_core::Shared<cst::Expr>)" in body
        assert (
            "        let mut children_term: Vec<&cst::ExprChild> = Vec::new();\n"
            "        let mut children_op: Vec<&cst::ExprChild> = Vec::new();\n" in body
        )
        assert (
            "        ::fltk_ast_core::check_fold_arity("
            'children_term.len(), children_op.len(), "expr", cst_node.span())?;\n' in body
        )

    def test_each_operand_carries_the_span_of_its_own_child(self, fold_src: str) -> None:
        """A link's span is merged out of these, and an erased operand has none of its own."""
        body = block(fold_src, "impl Expr {\n    /// Convert")
        assert (
            "        let mut operands = Vec::with_capacity(children_term.len());\n"
            "        for child in &children_term {\n"
            "            let cst::ExprChild::Term(child_node) = child else {\n"
            '                return Err(::fltk_ast_core::unexpected_child("expr", "term", cst_node.span()));\n'
            "            };\n"
            "            let operand_span = child_node.read().span().clone();\n"
            "            operands.push((Term::from_cst(child_node)?, operand_span));\n"
            "        }\n" in body
        )

    def test_the_operators_are_converted_in_source_order(self, fold_src: str) -> None:
        body = block(fold_src, "impl Expr {\n    /// Convert")
        assert (
            "        let mut operators = Vec::with_capacity(children_op.len());\n"
            "        for child in &children_op {\n"
            "            let cst::ExprChild::AddOp(child_node) = child else {\n"
            '                return Err(::fltk_ast_core::unexpected_child("expr", "op", cst_node.span()));\n'
            "            };\n"
            "            operators.push(_erased_add_op_from_cst(child_node)?);\n"
            "        }\n" in body
        )

    def test_the_two_closures_are_the_only_part_naming_generated_types(self, fold_src: str) -> None:
        body = block(fold_src, "impl Expr {\n    /// Convert")
        assert (
            "        ::fltk_ast_core::fold_left(\n"
            '            "expr",\n'
            "            cst_node.span(),\n"
            "            operands,\n"
            "            operators,\n"
            "            |operand| Self::Operand(Box::new(operand)),\n"
            "            |operator, lhs, rhs, span| {\n"
            "                Self::Binary(ExprBinary {\n"
            "                    op: operator,\n"
            "                    lhs: Box::new(lhs),\n"
            "                    rhs: Box::new(rhs),\n"
            "                    span,\n"
            "                })\n"
            "            },\n"
            "        )\n" in body
        )

    def test_the_direction_picks_the_runtime_helper(self) -> None:
        src = generate(fixtures.FOLD_GRAMMAR, self.RIGHT_SIDECAR)
        assert "::fltk_ast_core::fold_right(" in block(src, "impl Expr {\n    /// Convert")
        assert "::fltk_ast_core::fold_left(" not in src

    def test_an_unboxed_operand_is_handed_over_as_the_constructor_itself(self) -> None:
        """`sum`'s operand closes no cycle, so the payload is unboxed and the variant is the function.

        A closure that only calls the constructor is a `clippy::redundant_closure`, which is a hard
        build failure in a consumer compiling generated code with `-D warnings`.
        """
        src = generate(
            'sum := num , ( , op:add_op , num)* ;\nadd_op := plus:"+" | minus:"-" ;\nnum := d:/[0-9]+/ ;\n',
            "rule sum { fold_left: op; }\nrule add_op { transparent; }\n",
        )
        assert "    Operand(Num),\n" in block(src, "pub enum Sum")
        body = block(src, "impl Sum {\n    /// Convert")
        assert "            Self::Operand,\n" in body
        assert "|operand|" not in body

    def test_a_renamed_operator_member_keeps_the_closure_parameter(self) -> None:
        src = generate(fixtures.FOLD_GRAMMAR, self.renamed("sign"))
        assert "                    sign: operator,\n" in block(src, "impl Expr {\n    /// Convert")

    def test_an_operator_member_already_called_operator_is_not_named_twice(self) -> None:
        """`operator: operator` is a redundant field name, which `-D warnings` refuses."""
        src = generate(fixtures.FOLD_GRAMMAR, self.renamed("operator"))
        assert "                    operator,\n" in block(src, "impl Expr {\n    /// Convert")

    def test_a_synthesized_link_stands_for_no_cst_node(self, fold_src: str) -> None:
        src = generate(fixtures.FOLD_GRAMMAR, "option cst = true;\n" + fixtures.FOLD_SIDECAR)
        body = block(src, "impl Expr {\n    /// Convert")
        assert "                    cst: None,\n" in body
        assert "cst: None," not in block(fold_src, "impl Expr {\n    /// Convert")


class TestDispatchConditions:
    """The comparison a count bound renders as, which is what picks the alternative at runtime.

    A wrong operator here is legal Rust that selects the wrong alternative for a CST the parser
    just produced, so no compile gate can catch it.
    """

    LEAVES = "word := w:/[a-z]+/ ;\nother := o:/[0-9]+/ ;\n"

    def conditions(self, body: str) -> list[str]:
        src = generate(f"s := {body} ;\n{self.LEAVES}")
        return [line.strip() for line in block(src, "fn _s_alternative").splitlines() if line.startswith("    if ")]

    def test_a_repeated_label_compares_against_its_minimum(self) -> None:
        assert self.conditions("a:word+ . b:other | c:word")[0] == (
            "if counts[0] >= 1 && counts[1] == 1 && counts[2] == 0 {"
        )

    def test_an_optional_label_compares_against_its_maximum(self) -> None:
        assert self.conditions("a:word . b:word? | c:other")[0] == (
            "if counts[0] == 1 && counts[1] <= 1 && counts[2] == 0 {"
        )

    def test_a_label_present_exactly_once_compares_for_equality(self, config_src: str) -> None:
        assert "if counts[0] == 1 && counts[1] == 0 {" in block(config_src, "fn _stanza_alternative")

    def test_a_rule_holding_one_kind_of_child_counts_without_a_kind_test(self) -> None:
        """No clause reads the child, so it must not be bound by name: that is a warning."""
        src = generate(f's := a:word . "!" | b:word . c:word ;\n{self.LEAVES}')
        body = block(src, "fn _s_alternative")
        assert "for (label, _child) in node.children() {" in body
        assert "matches!(child" not in body
        assert (
            "        if matches!(label, Some(cst::SLabel::A)) {\n"
            "            counts[0] += 1;\n"
            "        } else if matches!(label, Some(cst::SLabel::B)) {\n"
        ) in body

    def test_a_rule_holding_several_kinds_binds_the_child_it_tests(self, config_src: str) -> None:
        body = block(config_src, "fn _stanza_alternative")
        assert "for (label, child) in node.children() {" in body
        assert "if matches!(child, cst::StanzaChild::ServerDef(_)) {" in body


class TestFlattenShapes:
    """The hoist spellings ``TASK_GRAMMAR``'s single optional two-field wrapper does not reach."""

    LEAVES = "identifier := name:/[a-z_]+/ ;\nnumber := val:/[0-9]+/ ;\n"
    LEAF_SIDECAR = "rule identifier { transparent; }\nrule number { type: i64; transparent; }\n"

    WRAPPER_GRAMMAR = (
        'doc := "doc" : extra? , ";" , ;\n'
        'extra := "with" : pub:"pub"? , setting* ;\n'
        'setting := key:identifier , "=" , value:number , ";" , ;\n'
    ) + LEAVES

    ONE_FIELD_GRAMMAR = 'doc := "doc" : only? , ";" , ;\nonly := "of" : n:number ;\n' + LEAVES

    CYCLE_GRAMMAR = 'tree := name:word . wrap? ;\nwrap := "(" . t:tree . ")" ;\nword := w:/[a-z]+/ ;\n'
    OPTIONAL_CYCLE_GRAMMAR = 'tree := name:word . wrap? ;\nwrap := "(" . t:tree? . ")" ;\nword := w:/[a-z]+/ ;\n'
    REQUIRED_CYCLE_GRAMMAR = 'tree := name:word . wrap ;\nwrap := "(" . t:tree . ")" ;\nword := w:/[a-z]+/ ;\n'

    def test_a_required_use_site_reads_the_wrapper_unconditionally(self) -> None:
        """No ``match``, no absent arm: a required wrapper is always there to hoist from."""
        src = generate(
            'task_def := "task" : name:identifier , schedule , "{" , "}" , ;\n'
            'schedule := "every" : interval:number . unit:time_unit ;\n'
            'time_unit := sec:"s" | min:"m" ;\n' + self.LEAVES,
            self.LEAF_SIDECAR + "rule schedule { flatten; }\nrule time_unit { transparent; }\n",
        )
        body = block(src, "impl TaskDef {")
        assert (
            "        let hoisted_schedule = {\n"
            '            let child = ::fltk_ast_core::one(&children_schedule, "task_def", "schedule",'
            " cst_node.span())?;\n"
        ) in body
        assert "match ::fltk_ast_core::optional" not in body
        assert "let (v0, v1) = _flat_schedule_from_cst(child_node)?;\n            (v0, v1)" in body

    def test_an_absent_wrapper_leaves_a_flag_false_and_a_collection_empty(self) -> None:
        src = generate(self.WRAPPER_GRAMMAR, self.LEAF_SIDECAR + "rule extra { flatten; }\n")
        assert "None => (false, Vec::new())," in block(src, "impl Doc {")

    def test_an_absent_wrapper_leaves_a_keyed_collection_empty(self) -> None:
        src = generate(
            self.WRAPPER_GRAMMAR,
            self.LEAF_SIDECAR + "rule extra { flatten; }\nrule setting { key: key; }\n",
        )
        assert "None => (false, ::fltk_ast_core::IndexMap::new())," in block(src, "impl Doc {")

    def test_a_wrapper_of_one_field_hands_back_a_one_element_tuple(self) -> None:
        """The trailing comma is the difference between a tuple and a parenthesized value."""
        src = generate(self.ONE_FIELD_GRAMMAR, self.LEAF_SIDECAR + "rule only { flatten; }\n")
        assert "fn _flat_only_from_cst(node: &::fltk_cst_core::Shared<cst::Only>) -> Result<(i64,)," in src
        body = block(src, "impl Doc {")
        assert "let (v0,) = _flat_only_from_cst(child_node)?;" in body
        assert "(Some(v0),)" in body
        assert "None => (None,)," in body

    @pytest.mark.parametrize(
        ("grammar", "spelling"),
        [
            (CYCLE_GRAMMAR, "(Some(Box::new(v0)),)"),
            (OPTIONAL_CYCLE_GRAMMAR, "(v0.map(Box::new),)"),
            (REQUIRED_CYCLE_GRAMMAR, "(Box::new(v0),)"),
        ],
        ids=["optional site", "optional site, optional field", "required site"],
    )
    def test_a_hoisted_field_inside_a_cycle_is_boxed_where_the_owner_holds_it(
        self, grammar: str, spelling: str
    ) -> None:
        """Without the ``Box`` the containing type is infinitely sized and does not compile."""
        src = generate(grammar, "rule wrap { flatten; }\n")
        assert spelling in block(src, "impl Tree {\n    /// Convert")


class TestReverseConverters:
    """``to_cst`` on the forms whose whole CST node comes out of their own value."""

    def test_a_terminal_rule_gets_one_static_holding_its_alternatives(self, leaf_src: str) -> None:
        """The patterns are data; the regexes behind them are compiled on first use."""
        assert (
            "static _TAG_TERMINALS: ::fltk_ast_core::TerminalShape =\n"
            "    ::fltk_ast_core::TerminalShape::new(&[\n"
            "        ::fltk_ast_core::TerminalAlt {\n"
            '            pattern: Some("(?:\\\\#)(?P<_ast_g1>[a-z]+)"),\n'
            '            groups: &[None, Some("_ast_g1")],\n'
            "        },\n"
            "        ::fltk_ast_core::TerminalAlt {\n"
            '            pattern: Some("(?P<_ast_g0>[A-Z]+)"),\n'
            '            groups: &[Some("_ast_g0")],\n'
            "        },\n"
            "    ]);\n"
        ) in leaf_src

    def test_a_terminal_rule_splits_its_own_text_across_the_grammars_items(self, leaf_src: str) -> None:
        assert block(leaf_src, "impl Num {\n    /// Synthesise") == (
            "impl Num {\n"
            "    /// Synthesise a `num` CST node from the text of `text`.\n"
            "    pub fn to_cst(&self) -> Result<::fltk_cst_core::Shared<cst::Num>, ::fltk_ast_core::AstError> {\n"
            "        let text = self.text.as_str();\n"
            '        let split = _NUM_TERMINALS.split(text, "num")?;\n'
            "        let mut cst_node = cst::Num::new(::fltk_ast_core::source_span(text));\n"
            "        cst_node.push_child(Some(cst::NumLabel::D), cst::NumChild::Span(split.spans[0].clone()));\n"
            "        Ok(cst_node.into())\n"
            "    }\n"
            "}"
        )

    def test_the_alternative_the_text_matched_decides_which_children_are_appended(self, leaf_src: str) -> None:
        body = block(leaf_src, "impl Tag {\n    /// Synthesise")
        assert "if split.alternative == 0 {" in body
        # The `$`-included literal takes a position; only the regex item takes a span from the split.
        assert "cst_node.push_child(None, cst::TagChild::Span(split.spans[0].clone()));" in body
        assert "cst_node.push_child(Some(cst::TagLabel::Name), cst::TagChild::Span(split.spans[1].clone()));" in body
        assert "} else if split.alternative == 1 {" in body
        assert "cst_node.push_child(Some(cst::TagLabel::Name), cst::TagChild::Span(split.spans[0].clone()));" in body

    def test_a_redirected_text_leaves_the_node_span_unknown(self, leaf_src: str) -> None:
        """``from_cst`` reads the text off the named child there, not off the node's own span."""
        body = block(leaf_src, "impl Quoted {\n    /// Synthesise")
        assert "let cst_node = cst::Quoted::new" not in body
        assert "let mut cst_node = cst::Quoted::new(::fltk_cst_core::Span::unknown());" in body
        assert "push_child(Some(cst::QuotedLabel::Content)" in body

    def test_an_integer_coercion_renders_natively(self, leaf_src: str) -> None:
        """The member is the width itself, so there is no range left to check."""
        assert "let rendered = self.value.to_string();" in block(leaf_src, "impl Count {\n    /// Synthesise")

    def test_a_float_coercion_renders_through_the_shared_renderer(self, leaf_src: str) -> None:
        body = block(leaf_src, "impl Ratio {\n    /// Synthesise")
        assert 'let rendered = ::fltk_ast_core::scalar::render_f32(self.value, "ratio", &self.span)?;' in body

    def test_the_wide_builtins_render_through_the_runtime(self) -> None:
        src = generate(
            "doc := id:ident , amount:money ;\nident := d:/[0-9a-f-]+/ ;\nmoney := m:/[0-9.]+/ ;\n",
            "rule ident { type: uuid; }\nrule money { type: decimal; }\n",
        )
        assert "let rendered = ::fltk_ast_core::scalar::render_uuid(&self.value);" in src
        assert "let rendered = ::fltk_ast_core::scalar::render_decimal(&self.value);" in src

    def test_a_custom_coercion_renders_through_the_users_function(self) -> None:
        src = generate(
            "money := d:/[0-9]+/ ;\n",
            'rule money { type: custom(rust_type: "crate::Money", rust_parse: "crate::parse",'
            ' rust_unparse: "crate::render", py_type: "app.Money", py_parse: "app.parse",'
            ' py_unparse: "app.render"); }\n',
        )
        assert "let rendered = crate::render(&self.value);" in src

    def test_a_custom_coercion_without_a_rust_unparse_entry_cannot_be_emitted(self) -> None:
        """The validator refuses this when Rust is a target, so only a hand-built config reaches it."""
        grammar = fixtures.classified_grammar("money := d:/[0-9]+/ ;\n")
        python_only = ac.load_ast_config(
            'rule money { type: custom(rust_type: "crate::Money", rust_parse: "crate::parse",'
            ' py_type: "app.Money", py_parse: "app.parse", py_unparse: "app.render"); }\n',
            grammar,
            {ac.Backend.PYTHON},
        )
        with pytest.raises(ValueError, match=r"names no `rust_unparse:` type"):
            gsm2ast_rs.generate_ast_rs(am.build_ast_model(grammar, python_only))

    def test_an_enum_shaped_rule_matches_its_value_to_the_alternatives_label(self, leaf_src: str) -> None:
        assert block(leaf_src, "impl Pick {\n    /// Synthesise") == (
            "impl Pick {\n"
            "    /// Synthesise a `pick` CST node for the alternative `value` names.\n"
            "    pub fn to_cst(&self) -> Result<::fltk_cst_core::Shared<cst::Pick>, ::fltk_ast_core::AstError> {\n"
            "        let label = match self.value {\n"
            "            PickValue::A => cst::PickLabel::A,\n"
            "            PickValue::B => cst::PickLabel::B,\n"
            "        };\n"
            "        let mut cst_node = cst::Pick::new(::fltk_cst_core::Span::unknown());\n"
            "        cst_node.push_child(Some(label), cst::PickChild::Span(::fltk_cst_core::Span::unknown()));\n"
            "        Ok(cst_node.into())\n"
            "    }\n"
            "}"
        )

    def test_a_boolean_rule_names_the_alternative_its_value_stands_for(self, leaf_src: str) -> None:
        body = block(leaf_src, "impl Flag {\n    /// Synthesise")
        assert "let label = if self.value {\n            cst::FlagLabel::Yes\n        } else {\n" in body
        assert "            cst::FlagLabel::No\n        };\n" in body

    def test_an_erased_rule_crosses_the_boundary_through_a_helper(self, config_src: str) -> None:
        """A `transparent;` rule has no type to hang a method on; its use sites call a function."""
        assert "impl Number {" not in config_src
        assert (
            "fn _erased_number_to_cst(value: &i64) -> Result<::fltk_cst_core::Shared<cst::Number>,"
            " ::fltk_ast_core::AstError> {\n"
        ) in config_src
        # It still splits its text back across the grammar's items, so it still needs the table.
        assert "static _NUMBER_TERMINALS: ::fltk_ast_core::TerminalShape =" in config_src
        # An enum-shaped rule carries no text at all, so it has no table either way.
        assert "_METRIC_TYPE_TERMINALS" not in config_src

    def test_a_shape_no_split_can_rebuild_still_gets_a_table(self) -> None:
        """A repeated included item leaves no determined split, which the runtime reports."""
        src = generate("parts := p:/[a-z]/* ;")
        assert (
            "static _PARTS_TERMINALS: ::fltk_ast_core::TerminalShape =\n"
            "    ::fltk_ast_core::TerminalShape::new(&[\n"
            "        ::fltk_ast_core::TerminalAlt {\n"
            "            pattern: None,\n"
            "            groups: &[],\n"
            "        },\n"
            "    ]);\n"
        ) in src
        body = block(src, "impl Parts {\n    /// Synthesise")
        # Nothing is appended, so the node needs no `mut` — and the split still runs, because it
        # is what refuses the text.
        assert '        let _split = _PARTS_TERMINALS.split(text, "parts")?;\n' in body
        assert "        let cst_node = cst::Parts::new(::fltk_ast_core::source_span(text));\n" in body


MERGED_GRAMMAR = 'import := "import" : name:word | "import" : name:word : "as" : alias:word ;\nword := w:/[a-z]+/ ;\n'
"""Two alternatives, one a strict subset of the other: a merged product, so ``to_cst`` trials them."""

BRANCH_GRAMMAR = (
    'doc := bang:"!" , stars:"*"* , pub:"pub"? , ( a:num | a:word ) , part:word , ( "." . part:word )* ;\n'
    "num := d:/[0-9]+/ ;\nword := w:/[a-z]+/ ;\n"
)
"""Labeled literals at three arities, an alternation over one label, and a repeated label."""


@pytest.fixture(scope="module")
def branch_src() -> str:
    return generate(BRANCH_GRAMMAR)


class TestReverseProducts:
    """``to_cst`` on the forms that hold fields, and hand each field's values to item positions."""

    def test_a_products_fields_are_handed_to_the_positions_that_carry_them(self, config_src: str) -> None:
        assert block(config_src, "impl Setting {\n    /// Synthesise") == (
            "impl Setting {\n"
            "    /// Synthesise a `setting` CST node from this value's fields.\n"
            "    pub fn to_cst(&self) -> Result<::fltk_cst_core::Shared<cst::Setting>, ::fltk_ast_core::AstError> {\n"
            "        let mut cst_node = cst::Setting::new(::fltk_cst_core::Span::unknown());\n"
            "        let mut cursor_key = ::fltk_ast_core::Cursor::new(vec![&self.key]);\n"
            "        let mut cursor_value = ::fltk_ast_core::Cursor::new(vec![&self.value]);\n"
            "        let taken = cursor_key.take(1, 0);\n"
            '        ::fltk_ast_core::filled(taken.len(), 1, "setting", "key")?;\n'
            "        for item in taken {\n"
            "            cst_node.push_child(\n"
            "                Some(cst::SettingLabel::Key),\n"
            "                cst::SettingChild::Identifier(_erased_identifier_to_cst(item)?),\n"
            "            );\n"
            "        }\n"
            "        let taken = cursor_value.take(1, 0);\n"
            '        ::fltk_ast_core::filled(taken.len(), 1, "setting", "value")?;\n'
            "        for item in taken {\n"
            "            cst_node.push_child(Some(cst::SettingLabel::Value),"
            " cst::SettingChild::Value(item.to_cst()?));\n"
            "        }\n"
            '        ::fltk_ast_core::check_consumed("setting", "key", cursor_key.remaining())?;\n'
            '        ::fltk_ast_core::check_consumed("setting", "value", cursor_value.remaining())?;\n'
            "        Ok(cst_node.into())\n"
            "    }\n"
            "}"
        )

    def test_an_optional_position_has_no_lower_bound_to_check(self, config_src: str) -> None:
        body = block(config_src, "impl MetricDef {\n    /// Synthesise")
        assert "let taken = cursor_interval.take(1, 0);\n" in body
        assert '"metric_def", "interval")?' not in body, "an absent optional is not a shortfall"

    def test_a_keyed_collection_is_iterated_in_insertion_order(self, config_src: str) -> None:
        """The map's keys are never read back: each element carries the authoritative one."""
        body = block(config_src, "impl ServerDef {\n    /// Synthesise")
        assert "let mut cursor_setting = ::fltk_ast_core::Cursor::new(self.settings.values().collect());" in body

    def test_a_merged_product_delegates_to_the_first_alternative_that_fits(self) -> None:
        src = generate(MERGED_GRAMMAR)
        assert block(src, "impl Import {\n    /// Synthesise a") == (
            "impl Import {\n"
            "    /// Synthesise a `import` CST node from this value's fields.\n"
            "    pub fn to_cst(&self) -> Result<::fltk_cst_core::Shared<cst::Import>, ::fltk_ast_core::AstError> {\n"
            "        let present = ::fltk_ast_core::populated"
            '(&[("name", true), ("alias", self.alias.is_some())]);\n'
            '        if ::fltk_ast_core::alternative_fits(&present, &["name"], &["name"]) {\n'
            "            return self.to_cst_alt0();\n"
            "        }\n"
            "        if ::fltk_ast_core::alternative_fits(&present,"
            ' &["alias", "name"], &["alias", "name"]) {\n'
            "            return self.to_cst_alt1();\n"
            "        }\n"
            '        Err(::fltk_ast_core::AstError::new("rule \\"import\\":'
            ' no alternative fits the populated fields", ::fltk_cst_core::Span::unknown()))\n'
            "    }\n"
            "}"
        )

    UNION_LABEL_GRAMMAR = "val := item:num | item:word | item:/[!@#]+/ ;\nnum := d:/[0-9]+/ ;\nword := c:/[a-z]+/ ;\n"
    """One label carrying three types, so every alternative's populated names are identical."""

    def test_alternatives_sharing_a_label_signature_are_told_apart_by_kind(self) -> None:
        src = generate(self.UNION_LABEL_GRAMMAR, "rule val { product; }\n")
        assert block(src, "impl Val {\n    /// Synthesise a") == (
            "impl Val {\n"
            "    /// Synthesise a `val` CST node from this value's fields.\n"
            "    pub fn to_cst(&self) -> Result<::fltk_cst_core::Shared<cst::Val>, ::fltk_ast_core::AstError> {\n"
            '        let present = ::fltk_ast_core::populated(&[("item", true)]);\n'
            '        if ::fltk_ast_core::alternative_fits(&present, &["item"], &["item"])'
            " && matches!(self.item, ValItem::Num(_)) {\n"
            "            return self.to_cst_alt0();\n"
            "        }\n"
            '        if ::fltk_ast_core::alternative_fits(&present, &["item"], &["item"])'
            " && matches!(self.item, ValItem::Word(_)) {\n"
            "            return self.to_cst_alt1();\n"
            "        }\n"
            '        if ::fltk_ast_core::alternative_fits(&present, &["item"], &["item"])'
            " && matches!(self.item, ValItem::Text(_)) {\n"
            "            return self.to_cst_alt2();\n"
            "        }\n"
            '        Err(::fltk_ast_core::AstError::new("rule \\"val\\":'
            ' no alternative fits the populated fields", ::fltk_cst_core::Span::unknown()))\n'
            "    }\n"
            "}"
        )

    SCALAR_VARIANT_GRAMMAR = 'doc := a:"lit" , a:/[0-9]+/ , a:item ;\nitem := n:/[a-z]+/ ;\n'
    """A literal, a regex and a node under one label: the literal's span is text where the label
    carries anything else, so the field enum's scalar variants are the one ``Text``."""

    def test_a_literal_and_a_regex_position_place_through_one_scalar_variant(self) -> None:
        body = block(generate(self.SCALAR_VARIANT_GRAMMAR), "impl Doc {\n    /// Synthesise")
        assert 'let taken = cursor_a.take_if(1, 0, |item| matches!(item, DocA::Text(text) if text == "lit"));' in body
        assert "let taken = cursor_a.take_if(1, 0, |item| matches!(item, DocA::Text(_)));" in body
        assert "let taken = cursor_a.take_if(1, 0, |item| matches!(item, DocA::Item(_)));" in body
        # The literal renders from the grammar; only the regex position reads the text it took.
        assert body.count("let DocA::Text(inner) = item else {") == 1

    def test_an_optional_union_field_passes_the_kind_test_when_it_is_absent(self) -> None:
        src = generate(
            "top := x:num? , y:word | x:word? ;\nnum := d:/[0-9]+/ ;\nword := c:/[a-z]+/ ;\n",
            "rule top { product; }\n",
        )
        body = block(src, "impl Top {\n    /// Synthesise a")
        assert "&& self.x.as_ref().into_iter().all(|item| matches!(item, TopX::Num(_)))" in body
        assert "&& self.x.as_ref().into_iter().all(|item| matches!(item, TopX::Word(_)))" in body

    def test_every_value_of_a_repeated_union_field_has_to_be_an_accepted_kind(self) -> None:
        src = generate(
            "top := x:num* , y:word | x:word* ;\nnum := d:/[0-9]+/ ;\nword := c:/[a-z]+/ ;\n",
            "rule top { product; }\n",
        )
        body = block(src, "impl Top {\n    /// Synthesise a")
        assert "&& self.x.iter().all(|item| matches!(item, TopX::Num(_)))" in body
        assert "&& self.x.iter().all(|item| matches!(item, TopX::Word(_)))" in body

    def test_a_cursor_no_position_draws_from_is_not_mutable(self) -> None:
        """The alternative that has no `alias` position still reads the cursor for what it holds."""
        body = block(generate(MERGED_GRAMMAR), "impl Import {\n    /// Synthesise alternative 0")
        assert "let cursor_alias = ::fltk_ast_core::Cursor::new(self.alias.iter().collect());" in body
        assert '::fltk_ast_core::check_consumed("import", "alias", cursor_alias.remaining())?;' in body

    def test_a_sums_variant_is_the_alternative_so_nothing_is_tried(self, config_src: str) -> None:
        body = block(config_src, "impl Value {\n    /// Synthesise")
        assert "alternative_fits" not in body
        assert "            Self::Number(payload) => {\n" in body
        assert (
            "                cst_node.push_child(\n"
            "                    Some(cst::ValueLabel::Number),\n"
            "                    cst::ValueChild::Number(_erased_number_to_cst(payload)?),\n"
            "                );\n"
        ) in body

    def test_a_dispatch_run_routes_each_value_to_the_branch_that_accepts_it(self, branch_src: str) -> None:
        """One loop over the label's values, not one per branch: the values arrive interleaved."""
        body = block(branch_src, "impl Doc {\n    /// Synthesise")
        assert (
            "        let taken = cursor_a.take(1, 0);\n"
            '        ::fltk_ast_core::filled(taken.len(), 1, "doc", "a")?;\n'
            "        for item in taken {\n"
            "            if matches!(item, DocA::Num(_)) {\n"
            "                let DocA::Num(inner) = item else {\n"
            '                    return Err(::fltk_ast_core::unplaceable("doc", "a", "DocA"));\n'
            "                };\n"
            "                cst_node.push_child(Some(cst::DocLabel::A), cst::DocChild::Num(inner.to_cst()?));\n"
            "            } else if matches!(item, DocA::Word(_)) {\n"
        ) in body
        assert (
            "            } else {\n"
            '                return Err(::fltk_ast_core::unplaceable("doc", "a", "DocA"));\n'
            "            }\n"
        ) in body

    def test_a_labeled_literal_position_appends_position_only(self, branch_src: str) -> None:
        """Its text is a grammar constant, so the loop never reads the value it stands for."""
        body = block(branch_src, "impl Doc {\n    /// Synthesise")
        assert (
            "        for _item in taken {\n"
            "            cst_node.push_child(Some(cst::DocLabel::Bang),"
            " cst::DocChild::Span(::fltk_cst_core::Span::unknown()));\n"
            "        }\n"
        ) in body

    def test_a_presence_flag_is_one_occurrence_where_it_is_set(self, branch_src: str) -> None:
        body = block(branch_src, "impl Doc {\n    /// Synthesise")
        assert (
            "let mut cursor_pub = ::fltk_ast_core::Cursor::new"
            "(if self.r#pub { vec![&self.r#pub] } else { Vec::new() });"
        ) in body

    def test_an_alternation_is_checked_before_the_node_is_built(self, branch_src: str) -> None:
        """A value set no single branch can carry is named before any child is appended."""
        body = block(branch_src, "impl Doc {\n    /// Synthesise")
        assert body.index("::fltk_ast_core::check_group(") < body.index("let mut cst_node")
        assert (
            "        ::fltk_ast_core::check_group(\n"
            '            "doc",\n'
            '            &::fltk_ast_core::populated(&[("a", true)]),\n'
            '            &[&["a"], &["a"]],\n'
            '            &["a"],\n'
            "            true,\n"
            "        )?;\n"
        ) in body

    def test_a_flattened_wrapper_is_rebuilt_from_the_fields_hoisted_out_of_it(self, task_src: str) -> None:
        body = block(task_src, "impl TaskDef {\n    /// Synthesise")
        # The wrapper is emitted exactly when something it would carry is populated.
        assert ("if ::fltk_ast_core::wrapper_needed(&[self.interval.is_some(), self.unit.is_some()]) {") in body
        # A field the wrapper requires was degraded at the optional use site, so it is checked.
        assert (
            '_flat_schedule_to_cst(::fltk_ast_core::hoisted(self.interval.as_ref(), "schedule", "interval")?,'
            ' ::fltk_ast_core::hoisted(self.unit.as_ref(), "schedule", "unit")?)?'
        ) in body
        # The helper distributes those fields over the wrapper's own item positions.
        helper = block(task_src, "fn _flat_schedule_to_cst")
        assert "let mut cursor_interval = ::fltk_ast_core::Cursor::new(vec![v0]);" in helper
        assert "cst::ScheduleChild::Number(_erased_number_to_cst(item)?)," in helper

    def test_a_fold_walks_down_its_own_nesting_side(self, fold_src: str) -> None:
        """The operands come off the chain in source order, which a left fold sees back to front."""
        body = block(fold_src, "impl Expr {\n    /// Synthesise")
        assert (
            "                Self::Binary(link) => {\n"
            "                    operators.push(&link.op);\n"
            "                    match link.rhs.as_ref() {\n"
            "                        Self::Operand(operand) => operands.push(operand),\n"
            "                        Self::Binary(_) => {\n"
            '                            return Err(::fltk_ast_core::against_direction("expr", "right"));\n'
            "                        }\n"
            "                    }\n"
            "                    chain = link.lhs.as_ref();\n"
        ) in body
        assert "        operands.reverse();\n        operators.reverse();\n" in body

    def test_the_unfolded_run_interleaves_the_operators_between_the_operands(self, fold_src: str) -> None:
        body = block(fold_src, "impl Expr {\n    /// Synthesise")
        assert (
            "        cst_node.push_child(Some(cst::ExprLabel::Term), cst::ExprChild::Term(operands[0].to_cst()?));\n"
            "        for (operator, operand) in operators.into_iter().zip(operands.into_iter().skip(1)) {\n"
            "            cst_node.push_child(Some(cst::ExprLabel::Op),"
            " cst::ExprChild::AddOp(_erased_add_op_to_cst(operator)?));\n"
            "            cst_node.push_child(Some(cst::ExprLabel::Term), cst::ExprChild::Term(operand.to_cst()?));\n"
            "        }\n"
        ) in body

    def test_a_right_fold_descends_the_other_side(self) -> None:
        src = generate(fixtures.FOLD_GRAMMAR, fixtures.FOLD_SIDECAR.replace("fold_left", "fold_right"))
        body = block(src, "impl Expr {\n    /// Synthesise")
        assert "match link.lhs.as_ref() {" in body
        assert "chain = link.rhs.as_ref();" in body
        assert '::fltk_ast_core::against_direction("expr", "left")' in body
        # The walk already saw the chain in source order.
        assert "operands.reverse();" not in body


class TestEntryPoints:
    """``parse_str`` and ``unparse_str``: text in, text out, each gated on the module behind it."""

    def test_neither_entry_point_is_emitted_without_its_module(self, config_src: str) -> None:
        assert "pub fn parse_str" not in config_src
        assert "pub fn unparse_str" not in config_src
        assert "use super::parser;" not in config_src

    def test_the_parser_module_is_imported_and_aliased_where_it_has_another_name(self) -> None:
        grammar = "word := w:/[a-z]+/ ;"
        assert "use super::parser;" in generate(grammar, parser_mod_path="super::parser")
        assert "use crate::gen::p as parser;" in generate(grammar, parser_mod_path="crate::gen::p")
        assert "use super::unparser;" in generate(grammar, unparser_mod_path="super::unparser")
        assert "use crate::gen::u as unparser;" in generate(grammar, unparser_mod_path="crate::gen::u")

    def test_parse_str_runs_the_parser_pipeline_then_the_converter(self) -> None:
        src = generate("word := w:/[a-z]+/ ;", parser_mod_path="super::parser")
        failed = "        return Err(::fltk_ast_core::ParseToAstError::Parse(parser.error_message()));\n"
        assert block(src, "pub fn parse_str") == (
            "pub fn parse_str(src: &str, filename: Option<&str>)"
            " -> Result<Word, ::fltk_ast_core::ParseToAstError> {\n"
            # The `false` is the trivia-capture flag: a converter drops unlabeled children, so
            # there is nothing to capture trivia for.
            "    let mut parser = parser::Parser::new(src, filename, false);\n"
            "    let result = parser.apply__parse_word(0);\n"
            "    // A depth-rejected parse can still come back as `Some` holding a wrong tree.\n"
            "    if parser.depth_exceeded() {\n"
            f"{failed}"
            "    }\n"
            "    let Some(parsed) = result else {\n"
            f"{failed}"
            "    };\n"
            "    // The whole input has to be consumed; `pos` counts characters, not bytes.\n"
            "    if parsed.pos != src.chars().count() as i64 {\n"
            f"{failed}"
            "    }\n"
            "    Ok(Word::from_cst(&parsed.result)?)\n"
            "}"
        )

    def test_unparse_str_renders_a_synthesised_cst_through_the_formatter(self) -> None:
        src = generate("word := w:/[a-z]+/ ;", unparser_mod_path="super::unparser")
        assert block(src, "pub fn unparse_str") == (
            "pub fn unparse_str(value: &Word, max_width: usize, indent_width: usize)"
            " -> Result<String, ::fltk_ast_core::AstError> {\n"
            "    let node = value.to_cst()?;\n"
            "    let guard = node.read();\n"
            "    let Some(unparsed) = unparser::Unparser::new().unparse_word(&guard) else {\n"
            '        return Err(::fltk_ast_core::unrenderable("word"));\n'
            "    };\n"
            "    let resolved = ::fltk_unparser_core::resolve_spacing_specs(unparsed.doc());\n"
            "    let config = ::fltk_unparser_core::RendererConfig {\n"
            "        indent_width,\n"
            "        max_width,\n"
            "    };\n"
            "    Ok(::fltk_unparser_core::Renderer::new(config).render(&resolved))\n"
            "}"
        )

    def test_the_goal_rule_defaults_to_the_first_rule_and_is_overridable(self) -> None:
        grammar = "doc := w:word ;\nword := w:/[a-z]+/ ;\n"
        assert "-> Result<Doc, ::fltk_ast_core::ParseToAstError>" in generate(grammar, parser_mod_path="super::parser")
        named = generate(grammar, parser_mod_path="super::parser", goal_rule="word")
        assert "-> Result<Word, ::fltk_ast_core::ParseToAstError>" in named
        assert "parser.apply__parse_word(0)" in named

    def test_an_unknown_goal_rule_is_refused(self) -> None:
        with pytest.raises(ValueError, match=r"goal rule 'nope' has no AST node"):
            generate("word := w:/[a-z]+/ ;", parser_mod_path="super::parser", goal_rule="nope")

    def test_a_goal_rule_is_checked_even_where_no_entry_point_names_it(self) -> None:
        """An option that reached the generator and changed nothing would be silently ignored."""
        with pytest.raises(ValueError, match=r"goal rule 'nope' has no AST node"):
            generate("word := w:/[a-z]+/ ;", goal_rule="nope")

    def test_an_erased_goal_rule_carries_its_payload_through_both_directions(self) -> None:
        """The conveniences take and return whatever the goal rule's type erases to."""
        src = generate(
            "num := d:/[0-9]+/ ;",
            "rule num { transparent; }\n",
            parser_mod_path="super::parser",
            unparser_mod_path="super::unparser",
        )
        assert "-> Result<String, ::fltk_ast_core::ParseToAstError>" in block(src, "pub fn parse_str")
        assert "Ok(_erased_num_from_cst(&parsed.result)?)" in src
        # A `&String` parameter is a lint, so the borrowed spelling is the one emitted.
        assert "pub fn unparse_str(value: &str," in src
        assert "let node = _erased_num_to_cst(value)?;" in src

    def test_a_coerced_erased_goal_rule_carries_the_coercions_value(self) -> None:
        src = generate(
            "num := d:/[0-9]+/ ;",
            "rule num { type: i64; transparent; }\n",
            parser_mod_path="super::parser",
            unparser_mod_path="super::unparser",
        )
        assert "-> Result<i64, ::fltk_ast_core::ParseToAstError>" in src
        assert "pub fn unparse_str(value: &i64," in src

    def test_a_custom_goal_rule_is_reached_through_the_traits(self) -> None:
        src = generate(
            "money := d:/[0-9]+/ ;",
            'rule money { custom(rust: "crate::Money", python: "app.Money"); }\n',
            parser_mod_path="super::parser",
            unparser_mod_path="super::unparser",
        )
        assert "-> Result<crate::Money, ::fltk_ast_core::ParseToAstError>" in src
        assert (
            "Ok(<crate::Money as ::fltk_ast_core::FromCst<::fltk_cst_core::Shared<cst::Money>>>"
            "::from_cst(&parsed.result)?)"
        ) in src
        assert (
            "let node = <crate::Money as ::fltk_ast_core::ToCst<::fltk_cst_core::Shared<cst::Money>>>::to_cst(value)?;"
        ) in src


class TestInTreeGrammars:
    @pytest.mark.parametrize("path", [_FLTK_ROOT / "fegen" / "fegen.fltkg", _FLTK_ROOT / "lsp" / "fltklsp.fltkg"])
    def test_the_emitted_types_are_exactly_the_ones_the_model_claimed(self, path: pathlib.Path) -> None:
        """Equality, not containment: the subset direction alone cannot see a *dropped* type.

        This is the only test that runs the emitter over a real grammar of ninety-odd rules, so a
        classification change or an early return that silently stops emitting a whole family of
        rules has to fail here.
        """
        model = am.build_ast_model(fixtures.classify(parse_grammar_file(path)))
        src = gsm2ast_rs.generate_ast_rs(model, source_name=path.name)
        emitted = {
            line.split()[2].removesuffix("{").strip()
            for line in src.splitlines()
            if line.startswith(("pub struct ", "pub enum "))
        }
        known = (
            {
                node.name
                for rule, node in model.nodes.items()
                if rule not in model.transparent_types and rule not in model.flattened_rules
            }
            | set(model.payload_classes)
            | set(model.field_enums)
            | set(model.value_enums)
        )
        assert emitted == known
        assert emitted
