# Stub package for the rust_parser_fixture compiled extension.
# Generated by gen-rust-* --init-pyi-output; do not edit by hand.
# This __init__.pyi exists only to make rust_parser_fixture a recognized stub package;
# the extension's top-level module exports nothing directly (only submodules cst, parser, unparser, unparser_default, collision_cst, collision_parser).
