# Stub package for rust_parser_fixture (compiled maturin extension tests/rust_parser_fixture).
# unparser.pyi is generated by `make gencode` (gen-rust-unparser with --pyi-output) and
# dogfoods the OQ-3 unparser .pyi surface under pyright.
# This __init__.pyi exists only to make rust_parser_fixture a recognized stub package;
# the extension's top-level module exports nothing directly (only submodules cst, parser,
# unparser, unparser_default, collision_cst, collision_parser).
