from __future__ import annotations

import tests.rust_parser_fixture_cst_protocol as _proto

class Doc:
    def render(self, max_width: int = ..., indent_width: int = ...) -> str: ...
    def __repr__(self) -> str: ...

class Unparser:
    def __init__(self) -> None: ...
    def unparse_num(self, node: _proto.Num, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_num_doc(self, node: _proto.Num) -> Doc | None: ...
    def unparse_name(self, node: _proto.Name, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_name_doc(self, node: _proto.Name) -> Doc | None: ...
    def unparse_atom(self, node: _proto.Atom, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_atom_doc(self, node: _proto.Atom) -> Doc | None: ...
    def unparse_paren_expr(
        self, node: _proto.ParenExpr, max_width: int = ..., indent_width: int = ...
    ) -> str | None: ...
    def unparse_paren_expr_doc(self, node: _proto.ParenExpr) -> Doc | None: ...
    def unparse_stmt(self, node: _proto.Stmt, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_stmt_doc(self, node: _proto.Stmt) -> Doc | None: ...
    def unparse_items(self, node: _proto.Items, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_items_doc(self, node: _proto.Items) -> Doc | None: ...
    def unparse_opt_item(self, node: _proto.OptItem, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_opt_item_doc(self, node: _proto.OptItem) -> Doc | None: ...
    def unparse_zero_items(
        self, node: _proto.ZeroItems, max_width: int = ..., indent_width: int = ...
    ) -> str | None: ...
    def unparse_zero_items_doc(self, node: _proto.ZeroItems) -> Doc | None: ...
    def unparse_expr(self, node: _proto.Expr, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_expr_doc(self, node: _proto.Expr) -> Doc | None: ...
    def unparse_lval(self, node: _proto.Lval, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_lval_doc(self, node: _proto.Lval) -> Doc | None: ...
    def unparse_rval(self, node: _proto.Rval, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_rval_doc(self, node: _proto.Rval) -> Doc | None: ...
    def unparse_arrow(self, node: _proto.Arrow, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_arrow_doc(self, node: _proto.Arrow) -> Doc | None: ...
    def unparse_latin_word(
        self, node: _proto.LatinWord, max_width: int = ..., indent_width: int = ...
    ) -> str | None: ...
    def unparse_latin_word_doc(self, node: _proto.LatinWord) -> Doc | None: ...
    def unparse_tagged(self, node: _proto.Tagged, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_tagged_doc(self, node: _proto.Tagged) -> Doc | None: ...
    def unparse_val(self, node: _proto.Val, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_val_doc(self, node: _proto.Val) -> Doc | None: ...
    def unparse_leading_ws(
        self, node: _proto.LeadingWs, max_width: int = ..., indent_width: int = ...
    ) -> str | None: ...
    def unparse_leading_ws_doc(self, node: _proto.LeadingWs) -> Doc | None: ...
    def unparse_grouped(self, node: _proto.Grouped, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_grouped_doc(self, node: _proto.Grouped) -> Doc | None: ...
    def unparse_rec_via_sub(
        self, node: _proto.RecViaSub, max_width: int = ..., indent_width: int = ...
    ) -> str | None: ...
    def unparse_rec_via_sub_doc(self, node: _proto.RecViaSub) -> Doc | None: ...
    def unparse_nest(self, node: _proto.Nest, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_nest_doc(self, node: _proto.Nest) -> Doc | None: ...
    def unparse_nest_sum(self, node: _proto.NestSum, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_nest_sum_doc(self, node: _proto.NestSum) -> Doc | None: ...
    def unparse_digit_seq(self, node: _proto.DigitSeq, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_digit_seq_doc(self, node: _proto.DigitSeq) -> Doc | None: ...
    def unparse_word_seq(self, node: _proto.WordSeq, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_word_seq_doc(self, node: _proto.WordSeq) -> Doc | None: ...
    def unparse_ws_seq(self, node: _proto.WsSeq, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_ws_seq_doc(self, node: _proto.WsSeq) -> Doc | None: ...
    def unparse_three_to_five_digits(
        self, node: _proto.ThreeToFiveDigits, max_width: int = ..., indent_width: int = ...
    ) -> str | None: ...
    def unparse_three_to_five_digits_doc(self, node: _proto.ThreeToFiveDigits) -> Doc | None: ...
    def unparse_exactly_two_digits(
        self, node: _proto.ExactlyTwoDigits, max_width: int = ..., indent_width: int = ...
    ) -> str | None: ...
    def unparse_exactly_two_digits_doc(self, node: _proto.ExactlyTwoDigits) -> Doc | None: ...
    def unparse_escaped_metas(
        self, node: _proto.EscapedMetas, max_width: int = ..., indent_width: int = ...
    ) -> str | None: ...
    def unparse_escaped_metas_doc(self, node: _proto.EscapedMetas) -> Doc | None: ...
    def unparse_latin_range(
        self, node: _proto.LatinRange, max_width: int = ..., indent_width: int = ...
    ) -> str | None: ...
    def unparse_latin_range_doc(self, node: _proto.LatinRange) -> Doc | None: ...
    def unparse_nc_group_alt(
        self, node: _proto.NcGroupAlt, max_width: int = ..., indent_width: int = ...
    ) -> str | None: ...
    def unparse_nc_group_alt_doc(self, node: _proto.NcGroupAlt) -> Doc | None: ...
    def unparse_case_insensitive(
        self, node: _proto.CaseInsensitive, max_width: int = ..., indent_width: int = ...
    ) -> str | None: ...
    def unparse_case_insensitive_doc(self, node: _proto.CaseInsensitive) -> Doc | None: ...
    def unparse_anchored_word(
        self, node: _proto.AnchoredWord, max_width: int = ..., indent_width: int = ...
    ) -> str | None: ...
    def unparse_anchored_word_doc(self, node: _proto.AnchoredWord) -> Doc | None: ...
    def unparse__trivia(self, node: _proto.Trivia, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse__trivia_doc(self, node: _proto.Trivia) -> Doc | None: ...
