# Stub package for fegen_rust_cst (compiled maturin extension crates/fegen-rust).
# cst.pyi is generated by `make gencode` (gen-rust-cst with --pyi-output).
# This __init__.pyi exists only to make fegen_rust_cst a recognized stub package;
# the extension's top-level module exports nothing directly (only submodules cst and parser).
