# Stub package for the fegen_rust_cst compiled extension.
# Generated by gen-rust-* --init-pyi-output; do not edit by hand.
# This __init__.pyi exists only to make fegen_rust_cst a recognized stub package;
# the extension's top-level module exports nothing directly (only submodules cst, parser, unparser).
