from __future__ import annotations

import typing

import fltk.fegen.fltk_cst_protocol as _proto
import fltk.fegen.pyrt.label_protocol
import fltk.fegen.pyrt.span_protocol

NodeKind = _proto.NodeKind

class Grammar:
    Label = _proto.GrammarLabel
    kind: typing.Literal[_proto.NodeKind.GRAMMAR]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, Rule | Trivia]]
    def append(
        self, child: _proto.Rule | _proto.Trivia, label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[_proto.Rule | _proto.Trivia],
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.Grammar) -> None: ...
    def child(self) -> tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, Rule | Trivia]: ...
    def insert(
        self,
        index: int,
        child: _proto.Rule | _proto.Trivia,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def remove_at(self, index: int) -> tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, Rule | Trivia]: ...
    def replace_at(
        self,
        index: int,
        child: _proto.Rule | _proto.Trivia,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_rule(self, child: _proto.Rule) -> None: ...
    def extend_rule(self, children: typing.Iterable[_proto.Rule]) -> None: ...
    def children_rule(self) -> typing.Iterator[Rule]: ...
    def child_rule(self) -> Rule: ...
    def maybe_rule(self) -> Rule | None: ...
    def rule(self) -> list[Rule]: ...

class Rule:
    Label = _proto.RuleLabel
    kind: typing.Literal[_proto.NodeKind.RULE]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, Alternatives | Identifier | Trivia]]
    def append(
        self,
        child: _proto.Alternatives | _proto.Identifier | _proto.Trivia,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[_proto.Alternatives | _proto.Identifier | _proto.Trivia],
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.Rule) -> None: ...
    def child(
        self,
    ) -> tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, Alternatives | Identifier | Trivia]: ...
    def insert(
        self,
        index: int,
        child: _proto.Alternatives | _proto.Identifier | _proto.Trivia,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, Alternatives | Identifier | Trivia]: ...
    def replace_at(
        self,
        index: int,
        child: _proto.Alternatives | _proto.Identifier | _proto.Trivia,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_alternatives(self, child: _proto.Alternatives) -> None: ...
    def extend_alternatives(self, children: typing.Iterable[_proto.Alternatives]) -> None: ...
    def children_alternatives(self) -> typing.Iterator[Alternatives]: ...
    def child_alternatives(self) -> Alternatives: ...
    def maybe_alternatives(self) -> Alternatives | None: ...
    def append_name(self, child: _proto.Identifier) -> None: ...
    def extend_name(self, children: typing.Iterable[_proto.Identifier]) -> None: ...
    def children_name(self) -> typing.Iterator[Identifier]: ...
    def child_name(self) -> Identifier: ...
    def maybe_name(self) -> Identifier | None: ...
    def alternatives(self) -> Alternatives: ...
    def name(self) -> Identifier: ...

class Alternatives:
    Label = _proto.AlternativesLabel
    kind: typing.Literal[_proto.NodeKind.ALTERNATIVES]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, Items | Trivia]]
    def append(
        self, child: _proto.Items | _proto.Trivia, label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[_proto.Items | _proto.Trivia],
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.Alternatives) -> None: ...
    def child(self) -> tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, Items | Trivia]: ...
    def insert(
        self,
        index: int,
        child: _proto.Items | _proto.Trivia,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def remove_at(self, index: int) -> tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, Items | Trivia]: ...
    def replace_at(
        self,
        index: int,
        child: _proto.Items | _proto.Trivia,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_items(self, child: _proto.Items) -> None: ...
    def extend_items(self, children: typing.Iterable[_proto.Items]) -> None: ...
    def children_items(self) -> typing.Iterator[Items]: ...
    def child_items(self) -> Items: ...
    def maybe_items(self) -> Items | None: ...
    def items(self) -> list[Items]: ...

class Items:
    Label = _proto.ItemsLabel
    kind: typing.Literal[_proto.NodeKind.ITEMS]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[
        tuple[
            fltk.fegen.pyrt.label_protocol.LabelProtocol | None,
            Item | Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol,
        ]
    ]
    def append(
        self,
        child: _proto.Item | _proto.Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[_proto.Item | _proto.Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol],
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.Items) -> None: ...
    def child(
        self,
    ) -> tuple[
        fltk.fegen.pyrt.label_protocol.LabelProtocol | None, Item | Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol
    ]: ...
    def insert(
        self,
        index: int,
        child: _proto.Item | _proto.Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[
        fltk.fegen.pyrt.label_protocol.LabelProtocol | None, Item | Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol
    ]: ...
    def replace_at(
        self,
        index: int,
        child: _proto.Item | _proto.Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_item(self, child: _proto.Item) -> None: ...
    def extend_item(self, children: typing.Iterable[_proto.Item]) -> None: ...
    def children_item(self) -> typing.Iterator[Item]: ...
    def child_item(self) -> Item: ...
    def maybe_item(self) -> Item | None: ...
    def append_no_ws(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_no_ws(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_no_ws(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_no_ws(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_no_ws(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def append_ws_allowed(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_ws_allowed(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_ws_allowed(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_ws_allowed(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_ws_allowed(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def append_ws_required(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_ws_required(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_ws_required(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_ws_required(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_ws_required(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def item(self) -> list[Item]: ...
    def no_ws(self) -> list[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def ws_allowed(self) -> list[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def ws_required(self) -> list[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

class Item:
    Label = _proto.ItemLabel
    kind: typing.Literal[_proto.NodeKind.ITEM]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[
        tuple[
            fltk.fegen.pyrt.label_protocol.LabelProtocol | None, Disposition | Identifier | Quantifier | Term | Trivia
        ]
    ]
    def append(
        self,
        child: _proto.Disposition | _proto.Identifier | _proto.Quantifier | _proto.Term | _proto.Trivia,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[
            _proto.Disposition | _proto.Identifier | _proto.Quantifier | _proto.Term | _proto.Trivia
        ],
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.Item) -> None: ...
    def child(
        self,
    ) -> tuple[
        fltk.fegen.pyrt.label_protocol.LabelProtocol | None, Disposition | Identifier | Quantifier | Term | Trivia
    ]: ...
    def insert(
        self,
        index: int,
        child: _proto.Disposition | _proto.Identifier | _proto.Quantifier | _proto.Term | _proto.Trivia,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[
        fltk.fegen.pyrt.label_protocol.LabelProtocol | None, Disposition | Identifier | Quantifier | Term | Trivia
    ]: ...
    def replace_at(
        self,
        index: int,
        child: _proto.Disposition | _proto.Identifier | _proto.Quantifier | _proto.Term | _proto.Trivia,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_disposition(self, child: _proto.Disposition) -> None: ...
    def extend_disposition(self, children: typing.Iterable[_proto.Disposition]) -> None: ...
    def children_disposition(self) -> typing.Iterator[Disposition]: ...
    def child_disposition(self) -> Disposition: ...
    def maybe_disposition(self) -> Disposition | None: ...
    def append_label(self, child: _proto.Identifier) -> None: ...
    def extend_label(self, children: typing.Iterable[_proto.Identifier]) -> None: ...
    def children_label(self) -> typing.Iterator[Identifier]: ...
    def child_label(self) -> Identifier: ...
    def maybe_label(self) -> Identifier | None: ...
    def append_quantifier(self, child: _proto.Quantifier) -> None: ...
    def extend_quantifier(self, children: typing.Iterable[_proto.Quantifier]) -> None: ...
    def children_quantifier(self) -> typing.Iterator[Quantifier]: ...
    def child_quantifier(self) -> Quantifier: ...
    def maybe_quantifier(self) -> Quantifier | None: ...
    def append_term(self, child: _proto.Term) -> None: ...
    def extend_term(self, children: typing.Iterable[_proto.Term]) -> None: ...
    def children_term(self) -> typing.Iterator[Term]: ...
    def child_term(self) -> Term: ...
    def maybe_term(self) -> Term | None: ...
    def disposition(self) -> Disposition | None: ...
    def label(self) -> Identifier | None: ...
    def quantifier(self) -> Quantifier | None: ...
    def term(self) -> Term: ...

class Term:
    Label = _proto.TermLabel
    kind: typing.Literal[_proto.NodeKind.TERM]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[
        tuple[
            fltk.fegen.pyrt.label_protocol.LabelProtocol | None,
            Alternatives | Identifier | Literal | RawString | Trivia,
        ]
    ]
    def append(
        self,
        child: _proto.Alternatives | _proto.Identifier | _proto.Literal | _proto.RawString | _proto.Trivia,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[
            _proto.Alternatives | _proto.Identifier | _proto.Literal | _proto.RawString | _proto.Trivia
        ],
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.Term) -> None: ...
    def child(
        self,
    ) -> tuple[
        fltk.fegen.pyrt.label_protocol.LabelProtocol | None, Alternatives | Identifier | Literal | RawString | Trivia
    ]: ...
    def insert(
        self,
        index: int,
        child: _proto.Alternatives | _proto.Identifier | _proto.Literal | _proto.RawString | _proto.Trivia,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[
        fltk.fegen.pyrt.label_protocol.LabelProtocol | None, Alternatives | Identifier | Literal | RawString | Trivia
    ]: ...
    def replace_at(
        self,
        index: int,
        child: _proto.Alternatives | _proto.Identifier | _proto.Literal | _proto.RawString | _proto.Trivia,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_alternatives(self, child: _proto.Alternatives) -> None: ...
    def extend_alternatives(self, children: typing.Iterable[_proto.Alternatives]) -> None: ...
    def children_alternatives(self) -> typing.Iterator[Alternatives]: ...
    def child_alternatives(self) -> Alternatives: ...
    def maybe_alternatives(self) -> Alternatives | None: ...
    def append_identifier(self, child: _proto.Identifier) -> None: ...
    def extend_identifier(self, children: typing.Iterable[_proto.Identifier]) -> None: ...
    def children_identifier(self) -> typing.Iterator[Identifier]: ...
    def child_identifier(self) -> Identifier: ...
    def maybe_identifier(self) -> Identifier | None: ...
    def append_literal(self, child: _proto.Literal) -> None: ...
    def extend_literal(self, children: typing.Iterable[_proto.Literal]) -> None: ...
    def children_literal(self) -> typing.Iterator[Literal]: ...
    def child_literal(self) -> Literal: ...
    def maybe_literal(self) -> Literal | None: ...
    def append_regex(self, child: _proto.RawString) -> None: ...
    def extend_regex(self, children: typing.Iterable[_proto.RawString]) -> None: ...
    def children_regex(self) -> typing.Iterator[RawString]: ...
    def child_regex(self) -> RawString: ...
    def maybe_regex(self) -> RawString | None: ...
    def alternatives(self) -> Alternatives | None: ...
    def identifier(self) -> Identifier | None: ...
    def literal(self) -> Literal | None: ...
    def regex(self) -> RawString | None: ...

class Disposition:
    Label = _proto.DispositionLabel
    kind: typing.Literal[_proto.NodeKind.DISPOSITION]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[
        tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]
    ]
    def append(
        self,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol],
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.Disposition) -> None: ...
    def child(
        self,
    ) -> tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def insert(
        self,
        index: int,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def replace_at(
        self,
        index: int,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_include(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_include(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_include(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_include(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_include(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def append_inline(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_inline(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_inline(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_inline(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_inline(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def append_suppress(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_suppress(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_suppress(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_suppress(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_suppress(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def include(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def include_text(self) -> str | None: ...
    def inline(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def inline_text(self) -> str | None: ...
    def suppress(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def suppress_text(self) -> str | None: ...
    def text(self) -> str: ...
    def variant(self) -> fltk.fegen.pyrt.label_protocol.LabelProtocol: ...

class Quantifier:
    Label = _proto.QuantifierLabel
    kind: typing.Literal[_proto.NodeKind.QUANTIFIER]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[
        tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]
    ]
    def append(
        self,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol],
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.Quantifier) -> None: ...
    def child(
        self,
    ) -> tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def insert(
        self,
        index: int,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def replace_at(
        self,
        index: int,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_one_or_more(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_one_or_more(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_one_or_more(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_one_or_more(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_one_or_more(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def append_optional(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_optional(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_optional(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_optional(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_optional(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def append_zero_or_more(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_zero_or_more(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_zero_or_more(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_zero_or_more(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_zero_or_more(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def one_or_more(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def one_or_more_text(self) -> str | None: ...
    def optional(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def optional_text(self) -> str | None: ...
    def zero_or_more(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def zero_or_more_text(self) -> str | None: ...
    def text(self) -> str: ...
    def variant(self) -> fltk.fegen.pyrt.label_protocol.LabelProtocol: ...

class Identifier:
    Label = _proto.IdentifierLabel
    kind: typing.Literal[_proto.NodeKind.IDENTIFIER]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[
        tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]
    ]
    def append(
        self,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol],
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.Identifier) -> None: ...
    def child(
        self,
    ) -> tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def insert(
        self,
        index: int,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def replace_at(
        self,
        index: int,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_name(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_name(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_name(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_name(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_name(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def name(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def name_text(self) -> str: ...
    def text(self) -> str: ...

class RawString:
    Label = _proto.RawStringLabel
    kind: typing.Literal[_proto.NodeKind.RAWSTRING]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[
        tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]
    ]
    def append(
        self,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol],
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.RawString) -> None: ...
    def child(
        self,
    ) -> tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def insert(
        self,
        index: int,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def replace_at(
        self,
        index: int,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def value_text(self) -> str: ...
    def text(self) -> str: ...

class Literal:
    Label = _proto.LiteralLabel
    kind: typing.Literal[_proto.NodeKind.LITERAL]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[
        tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]
    ]
    def append(
        self,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol],
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.Literal) -> None: ...
    def child(
        self,
    ) -> tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def insert(
        self,
        index: int,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def replace_at(
        self,
        index: int,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def value_text(self) -> str: ...
    def text(self) -> str: ...

class Trivia:
    Label = _proto.TriviaLabel
    kind: typing.Literal[_proto.NodeKind.TRIVIA]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[
        tuple[
            fltk.fegen.pyrt.label_protocol.LabelProtocol | None,
            BlockComment | LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol,
        ]
    ]
    def append(
        self,
        child: _proto.BlockComment | _proto.LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[
            _proto.BlockComment | _proto.LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol
        ],
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.Trivia) -> None: ...
    def child(
        self,
    ) -> tuple[
        fltk.fegen.pyrt.label_protocol.LabelProtocol | None,
        BlockComment | LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol,
    ]: ...
    def insert(
        self,
        index: int,
        child: _proto.BlockComment | _proto.LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[
        fltk.fegen.pyrt.label_protocol.LabelProtocol | None,
        BlockComment | LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol,
    ]: ...
    def replace_at(
        self,
        index: int,
        child: _proto.BlockComment | _proto.LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_block_comment(self, child: _proto.BlockComment) -> None: ...
    def extend_block_comment(self, children: typing.Iterable[_proto.BlockComment]) -> None: ...
    def children_block_comment(self) -> typing.Iterator[BlockComment]: ...
    def child_block_comment(self) -> BlockComment: ...
    def maybe_block_comment(self) -> BlockComment | None: ...
    def append_line_comment(self, child: _proto.LineComment) -> None: ...
    def extend_line_comment(self, children: typing.Iterable[_proto.LineComment]) -> None: ...
    def children_line_comment(self) -> typing.Iterator[LineComment]: ...
    def child_line_comment(self) -> LineComment: ...
    def maybe_line_comment(self) -> LineComment | None: ...
    def block_comment(self) -> list[BlockComment]: ...
    def line_comment(self) -> list[LineComment]: ...

class LineComment:
    Label = _proto.LineCommentLabel
    kind: typing.Literal[_proto.NodeKind.LINECOMMENT]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[
        tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]
    ]
    def append(
        self,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol],
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.LineComment) -> None: ...
    def child(
        self,
    ) -> tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def insert(
        self,
        index: int,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def replace_at(
        self,
        index: int,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_content(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_content(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_content(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_content(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_content(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def append_prefix(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_prefix(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_prefix(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_prefix(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_prefix(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def content(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def content_text(self) -> str: ...
    def prefix(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def prefix_text(self) -> str: ...
    def text(self) -> str: ...

class BlockComment:
    Label = _proto.BlockCommentLabel
    kind: typing.Literal[_proto.NodeKind.BLOCKCOMMENT]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[
        tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]
    ]
    def append(
        self,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol],
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.BlockComment) -> None: ...
    def child(
        self,
    ) -> tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def insert(
        self,
        index: int,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[fltk.fegen.pyrt.label_protocol.LabelProtocol | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def replace_at(
        self,
        index: int,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: fltk.fegen.pyrt.label_protocol.LabelProtocol | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_content(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_content(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_content(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_content(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_content(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def append_end(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_end(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_end(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_end(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_end(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def append_start(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_start(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_start(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_start(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_start(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def content(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def content_text(self) -> str: ...
    def end(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def end_text(self) -> str: ...
    def start(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def start_text(self) -> str: ...
    def text(self) -> str: ...
