from __future__ import annotations

import typing

import fltk.fegen.fltk_cst_protocol as _proto
import fltk.fegen.pyrt.span_protocol

NodeKind = _proto.NodeKind

class Grammar:
    Label = _proto.Grammar.Label
    kind: typing.Literal[_proto.NodeKind.GRAMMAR]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[_proto.Grammar.Label | None, _proto.Rule | _proto.Trivia]]
    def append(self, child: _proto.Rule | _proto.Trivia, label: _proto.Grammar.Label | None = ...) -> None: ...
    def extend(
        self, children: typing.Iterable[_proto.Rule | _proto.Trivia], label: _proto.Grammar.Label | None = ...
    ) -> None: ...
    def extend_children(self, other: _proto.Grammar) -> None: ...
    def child(self) -> tuple[_proto.Grammar.Label | None, _proto.Rule | _proto.Trivia]: ...
    def insert(
        self, index: int, child: _proto.Rule | _proto.Trivia, label: _proto.Grammar.Label | None = ...
    ) -> None: ...
    def remove_at(self, index: int) -> tuple[_proto.Grammar.Label | None, _proto.Rule | _proto.Trivia]: ...
    def replace_at(
        self, index: int, child: _proto.Rule | _proto.Trivia, label: _proto.Grammar.Label | None = ...
    ) -> None: ...
    def clear(self) -> None: ...
    def append_rule(self, child: _proto.Rule) -> None: ...
    def extend_rule(self, children: typing.Iterable[_proto.Rule]) -> None: ...
    def children_rule(self) -> typing.Iterator[_proto.Rule]: ...
    def child_rule(self) -> _proto.Rule: ...
    def maybe_rule(self) -> _proto.Rule | None: ...

class Rule:
    Label = _proto.Rule.Label
    kind: typing.Literal[_proto.NodeKind.RULE]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[_proto.Rule.Label | None, _proto.Alternatives | _proto.Identifier | _proto.Trivia]]
    def append(
        self, child: _proto.Alternatives | _proto.Identifier | _proto.Trivia, label: _proto.Rule.Label | None = ...
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[_proto.Alternatives | _proto.Identifier | _proto.Trivia],
        label: _proto.Rule.Label | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.Rule) -> None: ...
    def child(self) -> tuple[_proto.Rule.Label | None, _proto.Alternatives | _proto.Identifier | _proto.Trivia]: ...
    def insert(
        self,
        index: int,
        child: _proto.Alternatives | _proto.Identifier | _proto.Trivia,
        label: _proto.Rule.Label | None = ...,
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[_proto.Rule.Label | None, _proto.Alternatives | _proto.Identifier | _proto.Trivia]: ...
    def replace_at(
        self,
        index: int,
        child: _proto.Alternatives | _proto.Identifier | _proto.Trivia,
        label: _proto.Rule.Label | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_alternatives(self, child: _proto.Alternatives) -> None: ...
    def extend_alternatives(self, children: typing.Iterable[_proto.Alternatives]) -> None: ...
    def children_alternatives(self) -> typing.Iterator[_proto.Alternatives]: ...
    def child_alternatives(self) -> _proto.Alternatives: ...
    def maybe_alternatives(self) -> _proto.Alternatives | None: ...
    def append_name(self, child: _proto.Identifier) -> None: ...
    def extend_name(self, children: typing.Iterable[_proto.Identifier]) -> None: ...
    def children_name(self) -> typing.Iterator[_proto.Identifier]: ...
    def child_name(self) -> _proto.Identifier: ...
    def maybe_name(self) -> _proto.Identifier | None: ...

class Alternatives:
    Label = _proto.Alternatives.Label
    kind: typing.Literal[_proto.NodeKind.ALTERNATIVES]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[_proto.Alternatives.Label | None, _proto.Items | _proto.Trivia]]
    def append(self, child: _proto.Items | _proto.Trivia, label: _proto.Alternatives.Label | None = ...) -> None: ...
    def extend(
        self, children: typing.Iterable[_proto.Items | _proto.Trivia], label: _proto.Alternatives.Label | None = ...
    ) -> None: ...
    def extend_children(self, other: _proto.Alternatives) -> None: ...
    def child(self) -> tuple[_proto.Alternatives.Label | None, _proto.Items | _proto.Trivia]: ...
    def insert(
        self, index: int, child: _proto.Items | _proto.Trivia, label: _proto.Alternatives.Label | None = ...
    ) -> None: ...
    def remove_at(self, index: int) -> tuple[_proto.Alternatives.Label | None, _proto.Items | _proto.Trivia]: ...
    def replace_at(
        self, index: int, child: _proto.Items | _proto.Trivia, label: _proto.Alternatives.Label | None = ...
    ) -> None: ...
    def clear(self) -> None: ...
    def append_items(self, child: _proto.Items) -> None: ...
    def extend_items(self, children: typing.Iterable[_proto.Items]) -> None: ...
    def children_items(self) -> typing.Iterator[_proto.Items]: ...
    def child_items(self) -> _proto.Items: ...
    def maybe_items(self) -> _proto.Items | None: ...

class Items:
    Label = _proto.Items.Label
    kind: typing.Literal[_proto.NodeKind.ITEMS]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[
        tuple[_proto.Items.Label | None, _proto.Item | _proto.Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol]
    ]
    def append(
        self,
        child: _proto.Item | _proto.Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: _proto.Items.Label | None = ...,
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[_proto.Item | _proto.Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol],
        label: _proto.Items.Label | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.Items) -> None: ...
    def child(
        self,
    ) -> tuple[_proto.Items.Label | None, _proto.Item | _proto.Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def insert(
        self,
        index: int,
        child: _proto.Item | _proto.Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: _proto.Items.Label | None = ...,
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[_proto.Items.Label | None, _proto.Item | _proto.Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def replace_at(
        self,
        index: int,
        child: _proto.Item | _proto.Trivia | fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: _proto.Items.Label | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_item(self, child: _proto.Item) -> None: ...
    def extend_item(self, children: typing.Iterable[_proto.Item]) -> None: ...
    def children_item(self) -> typing.Iterator[_proto.Item]: ...
    def child_item(self) -> _proto.Item: ...
    def maybe_item(self) -> _proto.Item | None: ...
    def append_no_ws(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_no_ws(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_no_ws(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_no_ws(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_no_ws(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def append_ws_allowed(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_ws_allowed(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_ws_allowed(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_ws_allowed(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_ws_allowed(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def append_ws_required(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_ws_required(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_ws_required(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_ws_required(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_ws_required(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

class Item:
    Label = _proto.Item.Label
    kind: typing.Literal[_proto.NodeKind.ITEM]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[
        tuple[
            _proto.Item.Label | None,
            _proto.Disposition | _proto.Identifier | _proto.Quantifier | _proto.Term | _proto.Trivia,
        ]
    ]
    def append(
        self,
        child: _proto.Disposition | _proto.Identifier | _proto.Quantifier | _proto.Term | _proto.Trivia,
        label: _proto.Item.Label | None = ...,
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[
            _proto.Disposition | _proto.Identifier | _proto.Quantifier | _proto.Term | _proto.Trivia
        ],
        label: _proto.Item.Label | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.Item) -> None: ...
    def child(
        self,
    ) -> tuple[
        _proto.Item.Label | None,
        _proto.Disposition | _proto.Identifier | _proto.Quantifier | _proto.Term | _proto.Trivia,
    ]: ...
    def insert(
        self,
        index: int,
        child: _proto.Disposition | _proto.Identifier | _proto.Quantifier | _proto.Term | _proto.Trivia,
        label: _proto.Item.Label | None = ...,
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[
        _proto.Item.Label | None,
        _proto.Disposition | _proto.Identifier | _proto.Quantifier | _proto.Term | _proto.Trivia,
    ]: ...
    def replace_at(
        self,
        index: int,
        child: _proto.Disposition | _proto.Identifier | _proto.Quantifier | _proto.Term | _proto.Trivia,
        label: _proto.Item.Label | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_disposition(self, child: _proto.Disposition) -> None: ...
    def extend_disposition(self, children: typing.Iterable[_proto.Disposition]) -> None: ...
    def children_disposition(self) -> typing.Iterator[_proto.Disposition]: ...
    def child_disposition(self) -> _proto.Disposition: ...
    def maybe_disposition(self) -> _proto.Disposition | None: ...
    def append_label(self, child: _proto.Identifier) -> None: ...
    def extend_label(self, children: typing.Iterable[_proto.Identifier]) -> None: ...
    def children_label(self) -> typing.Iterator[_proto.Identifier]: ...
    def child_label(self) -> _proto.Identifier: ...
    def maybe_label(self) -> _proto.Identifier | None: ...
    def append_quantifier(self, child: _proto.Quantifier) -> None: ...
    def extend_quantifier(self, children: typing.Iterable[_proto.Quantifier]) -> None: ...
    def children_quantifier(self) -> typing.Iterator[_proto.Quantifier]: ...
    def child_quantifier(self) -> _proto.Quantifier: ...
    def maybe_quantifier(self) -> _proto.Quantifier | None: ...
    def append_term(self, child: _proto.Term) -> None: ...
    def extend_term(self, children: typing.Iterable[_proto.Term]) -> None: ...
    def children_term(self) -> typing.Iterator[_proto.Term]: ...
    def child_term(self) -> _proto.Term: ...
    def maybe_term(self) -> _proto.Term | None: ...

class Term:
    Label = _proto.Term.Label
    kind: typing.Literal[_proto.NodeKind.TERM]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[
        tuple[
            _proto.Term.Label | None,
            _proto.Alternatives | _proto.Identifier | _proto.Literal | _proto.RawString | _proto.Trivia,
        ]
    ]
    def append(
        self,
        child: _proto.Alternatives | _proto.Identifier | _proto.Literal | _proto.RawString | _proto.Trivia,
        label: _proto.Term.Label | None = ...,
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[
            _proto.Alternatives | _proto.Identifier | _proto.Literal | _proto.RawString | _proto.Trivia
        ],
        label: _proto.Term.Label | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.Term) -> None: ...
    def child(
        self,
    ) -> tuple[
        _proto.Term.Label | None,
        _proto.Alternatives | _proto.Identifier | _proto.Literal | _proto.RawString | _proto.Trivia,
    ]: ...
    def insert(
        self,
        index: int,
        child: _proto.Alternatives | _proto.Identifier | _proto.Literal | _proto.RawString | _proto.Trivia,
        label: _proto.Term.Label | None = ...,
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[
        _proto.Term.Label | None,
        _proto.Alternatives | _proto.Identifier | _proto.Literal | _proto.RawString | _proto.Trivia,
    ]: ...
    def replace_at(
        self,
        index: int,
        child: _proto.Alternatives | _proto.Identifier | _proto.Literal | _proto.RawString | _proto.Trivia,
        label: _proto.Term.Label | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_alternatives(self, child: _proto.Alternatives) -> None: ...
    def extend_alternatives(self, children: typing.Iterable[_proto.Alternatives]) -> None: ...
    def children_alternatives(self) -> typing.Iterator[_proto.Alternatives]: ...
    def child_alternatives(self) -> _proto.Alternatives: ...
    def maybe_alternatives(self) -> _proto.Alternatives | None: ...
    def append_identifier(self, child: _proto.Identifier) -> None: ...
    def extend_identifier(self, children: typing.Iterable[_proto.Identifier]) -> None: ...
    def children_identifier(self) -> typing.Iterator[_proto.Identifier]: ...
    def child_identifier(self) -> _proto.Identifier: ...
    def maybe_identifier(self) -> _proto.Identifier | None: ...
    def append_literal(self, child: _proto.Literal) -> None: ...
    def extend_literal(self, children: typing.Iterable[_proto.Literal]) -> None: ...
    def children_literal(self) -> typing.Iterator[_proto.Literal]: ...
    def child_literal(self) -> _proto.Literal: ...
    def maybe_literal(self) -> _proto.Literal | None: ...
    def append_regex(self, child: _proto.RawString) -> None: ...
    def extend_regex(self, children: typing.Iterable[_proto.RawString]) -> None: ...
    def children_regex(self) -> typing.Iterator[_proto.RawString]: ...
    def child_regex(self) -> _proto.RawString: ...
    def maybe_regex(self) -> _proto.RawString | None: ...

class Disposition:
    Label = _proto.Disposition.Label
    kind: typing.Literal[_proto.NodeKind.DISPOSITION]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[_proto.Disposition.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]
    def append(
        self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: _proto.Disposition.Label | None = ...
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol],
        label: _proto.Disposition.Label | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.Disposition) -> None: ...
    def child(self) -> tuple[_proto.Disposition.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def insert(
        self,
        index: int,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: _proto.Disposition.Label | None = ...,
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[_proto.Disposition.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def replace_at(
        self,
        index: int,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: _proto.Disposition.Label | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_include(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_include(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_include(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_include(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_include(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def append_inline(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_inline(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_inline(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_inline(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_inline(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def append_suppress(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_suppress(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_suppress(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_suppress(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_suppress(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

class Quantifier:
    Label = _proto.Quantifier.Label
    kind: typing.Literal[_proto.NodeKind.QUANTIFIER]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[_proto.Quantifier.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]
    def append(
        self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: _proto.Quantifier.Label | None = ...
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol],
        label: _proto.Quantifier.Label | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.Quantifier) -> None: ...
    def child(self) -> tuple[_proto.Quantifier.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: _proto.Quantifier.Label | None = ...
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[_proto.Quantifier.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: _proto.Quantifier.Label | None = ...
    ) -> None: ...
    def clear(self) -> None: ...
    def append_one_or_more(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_one_or_more(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_one_or_more(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_one_or_more(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_one_or_more(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def append_optional(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_optional(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_optional(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_optional(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_optional(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def append_zero_or_more(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_zero_or_more(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_zero_or_more(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_zero_or_more(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_zero_or_more(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

class Identifier:
    Label = _proto.Identifier.Label
    kind: typing.Literal[_proto.NodeKind.IDENTIFIER]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[_proto.Identifier.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]
    def append(
        self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: _proto.Identifier.Label | None = ...
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol],
        label: _proto.Identifier.Label | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.Identifier) -> None: ...
    def child(self) -> tuple[_proto.Identifier.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: _proto.Identifier.Label | None = ...
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[_proto.Identifier.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: _proto.Identifier.Label | None = ...
    ) -> None: ...
    def clear(self) -> None: ...
    def append_name(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_name(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_name(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_name(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_name(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

class RawString:
    Label = _proto.RawString.Label
    kind: typing.Literal[_proto.NodeKind.RAWSTRING]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[_proto.RawString.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]
    def append(
        self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: _proto.RawString.Label | None = ...
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol],
        label: _proto.RawString.Label | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.RawString) -> None: ...
    def child(self) -> tuple[_proto.RawString.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: _proto.RawString.Label | None = ...
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[_proto.RawString.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: _proto.RawString.Label | None = ...
    ) -> None: ...
    def clear(self) -> None: ...
    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

class Literal:
    Label = _proto.Literal.Label
    kind: typing.Literal[_proto.NodeKind.LITERAL]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[_proto.Literal.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]
    def append(
        self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: _proto.Literal.Label | None = ...
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol],
        label: _proto.Literal.Label | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.Literal) -> None: ...
    def child(self) -> tuple[_proto.Literal.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: _proto.Literal.Label | None = ...
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[_proto.Literal.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: _proto.Literal.Label | None = ...
    ) -> None: ...
    def clear(self) -> None: ...
    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

class Trivia:
    Label = _proto.Trivia.Label
    kind: typing.Literal[_proto.NodeKind.TRIVIA]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[
        tuple[
            _proto.Trivia.Label | None,
            _proto.BlockComment | _proto.LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol,
        ]
    ]
    def append(
        self,
        child: _proto.BlockComment | _proto.LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: _proto.Trivia.Label | None = ...,
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[
            _proto.BlockComment | _proto.LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol
        ],
        label: _proto.Trivia.Label | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.Trivia) -> None: ...
    def child(
        self,
    ) -> tuple[
        _proto.Trivia.Label | None,
        _proto.BlockComment | _proto.LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol,
    ]: ...
    def insert(
        self,
        index: int,
        child: _proto.BlockComment | _proto.LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: _proto.Trivia.Label | None = ...,
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[
        _proto.Trivia.Label | None,
        _proto.BlockComment | _proto.LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol,
    ]: ...
    def replace_at(
        self,
        index: int,
        child: _proto.BlockComment | _proto.LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: _proto.Trivia.Label | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_block_comment(self, child: _proto.BlockComment) -> None: ...
    def extend_block_comment(self, children: typing.Iterable[_proto.BlockComment]) -> None: ...
    def children_block_comment(self) -> typing.Iterator[_proto.BlockComment]: ...
    def child_block_comment(self) -> _proto.BlockComment: ...
    def maybe_block_comment(self) -> _proto.BlockComment | None: ...
    def append_line_comment(self, child: _proto.LineComment) -> None: ...
    def extend_line_comment(self, children: typing.Iterable[_proto.LineComment]) -> None: ...
    def children_line_comment(self) -> typing.Iterator[_proto.LineComment]: ...
    def child_line_comment(self) -> _proto.LineComment: ...
    def maybe_line_comment(self) -> _proto.LineComment | None: ...

class LineComment:
    Label = _proto.LineComment.Label
    kind: typing.Literal[_proto.NodeKind.LINECOMMENT]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[_proto.LineComment.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]
    def append(
        self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: _proto.LineComment.Label | None = ...
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol],
        label: _proto.LineComment.Label | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.LineComment) -> None: ...
    def child(self) -> tuple[_proto.LineComment.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def insert(
        self,
        index: int,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: _proto.LineComment.Label | None = ...,
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[_proto.LineComment.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def replace_at(
        self,
        index: int,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: _proto.LineComment.Label | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_content(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_content(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_content(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_content(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_content(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def append_prefix(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_prefix(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_prefix(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_prefix(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_prefix(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

class BlockComment:
    Label = _proto.BlockComment.Label
    kind: typing.Literal[_proto.NodeKind.BLOCKCOMMENT]
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[_proto.BlockComment.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]
    def append(
        self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: _proto.BlockComment.Label | None = ...
    ) -> None: ...
    def extend(
        self,
        children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol],
        label: _proto.BlockComment.Label | None = ...,
    ) -> None: ...
    def extend_children(self, other: _proto.BlockComment) -> None: ...
    def child(self) -> tuple[_proto.BlockComment.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def insert(
        self,
        index: int,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: _proto.BlockComment.Label | None = ...,
    ) -> None: ...
    def remove_at(
        self, index: int
    ) -> tuple[_proto.BlockComment.Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def replace_at(
        self,
        index: int,
        child: fltk.fegen.pyrt.span_protocol.SpanProtocol,
        label: _proto.BlockComment.Label | None = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    def append_content(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_content(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_content(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_content(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_content(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def append_end(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_end(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_end(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_end(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_end(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
    def append_start(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...
    def extend_start(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...
    def children_start(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...
    def child_start(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...
    def maybe_start(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...
