from __future__ import annotations

import fltk.fegen.fltk_cst_protocol as _proto

class Doc:
    def render(self, max_width: int = ..., indent_width: int = ...) -> str: ...
    def __repr__(self) -> str: ...

class Unparser:
    def __init__(self) -> None: ...
    def unparse_grammar(self, node: _proto.Grammar, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_grammar_doc(self, node: _proto.Grammar) -> Doc | None: ...
    def unparse_rule(self, node: _proto.Rule, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_rule_doc(self, node: _proto.Rule) -> Doc | None: ...
    def unparse_alternatives(
        self, node: _proto.Alternatives, max_width: int = ..., indent_width: int = ...
    ) -> str | None: ...
    def unparse_alternatives_doc(self, node: _proto.Alternatives) -> Doc | None: ...
    def unparse_items(self, node: _proto.Items, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_items_doc(self, node: _proto.Items) -> Doc | None: ...
    def unparse_item(self, node: _proto.Item, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_item_doc(self, node: _proto.Item) -> Doc | None: ...
    def unparse_term(self, node: _proto.Term, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_term_doc(self, node: _proto.Term) -> Doc | None: ...
    def unparse_disposition(
        self, node: _proto.Disposition, max_width: int = ..., indent_width: int = ...
    ) -> str | None: ...
    def unparse_disposition_doc(self, node: _proto.Disposition) -> Doc | None: ...
    def unparse_quantifier(
        self, node: _proto.Quantifier, max_width: int = ..., indent_width: int = ...
    ) -> str | None: ...
    def unparse_quantifier_doc(self, node: _proto.Quantifier) -> Doc | None: ...
    def unparse_identifier(
        self, node: _proto.Identifier, max_width: int = ..., indent_width: int = ...
    ) -> str | None: ...
    def unparse_identifier_doc(self, node: _proto.Identifier) -> Doc | None: ...
    def unparse_raw_string(
        self, node: _proto.RawString, max_width: int = ..., indent_width: int = ...
    ) -> str | None: ...
    def unparse_raw_string_doc(self, node: _proto.RawString) -> Doc | None: ...
    def unparse_literal(self, node: _proto.Literal, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse_literal_doc(self, node: _proto.Literal) -> Doc | None: ...
    def unparse__trivia(self, node: _proto.Trivia, max_width: int = ..., indent_width: int = ...) -> str | None: ...
    def unparse__trivia_doc(self, node: _proto.Trivia) -> Doc | None: ...
    def unparse_line_comment(
        self, node: _proto.LineComment, max_width: int = ..., indent_width: int = ...
    ) -> str | None: ...
    def unparse_line_comment_doc(self, node: _proto.LineComment) -> Doc | None: ...
    def unparse_block_comment(
        self, node: _proto.BlockComment, max_width: int = ..., indent_width: int = ...
    ) -> str | None: ...
    def unparse_block_comment_doc(self, node: _proto.BlockComment) -> Doc | None: ...
