# ruff: noqa: N802
from __future__ import annotations

import typing

import fltk.fegen.pyrt.terminalsrc


class GrammarNode(typing.Protocol):
    class Label:
        RULE: typing.ClassVar[object]

    span: fltk.fegen.pyrt.terminalsrc.Span
    children: list[tuple[Label | None, RuleNode | TriviaNode]]

    def append(self, child: RuleNode | TriviaNode, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[RuleNode | TriviaNode], label: Label | None = None) -> None: ...

    def child(self) -> tuple[Label | None, RuleNode | TriviaNode]: ...

    def append_rule(self, child: RuleNode) -> None: ...

    def extend_rule(self, children: typing.Iterable[RuleNode]) -> None: ...

    def children_rule(self) -> typing.Iterator[RuleNode]: ...

    def child_rule(self) -> RuleNode: ...

    def maybe_rule(self) -> RuleNode | None: ...


class RuleNode(typing.Protocol):
    class Label:
        ALTERNATIVES: typing.ClassVar[object]
        NAME: typing.ClassVar[object]

    span: fltk.fegen.pyrt.terminalsrc.Span
    children: list[tuple[Label | None, AlternativesNode | IdentifierNode | TriviaNode]]

    def append(self, child: AlternativesNode | IdentifierNode | TriviaNode, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[AlternativesNode | IdentifierNode | TriviaNode], label: Label | None = None
    ) -> None: ...

    def child(self) -> tuple[Label | None, AlternativesNode | IdentifierNode | TriviaNode]: ...

    def append_alternatives(self, child: AlternativesNode) -> None: ...

    def extend_alternatives(self, children: typing.Iterable[AlternativesNode]) -> None: ...

    def children_alternatives(self) -> typing.Iterator[AlternativesNode]: ...

    def child_alternatives(self) -> AlternativesNode: ...

    def maybe_alternatives(self) -> AlternativesNode | None: ...

    def append_name(self, child: IdentifierNode) -> None: ...

    def extend_name(self, children: typing.Iterable[IdentifierNode]) -> None: ...

    def children_name(self) -> typing.Iterator[IdentifierNode]: ...

    def child_name(self) -> IdentifierNode: ...

    def maybe_name(self) -> IdentifierNode | None: ...


class AlternativesNode(typing.Protocol):
    class Label:
        ITEMS: typing.ClassVar[object]

    span: fltk.fegen.pyrt.terminalsrc.Span
    children: list[tuple[Label | None, ItemsNode | TriviaNode]]

    def append(self, child: ItemsNode | TriviaNode, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[ItemsNode | TriviaNode], label: Label | None = None) -> None: ...

    def child(self) -> tuple[Label | None, ItemsNode | TriviaNode]: ...

    def append_items(self, child: ItemsNode) -> None: ...

    def extend_items(self, children: typing.Iterable[ItemsNode]) -> None: ...

    def children_items(self) -> typing.Iterator[ItemsNode]: ...

    def child_items(self) -> ItemsNode: ...

    def maybe_items(self) -> ItemsNode | None: ...


class ItemsNode(typing.Protocol):
    class Label:
        ITEM: typing.ClassVar[object]
        NO_WS: typing.ClassVar[object]
        WS_ALLOWED: typing.ClassVar[object]
        WS_REQUIRED: typing.ClassVar[object]

    span: fltk.fegen.pyrt.terminalsrc.Span
    children: list[tuple[Label | None, ItemNode | TriviaNode | fltk.fegen.pyrt.terminalsrc.Span]]

    def append(
        self, child: ItemNode | TriviaNode | fltk.fegen.pyrt.terminalsrc.Span, label: Label | None = None
    ) -> None: ...

    def extend(
        self,
        children: typing.Iterable[ItemNode | TriviaNode | fltk.fegen.pyrt.terminalsrc.Span],
        label: Label | None = None,
    ) -> None: ...

    def child(self) -> tuple[Label | None, ItemNode | TriviaNode | fltk.fegen.pyrt.terminalsrc.Span]: ...

    def append_item(self, child: ItemNode) -> None: ...

    def extend_item(self, children: typing.Iterable[ItemNode]) -> None: ...

    def children_item(self) -> typing.Iterator[ItemNode]: ...

    def child_item(self) -> ItemNode: ...

    def maybe_item(self) -> ItemNode | None: ...

    def append_no_ws(self, child: fltk.fegen.pyrt.terminalsrc.Span) -> None: ...

    def extend_no_ws(self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span]) -> None: ...

    def children_no_ws(self) -> typing.Iterator[fltk.fegen.pyrt.terminalsrc.Span]: ...

    def child_no_ws(self) -> fltk.fegen.pyrt.terminalsrc.Span: ...

    def maybe_no_ws(self) -> fltk.fegen.pyrt.terminalsrc.Span | None: ...

    def append_ws_allowed(self, child: fltk.fegen.pyrt.terminalsrc.Span) -> None: ...

    def extend_ws_allowed(self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span]) -> None: ...

    def children_ws_allowed(self) -> typing.Iterator[fltk.fegen.pyrt.terminalsrc.Span]: ...

    def child_ws_allowed(self) -> fltk.fegen.pyrt.terminalsrc.Span: ...

    def maybe_ws_allowed(self) -> fltk.fegen.pyrt.terminalsrc.Span | None: ...

    def append_ws_required(self, child: fltk.fegen.pyrt.terminalsrc.Span) -> None: ...

    def extend_ws_required(self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span]) -> None: ...

    def children_ws_required(self) -> typing.Iterator[fltk.fegen.pyrt.terminalsrc.Span]: ...

    def child_ws_required(self) -> fltk.fegen.pyrt.terminalsrc.Span: ...

    def maybe_ws_required(self) -> fltk.fegen.pyrt.terminalsrc.Span | None: ...


class ItemNode(typing.Protocol):
    class Label:
        DISPOSITION: typing.ClassVar[object]
        LABEL: typing.ClassVar[object]
        QUANTIFIER: typing.ClassVar[object]
        TERM: typing.ClassVar[object]

    span: fltk.fegen.pyrt.terminalsrc.Span
    children: list[tuple[Label | None, DispositionNode | IdentifierNode | QuantifierNode | TermNode | TriviaNode]]

    def append(
        self,
        child: DispositionNode | IdentifierNode | QuantifierNode | TermNode | TriviaNode,
        label: Label | None = None,
    ) -> None: ...

    def extend(
        self,
        children: typing.Iterable[DispositionNode | IdentifierNode | QuantifierNode | TermNode | TriviaNode],
        label: Label | None = None,
    ) -> None: ...

    def child(
        self,
    ) -> tuple[Label | None, DispositionNode | IdentifierNode | QuantifierNode | TermNode | TriviaNode]: ...

    def append_disposition(self, child: DispositionNode) -> None: ...

    def extend_disposition(self, children: typing.Iterable[DispositionNode]) -> None: ...

    def children_disposition(self) -> typing.Iterator[DispositionNode]: ...

    def child_disposition(self) -> DispositionNode: ...

    def maybe_disposition(self) -> DispositionNode | None: ...

    def append_label(self, child: IdentifierNode) -> None: ...

    def extend_label(self, children: typing.Iterable[IdentifierNode]) -> None: ...

    def children_label(self) -> typing.Iterator[IdentifierNode]: ...

    def child_label(self) -> IdentifierNode: ...

    def maybe_label(self) -> IdentifierNode | None: ...

    def append_quantifier(self, child: QuantifierNode) -> None: ...

    def extend_quantifier(self, children: typing.Iterable[QuantifierNode]) -> None: ...

    def children_quantifier(self) -> typing.Iterator[QuantifierNode]: ...

    def child_quantifier(self) -> QuantifierNode: ...

    def maybe_quantifier(self) -> QuantifierNode | None: ...

    def append_term(self, child: TermNode) -> None: ...

    def extend_term(self, children: typing.Iterable[TermNode]) -> None: ...

    def children_term(self) -> typing.Iterator[TermNode]: ...

    def child_term(self) -> TermNode: ...

    def maybe_term(self) -> TermNode | None: ...


class TermNode(typing.Protocol):
    class Label:
        ALTERNATIVES: typing.ClassVar[object]
        IDENTIFIER: typing.ClassVar[object]
        LITERAL: typing.ClassVar[object]
        REGEX: typing.ClassVar[object]

    span: fltk.fegen.pyrt.terminalsrc.Span
    children: list[tuple[Label | None, AlternativesNode | IdentifierNode | LiteralNode | RawStringNode | TriviaNode]]

    def append(
        self,
        child: AlternativesNode | IdentifierNode | LiteralNode | RawStringNode | TriviaNode,
        label: Label | None = None,
    ) -> None: ...

    def extend(
        self,
        children: typing.Iterable[AlternativesNode | IdentifierNode | LiteralNode | RawStringNode | TriviaNode],
        label: Label | None = None,
    ) -> None: ...

    def child(
        self,
    ) -> tuple[Label | None, AlternativesNode | IdentifierNode | LiteralNode | RawStringNode | TriviaNode]: ...

    def append_alternatives(self, child: AlternativesNode) -> None: ...

    def extend_alternatives(self, children: typing.Iterable[AlternativesNode]) -> None: ...

    def children_alternatives(self) -> typing.Iterator[AlternativesNode]: ...

    def child_alternatives(self) -> AlternativesNode: ...

    def maybe_alternatives(self) -> AlternativesNode | None: ...

    def append_identifier(self, child: IdentifierNode) -> None: ...

    def extend_identifier(self, children: typing.Iterable[IdentifierNode]) -> None: ...

    def children_identifier(self) -> typing.Iterator[IdentifierNode]: ...

    def child_identifier(self) -> IdentifierNode: ...

    def maybe_identifier(self) -> IdentifierNode | None: ...

    def append_literal(self, child: LiteralNode) -> None: ...

    def extend_literal(self, children: typing.Iterable[LiteralNode]) -> None: ...

    def children_literal(self) -> typing.Iterator[LiteralNode]: ...

    def child_literal(self) -> LiteralNode: ...

    def maybe_literal(self) -> LiteralNode | None: ...

    def append_regex(self, child: RawStringNode) -> None: ...

    def extend_regex(self, children: typing.Iterable[RawStringNode]) -> None: ...

    def children_regex(self) -> typing.Iterator[RawStringNode]: ...

    def child_regex(self) -> RawStringNode: ...

    def maybe_regex(self) -> RawStringNode | None: ...


class DispositionNode(typing.Protocol):
    class Label:
        INCLUDE: typing.ClassVar[object]
        INLINE: typing.ClassVar[object]
        SUPPRESS: typing.ClassVar[object]

    span: fltk.fegen.pyrt.terminalsrc.Span
    children: list[tuple[Label | None, fltk.fegen.pyrt.terminalsrc.Span]]

    def append(self, child: fltk.fegen.pyrt.terminalsrc.Span, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span], label: Label | None = None
    ) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.terminalsrc.Span]: ...

    def append_include(self, child: fltk.fegen.pyrt.terminalsrc.Span) -> None: ...

    def extend_include(self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span]) -> None: ...

    def children_include(self) -> typing.Iterator[fltk.fegen.pyrt.terminalsrc.Span]: ...

    def child_include(self) -> fltk.fegen.pyrt.terminalsrc.Span: ...

    def maybe_include(self) -> fltk.fegen.pyrt.terminalsrc.Span | None: ...

    def append_inline(self, child: fltk.fegen.pyrt.terminalsrc.Span) -> None: ...

    def extend_inline(self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span]) -> None: ...

    def children_inline(self) -> typing.Iterator[fltk.fegen.pyrt.terminalsrc.Span]: ...

    def child_inline(self) -> fltk.fegen.pyrt.terminalsrc.Span: ...

    def maybe_inline(self) -> fltk.fegen.pyrt.terminalsrc.Span | None: ...

    def append_suppress(self, child: fltk.fegen.pyrt.terminalsrc.Span) -> None: ...

    def extend_suppress(self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span]) -> None: ...

    def children_suppress(self) -> typing.Iterator[fltk.fegen.pyrt.terminalsrc.Span]: ...

    def child_suppress(self) -> fltk.fegen.pyrt.terminalsrc.Span: ...

    def maybe_suppress(self) -> fltk.fegen.pyrt.terminalsrc.Span | None: ...


class QuantifierNode(typing.Protocol):
    class Label:
        ONE_OR_MORE: typing.ClassVar[object]
        OPTIONAL: typing.ClassVar[object]
        ZERO_OR_MORE: typing.ClassVar[object]

    span: fltk.fegen.pyrt.terminalsrc.Span
    children: list[tuple[Label | None, fltk.fegen.pyrt.terminalsrc.Span]]

    def append(self, child: fltk.fegen.pyrt.terminalsrc.Span, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span], label: Label | None = None
    ) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.terminalsrc.Span]: ...

    def append_one_or_more(self, child: fltk.fegen.pyrt.terminalsrc.Span) -> None: ...

    def extend_one_or_more(self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span]) -> None: ...

    def children_one_or_more(self) -> typing.Iterator[fltk.fegen.pyrt.terminalsrc.Span]: ...

    def child_one_or_more(self) -> fltk.fegen.pyrt.terminalsrc.Span: ...

    def maybe_one_or_more(self) -> fltk.fegen.pyrt.terminalsrc.Span | None: ...

    def append_optional(self, child: fltk.fegen.pyrt.terminalsrc.Span) -> None: ...

    def extend_optional(self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span]) -> None: ...

    def children_optional(self) -> typing.Iterator[fltk.fegen.pyrt.terminalsrc.Span]: ...

    def child_optional(self) -> fltk.fegen.pyrt.terminalsrc.Span: ...

    def maybe_optional(self) -> fltk.fegen.pyrt.terminalsrc.Span | None: ...

    def append_zero_or_more(self, child: fltk.fegen.pyrt.terminalsrc.Span) -> None: ...

    def extend_zero_or_more(self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span]) -> None: ...

    def children_zero_or_more(self) -> typing.Iterator[fltk.fegen.pyrt.terminalsrc.Span]: ...

    def child_zero_or_more(self) -> fltk.fegen.pyrt.terminalsrc.Span: ...

    def maybe_zero_or_more(self) -> fltk.fegen.pyrt.terminalsrc.Span | None: ...


class IdentifierNode(typing.Protocol):
    class Label:
        NAME: typing.ClassVar[object]

    span: fltk.fegen.pyrt.terminalsrc.Span
    children: list[tuple[Label | None, fltk.fegen.pyrt.terminalsrc.Span]]

    def append(self, child: fltk.fegen.pyrt.terminalsrc.Span, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span], label: Label | None = None
    ) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.terminalsrc.Span]: ...

    def append_name(self, child: fltk.fegen.pyrt.terminalsrc.Span) -> None: ...

    def extend_name(self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span]) -> None: ...

    def children_name(self) -> typing.Iterator[fltk.fegen.pyrt.terminalsrc.Span]: ...

    def child_name(self) -> fltk.fegen.pyrt.terminalsrc.Span: ...

    def maybe_name(self) -> fltk.fegen.pyrt.terminalsrc.Span | None: ...


class RawStringNode(typing.Protocol):
    class Label:
        VALUE: typing.ClassVar[object]

    span: fltk.fegen.pyrt.terminalsrc.Span
    children: list[tuple[Label | None, fltk.fegen.pyrt.terminalsrc.Span]]

    def append(self, child: fltk.fegen.pyrt.terminalsrc.Span, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span], label: Label | None = None
    ) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.terminalsrc.Span]: ...

    def append_value(self, child: fltk.fegen.pyrt.terminalsrc.Span) -> None: ...

    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span]) -> None: ...

    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.terminalsrc.Span]: ...

    def child_value(self) -> fltk.fegen.pyrt.terminalsrc.Span: ...

    def maybe_value(self) -> fltk.fegen.pyrt.terminalsrc.Span | None: ...


class LiteralNode(typing.Protocol):
    class Label:
        VALUE: typing.ClassVar[object]

    span: fltk.fegen.pyrt.terminalsrc.Span
    children: list[tuple[Label | None, fltk.fegen.pyrt.terminalsrc.Span]]

    def append(self, child: fltk.fegen.pyrt.terminalsrc.Span, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span], label: Label | None = None
    ) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.terminalsrc.Span]: ...

    def append_value(self, child: fltk.fegen.pyrt.terminalsrc.Span) -> None: ...

    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span]) -> None: ...

    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.terminalsrc.Span]: ...

    def child_value(self) -> fltk.fegen.pyrt.terminalsrc.Span: ...

    def maybe_value(self) -> fltk.fegen.pyrt.terminalsrc.Span | None: ...


class TriviaNode(typing.Protocol):
    class Label:
        BLOCK_COMMENT: typing.ClassVar[object]
        LINE_COMMENT: typing.ClassVar[object]

    span: fltk.fegen.pyrt.terminalsrc.Span
    children: list[tuple[Label | None, BlockCommentNode | LineCommentNode | fltk.fegen.pyrt.terminalsrc.Span]]

    def append(
        self, child: BlockCommentNode | LineCommentNode | fltk.fegen.pyrt.terminalsrc.Span, label: Label | None = None
    ) -> None: ...

    def extend(
        self,
        children: typing.Iterable[BlockCommentNode | LineCommentNode | fltk.fegen.pyrt.terminalsrc.Span],
        label: Label | None = None,
    ) -> None: ...

    def child(self) -> tuple[Label | None, BlockCommentNode | LineCommentNode | fltk.fegen.pyrt.terminalsrc.Span]: ...

    def append_block_comment(self, child: BlockCommentNode) -> None: ...

    def extend_block_comment(self, children: typing.Iterable[BlockCommentNode]) -> None: ...

    def children_block_comment(self) -> typing.Iterator[BlockCommentNode]: ...

    def child_block_comment(self) -> BlockCommentNode: ...

    def maybe_block_comment(self) -> BlockCommentNode | None: ...

    def append_line_comment(self, child: LineCommentNode) -> None: ...

    def extend_line_comment(self, children: typing.Iterable[LineCommentNode]) -> None: ...

    def children_line_comment(self) -> typing.Iterator[LineCommentNode]: ...

    def child_line_comment(self) -> LineCommentNode: ...

    def maybe_line_comment(self) -> LineCommentNode | None: ...


class LineCommentNode(typing.Protocol):
    class Label:
        CONTENT: typing.ClassVar[object]
        PREFIX: typing.ClassVar[object]

    span: fltk.fegen.pyrt.terminalsrc.Span
    children: list[tuple[Label | None, fltk.fegen.pyrt.terminalsrc.Span]]

    def append(self, child: fltk.fegen.pyrt.terminalsrc.Span, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span], label: Label | None = None
    ) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.terminalsrc.Span]: ...

    def append_content(self, child: fltk.fegen.pyrt.terminalsrc.Span) -> None: ...

    def extend_content(self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span]) -> None: ...

    def children_content(self) -> typing.Iterator[fltk.fegen.pyrt.terminalsrc.Span]: ...

    def child_content(self) -> fltk.fegen.pyrt.terminalsrc.Span: ...

    def maybe_content(self) -> fltk.fegen.pyrt.terminalsrc.Span | None: ...

    def append_prefix(self, child: fltk.fegen.pyrt.terminalsrc.Span) -> None: ...

    def extend_prefix(self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span]) -> None: ...

    def children_prefix(self) -> typing.Iterator[fltk.fegen.pyrt.terminalsrc.Span]: ...

    def child_prefix(self) -> fltk.fegen.pyrt.terminalsrc.Span: ...

    def maybe_prefix(self) -> fltk.fegen.pyrt.terminalsrc.Span | None: ...


class BlockCommentNode(typing.Protocol):
    class Label:
        CONTENT: typing.ClassVar[object]
        END: typing.ClassVar[object]
        START: typing.ClassVar[object]

    span: fltk.fegen.pyrt.terminalsrc.Span
    children: list[tuple[Label | None, fltk.fegen.pyrt.terminalsrc.Span]]

    def append(self, child: fltk.fegen.pyrt.terminalsrc.Span, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span], label: Label | None = None
    ) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.terminalsrc.Span]: ...

    def append_content(self, child: fltk.fegen.pyrt.terminalsrc.Span) -> None: ...

    def extend_content(self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span]) -> None: ...

    def children_content(self) -> typing.Iterator[fltk.fegen.pyrt.terminalsrc.Span]: ...

    def child_content(self) -> fltk.fegen.pyrt.terminalsrc.Span: ...

    def maybe_content(self) -> fltk.fegen.pyrt.terminalsrc.Span | None: ...

    def append_end(self, child: fltk.fegen.pyrt.terminalsrc.Span) -> None: ...

    def extend_end(self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span]) -> None: ...

    def children_end(self) -> typing.Iterator[fltk.fegen.pyrt.terminalsrc.Span]: ...

    def child_end(self) -> fltk.fegen.pyrt.terminalsrc.Span: ...

    def maybe_end(self) -> fltk.fegen.pyrt.terminalsrc.Span | None: ...

    def append_start(self, child: fltk.fegen.pyrt.terminalsrc.Span) -> None: ...

    def extend_start(self, children: typing.Iterable[fltk.fegen.pyrt.terminalsrc.Span]) -> None: ...

    def children_start(self) -> typing.Iterator[fltk.fegen.pyrt.terminalsrc.Span]: ...

    def child_start(self) -> fltk.fegen.pyrt.terminalsrc.Span: ...

    def maybe_start(self) -> fltk.fegen.pyrt.terminalsrc.Span | None: ...


class CstModule(typing.Protocol):
    @property
    def Grammar(self) -> type[GrammarNode]: ...

    @property
    def Rule(self) -> type[RuleNode]: ...

    @property
    def Alternatives(self) -> type[AlternativesNode]: ...

    @property
    def Items(self) -> type[ItemsNode]: ...

    @property
    def Item(self) -> type[ItemNode]: ...

    @property
    def Term(self) -> type[TermNode]: ...

    @property
    def Disposition(self) -> type[DispositionNode]: ...

    @property
    def Quantifier(self) -> type[QuantifierNode]: ...

    @property
    def Identifier(self) -> type[IdentifierNode]: ...

    @property
    def RawString(self) -> type[RawStringNode]: ...

    @property
    def Literal(self) -> type[LiteralNode]: ...

    @property
    def Trivia(self) -> type[TriviaNode]: ...

    @property
    def LineComment(self) -> type[LineCommentNode]: ...

    @property
    def BlockComment(self) -> type[BlockCommentNode]: ...
