# ruff: noqa: N802
from __future__ import annotations

import enum
import typing

import fltk.fegen.pyrt.terminalsrc

if typing.TYPE_CHECKING:
    import fltk.fegen.pyrt.span_protocol
__all__ = [
    "AstSpec",
    "BoolStmt",
    "CstModule",
    "CustomArg",
    "CustomSpec",
    "CustomStmt",
    "FieldStatement",
    "FieldStmt",
    "FlattenStmt",
    "FoldDir",
    "FoldStmt",
    "Identifier",
    "KeyStmt",
    "LineComment",
    "NameStmt",
    "NodeKind",
    "OptionStmt",
    "OptionValue",
    "ProductStmt",
    "RuleConfig",
    "RuleStatement",
    "Span",
    "Statement",
    "String",
    "SumStmt",
    "TextFromStmt",
    "TransparentStmt",
    "Trivia",
    "TypeSpec",
    "TypeStmt",
    "VariantStmt",
]


class NodeKind(enum.Enum):
    ASTSPEC = enum.auto()
    STATEMENT = enum.auto()
    OPTIONSTMT = enum.auto()
    OPTIONVALUE = enum.auto()
    RULECONFIG = enum.auto()
    RULESTATEMENT = enum.auto()
    TYPESTMT = enum.auto()
    TYPESPEC = enum.auto()
    CUSTOMSPEC = enum.auto()
    CUSTOMARG = enum.auto()
    BOOLSTMT = enum.auto()
    TRANSPARENTSTMT = enum.auto()
    TEXTFROMSTMT = enum.auto()
    KEYSTMT = enum.auto()
    FOLDSTMT = enum.auto()
    FOLDDIR = enum.auto()
    FLATTENSTMT = enum.auto()
    CUSTOMSTMT = enum.auto()
    NAMESTMT = enum.auto()
    VARIANTSTMT = enum.auto()
    FIELDSTMT = enum.auto()
    FIELDSTATEMENT = enum.auto()
    SUMSTMT = enum.auto()
    PRODUCTSTMT = enum.auto()
    IDENTIFIER = enum.auto()
    STRING = enum.auto()
    TRIVIA = enum.auto()
    LINECOMMENT = enum.auto()
    _fltk_canonical_name: str

    def __eq__(self, other: object) -> bool:
        if other is self:
            return True
        if type(other) is type(self):
            return self.name == other.name
        cn = getattr(other, "_fltk_canonical_name", None)
        if cn is not None:
            return self._fltk_canonical_name == cn
        return NotImplemented

    def __hash__(self) -> int:
        return hash(self._fltk_canonical_name)


NodeKind.ASTSPEC._fltk_canonical_name = "NodeKind.ASTSPEC"
NodeKind.STATEMENT._fltk_canonical_name = "NodeKind.STATEMENT"
NodeKind.OPTIONSTMT._fltk_canonical_name = "NodeKind.OPTIONSTMT"
NodeKind.OPTIONVALUE._fltk_canonical_name = "NodeKind.OPTIONVALUE"
NodeKind.RULECONFIG._fltk_canonical_name = "NodeKind.RULECONFIG"
NodeKind.RULESTATEMENT._fltk_canonical_name = "NodeKind.RULESTATEMENT"
NodeKind.TYPESTMT._fltk_canonical_name = "NodeKind.TYPESTMT"
NodeKind.TYPESPEC._fltk_canonical_name = "NodeKind.TYPESPEC"
NodeKind.CUSTOMSPEC._fltk_canonical_name = "NodeKind.CUSTOMSPEC"
NodeKind.CUSTOMARG._fltk_canonical_name = "NodeKind.CUSTOMARG"
NodeKind.BOOLSTMT._fltk_canonical_name = "NodeKind.BOOLSTMT"
NodeKind.TRANSPARENTSTMT._fltk_canonical_name = "NodeKind.TRANSPARENTSTMT"
NodeKind.TEXTFROMSTMT._fltk_canonical_name = "NodeKind.TEXTFROMSTMT"
NodeKind.KEYSTMT._fltk_canonical_name = "NodeKind.KEYSTMT"
NodeKind.FOLDSTMT._fltk_canonical_name = "NodeKind.FOLDSTMT"
NodeKind.FOLDDIR._fltk_canonical_name = "NodeKind.FOLDDIR"
NodeKind.FLATTENSTMT._fltk_canonical_name = "NodeKind.FLATTENSTMT"
NodeKind.CUSTOMSTMT._fltk_canonical_name = "NodeKind.CUSTOMSTMT"
NodeKind.NAMESTMT._fltk_canonical_name = "NodeKind.NAMESTMT"
NodeKind.VARIANTSTMT._fltk_canonical_name = "NodeKind.VARIANTSTMT"
NodeKind.FIELDSTMT._fltk_canonical_name = "NodeKind.FIELDSTMT"
NodeKind.FIELDSTATEMENT._fltk_canonical_name = "NodeKind.FIELDSTATEMENT"
NodeKind.SUMSTMT._fltk_canonical_name = "NodeKind.SUMSTMT"
NodeKind.PRODUCTSTMT._fltk_canonical_name = "NodeKind.PRODUCTSTMT"
NodeKind.IDENTIFIER._fltk_canonical_name = "NodeKind.IDENTIFIER"
NodeKind.STRING._fltk_canonical_name = "NodeKind.STRING"
NodeKind.TRIVIA._fltk_canonical_name = "NodeKind.TRIVIA"
NodeKind.LINECOMMENT._fltk_canonical_name = "NodeKind.LINECOMMENT"


class _ProtocolLabelMember:
    _fltk_canonical_name: str

    def __init__(self, canonical_name: str) -> None:
        self._fltk_canonical_name = canonical_name

    def __eq__(self, other: object) -> bool:
        if other is self:
            return True
        if type(other) is type(self):
            return self._fltk_canonical_name == other._fltk_canonical_name
        cn = getattr(other, "_fltk_canonical_name", None)
        if cn is not None:
            return self._fltk_canonical_name == cn
        return NotImplemented

    def __hash__(self) -> int:
        return hash(self._fltk_canonical_name)

    def __repr__(self) -> str:
        return f"_ProtocolLabelMember({self._fltk_canonical_name!r})"


class AstSpec(typing.Protocol):
    class Label:
        STATEMENT: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.ASTSPEC] = NodeKind.ASTSPEC
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Statement | Trivia]]

    def append(self, child: Statement | Trivia, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Statement | Trivia], label: Label | None = None) -> None: ...

    def extend_children(self, other: AstSpec) -> None: ...

    def child(self) -> tuple[Label | None, Statement | Trivia]: ...

    def insert(self, index: int, child: Statement | Trivia, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Statement | Trivia]: ...

    def replace_at(self, index: int, child: Statement | Trivia, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_statement(self, child: Statement) -> None: ...

    def extend_statement(self, children: typing.Iterable[Statement]) -> None: ...

    def children_statement(self) -> typing.Iterator[Statement]: ...

    def child_statement(self) -> Statement: ...

    def maybe_statement(self) -> Statement | None: ...

    def statement(self) -> list[Statement]: ...


AstSpec.Label.STATEMENT = _ProtocolLabelMember("AstSpec.Label.STATEMENT")


class Statement(typing.Protocol):
    class Label:
        OPTION_STMT: typing.ClassVar[object]
        RULE_CONFIG: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.STATEMENT] = NodeKind.STATEMENT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, OptionStmt | RuleConfig]]

    def append(self, child: OptionStmt | RuleConfig, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[OptionStmt | RuleConfig], label: Label | None = None) -> None: ...

    def extend_children(self, other: Statement) -> None: ...

    def child(self) -> tuple[Label | None, OptionStmt | RuleConfig]: ...

    def insert(self, index: int, child: OptionStmt | RuleConfig, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, OptionStmt | RuleConfig]: ...

    def replace_at(self, index: int, child: OptionStmt | RuleConfig, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_option_stmt(self, child: OptionStmt) -> None: ...

    def extend_option_stmt(self, children: typing.Iterable[OptionStmt]) -> None: ...

    def children_option_stmt(self) -> typing.Iterator[OptionStmt]: ...

    def child_option_stmt(self) -> OptionStmt: ...

    def maybe_option_stmt(self) -> OptionStmt | None: ...

    def append_rule_config(self, child: RuleConfig) -> None: ...

    def extend_rule_config(self, children: typing.Iterable[RuleConfig]) -> None: ...

    def children_rule_config(self) -> typing.Iterator[RuleConfig]: ...

    def child_rule_config(self) -> RuleConfig: ...

    def maybe_rule_config(self) -> RuleConfig | None: ...

    def option_stmt(self) -> OptionStmt | None: ...

    def rule_config(self) -> RuleConfig | None: ...

    def variant(self) -> Label: ...


Statement.Label.OPTION_STMT = _ProtocolLabelMember("Statement.Label.OPTION_STMT")
Statement.Label.RULE_CONFIG = _ProtocolLabelMember("Statement.Label.RULE_CONFIG")


class OptionStmt(typing.Protocol):
    class Label:
        KEY: typing.ClassVar[object]
        VALUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.OPTIONSTMT] = NodeKind.OPTIONSTMT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Identifier | OptionValue | Trivia]]

    def append(self, child: Identifier | OptionValue | Trivia, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[Identifier | OptionValue | Trivia], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: OptionStmt) -> None: ...

    def child(self) -> tuple[Label | None, Identifier | OptionValue | Trivia]: ...

    def insert(self, index: int, child: Identifier | OptionValue | Trivia, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Identifier | OptionValue | Trivia]: ...

    def replace_at(self, index: int, child: Identifier | OptionValue | Trivia, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_key(self, child: Identifier) -> None: ...

    def extend_key(self, children: typing.Iterable[Identifier]) -> None: ...

    def children_key(self) -> typing.Iterator[Identifier]: ...

    def child_key(self) -> Identifier: ...

    def maybe_key(self) -> Identifier | None: ...

    def append_value(self, child: OptionValue) -> None: ...

    def extend_value(self, children: typing.Iterable[OptionValue]) -> None: ...

    def children_value(self) -> typing.Iterator[OptionValue]: ...

    def child_value(self) -> OptionValue: ...

    def maybe_value(self) -> OptionValue | None: ...

    def key(self) -> Identifier: ...

    def value(self) -> OptionValue: ...


OptionStmt.Label.KEY = _ProtocolLabelMember("OptionStmt.Label.KEY")
OptionStmt.Label.VALUE = _ProtocolLabelMember("OptionStmt.Label.VALUE")


class OptionValue(typing.Protocol):
    class Label:
        FALSE: typing.ClassVar[object]
        STRING: typing.ClassVar[object]
        TRUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.OPTIONVALUE] = NodeKind.OPTIONVALUE
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, String | fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(
        self, child: String | fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def extend(
        self, children: typing.Iterable[String | fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: OptionValue) -> None: ...

    def child(self) -> tuple[Label | None, String | fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: String | fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, String | fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: String | fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_false(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_false(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_false(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_false(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_false(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def append_string(self, child: String) -> None: ...

    def extend_string(self, children: typing.Iterable[String]) -> None: ...

    def children_string(self) -> typing.Iterator[String]: ...

    def child_string(self) -> String: ...

    def maybe_string(self) -> String | None: ...

    def append_true(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_true(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_true(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_true(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_true(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def false(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def false_text(self) -> str | None: ...

    def string(self) -> String | None: ...

    def true(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def true_text(self) -> str | None: ...

    def variant(self) -> Label: ...


OptionValue.Label.FALSE = _ProtocolLabelMember("OptionValue.Label.FALSE")
OptionValue.Label.STRING = _ProtocolLabelMember("OptionValue.Label.STRING")
OptionValue.Label.TRUE = _ProtocolLabelMember("OptionValue.Label.TRUE")


class RuleConfig(typing.Protocol):
    class Label:
        RULE_NAME: typing.ClassVar[object]
        RULE_STATEMENT: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.RULECONFIG] = NodeKind.RULECONFIG
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Identifier | RuleStatement | Trivia]]

    def append(self, child: Identifier | RuleStatement | Trivia, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[Identifier | RuleStatement | Trivia], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: RuleConfig) -> None: ...

    def child(self) -> tuple[Label | None, Identifier | RuleStatement | Trivia]: ...

    def insert(self, index: int, child: Identifier | RuleStatement | Trivia, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Identifier | RuleStatement | Trivia]: ...

    def replace_at(
        self, index: int, child: Identifier | RuleStatement | Trivia, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_rule_name(self, child: Identifier) -> None: ...

    def extend_rule_name(self, children: typing.Iterable[Identifier]) -> None: ...

    def children_rule_name(self) -> typing.Iterator[Identifier]: ...

    def child_rule_name(self) -> Identifier: ...

    def maybe_rule_name(self) -> Identifier | None: ...

    def append_rule_statement(self, child: RuleStatement) -> None: ...

    def extend_rule_statement(self, children: typing.Iterable[RuleStatement]) -> None: ...

    def children_rule_statement(self) -> typing.Iterator[RuleStatement]: ...

    def child_rule_statement(self) -> RuleStatement: ...

    def maybe_rule_statement(self) -> RuleStatement | None: ...

    def rule_name(self) -> Identifier: ...

    def rule_statement(self) -> list[RuleStatement]: ...


RuleConfig.Label.RULE_NAME = _ProtocolLabelMember("RuleConfig.Label.RULE_NAME")
RuleConfig.Label.RULE_STATEMENT = _ProtocolLabelMember("RuleConfig.Label.RULE_STATEMENT")


class RuleStatement(typing.Protocol):
    class Label:
        BOOL_STMT: typing.ClassVar[object]
        CUSTOM_STMT: typing.ClassVar[object]
        FIELD_STMT: typing.ClassVar[object]
        FLATTEN_STMT: typing.ClassVar[object]
        FOLD_STMT: typing.ClassVar[object]
        KEY_STMT: typing.ClassVar[object]
        NAME_STMT: typing.ClassVar[object]
        PRODUCT_STMT: typing.ClassVar[object]
        SUM_STMT: typing.ClassVar[object]
        TEXT_FROM_STMT: typing.ClassVar[object]
        TRANSPARENT_STMT: typing.ClassVar[object]
        TYPE_STMT: typing.ClassVar[object]
        VARIANT_STMT: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.RULESTATEMENT] = NodeKind.RULESTATEMENT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[
        tuple[
            Label | None,
            BoolStmt
            | CustomStmt
            | FieldStmt
            | FlattenStmt
            | FoldStmt
            | KeyStmt
            | NameStmt
            | ProductStmt
            | SumStmt
            | TextFromStmt
            | TransparentStmt
            | TypeStmt
            | VariantStmt,
        ]
    ]

    def append(
        self,
        child: BoolStmt
        | CustomStmt
        | FieldStmt
        | FlattenStmt
        | FoldStmt
        | KeyStmt
        | NameStmt
        | ProductStmt
        | SumStmt
        | TextFromStmt
        | TransparentStmt
        | TypeStmt
        | VariantStmt,
        label: Label | None = None,
    ) -> None: ...

    def extend(
        self,
        children: typing.Iterable[
            BoolStmt
            | CustomStmt
            | FieldStmt
            | FlattenStmt
            | FoldStmt
            | KeyStmt
            | NameStmt
            | ProductStmt
            | SumStmt
            | TextFromStmt
            | TransparentStmt
            | TypeStmt
            | VariantStmt
        ],
        label: Label | None = None,
    ) -> None: ...

    def extend_children(self, other: RuleStatement) -> None: ...

    def child(
        self,
    ) -> tuple[
        Label | None,
        BoolStmt
        | CustomStmt
        | FieldStmt
        | FlattenStmt
        | FoldStmt
        | KeyStmt
        | NameStmt
        | ProductStmt
        | SumStmt
        | TextFromStmt
        | TransparentStmt
        | TypeStmt
        | VariantStmt,
    ]: ...

    def insert(
        self,
        index: int,
        child: BoolStmt
        | CustomStmt
        | FieldStmt
        | FlattenStmt
        | FoldStmt
        | KeyStmt
        | NameStmt
        | ProductStmt
        | SumStmt
        | TextFromStmt
        | TransparentStmt
        | TypeStmt
        | VariantStmt,
        label: Label | None = None,
    ) -> None: ...

    def remove_at(
        self, index: int
    ) -> tuple[
        Label | None,
        BoolStmt
        | CustomStmt
        | FieldStmt
        | FlattenStmt
        | FoldStmt
        | KeyStmt
        | NameStmt
        | ProductStmt
        | SumStmt
        | TextFromStmt
        | TransparentStmt
        | TypeStmt
        | VariantStmt,
    ]: ...

    def replace_at(
        self,
        index: int,
        child: BoolStmt
        | CustomStmt
        | FieldStmt
        | FlattenStmt
        | FoldStmt
        | KeyStmt
        | NameStmt
        | ProductStmt
        | SumStmt
        | TextFromStmt
        | TransparentStmt
        | TypeStmt
        | VariantStmt,
        label: Label | None = None,
    ) -> None: ...

    def clear(self) -> None: ...

    def append_bool_stmt(self, child: BoolStmt) -> None: ...

    def extend_bool_stmt(self, children: typing.Iterable[BoolStmt]) -> None: ...

    def children_bool_stmt(self) -> typing.Iterator[BoolStmt]: ...

    def child_bool_stmt(self) -> BoolStmt: ...

    def maybe_bool_stmt(self) -> BoolStmt | None: ...

    def append_custom_stmt(self, child: CustomStmt) -> None: ...

    def extend_custom_stmt(self, children: typing.Iterable[CustomStmt]) -> None: ...

    def children_custom_stmt(self) -> typing.Iterator[CustomStmt]: ...

    def child_custom_stmt(self) -> CustomStmt: ...

    def maybe_custom_stmt(self) -> CustomStmt | None: ...

    def append_field_stmt(self, child: FieldStmt) -> None: ...

    def extend_field_stmt(self, children: typing.Iterable[FieldStmt]) -> None: ...

    def children_field_stmt(self) -> typing.Iterator[FieldStmt]: ...

    def child_field_stmt(self) -> FieldStmt: ...

    def maybe_field_stmt(self) -> FieldStmt | None: ...

    def append_flatten_stmt(self, child: FlattenStmt) -> None: ...

    def extend_flatten_stmt(self, children: typing.Iterable[FlattenStmt]) -> None: ...

    def children_flatten_stmt(self) -> typing.Iterator[FlattenStmt]: ...

    def child_flatten_stmt(self) -> FlattenStmt: ...

    def maybe_flatten_stmt(self) -> FlattenStmt | None: ...

    def append_fold_stmt(self, child: FoldStmt) -> None: ...

    def extend_fold_stmt(self, children: typing.Iterable[FoldStmt]) -> None: ...

    def children_fold_stmt(self) -> typing.Iterator[FoldStmt]: ...

    def child_fold_stmt(self) -> FoldStmt: ...

    def maybe_fold_stmt(self) -> FoldStmt | None: ...

    def append_key_stmt(self, child: KeyStmt) -> None: ...

    def extend_key_stmt(self, children: typing.Iterable[KeyStmt]) -> None: ...

    def children_key_stmt(self) -> typing.Iterator[KeyStmt]: ...

    def child_key_stmt(self) -> KeyStmt: ...

    def maybe_key_stmt(self) -> KeyStmt | None: ...

    def append_name_stmt(self, child: NameStmt) -> None: ...

    def extend_name_stmt(self, children: typing.Iterable[NameStmt]) -> None: ...

    def children_name_stmt(self) -> typing.Iterator[NameStmt]: ...

    def child_name_stmt(self) -> NameStmt: ...

    def maybe_name_stmt(self) -> NameStmt | None: ...

    def append_product_stmt(self, child: ProductStmt) -> None: ...

    def extend_product_stmt(self, children: typing.Iterable[ProductStmt]) -> None: ...

    def children_product_stmt(self) -> typing.Iterator[ProductStmt]: ...

    def child_product_stmt(self) -> ProductStmt: ...

    def maybe_product_stmt(self) -> ProductStmt | None: ...

    def append_sum_stmt(self, child: SumStmt) -> None: ...

    def extend_sum_stmt(self, children: typing.Iterable[SumStmt]) -> None: ...

    def children_sum_stmt(self) -> typing.Iterator[SumStmt]: ...

    def child_sum_stmt(self) -> SumStmt: ...

    def maybe_sum_stmt(self) -> SumStmt | None: ...

    def append_text_from_stmt(self, child: TextFromStmt) -> None: ...

    def extend_text_from_stmt(self, children: typing.Iterable[TextFromStmt]) -> None: ...

    def children_text_from_stmt(self) -> typing.Iterator[TextFromStmt]: ...

    def child_text_from_stmt(self) -> TextFromStmt: ...

    def maybe_text_from_stmt(self) -> TextFromStmt | None: ...

    def append_transparent_stmt(self, child: TransparentStmt) -> None: ...

    def extend_transparent_stmt(self, children: typing.Iterable[TransparentStmt]) -> None: ...

    def children_transparent_stmt(self) -> typing.Iterator[TransparentStmt]: ...

    def child_transparent_stmt(self) -> TransparentStmt: ...

    def maybe_transparent_stmt(self) -> TransparentStmt | None: ...

    def append_type_stmt(self, child: TypeStmt) -> None: ...

    def extend_type_stmt(self, children: typing.Iterable[TypeStmt]) -> None: ...

    def children_type_stmt(self) -> typing.Iterator[TypeStmt]: ...

    def child_type_stmt(self) -> TypeStmt: ...

    def maybe_type_stmt(self) -> TypeStmt | None: ...

    def append_variant_stmt(self, child: VariantStmt) -> None: ...

    def extend_variant_stmt(self, children: typing.Iterable[VariantStmt]) -> None: ...

    def children_variant_stmt(self) -> typing.Iterator[VariantStmt]: ...

    def child_variant_stmt(self) -> VariantStmt: ...

    def maybe_variant_stmt(self) -> VariantStmt | None: ...

    def bool_stmt(self) -> BoolStmt | None: ...

    def custom_stmt(self) -> CustomStmt | None: ...

    def field_stmt(self) -> FieldStmt | None: ...

    def flatten_stmt(self) -> FlattenStmt | None: ...

    def fold_stmt(self) -> FoldStmt | None: ...

    def key_stmt(self) -> KeyStmt | None: ...

    def name_stmt(self) -> NameStmt | None: ...

    def product_stmt(self) -> ProductStmt | None: ...

    def sum_stmt(self) -> SumStmt | None: ...

    def text_from_stmt(self) -> TextFromStmt | None: ...

    def transparent_stmt(self) -> TransparentStmt | None: ...

    def type_stmt(self) -> TypeStmt | None: ...

    def variant_stmt(self) -> VariantStmt | None: ...

    def variant(self) -> Label: ...


RuleStatement.Label.BOOL_STMT = _ProtocolLabelMember("RuleStatement.Label.BOOL_STMT")
RuleStatement.Label.CUSTOM_STMT = _ProtocolLabelMember("RuleStatement.Label.CUSTOM_STMT")
RuleStatement.Label.FIELD_STMT = _ProtocolLabelMember("RuleStatement.Label.FIELD_STMT")
RuleStatement.Label.FLATTEN_STMT = _ProtocolLabelMember("RuleStatement.Label.FLATTEN_STMT")
RuleStatement.Label.FOLD_STMT = _ProtocolLabelMember("RuleStatement.Label.FOLD_STMT")
RuleStatement.Label.KEY_STMT = _ProtocolLabelMember("RuleStatement.Label.KEY_STMT")
RuleStatement.Label.NAME_STMT = _ProtocolLabelMember("RuleStatement.Label.NAME_STMT")
RuleStatement.Label.PRODUCT_STMT = _ProtocolLabelMember("RuleStatement.Label.PRODUCT_STMT")
RuleStatement.Label.SUM_STMT = _ProtocolLabelMember("RuleStatement.Label.SUM_STMT")
RuleStatement.Label.TEXT_FROM_STMT = _ProtocolLabelMember("RuleStatement.Label.TEXT_FROM_STMT")
RuleStatement.Label.TRANSPARENT_STMT = _ProtocolLabelMember("RuleStatement.Label.TRANSPARENT_STMT")
RuleStatement.Label.TYPE_STMT = _ProtocolLabelMember("RuleStatement.Label.TYPE_STMT")
RuleStatement.Label.VARIANT_STMT = _ProtocolLabelMember("RuleStatement.Label.VARIANT_STMT")


class TypeStmt(typing.Protocol):
    class Label:
        SPEC: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.TYPESTMT] = NodeKind.TYPESTMT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Trivia | TypeSpec]]

    def append(self, child: Trivia | TypeSpec, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Trivia | TypeSpec], label: Label | None = None) -> None: ...

    def extend_children(self, other: TypeStmt) -> None: ...

    def child(self) -> tuple[Label | None, Trivia | TypeSpec]: ...

    def insert(self, index: int, child: Trivia | TypeSpec, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Trivia | TypeSpec]: ...

    def replace_at(self, index: int, child: Trivia | TypeSpec, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_spec(self, child: TypeSpec) -> None: ...

    def extend_spec(self, children: typing.Iterable[TypeSpec]) -> None: ...

    def children_spec(self) -> typing.Iterator[TypeSpec]: ...

    def child_spec(self) -> TypeSpec: ...

    def maybe_spec(self) -> TypeSpec | None: ...

    def spec(self) -> TypeSpec: ...


TypeStmt.Label.SPEC = _ProtocolLabelMember("TypeStmt.Label.SPEC")


class TypeSpec(typing.Protocol):
    class Label:
        BUILTIN: typing.ClassVar[object]
        CUSTOM: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.TYPESPEC] = NodeKind.TYPESPEC
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, CustomSpec | Identifier]]

    def append(self, child: CustomSpec | Identifier, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[CustomSpec | Identifier], label: Label | None = None) -> None: ...

    def extend_children(self, other: TypeSpec) -> None: ...

    def child(self) -> tuple[Label | None, CustomSpec | Identifier]: ...

    def insert(self, index: int, child: CustomSpec | Identifier, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, CustomSpec | Identifier]: ...

    def replace_at(self, index: int, child: CustomSpec | Identifier, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_builtin(self, child: Identifier) -> None: ...

    def extend_builtin(self, children: typing.Iterable[Identifier]) -> None: ...

    def children_builtin(self) -> typing.Iterator[Identifier]: ...

    def child_builtin(self) -> Identifier: ...

    def maybe_builtin(self) -> Identifier | None: ...

    def append_custom(self, child: CustomSpec) -> None: ...

    def extend_custom(self, children: typing.Iterable[CustomSpec]) -> None: ...

    def children_custom(self) -> typing.Iterator[CustomSpec]: ...

    def child_custom(self) -> CustomSpec: ...

    def maybe_custom(self) -> CustomSpec | None: ...

    def builtin(self) -> Identifier | None: ...

    def custom(self) -> CustomSpec | None: ...

    def variant(self) -> Label: ...


TypeSpec.Label.BUILTIN = _ProtocolLabelMember("TypeSpec.Label.BUILTIN")
TypeSpec.Label.CUSTOM = _ProtocolLabelMember("TypeSpec.Label.CUSTOM")


class CustomSpec(typing.Protocol):
    class Label:
        ARG: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.CUSTOMSPEC] = NodeKind.CUSTOMSPEC
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, CustomArg | Trivia]]

    def append(self, child: CustomArg | Trivia, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[CustomArg | Trivia], label: Label | None = None) -> None: ...

    def extend_children(self, other: CustomSpec) -> None: ...

    def child(self) -> tuple[Label | None, CustomArg | Trivia]: ...

    def insert(self, index: int, child: CustomArg | Trivia, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, CustomArg | Trivia]: ...

    def replace_at(self, index: int, child: CustomArg | Trivia, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_arg(self, child: CustomArg) -> None: ...

    def extend_arg(self, children: typing.Iterable[CustomArg]) -> None: ...

    def children_arg(self) -> typing.Iterator[CustomArg]: ...

    def child_arg(self) -> CustomArg: ...

    def maybe_arg(self) -> CustomArg | None: ...

    def arg(self) -> list[CustomArg]: ...


CustomSpec.Label.ARG = _ProtocolLabelMember("CustomSpec.Label.ARG")


class CustomArg(typing.Protocol):
    class Label:
        KEY: typing.ClassVar[object]
        VALUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.CUSTOMARG] = NodeKind.CUSTOMARG
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Identifier | String | Trivia]]

    def append(self, child: Identifier | String | Trivia, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Identifier | String | Trivia], label: Label | None = None) -> None: ...

    def extend_children(self, other: CustomArg) -> None: ...

    def child(self) -> tuple[Label | None, Identifier | String | Trivia]: ...

    def insert(self, index: int, child: Identifier | String | Trivia, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Identifier | String | Trivia]: ...

    def replace_at(self, index: int, child: Identifier | String | Trivia, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_key(self, child: Identifier) -> None: ...

    def extend_key(self, children: typing.Iterable[Identifier]) -> None: ...

    def children_key(self) -> typing.Iterator[Identifier]: ...

    def child_key(self) -> Identifier: ...

    def maybe_key(self) -> Identifier | None: ...

    def append_value(self, child: String) -> None: ...

    def extend_value(self, children: typing.Iterable[String]) -> None: ...

    def children_value(self) -> typing.Iterator[String]: ...

    def child_value(self) -> String: ...

    def maybe_value(self) -> String | None: ...

    def key(self) -> Identifier: ...

    def value(self) -> String: ...


CustomArg.Label.KEY = _ProtocolLabelMember("CustomArg.Label.KEY")
CustomArg.Label.VALUE = _ProtocolLabelMember("CustomArg.Label.VALUE")


class BoolStmt(typing.Protocol):
    class Label:
        TRUTHY: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.BOOLSTMT] = NodeKind.BOOLSTMT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Identifier | Trivia]]

    def append(self, child: Identifier | Trivia, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Identifier | Trivia], label: Label | None = None) -> None: ...

    def extend_children(self, other: BoolStmt) -> None: ...

    def child(self) -> tuple[Label | None, Identifier | Trivia]: ...

    def insert(self, index: int, child: Identifier | Trivia, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Identifier | Trivia]: ...

    def replace_at(self, index: int, child: Identifier | Trivia, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_truthy(self, child: Identifier) -> None: ...

    def extend_truthy(self, children: typing.Iterable[Identifier]) -> None: ...

    def children_truthy(self) -> typing.Iterator[Identifier]: ...

    def child_truthy(self) -> Identifier: ...

    def maybe_truthy(self) -> Identifier | None: ...

    def truthy(self) -> Identifier: ...


BoolStmt.Label.TRUTHY = _ProtocolLabelMember("BoolStmt.Label.TRUTHY")


class TransparentStmt(typing.Protocol):
    kind: typing.Literal[NodeKind.TRANSPARENTSTMT] = NodeKind.TRANSPARENTSTMT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[None, Trivia]]

    def append(self, child: Trivia, label: None = None) -> None: ...

    def extend(self, children: typing.Iterable[Trivia], label: None = None) -> None: ...

    def extend_children(self, other: TransparentStmt) -> None: ...

    def child(self) -> tuple[None, Trivia]: ...

    def insert(self, index: int, child: Trivia, label: None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[None, Trivia]: ...

    def replace_at(self, index: int, child: Trivia, label: None = None) -> None: ...

    def clear(self) -> None: ...

    def text(self) -> str: ...


class TextFromStmt(typing.Protocol):
    class Label:
        LABEL: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.TEXTFROMSTMT] = NodeKind.TEXTFROMSTMT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Identifier | Trivia]]

    def append(self, child: Identifier | Trivia, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Identifier | Trivia], label: Label | None = None) -> None: ...

    def extend_children(self, other: TextFromStmt) -> None: ...

    def child(self) -> tuple[Label | None, Identifier | Trivia]: ...

    def insert(self, index: int, child: Identifier | Trivia, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Identifier | Trivia]: ...

    def replace_at(self, index: int, child: Identifier | Trivia, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_label(self, child: Identifier) -> None: ...

    def extend_label(self, children: typing.Iterable[Identifier]) -> None: ...

    def children_label(self) -> typing.Iterator[Identifier]: ...

    def child_label(self) -> Identifier: ...

    def maybe_label(self) -> Identifier | None: ...

    def label(self) -> Identifier: ...


TextFromStmt.Label.LABEL = _ProtocolLabelMember("TextFromStmt.Label.LABEL")


class KeyStmt(typing.Protocol):
    class Label:
        LABEL: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.KEYSTMT] = NodeKind.KEYSTMT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Identifier | Trivia]]

    def append(self, child: Identifier | Trivia, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Identifier | Trivia], label: Label | None = None) -> None: ...

    def extend_children(self, other: KeyStmt) -> None: ...

    def child(self) -> tuple[Label | None, Identifier | Trivia]: ...

    def insert(self, index: int, child: Identifier | Trivia, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Identifier | Trivia]: ...

    def replace_at(self, index: int, child: Identifier | Trivia, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_label(self, child: Identifier) -> None: ...

    def extend_label(self, children: typing.Iterable[Identifier]) -> None: ...

    def children_label(self) -> typing.Iterator[Identifier]: ...

    def child_label(self) -> Identifier: ...

    def maybe_label(self) -> Identifier | None: ...

    def label(self) -> Identifier: ...


KeyStmt.Label.LABEL = _ProtocolLabelMember("KeyStmt.Label.LABEL")


class FoldStmt(typing.Protocol):
    class Label:
        DIR: typing.ClassVar[object]
        OP: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.FOLDSTMT] = NodeKind.FOLDSTMT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, FoldDir | Identifier | Trivia]]

    def append(self, child: FoldDir | Identifier | Trivia, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[FoldDir | Identifier | Trivia], label: Label | None = None) -> None: ...

    def extend_children(self, other: FoldStmt) -> None: ...

    def child(self) -> tuple[Label | None, FoldDir | Identifier | Trivia]: ...

    def insert(self, index: int, child: FoldDir | Identifier | Trivia, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, FoldDir | Identifier | Trivia]: ...

    def replace_at(self, index: int, child: FoldDir | Identifier | Trivia, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_dir(self, child: FoldDir) -> None: ...

    def extend_dir(self, children: typing.Iterable[FoldDir]) -> None: ...

    def children_dir(self) -> typing.Iterator[FoldDir]: ...

    def child_dir(self) -> FoldDir: ...

    def maybe_dir(self) -> FoldDir | None: ...

    def append_op(self, child: Identifier) -> None: ...

    def extend_op(self, children: typing.Iterable[Identifier]) -> None: ...

    def children_op(self) -> typing.Iterator[Identifier]: ...

    def child_op(self) -> Identifier: ...

    def maybe_op(self) -> Identifier | None: ...

    def dir(self) -> FoldDir: ...

    def op(self) -> Identifier: ...


FoldStmt.Label.DIR = _ProtocolLabelMember("FoldStmt.Label.DIR")
FoldStmt.Label.OP = _ProtocolLabelMember("FoldStmt.Label.OP")


class FoldDir(typing.Protocol):
    class Label:
        LEFT: typing.ClassVar[object]
        RIGHT: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.FOLDDIR] = NodeKind.FOLDDIR
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: FoldDir) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_left(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_left(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_left(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_left(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_left(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def append_right(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_right(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_right(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_right(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_right(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def left(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def left_text(self) -> str | None: ...

    def right(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def right_text(self) -> str | None: ...

    def text(self) -> str: ...

    def variant(self) -> Label: ...


FoldDir.Label.LEFT = _ProtocolLabelMember("FoldDir.Label.LEFT")
FoldDir.Label.RIGHT = _ProtocolLabelMember("FoldDir.Label.RIGHT")


class FlattenStmt(typing.Protocol):
    kind: typing.Literal[NodeKind.FLATTENSTMT] = NodeKind.FLATTENSTMT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[None, Trivia]]

    def append(self, child: Trivia, label: None = None) -> None: ...

    def extend(self, children: typing.Iterable[Trivia], label: None = None) -> None: ...

    def extend_children(self, other: FlattenStmt) -> None: ...

    def child(self) -> tuple[None, Trivia]: ...

    def insert(self, index: int, child: Trivia, label: None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[None, Trivia]: ...

    def replace_at(self, index: int, child: Trivia, label: None = None) -> None: ...

    def clear(self) -> None: ...

    def text(self) -> str: ...


class CustomStmt(typing.Protocol):
    class Label:
        ARG: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.CUSTOMSTMT] = NodeKind.CUSTOMSTMT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, CustomArg | Trivia]]

    def append(self, child: CustomArg | Trivia, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[CustomArg | Trivia], label: Label | None = None) -> None: ...

    def extend_children(self, other: CustomStmt) -> None: ...

    def child(self) -> tuple[Label | None, CustomArg | Trivia]: ...

    def insert(self, index: int, child: CustomArg | Trivia, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, CustomArg | Trivia]: ...

    def replace_at(self, index: int, child: CustomArg | Trivia, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_arg(self, child: CustomArg) -> None: ...

    def extend_arg(self, children: typing.Iterable[CustomArg]) -> None: ...

    def children_arg(self) -> typing.Iterator[CustomArg]: ...

    def child_arg(self) -> CustomArg: ...

    def maybe_arg(self) -> CustomArg | None: ...

    def arg(self) -> list[CustomArg]: ...


CustomStmt.Label.ARG = _ProtocolLabelMember("CustomStmt.Label.ARG")


class NameStmt(typing.Protocol):
    class Label:
        NEW_NAME: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.NAMESTMT] = NodeKind.NAMESTMT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Identifier | Trivia]]

    def append(self, child: Identifier | Trivia, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Identifier | Trivia], label: Label | None = None) -> None: ...

    def extend_children(self, other: NameStmt) -> None: ...

    def child(self) -> tuple[Label | None, Identifier | Trivia]: ...

    def insert(self, index: int, child: Identifier | Trivia, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Identifier | Trivia]: ...

    def replace_at(self, index: int, child: Identifier | Trivia, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_new_name(self, child: Identifier) -> None: ...

    def extend_new_name(self, children: typing.Iterable[Identifier]) -> None: ...

    def children_new_name(self) -> typing.Iterator[Identifier]: ...

    def child_new_name(self) -> Identifier: ...

    def maybe_new_name(self) -> Identifier | None: ...

    def new_name(self) -> Identifier: ...


NameStmt.Label.NEW_NAME = _ProtocolLabelMember("NameStmt.Label.NEW_NAME")


class VariantStmt(typing.Protocol):
    class Label:
        NEW_NAME: typing.ClassVar[object]
        SELECTOR: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.VARIANTSTMT] = NodeKind.VARIANTSTMT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, Identifier | Trivia]]

    def append(self, child: Identifier | Trivia, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[Identifier | Trivia], label: Label | None = None) -> None: ...

    def extend_children(self, other: VariantStmt) -> None: ...

    def child(self) -> tuple[Label | None, Identifier | Trivia]: ...

    def insert(self, index: int, child: Identifier | Trivia, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, Identifier | Trivia]: ...

    def replace_at(self, index: int, child: Identifier | Trivia, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_new_name(self, child: Identifier) -> None: ...

    def extend_new_name(self, children: typing.Iterable[Identifier]) -> None: ...

    def children_new_name(self) -> typing.Iterator[Identifier]: ...

    def child_new_name(self) -> Identifier: ...

    def maybe_new_name(self) -> Identifier | None: ...

    def append_selector(self, child: Identifier) -> None: ...

    def extend_selector(self, children: typing.Iterable[Identifier]) -> None: ...

    def children_selector(self) -> typing.Iterator[Identifier]: ...

    def child_selector(self) -> Identifier: ...

    def maybe_selector(self) -> Identifier | None: ...

    def new_name(self) -> Identifier: ...

    def selector(self) -> Identifier: ...


VariantStmt.Label.NEW_NAME = _ProtocolLabelMember("VariantStmt.Label.NEW_NAME")
VariantStmt.Label.SELECTOR = _ProtocolLabelMember("VariantStmt.Label.SELECTOR")


class FieldStmt(typing.Protocol):
    class Label:
        FIELD_STATEMENT: typing.ClassVar[object]
        LABEL: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.FIELDSTMT] = NodeKind.FIELDSTMT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, FieldStatement | Identifier | Trivia]]

    def append(self, child: FieldStatement | Identifier | Trivia, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[FieldStatement | Identifier | Trivia], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: FieldStmt) -> None: ...

    def child(self) -> tuple[Label | None, FieldStatement | Identifier | Trivia]: ...

    def insert(self, index: int, child: FieldStatement | Identifier | Trivia, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, FieldStatement | Identifier | Trivia]: ...

    def replace_at(
        self, index: int, child: FieldStatement | Identifier | Trivia, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_field_statement(self, child: FieldStatement) -> None: ...

    def extend_field_statement(self, children: typing.Iterable[FieldStatement]) -> None: ...

    def children_field_statement(self) -> typing.Iterator[FieldStatement]: ...

    def child_field_statement(self) -> FieldStatement: ...

    def maybe_field_statement(self) -> FieldStatement | None: ...

    def append_label(self, child: Identifier) -> None: ...

    def extend_label(self, children: typing.Iterable[Identifier]) -> None: ...

    def children_label(self) -> typing.Iterator[Identifier]: ...

    def child_label(self) -> Identifier: ...

    def maybe_label(self) -> Identifier | None: ...

    def field_statement(self) -> list[FieldStatement]: ...

    def label(self) -> Identifier: ...


FieldStmt.Label.FIELD_STATEMENT = _ProtocolLabelMember("FieldStmt.Label.FIELD_STATEMENT")
FieldStmt.Label.LABEL = _ProtocolLabelMember("FieldStmt.Label.LABEL")


class FieldStatement(typing.Protocol):
    class Label:
        NAME_STMT: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.FIELDSTATEMENT] = NodeKind.FIELDSTATEMENT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, NameStmt]]

    def append(self, child: NameStmt, label: Label | None = None) -> None: ...

    def extend(self, children: typing.Iterable[NameStmt], label: Label | None = None) -> None: ...

    def extend_children(self, other: FieldStatement) -> None: ...

    def child(self) -> tuple[Label | None, NameStmt]: ...

    def insert(self, index: int, child: NameStmt, label: Label | None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, NameStmt]: ...

    def replace_at(self, index: int, child: NameStmt, label: Label | None = None) -> None: ...

    def clear(self) -> None: ...

    def append_name_stmt(self, child: NameStmt) -> None: ...

    def extend_name_stmt(self, children: typing.Iterable[NameStmt]) -> None: ...

    def children_name_stmt(self) -> typing.Iterator[NameStmt]: ...

    def child_name_stmt(self) -> NameStmt: ...

    def maybe_name_stmt(self) -> NameStmt | None: ...

    def name_stmt(self) -> NameStmt: ...


FieldStatement.Label.NAME_STMT = _ProtocolLabelMember("FieldStatement.Label.NAME_STMT")


class SumStmt(typing.Protocol):
    kind: typing.Literal[NodeKind.SUMSTMT] = NodeKind.SUMSTMT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[None, Trivia]]

    def append(self, child: Trivia, label: None = None) -> None: ...

    def extend(self, children: typing.Iterable[Trivia], label: None = None) -> None: ...

    def extend_children(self, other: SumStmt) -> None: ...

    def child(self) -> tuple[None, Trivia]: ...

    def insert(self, index: int, child: Trivia, label: None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[None, Trivia]: ...

    def replace_at(self, index: int, child: Trivia, label: None = None) -> None: ...

    def clear(self) -> None: ...

    def text(self) -> str: ...


class ProductStmt(typing.Protocol):
    kind: typing.Literal[NodeKind.PRODUCTSTMT] = NodeKind.PRODUCTSTMT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[None, Trivia]]

    def append(self, child: Trivia, label: None = None) -> None: ...

    def extend(self, children: typing.Iterable[Trivia], label: None = None) -> None: ...

    def extend_children(self, other: ProductStmt) -> None: ...

    def child(self) -> tuple[None, Trivia]: ...

    def insert(self, index: int, child: Trivia, label: None = None) -> None: ...

    def remove_at(self, index: int) -> tuple[None, Trivia]: ...

    def replace_at(self, index: int, child: Trivia, label: None = None) -> None: ...

    def clear(self) -> None: ...

    def text(self) -> str: ...


class Identifier(typing.Protocol):
    class Label:
        NAME: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.IDENTIFIER] = NodeKind.IDENTIFIER
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: Identifier) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_name(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_name(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_name(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_name(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_name(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def name(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def name_text(self) -> str: ...

    def text(self) -> str: ...


Identifier.Label.NAME = _ProtocolLabelMember("Identifier.Label.NAME")


class String(typing.Protocol):
    class Label:
        VALUE: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.STRING] = NodeKind.STRING
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: String) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_value(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_value(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_value(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def value(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def value_text(self) -> str: ...

    def text(self) -> str: ...


String.Label.VALUE = _ProtocolLabelMember("String.Label.VALUE")


class Trivia(typing.Protocol):
    class Label:
        LINE_COMMENT: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.TRIVIA] = NodeKind.TRIVIA
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(
        self, child: LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def extend(
        self,
        children: typing.Iterable[LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol],
        label: Label | None = None,
    ) -> None: ...

    def extend_children(self, other: Trivia) -> None: ...

    def child(self) -> tuple[Label | None, LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(
        self, index: int
    ) -> tuple[Label | None, LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: LineComment | fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_line_comment(self, child: LineComment) -> None: ...

    def extend_line_comment(self, children: typing.Iterable[LineComment]) -> None: ...

    def children_line_comment(self) -> typing.Iterator[LineComment]: ...

    def child_line_comment(self) -> LineComment: ...

    def maybe_line_comment(self) -> LineComment | None: ...

    def line_comment(self) -> list[LineComment]: ...


Trivia.Label.LINE_COMMENT = _ProtocolLabelMember("Trivia.Label.LINE_COMMENT")


class LineComment(typing.Protocol):
    class Label:
        CONTENT: typing.ClassVar[object]
        NEWLINE: typing.ClassVar[object]
        PREFIX: typing.ClassVar[object]

    kind: typing.Literal[NodeKind.LINECOMMENT] = NodeKind.LINECOMMENT
    span: fltk.fegen.pyrt.span_protocol.SpanProtocol
    children: list[tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]]

    def append(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None) -> None: ...

    def extend(
        self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol], label: Label | None = None
    ) -> None: ...

    def extend_children(self, other: LineComment) -> None: ...

    def child(self) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def insert(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def remove_at(self, index: int) -> tuple[Label | None, fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def replace_at(
        self, index: int, child: fltk.fegen.pyrt.span_protocol.SpanProtocol, label: Label | None = None
    ) -> None: ...

    def clear(self) -> None: ...

    def append_content(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_content(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_content(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_content(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_content(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def append_newline(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_newline(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_newline(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_newline(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_newline(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def append_prefix(self, child: fltk.fegen.pyrt.span_protocol.SpanProtocol) -> None: ...

    def extend_prefix(self, children: typing.Iterable[fltk.fegen.pyrt.span_protocol.SpanProtocol]) -> None: ...

    def children_prefix(self) -> typing.Iterator[fltk.fegen.pyrt.span_protocol.SpanProtocol]: ...

    def child_prefix(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def maybe_prefix(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol | None: ...

    def content(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def content_text(self) -> str: ...

    def newline(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def newline_text(self) -> str: ...

    def prefix(self) -> fltk.fegen.pyrt.span_protocol.SpanProtocol: ...

    def prefix_text(self) -> str: ...

    def text(self) -> str: ...


LineComment.Label.CONTENT = _ProtocolLabelMember("LineComment.Label.CONTENT")
LineComment.Label.NEWLINE = _ProtocolLabelMember("LineComment.Label.NEWLINE")
LineComment.Label.PREFIX = _ProtocolLabelMember("LineComment.Label.PREFIX")


class Span(typing.Protocol):
    kind: typing.Literal[fltk.fegen.pyrt.terminalsrc.SpanKind.SPAN] = fltk.fegen.pyrt.terminalsrc.SpanKind.SPAN


class CstModule(typing.Protocol):
    @property
    def AstSpec(self) -> type[AstSpec]: ...

    @property
    def Statement(self) -> type[Statement]: ...

    @property
    def OptionStmt(self) -> type[OptionStmt]: ...

    @property
    def OptionValue(self) -> type[OptionValue]: ...

    @property
    def RuleConfig(self) -> type[RuleConfig]: ...

    @property
    def RuleStatement(self) -> type[RuleStatement]: ...

    @property
    def TypeStmt(self) -> type[TypeStmt]: ...

    @property
    def TypeSpec(self) -> type[TypeSpec]: ...

    @property
    def CustomSpec(self) -> type[CustomSpec]: ...

    @property
    def CustomArg(self) -> type[CustomArg]: ...

    @property
    def BoolStmt(self) -> type[BoolStmt]: ...

    @property
    def TransparentStmt(self) -> type[TransparentStmt]: ...

    @property
    def TextFromStmt(self) -> type[TextFromStmt]: ...

    @property
    def KeyStmt(self) -> type[KeyStmt]: ...

    @property
    def FoldStmt(self) -> type[FoldStmt]: ...

    @property
    def FoldDir(self) -> type[FoldDir]: ...

    @property
    def FlattenStmt(self) -> type[FlattenStmt]: ...

    @property
    def CustomStmt(self) -> type[CustomStmt]: ...

    @property
    def NameStmt(self) -> type[NameStmt]: ...

    @property
    def VariantStmt(self) -> type[VariantStmt]: ...

    @property
    def FieldStmt(self) -> type[FieldStmt]: ...

    @property
    def FieldStatement(self) -> type[FieldStatement]: ...

    @property
    def SumStmt(self) -> type[SumStmt]: ...

    @property
    def ProductStmt(self) -> type[ProductStmt]: ...

    @property
    def Identifier(self) -> type[Identifier]: ...

    @property
    def String(self) -> type[String]: ...

    @property
    def Trivia(self) -> type[Trivia]: ...

    @property
    def LineComment(self) -> type[LineComment]: ...
