"""Formatter normalization applied to every generated Python module.

Generation runs its output through ruff before returning, so a generated file is never a
format-check failure and no caller needs a separate normalization step.  Both halves of the
pipeline are pinned rather than discovered:

- the ruff binary comes from the ``ruff`` wheel the generator depends on, and
- the config is ``gencode-ruff.toml`` beside the ``fltk`` package, passed explicitly with
  ``--config`` so ruff never reads a ``pyproject.toml`` out of the working directory.

The second point is what keeps generated output a function of (grammar, generator, pinned
ruff, pinned config) alone: a build action's working directory may hold an unrelated
project's ruff settings, and discovery would silently reshape the emitted code.
"""

from __future__ import annotations

import os
import subprocess
from collections.abc import Sequence
from pathlib import Path

import fltk

#: Overrides the discovered ruff executable.  Escape hatch for an environment where the
#: wheel layout below does not apply.
RUFF_ENV_VAR = "FLTK_GENCODE_RUFF"

#: Overrides the discovered gencode-ruff.toml path.
CONFIG_ENV_VAR = "FLTK_GENCODE_RUFF_CONFIG"

CONFIG_BASENAME = "gencode-ruff.toml"


class NormalizationError(RuntimeError):
    """Generated source could not be normalized."""


def _package_parent() -> Path:
    """The directory holding the ``fltk`` package.

    In a source checkout that is the repo root; under Bazel it is the runfiles root of
    whichever module ships fltk.  ``gencode-ruff.toml`` sits directly in it either way.
    The path is deliberately not resolved: runfiles entries are symlinks back into the
    source tree, and following them would leave the runfiles tree.
    """
    package_init = fltk.__file__
    if package_init is None:  # pragma: no cover - namespace package, not a supported layout
        msg = "the fltk package has no __file__; cannot locate " + CONFIG_BASENAME
        raise NormalizationError(msg)
    return Path(package_init).absolute().parent.parent


def find_ruff() -> Path:
    """Return the ruff executable to normalize with.

    Only the ruff wheel the generator depends on is ever used: the binary is located
    relative to the imported ``ruff`` package, which is the same "``bin/ruff`` inside the
    extracted wheel" fact ``bzl/py_lint.bzl`` resolves at analysis time for the lint
    targets.  ``ruff.find_ruff_bin()`` is tried as well because it is what finds the binary
    in a virtualenv, where the script directory is not beside the package.

    A ruff found on ``$PATH`` is deliberately not a candidate: generated bytes are a
    function of (grammar, generator, pinned ruff, pinned config), and an ambient ruff of a
    different version silently reshapes them.  Set ``FLTK_GENCODE_RUFF`` to point at a
    specific binary when the wheel layout does not apply.
    """
    override = os.environ.get(RUFF_ENV_VAR)
    if override:
        return Path(override)

    candidates: list[Path] = []
    try:
        import ruff as ruff_pkg  # noqa: PLC0415
    except ImportError:
        ruff_pkg = None  # type: ignore[assignment]

    if ruff_pkg is not None and ruff_pkg.__file__ is not None:
        package_dir = Path(ruff_pkg.__file__).absolute().parent
        candidates.append(package_dir.parent.parent / "bin" / "ruff")
        try:
            candidates.append(Path(ruff_pkg.find_ruff_bin()))
        except FileNotFoundError:
            pass

    for candidate in candidates:
        if candidate.is_file():
            return candidate

    searched = "\n".join(f"  - {candidate}" for candidate in candidates) or "  (nothing to try)"
    msg = f"no ruff executable found; generated code cannot be normalized. Searched:\n{searched}"
    raise NormalizationError(msg)


def gencode_ruff_config() -> Path:
    """Return the pinned ruff config every normalization invocation is passed."""
    override = os.environ.get(CONFIG_ENV_VAR)
    config = Path(override) if override else _package_parent() / CONFIG_BASENAME
    if not config.is_file():
        msg = f"{CONFIG_BASENAME} not found at {config}; generated code cannot be normalized."
        raise NormalizationError(msg)
    return config


def _fix(ruff: Path, config: Path, files: Sequence[str]) -> None:
    """Run ``ruff check --fix``, discarding its findings report.

    Exit 1 means residual unfixable findings — a generated signature over the line length, an
    unused import ``unfixable`` protects — which are expected and are not this pipeline's
    business.  ``//:ruff_check`` is the gate for hand-written code; generated code is out of
    its scope.  Exit 2 is a different thing entirely: ruff itself failed (unreadable config,
    rejected flag, internal error), which degrades normalization to a silent no-op and
    surfaces much later as an unexplained byte difference in the seed or parity gate.
    """
    result = subprocess.run(  # noqa: S603
        [str(ruff), "check", "--config", str(config), "--fix", "--output-format", "concise", *files],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode > 1:
        msg = f"ruff check --fix failed on generated source (exit {result.returncode}):\n{result.stderr}"
        raise NormalizationError(msg)


def _format(ruff: Path, config: Path, files: Sequence[str]) -> None:
    """Run ``ruff format``, raising on failure (a formatter error is a real defect)."""
    result = subprocess.run(  # noqa: S603
        [str(ruff), "format", "--config", str(config), "-q", *files],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        msg = f"ruff format failed on generated source (exit {result.returncode}):\n{result.stderr}"
        raise NormalizationError(msg)


def normalize(paths: Sequence[Path]) -> None:
    """Normalize the generated files at ``paths`` in place.

    Three steps, in this order: ``check --fix`` rewrites constructs the formatter then has to
    wrap (``typing.Union[X, Y]`` becomes ``X | Y``), ``format`` applies the canonical layout,
    and a second ``check --fix`` cleans up what formatting exposed.  Reordering them changes
    the output.
    """
    files = [str(path) for path in paths]
    if not files:
        return
    ruff = find_ruff()
    config = gencode_ruff_config()
    _fix(ruff, config, files)
    _format(ruff, config, files)
    _fix(ruff, config, files)
