"""CLI for FLTK parser generation.

Generates parsers from FLTK grammar files with options for trivia handling.
"""

import re
from pathlib import Path
from typing import Annotated

import typer

from fltk.fegen import (
    fltk2gsm,
    gencode_format,
    gsm,
    gsm2lib_rs,
    gsm2parser,
    gsm2parser_rs,
    gsm2tree,
    gsm2tree_rs,
    naming,
    pybackend,
)
from fltk.fegen.ast_config import Backend, ResolvedAstConfig
from fltk.fegen.pybackend import generate_parser, parse_grammar_file, validate_python_module
from fltk.iir.context import CompilerContext, create_default_context
from fltk.iir.py import compiler
from fltk.iir.py import reg as pyreg
from fltk.plumbing import (
    generate_ast_source,
    generate_rust_ast_source,
    generate_rust_serde_source,
    generate_unparser_source,
    parse_ast_config_file,
    parse_format_config_file,
)
from fltk.unparse import gsm2unparser_rs
from fltk.unparse.fmt_config import FormatterConfig

__all__ = [
    "CompilerContext",
    "app",
    "compiler",
    "create_default_context",
    "fltk2gsm",
    "generate_parser",
    "gsm2parser",
    "gsm2tree",
    "parse_grammar_file",
    "pyreg",
    "validate_python_module",
]

app = typer.Typer(
    name="genparser",
    help="Generate parsers from FLTK grammar files",
    add_completion=False,
)


@app.command()
def generate(
    grammar_file: Annotated[Path, typer.Argument(help="Path to the FLTK grammar file (.fltkg)")],
    base_name: Annotated[str, typer.Argument(help="Base name for output files (without extension)")],
    cst_module_name: Annotated[
        str, typer.Argument(help='Module import name for CST classes (usually "<base_name>_cst")')
    ],
    *,
    output_dir: Annotated[
        Path | None,
        typer.Option("--output-dir", "-o", help="Output directory for generated files"),
    ] = None,
    trivia_only: Annotated[
        bool,
        typer.Option("--trivia-only", help="Generate only the trivia-preserving parser"),
    ] = False,
    no_trivia_only: Annotated[
        bool,
        typer.Option("--no-trivia-only", help="Generate only the non-trivia parser"),
    ] = False,
    protocol_only: Annotated[
        bool,
        typer.Option(
            "--protocol-only",
            help=(
                "Generate only the {base_name}_cst_protocol.py module, skipping the shared CST "
                "module and both parsers. Use when only the typing-protocol surface is needed "
                "(e.g. to type a Rust-backed unparser .pyi against)."
            ),
        ),
    ] = False,
    protocol: Annotated[
        bool,
        typer.Option(
            "--protocol",
            help=(
                "Deprecated no-op: the {base_name}_cst_protocol.py typing-protocol module is now "
                "always written alongside the CST and parsers, because the CST module imports its "
                "NodeKind from it. Accepted so existing invocations keep working."
            ),
        ),
    ] = False,
    verbose: Annotated[bool, typer.Option("--verbose", "-v", help="Enable verbose output")] = False,
) -> None:
    """Generate parsers from an FLTK grammar file.

    By default, this command generates a shared CST module, its typing-protocol companion, and
    both parser variants:
    - Shared CST classes that work with both parsers
    - The CST protocol module, which the CST module imports its NodeKind from
    - Parser without trivia preservation (faster, for compilers/interpreters)
    - Parser with trivia preservation (for formatters/syntax highlighters)

    Use --trivia-only or --no-trivia-only to generate just one parser variant.
    Use --protocol-only to generate just the CST protocol module (no CST, no parsers).

    Files generated by default:
    - {base_name}_cst.py (shared CST classes)
    - {base_name}_cst_protocol.py (typing protocol; required by the CST module at import time)
    - {base_name}_parser.py (no trivia)
    - {base_name}_trivia_parser.py (with trivia)

    CST_MODULE names the import path the {base_name}_cst.py file will have once it is importable.
    The CST module imports NodeKind from CST_MODULE + '_protocol', so the {base_name}_cst_protocol.py
    file must end up importable under that name too. Leaving the files where they are written
    requires CST_MODULE's last component to be '{base_name}_cst'; anything else means the files are
    being relocated (e.g. mylang_cst.py -> mylang/cst.py for CST_MODULE 'mylang.cst', which then
    also needs mylang_cst_protocol.py -> mylang/cst_protocol.py). A mismatch is only warned about,
    because that relocation is a supported layout.

    Examples:
        genparser generate grammar.fltkg mylang mylang.mylang_cst
        genparser generate grammar.fltkg mylang mylang.mylang_cst --trivia-only
        genparser generate grammar.fltkg mylang mylang.mylang_cst --protocol-only
        genparser generate grammar.fltkg mylang mylang.mylang_cst -o output/ --verbose
    """
    pybackend.generate(
        grammar_file,
        base_name,
        cst_module_name,
        output_dir=output_dir,
        trivia_only=trivia_only,
        no_trivia_only=no_trivia_only,
        protocol_only=protocol_only,
        protocol=protocol,
        verbose=verbose,
    )


@app.command(name="gen-py-unparser")
def gen_py_unparser(
    grammar_file: Annotated[Path, typer.Argument(help="Path to the FLTK grammar file (.fltkg)")],
    base_name: Annotated[str, typer.Argument(help="Base name for the output file (writes {base_name}_unparser.py)")],
    cst_module_name: Annotated[
        str, typer.Argument(help='Module import name for CST classes (usually "<base_name>_cst")')
    ],
    *,
    format_config: Annotated[
        Path | None,
        typer.Option(
            "--format-config",
            help=(
                "Path to a .fltkfmt formatter-config file. Its spacing/anchor/disposition "
                "decisions are baked into the generated unparser at generation time. When "
                "omitted, the default FormatterConfig (no extra spacing) is used."
            ),
        ),
    ] = None,
    output_dir: Annotated[
        Path | None,
        typer.Option("--output-dir", "-o", help="Output directory for the generated module"),
    ] = None,
    verbose: Annotated[bool, typer.Option("--verbose", "-v", help="Enable verbose output")] = False,
) -> None:
    """Emit the Python unparser module ({base_name}_unparser.py) from a grammar.

    The generated module holds one Unparser class whose unparse_{rule} methods walk the CST
    named by CST_MODULE and render it back to source text. Generate that CST module first
    with the `generate` command, and generate it with trivia preservation: the unparser reads
    the trivia the trivia-preserving parser captures.

    The emitted source is formatter-normalized, like every other generated Python module.

    Examples:
        genparser gen-py-unparser grammar.fltkg mylang mylang_cst -o mylang/
        genparser gen-py-unparser grammar.fltkg mylang mylang_cst \\
            --format-config grammar.fltkfmt -o mylang/
    """
    validate_python_module(cst_module_name, "CST_MODULE")

    if output_dir is None:
        output_dir = Path(".")

    if verbose:
        typer.echo(f"Parsing grammar file: {grammar_file}")

    grammar = _parse_grammar_raw(grammar_file)

    formatter_config = None
    if format_config is not None:
        if verbose:
            typer.echo(f"Parsing format config file: {format_config}")
        try:
            # OSError (not just FileNotFoundError) so a --format-config path that exists but is
            # unreadable / is a directory surfaces the clean CLI error, not a raw traceback.
            formatter_config = parse_format_config_file(format_config)
        except (ValueError, OSError) as e:
            typer.echo(f"Error: {e}", err=True)
            raise typer.Exit(1) from e

    if verbose:
        typer.echo("Generating unparser module...")

    # Generate before creating the output directory or opening the file so a generation error
    # leaves no artifacts behind.
    try:
        src = generate_unparser_source(grammar, cst_module_name, formatter_config)
    except (ValueError, RuntimeError) as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(1) from e

    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / f"{base_name}_unparser.py"
    _write_output_file(output_file, src, "unparser module")
    gencode_format.normalize([output_file])

    if verbose:
        typer.echo("✓ Unparser generation completed successfully")
        typer.echo(f"Unparser module: {output_file}")


@app.command(name="gen-ast")
def gen_ast(
    grammar_file: Annotated[Path, typer.Argument(help="Path to the FLTK grammar file (.fltkg)")],
    base_name: Annotated[str, typer.Argument(help="Base name for the output file (writes {base_name}_ast.py)")],
    cst_module_name: Annotated[
        str, typer.Argument(help='Module import name for CST classes (usually "<base_name>_cst")')
    ],
    *,
    protocol_module: Annotated[
        str | None,
        typer.Option(
            "--protocol-module",
            help=(
                "Import path of the generated CST protocol module for this grammar "
                "(e.g. 'mylang.mylang_cst_protocol'). The AST module's from_cst converters are "
                "annotated and keyed against it, so any conforming backend's CST — Python or "
                "Rust — converts through them. Defaults to CST_MODULE with '_protocol' appended, "
                "which is the layout `generate --protocol` produces."
            ),
        ),
    ] = None,
    ast_config: Annotated[
        Path | None,
        typer.Option(
            "--ast-config",
            help=(
                "Path to a .fltkast sidecar shaping the generated AST (type coercions, "
                "transparency, naming and shape overrides, custom rules). Validated against "
                "the grammar at generation time. When omitted, the AST is pure Tier 0 — "
                "derived from the grammar alone."
            ),
        ),
    ] = None,
    parser_module: Annotated[
        str | None,
        typer.Option(
            "--parser-module",
            help=(
                "Import path of the generated parser module for this grammar "
                "(e.g. 'mylang.mylang_parser'). When given, the AST module gains a "
                "parse(source, filename=None) convenience returning the goal rule's AST. "
                "When omitted, no parse() is emitted."
            ),
        ),
    ] = None,
    unparser_module: Annotated[
        str | None,
        typer.Option(
            "--unparser-module",
            help=(
                "Import path of the generated unparser module for this grammar "
                "(e.g. 'mylang.mylang_unparser'). When given, the AST module gains an "
                "unparse(value, renderer_config=None) convenience rendering an AST to source "
                "text. When omitted, no unparse() is emitted."
            ),
        ),
    ] = None,
    goal: Annotated[
        str | None,
        typer.Option(
            "--goal",
            help=(
                "Rule the parse()/unparse() conveniences target. Defaults to the grammar's "
                "first rule, matching the Python parse_text default."
            ),
        ),
    ] = None,
    output_dir: Annotated[
        Path | None,
        typer.Option("--output-dir", "-o", help="Output directory for the generated module"),
    ] = None,
    verbose: Annotated[bool, typer.Option("--verbose", "-v", help="Enable verbose output")] = False,
) -> None:
    """Emit Python AST node classes and CST converters ({base_name}_ast.py) from a grammar.

    The generated module holds one dataclass per rule (plus payload classes, union aliases
    and value enums as the rule shapes require) and the converters in both directions:
    from_cst/to_cst members on every class and module-level {rule}_from_cst / {rule}_to_cst
    functions. It imports the CST module named by CST_MODULE and the CST protocol module named
    by --protocol-module, so generate both first with the `generate --protocol` command.

    Naming a parser module adds parse(); naming an unparser module adds unparse(), closing
    the text -> AST -> text loop. A .fltkast sidecar passed with --ast-config shapes the
    result beyond the grammar-derived default.

    Examples:
        genparser gen-ast grammar.fltkg mylang mylang.mylang_cst -o mylang/
        genparser gen-ast grammar.fltkg mylang mylang.mylang_cst \\
            --ast-config grammar.fltkast \\
            --parser-module mylang.mylang_parser \\
            --unparser-module mylang.mylang_unparser --goal config -o mylang/
    """
    validate_python_module(cst_module_name, "CST_MODULE")
    protocol_module = protocol_module if protocol_module is not None else naming.protocol_module_name(cst_module_name)
    validate_python_module(protocol_module, "--protocol-module")
    if parser_module is not None:
        validate_python_module(parser_module, "--parser-module")
    if unparser_module is not None:
        validate_python_module(unparser_module, "--unparser-module")

    if output_dir is None:
        output_dir = Path(".")

    if verbose:
        typer.echo(f"Parsing grammar file: {grammar_file}")

    grammar = parse_grammar_file(grammar_file)

    resolved_config = None
    if ast_config is not None:
        if verbose:
            typer.echo(f"Parsing AST config file: {ast_config}")
        try:
            # Only the Python backend is generated here, so a `custom(...)` list may omit its
            # Rust entries.  AstConfigError is a ValueError; OSError covers an unreadable path.
            resolved_config = parse_ast_config_file(ast_config, grammar, {Backend.PYTHON})
        except (ValueError, OSError) as e:
            typer.echo(f"Error: {e}", err=True)
            raise typer.Exit(1) from e

    if verbose:
        typer.echo("Generating AST module...")

    # Generate before creating the output directory or opening the file so a model error leaves
    # no artifacts behind.  AstModelError is a ValueError, as is the unknown-goal error.
    try:
        src = generate_ast_source(
            grammar,
            cst_module_name,
            parser_module,
            unparser_module,
            goal,
            ast_config=resolved_config,
            protocol_module_name=protocol_module,
        )
    except ValueError as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(1) from e

    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / f"{base_name}_ast.py"
    _write_output_file(output_file, src, "AST module")
    gencode_format.normalize([output_file])

    if verbose:
        typer.echo("✓ AST generation completed successfully")
        typer.echo(f"AST module: {output_file}")


def _parse_grammar_raw(grammar_file: Path) -> gsm.Grammar:
    """Parse a grammar file and return the raw GSM without trivia processing.

    Unlike parse_grammar_file, this does NOT apply add_trivia_rule_to_grammar or
    classify_trivia_rules.  This is the correct input for RustCstGenerator, which
    applies trivia processing internally.
    """
    return pybackend.read_and_parse_grammar(grammar_file)


def _write_output_file(output_file: Path, src: str, artifact_label: str = "output file") -> None:
    """Write generated source to ``output_file``, exiting with a CLI error on failure.

    Shared by the Rust-backend subcommands (gen-rust-cst / gen-rust-parser / gen-rust-unparser /
    gen-rust-lib), which all write generated artifacts with the same error contract (so the
    message/exit-code stay a single maintenance point).  ``artifact_label`` names the artifact in
    the error message; it is overridden to ``".pyi stub"`` for the optional stub writes so the
    ``.rs`` and ``.pyi`` writes share this one helper instead of duplicating the try/except.
    """
    try:
        output_file.write_text(src)
    except Exception as e:
        typer.echo(f"Error: Failed to write {artifact_label} '{output_file}': {e}", err=True)
        raise typer.Exit(1) from e


class _ArtifactWriter:
    """Where the Rust-backend emitters put their generated text.

    Each ``_emit_rust_*`` helper generates every artifact it owns before writing any of them, so
    a generation error inside one artifact leaves nothing behind.  ``gen-rust-all`` runs several
    of them in sequence and needs the same property *across* artifacts: a failure while
    generating de.rs must not leave a freshly written cst.rs, parser.rs and unparser.rs behind
    for a build that would then compile a half-updated tree.

    In deferred mode nothing reaches disk until :meth:`flush`, which the merged subcommand calls
    once every artifact has been generated.  The single-purpose subcommands use the immediate
    mode, which is the plain write they always did.  Flush itself is a sequence of writes, so an
    I/O failure part-way through it can still leave a partial tree — the property restored here
    is that a *generation* failure cannot.
    """

    def __init__(self, *, deferred: bool = False) -> None:
        self._deferred = deferred
        self._pending: list[tuple[Path, str, str, bool]] = []

    def write(
        self, output_file: Path, src: str, artifact_label: str = "output file", *, normalize: bool = False
    ) -> None:
        """Write (or, deferred, record) one artifact.

        ``normalize`` runs the generated-Python formatter over the file once it is on disk; it
        is set for the ``.py`` artifacts, whose contract is byte-identity with the Python
        backend's output.
        """
        if self._deferred:
            self._pending.append((output_file, src, artifact_label, normalize))
            return
        self._put(output_file, src, artifact_label, normalize=normalize)

    def flush(self) -> None:
        """Write everything recorded so far, in the order it was recorded."""
        pending, self._pending = self._pending, []
        for output_file, src, artifact_label, normalize in pending:
            self._put(output_file, src, artifact_label, normalize=normalize)

    def _put(self, output_file: Path, src: str, artifact_label: str, *, normalize: bool) -> None:
        _write_output_file(output_file, src, artifact_label)
        if normalize:
            gencode_format.normalize([output_file])


@app.command(name="gen-rust-cst")
def gen_rust_cst(
    grammar_file: Annotated[Path, typer.Argument(help="Path to the FLTK grammar file (.fltkg)")],
    output_file: Annotated[Path, typer.Argument(help="Path to write the .rs source")],
    *,
    protocol_module: Annotated[
        str | None,
        typer.Option(
            "--protocol-module",
            help=(
                "Import path of the committed protocol module for this grammar "
                "(e.g. 'fltk.fegen.fltk_cst_protocol'). When provided, also emits a .pyi stub "
                "so pyright can verify the PyO3 surface satisfies CstModule. "
                "When omitted, no .pyi is emitted (backward compatible)."
            ),
        ),
    ] = None,
    pyi_output: Annotated[
        Path | None,
        typer.Option(
            "--pyi-output",
            help=(
                "Path to write the .pyi stub. The canonical location is "
                "<name>/cst.pyi inside a stub-package directory (alongside "
                "<name>/__init__.pyi). Defaults to output_file with .pyi suffix "
                "when --protocol-module is given. Override when the .rs stem differs "
                "from the compiled module's import name — pyright resolves stubs by "
                "import name, not .rs file name. "
                "Example: 'src/cst_fegen.rs' backs 'fltk._native.fegen_cst', "
                "so --pyi-output fltk/_native/fegen_cst.pyi is required."
            ),
        ),
    ] = None,
    protocol_output: Annotated[
        Path | None,
        typer.Option(
            "--protocol-output",
            help=(
                "Path to write the generated protocol .py module. Requires --protocol-module "
                "(which supplies the protocol's dotted import path that the .pyi imports). When "
                "set, the protocol module is written here AND the .pyi is emitted too — the protocol "
                ".py and its .pyi are a matched pair. The output is byte-identical to the Python "
                "`generate --protocol` protocol module for the same grammar. Off by default."
            ),
        ),
    ] = None,
    init_pyi_output: Annotated[
        Path | None,
        typer.Option(
            "--init-pyi-output",
            help=(
                "Path to write the stub-package __init__.pyi marker. Requires --extension-name "
                "and --submodules. The marker is comment-only and makes the <name>/ directory a "
                "recognized stub package for pyright (its top-level module exports nothing directly, "
                "only the listed submodules). Independent of --protocol-module."
            ),
        ),
    ] = None,
    extension_name: Annotated[
        str | None,
        typer.Option(
            "--extension-name",
            help=(
                "The compiled extension's importable name (e.g. 'fegen_rust_cst'), interpolated "
                "into the --init-pyi-output marker. Required when --init-pyi-output is given."
            ),
        ),
    ] = None,
    submodules: Annotated[
        str | None,
        typer.Option(
            "--submodules",
            help=(
                "Comma-separated names of the submodules the extension registers (e.g. "
                "'cst,parser'), interpolated into the --init-pyi-output marker. Required when "
                "--init-pyi-output is given; each entry must be a valid identifier."
            ),
        ),
    ] = None,
) -> None:
    """Emit Rust CST source (.rs) from a grammar file, and optionally a .pyi stub.

    Generates a standalone PyO3 Rust extension source file from a grammar.
    The user compiles and installs it with their own build tool (e.g. maturin).
    The generated .rs file is independent of FLTK's crate at link time; it
    depends on fltk._native only at runtime for the UnknownSpan sentinel.

    The generated cst.rs wires into the cst submodule of the compiled extension,
    e.g. <module>.cst. Import Span and SourceText from fltk._native, not from
    the generated module.

    Wire the generated cst.rs and parser.rs into your lib.rs like this:

        use fltk_cst_core::register_submodule;
        #[pymodule]
        fn my_grammar(m: &Bound<'_, PyModule>) -> PyResult<()> {
            register_submodule(m, "cst", cst::register_classes)?;
            register_submodule(m, "parser", parser::register_classes)?;
            Ok(())
        }

    When --protocol-module is given, also emits a .pyi stub derived from the same
    GSM so pyright can verify the compiled extension satisfies CstModule without a
    cast. The stub goes in a stub-package directory <name>/ as <name>/cst.pyi;
    use --pyi-output to control the exact path.

    When --protocol-output is given (which requires --protocol-module), the Rust
    generator also writes the protocol .py module itself, byte-identical to the
    Python `generate --protocol` output, alongside the .pyi.

    When --init-pyi-output is given (which requires --extension-name and
    --submodules), also writes a comment-only stub-package __init__.pyi marker so
    the <name>/ directory is a recognized stub package for pyright. The marker is
    independent of --protocol-module.

    Examples:
        genparser gen-rust-cst grammar.fltkg output/cst.rs
        genparser gen-rust-cst grammar.fltkg src/cst_fegen.rs \\
            --protocol-module fltk.fegen.fltk_cst_protocol \\
            --pyi-output fltk/_native/fegen_cst.pyi
        genparser gen-rust-cst grammar.fltkg out/cst.rs \\
            --protocol-module mylang.cst_protocol \\
            --protocol-output mylang/cst_protocol.py
        genparser gen-rust-cst grammar.fltkg out/cst/cst.rs \\
            --init-pyi-output out/cst/__init__.pyi \\
            --extension-name mylang_cst --submodules cst,parser
    """
    _require_together(pyi_output, "--pyi-output", protocol_module, "--protocol-module")
    _require_together(protocol_output, "--protocol-output", protocol_module, "--protocol-module")
    if protocol_module is not None:
        _validate_protocol_module(protocol_module)
    # Render the grammar-independent stub-package marker up front so a malformed marker never
    # reaches disk (validation precedes any output write, and even the grammar parse).
    init_pyi_text = _render_init_pyi(init_pyi_output, extension_name, submodules)

    grammar = _parse_grammar_raw(grammar_file)
    _emit_rust_cst(
        grammar,
        grammar_file,
        output_file,
        protocol_module=protocol_module,
        pyi_output=pyi_output,
        protocol_output=protocol_output,
        init_pyi_output=init_pyi_output,
        init_pyi_text=init_pyi_text,
        writer=_ArtifactWriter(),
    )


def _require_together(dependent: object | None, option: str, required: object | None, required_option: str) -> None:
    """Exit with a CLI error when ``option`` was given without ``required_option``.

    The one spelling of "these two flags come as a pair" for every Rust-backend subcommand: a
    flag that shapes an artifact the caller did not request, or names a stub whose protocol
    module is missing, would otherwise be silently ignored.
    """
    if dependent is not None and required is None:
        typer.echo(f"Error: {option} requires {required_option}", err=True)
        raise typer.Exit(1)


def _parse_ast_config_or_exit(ast_config: Path, grammar: gsm.Grammar, backend: Backend) -> ResolvedAstConfig:
    """Parse a .fltkast sidecar against ``grammar``, exiting with a CLI error on failure.

    Only one backend's generated code is in play per call, so a ``custom(...)`` list may omit the
    other backend's entries.  AstConfigError is a ValueError; OSError covers an unreadable path.
    """
    try:
        return parse_ast_config_file(ast_config, grammar, {backend})
    except (ValueError, OSError) as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(1) from e


def _emit_rust_cst(
    grammar: gsm.Grammar,
    grammar_file: Path,
    output_file: Path,
    *,
    protocol_module: str | None,
    pyi_output: Path | None,
    protocol_output: Path | None,
    init_pyi_output: Path | None,
    init_pyi_text: str | None,
    writer: _ArtifactWriter,
) -> None:
    """Write cst.rs and its optional .pyi / protocol .py / stub-package marker.

    ``grammar`` must be the raw GSM (before trivia processing); callers must have already
    validated their options and rendered ``init_pyi_text``.  ``writer`` decides when the text
    reaches disk.
    """
    try:
        gen = gsm2tree_rs.RustCstGenerator(grammar, source_name=str(grammar_file))
    except ValueError as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(1) from e

    # Generate all artifact text before opening any file so a generation error doesn't leave
    # partial files. Write order: .rs, then the protocol .py, then the .pyi.
    pyi_text: str | None = None
    protocol_text: str | None = None
    try:
        if protocol_module is not None:
            pyi_text = gen.generate_pyi(protocol_module)
        if protocol_output is not None:
            protocol_text = gen.generate_protocol()
        src = gen.generate()
    except (ValueError, RuntimeError) as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(1) from e
    writer.write(output_file, src)

    if protocol_output is not None:
        # generate_protocol() is the only assignment to protocol_text and any error in it exits
        # above, so protocol_text is non-None whenever protocol_output is set.  Assert the invariant
        # (mirroring the init_pyi_text writer below) rather than a double-condition guard that would
        # silently skip the write on a control-flow defect.
        assert protocol_text is not None
        # The Rust backend's protocol module must stay byte-identical to the Python
        # backend's for the same grammar — a consumer types one .pyi against whichever it
        # got.  The Python path normalizes what it writes, so this one does too.
        writer.write(protocol_output, protocol_text, "protocol module", normalize=True)

    if pyi_text is not None:
        stub_path = pyi_output if pyi_output is not None else output_file.with_suffix(".pyi")
        # Normalized like the .py the generator writes: a stub is Python source a consumer
        # type-checks and reads, and an unnormalized one cannot be byte-compared against
        # anything the same pinned ruff produces.
        writer.write(stub_path, pyi_text, ".pyi stub", normalize=True)

    if init_pyi_output is not None:
        # _render_init_pyi returns a non-None string whenever init_pyi_output is set (it exits
        # otherwise), so the marker is always written here; the assert documents that invariant
        # and narrows the type for the writer below.
        assert init_pyi_text is not None
        writer.write(init_pyi_output, init_pyi_text, "stub-package __init__.pyi")


# ``\Z`` rather than ``$``: ``$`` also matches before a trailing newline, which would let a
# value carrying one through into a ``use`` line.
_RUST_MOD_PATH_RE = re.compile(r"\A[A-Za-z_][A-Za-z0-9_]*(::[A-Za-z_][A-Za-z0-9_]*)*\Z")


def _validate_rust_mod_path(mod_path: str, option: str) -> None:
    """Exit with a CLI error when ``mod_path`` is not a valid Rust module path.

    ``option`` names the CLI option in the message.  Every caller interpolates the value verbatim
    into a generated ``use``/``mod`` line, so a malformed value would otherwise reach disk and fail
    only when rustc reads it.
    """
    if not _RUST_MOD_PATH_RE.match(mod_path):
        typer.echo(f"Error: {option} {mod_path!r} is not a valid Rust module path", err=True)
        raise typer.Exit(1)


def _validate_cst_mod_path(cst_mod_path: str) -> None:
    """Exit with a CLI error when ``--cst-mod-path`` is not a valid Rust module path.

    Shared by gen-rust-parser / gen-rust-unparser / gen-rust-ast, which all accept
    ``--cst-mod-path``.
    """
    _validate_rust_mod_path(cst_mod_path, "--cst-mod-path")


def _validate_protocol_module(protocol_module: str) -> None:
    """Exit with a CLI error when ``--protocol-module`` is not a valid Python dotted module path.

    Shared by gen-rust-cst / gen-rust-unparser, which both interpolate the value into the
    generated ``.pyi`` stub.
    """
    validate_python_module(protocol_module, "--protocol-module")


def _render_init_pyi(
    init_pyi_output: Path | None,
    extension_name: str | None,
    submodules: str | None,
) -> str | None:
    """Validate the stub-package marker options and render the ``__init__.pyi`` text.

    Shared by gen-rust-cst / gen-rust-unparser, which can both emit the grammar-independent
    stub-package marker alongside the ``.pyi`` they already write.  Returns
    ``None`` when ``--init-pyi-output`` is not given (no marker requested).  Otherwise exits via
    typer.Exit on a misconfiguration: ``--init-pyi-output`` requires both ``--extension-name``
    and ``--submodules``, and the extension name plus each comma-separated submodule entry must
    be a valid identifier (enforced by ``render_stub_package_init``).  The text is rendered
    before any output file is opened so a malformed marker never reaches disk.
    """
    if init_pyi_output is None:
        return None
    if extension_name is None or submodules is None:
        typer.echo("Error: --init-pyi-output requires --extension-name and --submodules", err=True)
        raise typer.Exit(1)
    submodule_names = [name.strip() for name in submodules.split(",")]
    try:
        return gsm2lib_rs.render_stub_package_init(extension_name, submodule_names)
    except ValueError as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(1) from e


@app.command(name="gen-rust-parser")
def gen_rust_parser(
    grammar_file: Annotated[Path, typer.Argument(help="Path to the FLTK grammar file (.fltkg)")],
    output_file: Annotated[Path, typer.Argument(help="Path to write the .rs source")],
    cst_mod_path: Annotated[
        str,
        typer.Option(
            "--cst-mod-path",
            help="Rust module path to the generated CST module (e.g. 'super::cst')",
        ),
    ] = "super::cst",
) -> None:
    """Emit Rust parser source (.rs) from a grammar file."""
    _validate_cst_mod_path(cst_mod_path)

    grammar = _parse_grammar_raw(grammar_file)
    _emit_rust_parser(grammar, grammar_file, output_file, cst_mod_path=cst_mod_path, writer=_ArtifactWriter())


def _emit_rust_parser(
    grammar: gsm.Grammar,
    grammar_file: Path,
    output_file: Path,
    *,
    cst_mod_path: str,
    writer: _ArtifactWriter,
) -> None:
    """Write parser.rs from the raw GSM."""
    try:
        gen = gsm2parser_rs.RustParserGenerator(grammar, cst_mod_path=cst_mod_path, source_name=str(grammar_file))
        src = gen.generate()
    except (ValueError, RuntimeError, NotImplementedError) as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(1) from e

    writer.write(output_file, src)


@app.command(name="gen-rust-unparser")
def gen_rust_unparser(
    grammar_file: Annotated[Path, typer.Argument(help="Path to the FLTK grammar file (.fltkg)")],
    output_file: Annotated[Path, typer.Argument(help="Path to write the .rs source")],
    *,
    cst_mod_path: Annotated[
        str,
        typer.Option(
            "--cst-mod-path",
            help="Rust module path to the generated CST module (e.g. 'super::cst')",
        ),
    ] = "super::cst",
    format_config: Annotated[
        Path | None,
        typer.Option(
            "--format-config",
            help=(
                "Path to a .fltkfmt formatter-config file.  Its spacing/anchor/disposition "
                "decisions are baked into the generated unparser at generation time.  When "
                "omitted, the default FormatterConfig (no extra spacing) is used."
            ),
        ),
    ] = None,
    protocol_module: Annotated[
        str | None,
        typer.Option(
            "--protocol-module",
            help=(
                "Import path of the committed CST protocol module for this grammar "
                "(e.g. 'mylang.cst_protocol'). When provided, also emits a .pyi stub "
                "describing the Unparser/Doc Python surface so pyright can type-check "
                "downstream calls; each unparse_{rule} method's node parameter is typed "
                "against this module. When omitted, no .pyi is emitted (backward compatible)."
            ),
        ),
    ] = None,
    pyi_output: Annotated[
        Path | None,
        typer.Option(
            "--pyi-output",
            help=(
                "Path to write the .pyi stub. Defaults to output_file with .pyi suffix "
                "when --protocol-module is given. Override when the .rs stem differs from "
                "the compiled module's import name (pyright resolves stubs by import name, "
                "not .rs file name)."
            ),
        ),
    ] = None,
    init_pyi_output: Annotated[
        Path | None,
        typer.Option(
            "--init-pyi-output",
            help=(
                "Path to write the stub-package __init__.pyi marker. Requires --extension-name "
                "and --submodules. The marker is comment-only and makes the <name>/ directory a "
                "recognized stub package for pyright (its top-level module exports nothing directly, "
                "only the listed submodules). Independent of --protocol-module."
            ),
        ),
    ] = None,
    extension_name: Annotated[
        str | None,
        typer.Option(
            "--extension-name",
            help=(
                "The compiled extension's importable name (e.g. 'rust_parser_fixture'), interpolated "
                "into the --init-pyi-output marker. Required when --init-pyi-output is given."
            ),
        ),
    ] = None,
    submodules: Annotated[
        str | None,
        typer.Option(
            "--submodules",
            help=(
                "Comma-separated names of the submodules the extension registers (e.g. "
                "'cst,parser,unparser'), interpolated into the --init-pyi-output marker. Required "
                "when --init-pyi-output is given; each entry must be a valid identifier."
            ),
        ),
    ] = None,
) -> None:
    """Emit Rust unparser source (.rs) from a grammar file, and optionally a .pyi stub.

    Mirrors gen-rust-parser: parses the grammar, optionally parses a .fltkfmt
    format-config file into a FormatterConfig, and writes the generated unparser
    .rs.  The generated pure-Rust layer links against the fltk-unparser-core
    runtime crate; the optional PyO3 wrapper (gated behind the `python` feature)
    accepts only the Rust CST handles, so a Python caller must pair it with the
    Rust parser backend.

    When --protocol-module is given, also emits a .pyi stub describing the
    Unparser/Doc Python surface so downstream code is type-checked;
    use --pyi-output to control the exact path.

    When --init-pyi-output is given (which requires --extension-name and
    --submodules), also writes a comment-only stub-package __init__.pyi marker so
    the <name>/ directory is a recognized stub package for pyright. The marker is
    independent of --protocol-module, so it can be attached to this unparser
    invocation even when the package's .pyi comes from the unparser path.

    Examples:
        genparser gen-rust-unparser grammar.fltkg output/unparser.rs
        genparser gen-rust-unparser grammar.fltkg src/unparser.rs \\
            --cst-mod-path super::cst --format-config grammar.fltkfmt
        genparser gen-rust-unparser grammar.fltkg src/unparser.rs \\
            --protocol-module mylang.cst_protocol --pyi-output mylang/unparser.pyi
        genparser gen-rust-unparser grammar.fltkg out/pkg/unparser.rs \\
            --init-pyi-output out/pkg/__init__.pyi \\
            --extension-name mylang_pkg --submodules cst,parser,unparser
    """
    _validate_cst_mod_path(cst_mod_path)

    _require_together(pyi_output, "--pyi-output", protocol_module, "--protocol-module")
    if protocol_module is not None:
        _validate_protocol_module(protocol_module)
    # Render the grammar-independent stub-package marker up front so a malformed marker never
    # reaches disk (validation precedes any output write, and even the grammar parse).
    init_pyi_text = _render_init_pyi(init_pyi_output, extension_name, submodules)

    grammar = _parse_grammar_raw(grammar_file)
    formatter_config = _parse_format_config_or_exit(format_config)
    _emit_rust_unparser(
        grammar,
        grammar_file,
        output_file,
        cst_mod_path=cst_mod_path,
        formatter_config=formatter_config,
        protocol_module=protocol_module,
        pyi_output=pyi_output,
        init_pyi_output=init_pyi_output,
        init_pyi_text=init_pyi_text,
        writer=_ArtifactWriter(),
    )


def _parse_format_config_or_exit(format_config: Path | None) -> FormatterConfig | None:
    """Parse a .fltkfmt file into a FormatterConfig, or return None when none was given.

    OSError (not just FileNotFoundError) so a --format-config path that exists but is
    unreadable / is a directory surfaces the clean CLI error, not a raw traceback.
    FileNotFoundError is an OSError subclass, so the not-found message still applies.
    """
    if format_config is None:
        return None
    try:
        return parse_format_config_file(format_config)
    except (ValueError, OSError) as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(1) from e


def _emit_rust_unparser(
    grammar: gsm.Grammar,
    grammar_file: Path,
    output_file: Path,
    *,
    cst_mod_path: str,
    formatter_config: FormatterConfig | None,
    protocol_module: str | None,
    pyi_output: Path | None,
    init_pyi_output: Path | None,
    init_pyi_text: str | None,
    writer: _ArtifactWriter,
) -> None:
    """Write unparser.rs and its optional .pyi / stub-package marker from the raw GSM."""
    # Generate the .pyi text (when requested) and the .rs together, before writing either file,
    # so a generation error leaves no partial artifacts -- matching gen-rust-cst.
    pyi_text: str | None = None
    try:
        gen = gsm2unparser_rs.RustUnparserGenerator(
            grammar,
            formatter_config=formatter_config,
            cst_mod_path=cst_mod_path,
            source_name=str(grammar_file),
        )
        if protocol_module is not None:
            pyi_text = gen.generate_pyi(protocol_module)
        src = gen.generate()
    except (ValueError, RuntimeError) as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(1) from e

    writer.write(output_file, src)

    if pyi_text is not None:
        stub_path = pyi_output if pyi_output is not None else output_file.with_suffix(".pyi")
        # Normalized like the .py the generator writes: a stub is Python source a consumer
        # type-checks and reads, and an unnormalized one cannot be byte-compared against
        # anything the same pinned ruff produces.
        writer.write(stub_path, pyi_text, ".pyi stub", normalize=True)

    if init_pyi_output is not None:
        # _render_init_pyi returns a non-None string whenever init_pyi_output is set (it exits
        # otherwise), so the marker is always written here; the assert documents that invariant
        # and narrows the type for the writer below.
        assert init_pyi_text is not None
        writer.write(init_pyi_output, init_pyi_text, "stub-package __init__.pyi")


@app.command(name="gen-rust-ast")
def gen_rust_ast(
    grammar_file: Annotated[Path, typer.Argument(help="Path to the FLTK grammar file (.fltkg)")],
    output_file: Annotated[Path, typer.Argument(help="Path to write the .rs source")],
    *,
    ast_config: Annotated[
        Path | None,
        typer.Option(
            "--ast-config",
            help=(
                "Path to a .fltkast sidecar shaping the generated AST (type coercions, "
                "transparency, naming and shape overrides, custom rules). Validated against "
                "the grammar at generation time. When omitted, the AST is pure Tier 0 — "
                "derived from the grammar alone."
            ),
        ),
    ] = None,
    cst_mod_path: Annotated[
        str,
        typer.Option(
            "--cst-mod-path",
            help="Rust module path to the generated CST module (e.g. 'super::cst')",
        ),
    ] = "super::cst",
    parser_mod_path: Annotated[
        str | None,
        typer.Option(
            "--parser-mod-path",
            help=(
                "Rust module path to the generated parser module (e.g. 'super::parser'). When "
                "given, the AST module gains a parse_str(src, filename) entry point returning the "
                "goal rule's AST. When omitted, no parse_str is emitted."
            ),
        ),
    ] = None,
    unparser_mod_path: Annotated[
        str | None,
        typer.Option(
            "--unparser-mod-path",
            help=(
                "Rust module path to the generated unparser module (e.g. 'super::unparser'). When "
                "given, the AST module gains an unparse_str(value, max_width, indent_width) entry "
                "point rendering an AST back to source text. When omitted, no unparse_str is emitted."
            ),
        ),
    ] = None,
    goal: Annotated[
        str | None,
        typer.Option(
            "--goal",
            help=(
                "Rule the parse_str/unparse_str entry points target. Defaults to the grammar's "
                "first rule carrying an AST type."
            ),
        ),
    ] = None,
) -> None:
    """Emit Rust AST source (.rs) from a grammar file.

    The generated module holds one Rust type per rule (plus payload structs, sums and value
    enums as the rule shapes require) and the converters in both directions: from_cst/to_cst
    associated functions on every type. It references the generated Rust CST module named by
    --cst-mod-path, so generate that module first with gen-rust-cst.

    Naming a parser module adds parse_str; naming an unparser module adds unparse_str, closing
    the text -> AST -> text loop. A .fltkast sidecar passed with --ast-config shapes the result
    beyond the grammar-derived default.

    The emitted module's header names the `fltk-ast-core` features it needs (indexmap for keyed
    collections, uuid / decimal for those scalar builtins); enable them on the runtime crate.

    Examples:
        genparser gen-rust-ast grammar.fltkg src/ast.rs
        genparser gen-rust-ast grammar.fltkg src/ast.rs \\
            --ast-config grammar.fltkast \\
            --parser-mod-path super::parser \\
            --unparser-mod-path super::unparser --goal config
    """
    _validate_cst_mod_path(cst_mod_path)
    if parser_mod_path is not None:
        _validate_rust_mod_path(parser_mod_path, "--parser-mod-path")
    if unparser_mod_path is not None:
        _validate_rust_mod_path(unparser_mod_path, "--unparser-mod-path")

    grammar = parse_grammar_file(grammar_file)

    resolved_config = None
    if ast_config is not None:
        resolved_config = _parse_ast_config_or_exit(ast_config, grammar, Backend.RUST)

    _emit_rust_ast(
        grammar,
        grammar_file,
        output_file,
        cst_mod_path=cst_mod_path,
        parser_mod_path=parser_mod_path,
        unparser_mod_path=unparser_mod_path,
        goal=goal,
        resolved_config=resolved_config,
        writer=_ArtifactWriter(),
    )


def _emit_rust_ast(
    grammar: gsm.Grammar,
    grammar_file: Path,
    output_file: Path,
    *,
    cst_mod_path: str,
    parser_mod_path: str | None,
    unparser_mod_path: str | None,
    goal: str | None,
    resolved_config: ResolvedAstConfig | None,
    writer: _ArtifactWriter,
) -> None:
    """Write ast.rs from the trivia-processed GSM."""
    # Generate before opening the file so a model error leaves no artifact behind.  AstModelError
    # is a ValueError, as are the unknown-goal and missing-Rust-type errors.
    try:
        src = generate_rust_ast_source(
            grammar,
            cst_mod_path,
            parser_mod_path=parser_mod_path,
            unparser_mod_path=unparser_mod_path,
            goal_rule=goal,
            ast_config=resolved_config,
            source_name=str(grammar_file),
        )
    except (ValueError, RuntimeError) as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(1) from e

    writer.write(output_file, src)


@app.command(name="gen-rust-serde")
def gen_rust_serde(
    grammar_file: Annotated[Path, typer.Argument(help="Path to the FLTK grammar file (.fltkg)")],
    output_file: Annotated[Path, typer.Argument(help="Path to write the .rs source")],
    *,
    ast_config: Annotated[
        Path,
        typer.Option(
            "--ast-config",
            help=(
                "Path to the .fltkast sidecar shaping the tree (keyed regions, transparency, "
                "flattening, renames). Required: the shaping statements are what tell the serde "
                "frontend a repetition is a keyed map and what keys it, and there is no "
                "serde-specific directive — one sidecar serves the AST emitters and this one."
            ),
        ),
    ],
    cst_mod_path: Annotated[
        str,
        typer.Option(
            "--cst-mod-path",
            help="Rust module path to the generated CST module (e.g. 'super::cst')",
        ),
    ] = "super::cst",
    parser_mod_path: Annotated[
        str | None,
        typer.Option(
            "--parser-mod-path",
            help=(
                "Rust module path to the generated parser module (e.g. 'super::parser'). When "
                "given, the serde module gains a from_str(src, filename) entry point parsing and "
                "deserializing in one call. When omitted, no from_str is emitted."
            ),
        ),
    ] = None,
    goal: Annotated[
        str | None,
        typer.Option(
            "--goal",
            help=(
                "Rule the from_str entry point targets. Defaults to the grammar's first rule; "
                "every rule gets a from_<rule>_cst entry point either way."
            ),
        ),
    ] = None,
    ast_mod_path: Annotated[
        str | None,
        typer.Option(
            "--ast-mod-path",
            help=(
                "Rust module path to the generated AST module (e.g. 'super::ast'), generated "
                "from the same grammar and sidecar. When given, the serde module also emits a "
                "Deserialize impl for every generated AST type, so a target can declare one as "
                "a field type (configs: IndexMap<String, ast::Expr>). When omitted, the "
                "frontend generates no types at all."
            ),
        ),
    ] = None,
) -> None:
    """Emit the Rust serde frontend (.rs) for a grammar file.

    The generated module describes this grammar's tree to the fltk-serde-core Deserializer —
    one shape per rule, one NodeShape impl per CST node type — and emits the entry points that
    run it: from_<rule>_cst for every rule, plus from_str when a parser module is named. It
    generates no types at all: the consumer's own #[derive(Deserialize)] structs are the schema,
    and serde's unknown-field / missing-field / invalid-type errors come back positioned by CST
    span. Naming an AST module adds a Deserialize impl per generated AST type, which is how an
    expression sub-language becomes a field of a hand-written target.

    It references the generated Rust CST module named by --cst-mod-path, so generate that module
    first with gen-rust-cst. A consumer crate depending on it needs exactly two crates: `serde`
    and `fltk-serde-core`.

    Name the output `de.rs` rather than `serde.rs`: a crate-root `mod serde` makes every
    `use serde::...` in the crate ambiguous.

    Examples:
        genparser gen-rust-serde grammar.fltkg src/de.rs --ast-config grammar.fltkast
        genparser gen-rust-serde grammar.fltkg src/de.rs \\
            --ast-config grammar.fltkast \\
            --parser-mod-path super::parser --goal config \\
            --ast-mod-path super::ast
    """
    _validate_cst_mod_path(cst_mod_path)
    if parser_mod_path is not None:
        _validate_rust_mod_path(parser_mod_path, "--parser-mod-path")
    if ast_mod_path is not None:
        _validate_rust_mod_path(ast_mod_path, "--ast-mod-path")

    grammar = parse_grammar_file(grammar_file)
    resolved_config = _parse_ast_config_or_exit(ast_config, grammar, Backend.RUST)

    _emit_rust_serde(
        grammar,
        grammar_file,
        output_file,
        cst_mod_path=cst_mod_path,
        parser_mod_path=parser_mod_path,
        goal=goal,
        ast_mod_path=ast_mod_path,
        resolved_config=resolved_config,
        writer=_ArtifactWriter(),
    )


def _emit_rust_serde(
    grammar: gsm.Grammar,
    grammar_file: Path,
    output_file: Path,
    *,
    cst_mod_path: str,
    parser_mod_path: str | None,
    goal: str | None,
    ast_mod_path: str | None,
    resolved_config: ResolvedAstConfig,
    writer: _ArtifactWriter,
) -> None:
    """Write de.rs from the trivia-processed GSM."""
    # Generate before opening the file so a model, name-collision or unknown-goal error leaves no
    # artifact behind.  All of them are ValueErrors.
    try:
        src = generate_rust_serde_source(
            grammar,
            cst_mod_path,
            parser_mod_path=parser_mod_path,
            goal_rule=goal,
            ast_mod_path=ast_mod_path,
            ast_config=resolved_config,
            source_name=str(grammar_file),
        )
    except (ValueError, RuntimeError) as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(1) from e

    writer.write(output_file, src)


@app.command(name="gen-rust-all")
def gen_rust_all(
    grammar_file: Annotated[Path, typer.Argument(help="Path to the FLTK grammar file (.fltkg)")],
    *,
    cst_output: Annotated[Path, typer.Option("--cst-output", help="Path to write the CST .rs source")],
    parser_output: Annotated[
        Path | None,
        typer.Option("--parser-output", help="Path to write the parser .rs source. Omit to skip the parser."),
    ] = None,
    unparser_output: Annotated[
        Path | None,
        typer.Option("--unparser-output", help="Path to write the unparser .rs source. Omit to skip the unparser."),
    ] = None,
    ast_output: Annotated[
        Path | None,
        typer.Option("--ast-output", help="Path to write the AST .rs source. Omit to skip the AST."),
    ] = None,
    serde_output: Annotated[
        Path | None,
        typer.Option(
            "--serde-output",
            help="Path to write the serde frontend .rs source (name it de.rs). Requires --ast-config.",
        ),
    ] = None,
    cst_mod_path: Annotated[
        str,
        typer.Option("--cst-mod-path", help="Rust module path to the generated CST module (e.g. 'super::cst')"),
    ] = "super::cst",
    parser_mod_path: Annotated[
        str | None,
        typer.Option("--parser-mod-path", help="Rust module path to the generated parser module, for ast.rs / de.rs"),
    ] = None,
    unparser_mod_path: Annotated[
        str | None,
        typer.Option("--unparser-mod-path", help="Rust module path to the generated unparser module, for ast.rs"),
    ] = None,
    ast_mod_path: Annotated[
        str | None,
        typer.Option("--ast-mod-path", help="Rust module path to the generated AST module, for de.rs"),
    ] = None,
    ast_config: Annotated[
        Path | None,
        typer.Option("--ast-config", help="Path to the .fltkast sidecar shaping ast.rs / de.rs"),
    ] = None,
    format_config: Annotated[
        Path | None,
        typer.Option("--format-config", help="Path to a .fltkfmt file baked into the generated unparser"),
    ] = None,
    goal: Annotated[
        str | None,
        typer.Option("--goal", help="Rule the ast.rs / de.rs entry points target"),
    ] = None,
    protocol_module: Annotated[
        str | None,
        typer.Option("--protocol-module", help="Dotted import path of the CST protocol module, required by the stubs"),
    ] = None,
    cst_pyi_output: Annotated[
        Path | None,
        typer.Option("--cst-pyi-output", help="Path to write the CST .pyi stub. Requires --protocol-module."),
    ] = None,
    unparser_pyi_output: Annotated[
        Path | None,
        typer.Option(
            "--unparser-pyi-output",
            help="Path to write the unparser .pyi stub. Requires --protocol-module and --unparser-output.",
        ),
    ] = None,
    protocol_output: Annotated[
        Path | None,
        typer.Option("--protocol-output", help="Path to write the protocol .py module. Requires --protocol-module."),
    ] = None,
    init_pyi_output: Annotated[
        Path | None,
        typer.Option(
            "--init-pyi-output",
            help="Path to write the stub-package __init__.pyi marker. Requires --extension-name and --submodules.",
        ),
    ] = None,
    extension_name: Annotated[
        str | None,
        typer.Option(
            "--extension-name",
            help="The compiled extension's importable name, for the __init__.pyi marker. Requires --init-pyi-output.",
        ),
    ] = None,
    submodules: Annotated[
        str | None,
        typer.Option(
            "--submodules",
            help="Comma-separated submodule names for the __init__.pyi marker. Requires --init-pyi-output.",
        ),
    ] = None,
) -> None:
    """Emit every requested Rust artifact for a grammar in one process.

    This is the merged form of gen-rust-cst / gen-rust-parser / gen-rust-unparser /
    gen-rust-ast / gen-rust-serde: it takes the union of their flags, reads and parses the
    grammar once, and writes whichever outputs were named. The five single-purpose
    subcommands remain available and produce byte-identical artifacts; this one exists so a
    build system generating four or five files from one grammar pays for one interpreter
    startup and one grammar parse instead of five.

    Each output is named by its own option rather than a positional path, so the request is
    explicit: --cst-output is always required (the CST is what every other artifact is
    generated against), and each of the others is emitted exactly when its option is given.
    A flag shaping an artifact that was not requested is an error, not a silent no-op.

    It is all-or-nothing: every artifact is generated before any of them is written, so a
    failure part-way through leaves the output tree untouched rather than half-updated.

    Examples:
        genparser gen-rust-all grammar.fltkg \\
            --cst-output out/cst.rs --parser-output out/parser.rs
        genparser gen-rust-all grammar.fltkg \\
            --cst-output out/cst.rs --parser-output out/parser.rs \\
            --unparser-output out/unparser.rs --format-config grammar.fltkfmt \\
            --ast-output out/ast.rs --serde-output out/de.rs \\
            --ast-config grammar.fltkast --goal config \\
            --parser-mod-path super::parser --unparser-mod-path super::unparser \\
            --ast-mod-path super::ast
    """
    _validate_cst_mod_path(cst_mod_path)
    if parser_mod_path is not None:
        _validate_rust_mod_path(parser_mod_path, "--parser-mod-path")
    if unparser_mod_path is not None:
        _validate_rust_mod_path(unparser_mod_path, "--unparser-mod-path")
    if ast_mod_path is not None:
        _validate_rust_mod_path(ast_mod_path, "--ast-mod-path")

    _require_together(cst_pyi_output, "--cst-pyi-output", protocol_module, "--protocol-module")
    _require_together(unparser_pyi_output, "--unparser-pyi-output", protocol_module, "--protocol-module")
    _require_together(protocol_output, "--protocol-output", protocol_module, "--protocol-module")
    if protocol_module is not None:
        _validate_protocol_module(protocol_module)

    # Every emitted file must be named by an option; defaulting the .pyi path would put an
    # unnamed file next to the .rs.
    _require_together(protocol_module, "--protocol-module", cst_pyi_output, "--cst-pyi-output")

    # The two marker fields shape --init-pyi-output's file and nothing else, so without it they
    # would be discarded in silence.
    _require_together(extension_name, "--extension-name", init_pyi_output, "--init-pyi-output")
    _require_together(submodules, "--submodules", init_pyi_output, "--init-pyi-output")

    _require_together(format_config, "--format-config", unparser_output, "--unparser-output")
    _require_together(unparser_pyi_output, "--unparser-pyi-output", unparser_output, "--unparser-output")

    # The unparser stub is the only thing --protocol-module shapes on the unparser path. Omitting
    # its output path would either drop the stub or write it to an unnamed path beside
    # unparser.rs, and every emitted file here must be named by an option.
    if protocol_module is not None and unparser_output is not None and unparser_pyi_output is None:
        typer.echo("Error: --unparser-output with --protocol-module requires --unparser-pyi-output", err=True)
        raise typer.Exit(1)

    _require_together(unparser_mod_path, "--unparser-mod-path", ast_output, "--ast-output")
    _require_together(ast_mod_path, "--ast-mod-path", serde_output, "--serde-output")

    _require_together(serde_output, "--serde-output", ast_config, "--ast-config")
    for value, option in (
        (ast_config, "--ast-config"),
        (goal, "--goal"),
        (parser_mod_path, "--parser-mod-path"),
    ):
        if value is not None and ast_output is None and serde_output is None:
            typer.echo(f"Error: {option} requires --ast-output or --serde-output", err=True)
            raise typer.Exit(1)

    # Render the grammar-independent stub-package marker up front so a malformed marker never
    # reaches disk (validation precedes any output write, and even the grammar parse).
    init_pyi_text = _render_init_pyi(init_pyi_output, extension_name, submodules)
    formatter_config = _parse_format_config_or_exit(format_config)

    # The _emit_rust_cst/parser/unparser functions take the raw GSM; _emit_rust_ast/serde
    # take the trivia-processed one, derived below rather than by a second file read.
    grammar = _parse_grammar_raw(grammar_file)

    # Deferred: nothing this subcommand generates reaches disk until every artifact has been
    # generated, so a failure part-way through leaves the tree as it was rather than
    # half-updated.
    writer = _ArtifactWriter(deferred=True)

    _emit_rust_cst(
        grammar,
        grammar_file,
        cst_output,
        protocol_module=protocol_module,
        pyi_output=cst_pyi_output,
        protocol_output=protocol_output,
        init_pyi_output=init_pyi_output,
        init_pyi_text=init_pyi_text,
        writer=writer,
    )

    if parser_output is not None:
        _emit_rust_parser(grammar, grammar_file, parser_output, cst_mod_path=cst_mod_path, writer=writer)

    if unparser_output is not None:
        _emit_rust_unparser(
            grammar,
            grammar_file,
            unparser_output,
            cst_mod_path=cst_mod_path,
            formatter_config=formatter_config,
            protocol_module=protocol_module,
            pyi_output=unparser_pyi_output,
            init_pyi_output=None,
            init_pyi_text=None,
            writer=writer,
        )

    if ast_output is not None or serde_output is not None:
        trivia_grammar = pybackend.apply_trivia_processing(grammar)
        resolved_config = None
        if ast_config is not None:
            resolved_config = _parse_ast_config_or_exit(ast_config, trivia_grammar, Backend.RUST)

        if ast_output is not None:
            _emit_rust_ast(
                trivia_grammar,
                grammar_file,
                ast_output,
                cst_mod_path=cst_mod_path,
                parser_mod_path=parser_mod_path,
                unparser_mod_path=unparser_mod_path,
                goal=goal,
                resolved_config=resolved_config,
                writer=writer,
            )

        if serde_output is not None:
            # --serde-output requires --ast-config, so resolved_config is set on this path.
            assert resolved_config is not None
            _emit_rust_serde(
                trivia_grammar,
                grammar_file,
                serde_output,
                cst_mod_path=cst_mod_path,
                parser_mod_path=parser_mod_path,
                goal=goal,
                ast_mod_path=ast_mod_path,
                resolved_config=resolved_config,
                writer=writer,
            )

    writer.flush()


@app.command(name="gen-rust-lib")
def gen_rust_lib(
    output_file: Annotated[Path, typer.Argument(help="Path to write the lib.rs source")],
    module_name: Annotated[
        str,
        typer.Option(
            "--module-name",
            help="The #[pymodule] function name / importable module name (e.g. 'clockwork_native').",
        ),
    ],
    *,
    no_parser: Annotated[
        bool,
        typer.Option("--no-parser", help="Emit a CST-only lib.rs (omit mod parser; and its registration)."),
    ] = False,
    unparser: Annotated[
        bool,
        typer.Option("--unparser", help="Also include the unparser submodule (mod unparser; and its registration)."),
    ] = False,
    no_cst: Annotated[
        bool,
        typer.Option(
            "--no-cst",
            help="Emit zero submodules (omit mod cst; and all registrations). "
            "Use with --register-span-types/--unknown-span-static for runtime-only libs.",
        ),
    ] = False,
    plain_module: Annotated[
        list[str] | None,
        typer.Option(
            "--plain-module",
            help=(
                "Declare a module that is NOT registered as a Python submodule (repeatable). "
                "The generated 'ast' and 'de' modules are Rust-only — they hold no pyclasses "
                "and have no register_classes — so they need `pub mod <name>;` in the crate "
                "root and nothing else. Each name must be a valid Rust identifier that is not a "
                "keyword (the generated lib.rs spells it bare, never as r#name) and must not "
                "name a module the generator already declares (a registered submodule, or 'span' "
                "under --register-span-types)."
            ),
        ),
    ] = None,
    register_span_types: Annotated[
        bool,
        typer.Option(
            "--register-span-types",
            help="Emit Span/SourceText/LineColPos class registration and span module import "
            "(the consumer's `mod span;` must export LineColPos, e.g. by re-exporting from fltk-cst-core).",
        ),
    ] = False,
    unknown_span_static: Annotated[
        bool,
        typer.Option("--unknown-span-static", help="Emit the UNKNOWN_SPAN static declaration and once-init."),
    ] = False,
) -> None:
    """Emit a Rust lib.rs module-wiring boilerplate for a standard pyo3 cdylib.

    Unlike gen-rust-cst / gen-rust-parser, this command needs no grammar file —
    lib.rs has no rule-derived content.  It is parameterized only by the module
    name and whether a parser submodule is included.

    Standard path: declares mod cst; (and mod parser; unless --no-parser, and
    mod unparser; when --unparser), and a #[pymodule] fn that registers them as
    Python submodules.

    Runtime-only path (--no-cst --register-span-types --unknown-span-static):
    emits span/UNKNOWN_SPAN wiring with zero submodules. Used for fltk._native.
    (--unparser, like --no-parser, has no effect when --no-cst is given.)

    Note: do NOT include #![recursion_limit] in the module name or output — the
    fltk_pyo3_cdylib Bazel macro injects it at assembly time.

    Examples:
        genparser gen-rust-lib lib.rs --module-name clockwork_native
        genparser gen-rust-lib lib.rs --module-name my_module --no-parser
        genparser gen-rust-lib lib.rs --module-name my_module --unparser
        genparser gen-rust-lib lib.rs --module-name my_module --plain-module ast --plain-module de
        genparser gen-rust-lib src/lib.rs --module-name _native --no-cst --register-span-types --unknown-span-static
    """
    plain_modules = tuple(plain_module or ())
    if not no_cst and (register_span_types or unknown_span_static):
        typer.echo(
            "Error: --register-span-types and --unknown-span-static require --no-cst. "
            "Combining span-type registration with grammar submodules is not a supported use case.",
            err=True,
        )
        raise typer.Exit(1)
    if no_cst:
        spec = gsm2lib_rs.LibSpec(
            module_name=module_name,
            submodules=(),
            plain_modules=plain_modules,
            register_span_types=register_span_types,
            unknown_span_static=unknown_span_static,
        )
    else:
        spec = gsm2lib_rs.LibSpec.standard(
            module_name,
            with_parser=not no_parser,
            with_unparser=unparser,
            plain_modules=plain_modules,
        )
    try:
        gen = gsm2lib_rs.RustLibGenerator(spec)
        src = gen.generate()
    except ValueError as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(1) from e

    _write_output_file(output_file, src)


if __name__ == "__main__":
    app()
