//! Generated by fltk gen-rust-parser from `fltk/fegen/fegen.fltkg`. Do not edit.
//! **Stack depth warning**: this parser is recursive-descent with no depth limit.
//! Deeply nested input (e.g. `((((…))))`) is proportional to native stack depth.
//! Stack exhaustion aborts the process (cannot be caught with `catch_unwind`).
//! Callers parsing untrusted input should impose a nesting-depth limit upstream
//! or run the parser on a thread with a known stack size.
//! TODO(parser-depth-limit): emit a configurable depth counter in the generated Parser.
// Allow double-underscore names used in generated parse function paths.
#![allow(non_snake_case)]

use std::sync::OnceLock;
use fltk_parser_core::regex::Regex;

use fltk_cst_core::{Shared, SourceText, Span};
use fltk_parser_core::{apply, ApplyResult, Cache, ErrorTracker, PackratState, TerminalSource};

use super::cst;

pub const RULE_NAMES: [&str; 14] = ["grammar", "rule", "alternatives", "items", "item", "term", "disposition", "quantifier", "identifier", "raw_string", "literal", "_trivia", "line_comment", "block_comment"];

const REGEX_PATTERNS: [&str; 7] = ["[_a-z][_a-z0-9]*", "([^\\/\\n\\\\]|\\\\.)+", "(\"([^\"\\n\\\\]|\\\\.)+\"|'([^'\\n\\\\]|\\\\.)+')", "\\s+", "[^\\n]*", "(?:[^*]|\\*+[^\\/\\*])*", "\\*+\\/"];
static REGEX_CELLS: [OnceLock<Regex>; 7] = [OnceLock::new(), OnceLock::new(), OnceLock::new(), OnceLock::new(), OnceLock::new(), OnceLock::new(), OnceLock::new()];

fn regex_at(idx: usize) -> &'static Regex {
    REGEX_CELLS[idx].get_or_init(|| {
        Regex::new(REGEX_PATTERNS[idx])
            .unwrap_or_else(|e| panic!("invalid regex pattern {:?}: {e}", REGEX_PATTERNS[idx]))
    })
}

pub struct Parser {
    terminals: TerminalSource,
    packrat: PackratState,
    error_tracker: ErrorTracker,
    capture_trivia: bool,
    cache__parse_grammar: Cache<Shared<cst::Grammar>>,
    cache__parse_rule: Cache<Shared<cst::Rule>>,
    cache__parse_alternatives: Cache<Shared<cst::Alternatives>>,
    cache__parse_items: Cache<Shared<cst::Items>>,
    cache__parse_item: Cache<Shared<cst::Item>>,
    cache__parse_term: Cache<Shared<cst::Term>>,
    cache__parse_disposition: Cache<Shared<cst::Disposition>>,
    cache__parse_quantifier: Cache<Shared<cst::Quantifier>>,
    cache__parse_identifier: Cache<Shared<cst::Identifier>>,
    cache__parse_raw_string: Cache<Shared<cst::RawString>>,
    cache__parse_literal: Cache<Shared<cst::Literal>>,
    cache__parse__trivia: Cache<Shared<cst::Trivia>>,
    cache__parse_line_comment: Cache<Shared<cst::LineComment>>,
    cache__parse_block_comment: Cache<Shared<cst::BlockComment>>,
}

impl Parser {
    pub fn new(text: &str, capture_trivia: bool) -> Self {
        Self::from_source_text(SourceText::from_str(text), capture_trivia)
    }

    pub fn from_source_text(source: SourceText, capture_trivia: bool) -> Self {
        let terminals = TerminalSource::from_source_text(source);
        Self {
            terminals,
            packrat: PackratState::default(),
            error_tracker: ErrorTracker::default(),
            capture_trivia,
            cache__parse_grammar: Cache::new(),
            cache__parse_rule: Cache::new(),
            cache__parse_alternatives: Cache::new(),
            cache__parse_items: Cache::new(),
            cache__parse_item: Cache::new(),
            cache__parse_term: Cache::new(),
            cache__parse_disposition: Cache::new(),
            cache__parse_quantifier: Cache::new(),
            cache__parse_identifier: Cache::new(),
            cache__parse_raw_string: Cache::new(),
            cache__parse_literal: Cache::new(),
            cache__parse__trivia: Cache::new(),
            cache__parse_line_comment: Cache::new(),
            cache__parse_block_comment: Cache::new(),
        }
    }

    pub fn terminals(&self) -> &TerminalSource { &self.terminals }
    pub fn capture_trivia(&self) -> bool { self.capture_trivia }
    pub fn rule_names(&self) -> &'static [&'static str] { &RULE_NAMES }

    pub fn error_message(&self) -> String {
        fltk_parser_core::format_error_message(&self.error_tracker, &self.terminals, &RULE_NAMES)
    }

    pub fn error_position(&self) -> Option<i64> {
        (self.error_tracker.longest_parse_len >= 0).then_some(self.error_tracker.longest_parse_len)
    }

    fn consume_literal(&mut self, pos: i64, literal: &'static str) -> Option<ApplyResult<Span>> {
        if let Some(span) = self.terminals.consume_literal(pos, literal) {
            return Some(ApplyResult { pos: span.end(), result: span });
        }
        let rule_id = *self.packrat.invocation_stack.last()
            .expect("consume_literal called outside apply__* frame");
        self.error_tracker.fail_literal(pos, rule_id, literal);
        None
    }

    fn consume_regex(&mut self, pos: i64, regex_idx: usize) -> Option<ApplyResult<Span>> {
        if let Some(span) = self.terminals.consume_regex(pos, regex_at(regex_idx)) {
            return Some(ApplyResult { pos: span.end(), result: span });
        }
        let rule_id = *self.packrat.invocation_stack.last()
            .expect("consume_regex called outside apply__* frame");
        self.error_tracker.fail_regex(pos, rule_id, REGEX_PATTERNS[regex_idx]);
        None
    }

    pub fn apply__parse_grammar(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Grammar>>> {
        apply(self, 0u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_grammar, Self::parse_grammar)
    }

    fn parse_grammar__alt0__item0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Grammar>> {
        let span_start = pos;
        let mut result = cst::Grammar::new(Span::unknown());
        while let Some(one_result) = {
            self.apply__parse_rule(pos)
        } {
            pos = one_result.pos;
            result.append_rule(one_result.result);
        }
        if pos == span_start {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_grammar__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Grammar>> {
        let span_start = pos;
        let mut result = cst::Grammar::new(Span::unknown());
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::GrammarChild::Trivia(ws.result));
            }
        }
        if let Some(item0) = self.parse_grammar__alt0__item0(pos) {
            pos = item0.pos;
            result.extend_children(&item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_grammar(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Grammar>>> {
        if let Some(alt0) = self.parse_grammar__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_rule(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Rule>>> {
        apply(self, 1u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_rule, Self::parse_rule)
    }

    fn parse_rule__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Identifier>>> {
        self.apply__parse_identifier(pos)
    }

    fn parse_rule__alt0__item1(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, ":=")
    }

    fn parse_rule__alt0__item2(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Alternatives>>> {
        self.apply__parse_alternatives(pos)
    }

    fn parse_rule__alt0__item3(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, ";")
    }

    fn parse_rule__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Rule>> {
        let span_start = pos;
        let mut result = cst::Rule::new(Span::unknown());
        if let Some(item0) = self.parse_rule__alt0__item0(pos) {
            pos = item0.pos;
            result.append_name(item0.result);
        } else {
            return None;
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::RuleChild::Trivia(ws.result));
            }
        }
        if let Some(item1) = self.parse_rule__alt0__item1(pos) {
            pos = item1.pos;
        } else {
            return None;
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::RuleChild::Trivia(ws.result));
            }
        }
        if let Some(item2) = self.parse_rule__alt0__item2(pos) {
            pos = item2.pos;
            result.append_alternatives(item2.result);
        } else {
            return None;
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::RuleChild::Trivia(ws.result));
            }
        }
        if let Some(item3) = self.parse_rule__alt0__item3(pos) {
            pos = item3.pos;
        } else {
            return None;
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::RuleChild::Trivia(ws.result));
            }
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_rule(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Rule>>> {
        if let Some(alt0) = self.parse_rule__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_alternatives(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Alternatives>>> {
        apply(self, 2u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_alternatives, Self::parse_alternatives)
    }

    fn parse_alternatives__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Items>>> {
        self.apply__parse_items(pos)
    }

    fn parse_alternatives__alt0__item1__alts__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "|")
    }

    fn parse_alternatives__alt0__item1__alts__alt0__item1(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Items>>> {
        self.apply__parse_items(pos)
    }

    fn parse_alternatives__alt0__item1__alts__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Alternatives>> {
        let span_start = pos;
        let mut result = cst::Alternatives::new(Span::unknown());
        if let Some(item0) = self.parse_alternatives__alt0__item1__alts__alt0__item0(pos) {
            pos = item0.pos;
        } else {
            return None;
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::AlternativesChild::Trivia(ws.result));
            }
        }
        if let Some(item1) = self.parse_alternatives__alt0__item1__alts__alt0__item1(pos) {
            pos = item1.pos;
            result.append_items(item1.result);
        } else {
            return None;
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::AlternativesChild::Trivia(ws.result));
            }
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_alternatives__alt0__item1__alts(&mut self, pos: i64) -> Option<ApplyResult<cst::Alternatives>> {
        if let Some(r) = self.parse_alternatives__alt0__item1__alts__alt0(pos) {
            return Some(r);
        }
        None
    }

    fn parse_alternatives__alt0__item1(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Alternatives>> {
        let span_start = pos;
        let mut result = cst::Alternatives::new(Span::unknown());
        while let Some(one_result) = {
            self.parse_alternatives__alt0__item1__alts(pos)
        } {
            pos = one_result.pos;
            result.extend_children(&one_result.result);
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_alternatives__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Alternatives>> {
        let span_start = pos;
        let mut result = cst::Alternatives::new(Span::unknown());
        if let Some(item0) = self.parse_alternatives__alt0__item0(pos) {
            pos = item0.pos;
            result.append_items(item0.result);
        } else {
            return None;
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::AlternativesChild::Trivia(ws.result));
            }
        }
        if let Some(item1) = self.parse_alternatives__alt0__item1(pos) {
            pos = item1.pos;
            result.extend_children(&item1.result);
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_alternatives(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Alternatives>>> {
        if let Some(alt0) = self.parse_alternatives__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_items(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Items>>> {
        apply(self, 3u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_items, Self::parse_items)
    }

    fn parse_items__alt0__item0__alts__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, ".")
    }

    fn parse_items__alt0__item0__alts__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Items>> {
        let span_start = pos;
        let mut result = cst::Items::new(Span::unknown());
        if let Some(item0) = self.parse_items__alt0__item0__alts__alt0__item0(pos) {
            pos = item0.pos;
            result.append_no_ws(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_items__alt0__item0__alts__alt1__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, ",")
    }

    fn parse_items__alt0__item0__alts__alt1(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Items>> {
        let span_start = pos;
        let mut result = cst::Items::new(Span::unknown());
        if let Some(item0) = self.parse_items__alt0__item0__alts__alt1__item0(pos) {
            pos = item0.pos;
            result.append_ws_allowed(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_items__alt0__item0__alts__alt2__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, ":")
    }

    fn parse_items__alt0__item0__alts__alt2(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Items>> {
        let span_start = pos;
        let mut result = cst::Items::new(Span::unknown());
        if let Some(item0) = self.parse_items__alt0__item0__alts__alt2__item0(pos) {
            pos = item0.pos;
            result.append_ws_required(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_items__alt0__item0__alts(&mut self, pos: i64) -> Option<ApplyResult<cst::Items>> {
        if let Some(r) = self.parse_items__alt0__item0__alts__alt0(pos) {
            return Some(r);
        }
        if let Some(r) = self.parse_items__alt0__item0__alts__alt1(pos) {
            return Some(r);
        }
        if let Some(r) = self.parse_items__alt0__item0__alts__alt2(pos) {
            return Some(r);
        }
        None
    }

    fn parse_items__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<cst::Items>> {
        self.parse_items__alt0__item0__alts(pos)
    }

    fn parse_items__alt0__item1(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Item>>> {
        self.apply__parse_item(pos)
    }

    fn parse_items__alt0__item2__alts__alt0__item0__alts__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, ".")
    }

    fn parse_items__alt0__item2__alts__alt0__item0__alts__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Items>> {
        let span_start = pos;
        let mut result = cst::Items::new(Span::unknown());
        if let Some(item0) = self.parse_items__alt0__item2__alts__alt0__item0__alts__alt0__item0(pos) {
            pos = item0.pos;
            result.append_no_ws(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_items__alt0__item2__alts__alt0__item0__alts__alt1__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, ",")
    }

    fn parse_items__alt0__item2__alts__alt0__item0__alts__alt1(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Items>> {
        let span_start = pos;
        let mut result = cst::Items::new(Span::unknown());
        if let Some(item0) = self.parse_items__alt0__item2__alts__alt0__item0__alts__alt1__item0(pos) {
            pos = item0.pos;
            result.append_ws_allowed(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_items__alt0__item2__alts__alt0__item0__alts__alt2__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, ":")
    }

    fn parse_items__alt0__item2__alts__alt0__item0__alts__alt2(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Items>> {
        let span_start = pos;
        let mut result = cst::Items::new(Span::unknown());
        if let Some(item0) = self.parse_items__alt0__item2__alts__alt0__item0__alts__alt2__item0(pos) {
            pos = item0.pos;
            result.append_ws_required(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_items__alt0__item2__alts__alt0__item0__alts(&mut self, pos: i64) -> Option<ApplyResult<cst::Items>> {
        if let Some(r) = self.parse_items__alt0__item2__alts__alt0__item0__alts__alt0(pos) {
            return Some(r);
        }
        if let Some(r) = self.parse_items__alt0__item2__alts__alt0__item0__alts__alt1(pos) {
            return Some(r);
        }
        if let Some(r) = self.parse_items__alt0__item2__alts__alt0__item0__alts__alt2(pos) {
            return Some(r);
        }
        None
    }

    fn parse_items__alt0__item2__alts__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<cst::Items>> {
        self.parse_items__alt0__item2__alts__alt0__item0__alts(pos)
    }

    fn parse_items__alt0__item2__alts__alt0__item1(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Item>>> {
        self.apply__parse_item(pos)
    }

    fn parse_items__alt0__item2__alts__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Items>> {
        let span_start = pos;
        let mut result = cst::Items::new(Span::unknown());
        if let Some(item0) = self.parse_items__alt0__item2__alts__alt0__item0(pos) {
            pos = item0.pos;
            result.extend_children(&item0.result);
        } else {
            return None;
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::ItemsChild::Trivia(ws.result));
            }
        }
        if let Some(item1) = self.parse_items__alt0__item2__alts__alt0__item1(pos) {
            pos = item1.pos;
            result.append_item(item1.result);
        } else {
            return None;
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::ItemsChild::Trivia(ws.result));
            }
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_items__alt0__item2__alts(&mut self, pos: i64) -> Option<ApplyResult<cst::Items>> {
        if let Some(r) = self.parse_items__alt0__item2__alts__alt0(pos) {
            return Some(r);
        }
        None
    }

    fn parse_items__alt0__item2(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Items>> {
        let span_start = pos;
        let mut result = cst::Items::new(Span::unknown());
        while let Some(one_result) = {
            self.parse_items__alt0__item2__alts(pos)
        } {
            pos = one_result.pos;
            result.extend_children(&one_result.result);
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_items__alt0__item3__alts__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, ".")
    }

    fn parse_items__alt0__item3__alts__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Items>> {
        let span_start = pos;
        let mut result = cst::Items::new(Span::unknown());
        if let Some(item0) = self.parse_items__alt0__item3__alts__alt0__item0(pos) {
            pos = item0.pos;
            result.append_no_ws(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_items__alt0__item3__alts__alt1__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, ",")
    }

    fn parse_items__alt0__item3__alts__alt1(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Items>> {
        let span_start = pos;
        let mut result = cst::Items::new(Span::unknown());
        if let Some(item0) = self.parse_items__alt0__item3__alts__alt1__item0(pos) {
            pos = item0.pos;
            result.append_ws_allowed(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_items__alt0__item3__alts__alt2__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, ":")
    }

    fn parse_items__alt0__item3__alts__alt2(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Items>> {
        let span_start = pos;
        let mut result = cst::Items::new(Span::unknown());
        if let Some(item0) = self.parse_items__alt0__item3__alts__alt2__item0(pos) {
            pos = item0.pos;
            result.append_ws_required(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_items__alt0__item3__alts(&mut self, pos: i64) -> Option<ApplyResult<cst::Items>> {
        if let Some(r) = self.parse_items__alt0__item3__alts__alt0(pos) {
            return Some(r);
        }
        if let Some(r) = self.parse_items__alt0__item3__alts__alt1(pos) {
            return Some(r);
        }
        if let Some(r) = self.parse_items__alt0__item3__alts__alt2(pos) {
            return Some(r);
        }
        None
    }

    fn parse_items__alt0__item3(&mut self, pos: i64) -> Option<ApplyResult<cst::Items>> {
        self.parse_items__alt0__item3__alts(pos)
    }

    fn parse_items__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Items>> {
        let span_start = pos;
        let mut result = cst::Items::new(Span::unknown());
        if let Some(item0) = self.parse_items__alt0__item0(pos) {
            pos = item0.pos;
            result.extend_children(&item0.result);
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::ItemsChild::Trivia(ws.result));
            }
        }
        if let Some(item1) = self.parse_items__alt0__item1(pos) {
            pos = item1.pos;
            result.append_item(item1.result);
        } else {
            return None;
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::ItemsChild::Trivia(ws.result));
            }
        }
        if let Some(item2) = self.parse_items__alt0__item2(pos) {
            pos = item2.pos;
            result.extend_children(&item2.result);
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::ItemsChild::Trivia(ws.result));
            }
        }
        if let Some(item3) = self.parse_items__alt0__item3(pos) {
            pos = item3.pos;
            result.extend_children(&item3.result);
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::ItemsChild::Trivia(ws.result));
            }
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_items(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Items>>> {
        if let Some(alt0) = self.parse_items__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_item(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Item>>> {
        apply(self, 4u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_item, Self::parse_item)
    }

    fn parse_item__alt0__item0__alts__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Identifier>>> {
        self.apply__parse_identifier(pos)
    }

    fn parse_item__alt0__item0__alts__alt0__item1(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, ":")
    }

    fn parse_item__alt0__item0__alts__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Item>> {
        let span_start = pos;
        let mut result = cst::Item::new(Span::unknown());
        if let Some(item0) = self.parse_item__alt0__item0__alts__alt0__item0(pos) {
            pos = item0.pos;
            result.append_label(item0.result);
        } else {
            return None;
        }
        if let Some(item1) = self.parse_item__alt0__item0__alts__alt0__item1(pos) {
            pos = item1.pos;
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_item__alt0__item0__alts(&mut self, pos: i64) -> Option<ApplyResult<cst::Item>> {
        if let Some(r) = self.parse_item__alt0__item0__alts__alt0(pos) {
            return Some(r);
        }
        None
    }

    fn parse_item__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<cst::Item>> {
        self.parse_item__alt0__item0__alts(pos)
    }

    fn parse_item__alt0__item1(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Disposition>>> {
        self.apply__parse_disposition(pos)
    }

    fn parse_item__alt0__item2(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Term>>> {
        self.apply__parse_term(pos)
    }

    fn parse_item__alt0__item3(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Quantifier>>> {
        self.apply__parse_quantifier(pos)
    }

    fn parse_item__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Item>> {
        let span_start = pos;
        let mut result = cst::Item::new(Span::unknown());
        if let Some(item0) = self.parse_item__alt0__item0(pos) {
            pos = item0.pos;
            result.extend_children(&item0.result);
        }
        if let Some(item1) = self.parse_item__alt0__item1(pos) {
            pos = item1.pos;
            result.append_disposition(item1.result);
        }
        if let Some(item2) = self.parse_item__alt0__item2(pos) {
            pos = item2.pos;
            result.append_term(item2.result);
        } else {
            return None;
        }
        if let Some(item3) = self.parse_item__alt0__item3(pos) {
            pos = item3.pos;
            result.append_quantifier(item3.result);
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::ItemChild::Trivia(ws.result));
            }
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_item(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Item>>> {
        if let Some(alt0) = self.parse_item__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_term(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Term>>> {
        apply(self, 5u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_term, Self::parse_term)
    }

    fn parse_term__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Identifier>>> {
        self.apply__parse_identifier(pos)
    }

    fn parse_term__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Term>> {
        let span_start = pos;
        let mut result = cst::Term::new(Span::unknown());
        if let Some(item0) = self.parse_term__alt0__item0(pos) {
            pos = item0.pos;
            result.append_identifier(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_term__alt1__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Literal>>> {
        self.apply__parse_literal(pos)
    }

    fn parse_term__alt1(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Term>> {
        let span_start = pos;
        let mut result = cst::Term::new(Span::unknown());
        if let Some(item0) = self.parse_term__alt1__item0(pos) {
            pos = item0.pos;
            result.append_literal(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_term__alt2__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "/")
    }

    fn parse_term__alt2__item1(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::RawString>>> {
        self.apply__parse_raw_string(pos)
    }

    fn parse_term__alt2__item2(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "/")
    }

    fn parse_term__alt2(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Term>> {
        let span_start = pos;
        let mut result = cst::Term::new(Span::unknown());
        if let Some(item0) = self.parse_term__alt2__item0(pos) {
            pos = item0.pos;
        } else {
            return None;
        }
        if let Some(item1) = self.parse_term__alt2__item1(pos) {
            pos = item1.pos;
            result.append_regex(item1.result);
        } else {
            return None;
        }
        if let Some(item2) = self.parse_term__alt2__item2(pos) {
            pos = item2.pos;
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_term__alt3__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "(")
    }

    fn parse_term__alt3__item1(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Alternatives>>> {
        self.apply__parse_alternatives(pos)
    }

    fn parse_term__alt3__item2(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, ")")
    }

    fn parse_term__alt3(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Term>> {
        let span_start = pos;
        let mut result = cst::Term::new(Span::unknown());
        if let Some(item0) = self.parse_term__alt3__item0(pos) {
            pos = item0.pos;
        } else {
            return None;
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::TermChild::Trivia(ws.result));
            }
        }
        if let Some(item1) = self.parse_term__alt3__item1(pos) {
            pos = item1.pos;
            result.append_alternatives(item1.result);
        } else {
            return None;
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::TermChild::Trivia(ws.result));
            }
        }
        if let Some(item2) = self.parse_term__alt3__item2(pos) {
            pos = item2.pos;
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_term(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Term>>> {
        if let Some(alt0) = self.parse_term__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        if let Some(alt1) = self.parse_term__alt1(pos) {
            return Some(ApplyResult { pos: alt1.pos, result: Shared::new(alt1.result) });
        }
        if let Some(alt2) = self.parse_term__alt2(pos) {
            return Some(ApplyResult { pos: alt2.pos, result: Shared::new(alt2.result) });
        }
        if let Some(alt3) = self.parse_term__alt3(pos) {
            return Some(ApplyResult { pos: alt3.pos, result: Shared::new(alt3.result) });
        }
        None
    }

    pub fn apply__parse_disposition(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Disposition>>> {
        apply(self, 6u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_disposition, Self::parse_disposition)
    }

    fn parse_disposition__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "%")
    }

    fn parse_disposition__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Disposition>> {
        let span_start = pos;
        let mut result = cst::Disposition::new(Span::unknown());
        if let Some(item0) = self.parse_disposition__alt0__item0(pos) {
            pos = item0.pos;
            result.append_suppress(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_disposition__alt1__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "$")
    }

    fn parse_disposition__alt1(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Disposition>> {
        let span_start = pos;
        let mut result = cst::Disposition::new(Span::unknown());
        if let Some(item0) = self.parse_disposition__alt1__item0(pos) {
            pos = item0.pos;
            result.append_include(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_disposition__alt2__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "!")
    }

    fn parse_disposition__alt2(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Disposition>> {
        let span_start = pos;
        let mut result = cst::Disposition::new(Span::unknown());
        if let Some(item0) = self.parse_disposition__alt2__item0(pos) {
            pos = item0.pos;
            result.append_inline(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_disposition(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Disposition>>> {
        if let Some(alt0) = self.parse_disposition__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        if let Some(alt1) = self.parse_disposition__alt1(pos) {
            return Some(ApplyResult { pos: alt1.pos, result: Shared::new(alt1.result) });
        }
        if let Some(alt2) = self.parse_disposition__alt2(pos) {
            return Some(ApplyResult { pos: alt2.pos, result: Shared::new(alt2.result) });
        }
        None
    }

    pub fn apply__parse_quantifier(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Quantifier>>> {
        apply(self, 7u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_quantifier, Self::parse_quantifier)
    }

    fn parse_quantifier__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "?")
    }

    fn parse_quantifier__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Quantifier>> {
        let span_start = pos;
        let mut result = cst::Quantifier::new(Span::unknown());
        if let Some(item0) = self.parse_quantifier__alt0__item0(pos) {
            pos = item0.pos;
            result.append_optional(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_quantifier__alt1__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "+")
    }

    fn parse_quantifier__alt1(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Quantifier>> {
        let span_start = pos;
        let mut result = cst::Quantifier::new(Span::unknown());
        if let Some(item0) = self.parse_quantifier__alt1__item0(pos) {
            pos = item0.pos;
            result.append_one_or_more(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_quantifier__alt2__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "*")
    }

    fn parse_quantifier__alt2(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Quantifier>> {
        let span_start = pos;
        let mut result = cst::Quantifier::new(Span::unknown());
        if let Some(item0) = self.parse_quantifier__alt2__item0(pos) {
            pos = item0.pos;
            result.append_zero_or_more(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_quantifier(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Quantifier>>> {
        if let Some(alt0) = self.parse_quantifier__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        if let Some(alt1) = self.parse_quantifier__alt1(pos) {
            return Some(ApplyResult { pos: alt1.pos, result: Shared::new(alt1.result) });
        }
        if let Some(alt2) = self.parse_quantifier__alt2(pos) {
            return Some(ApplyResult { pos: alt2.pos, result: Shared::new(alt2.result) });
        }
        None
    }

    pub fn apply__parse_identifier(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Identifier>>> {
        apply(self, 8u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_identifier, Self::parse_identifier)
    }

    fn parse_identifier__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_regex(pos, 0)
    }

    fn parse_identifier__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Identifier>> {
        let span_start = pos;
        let mut result = cst::Identifier::new(Span::unknown());
        if let Some(item0) = self.parse_identifier__alt0__item0(pos) {
            pos = item0.pos;
            result.append_name(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_identifier(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Identifier>>> {
        if let Some(alt0) = self.parse_identifier__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_raw_string(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::RawString>>> {
        apply(self, 9u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_raw_string, Self::parse_raw_string)
    }

    fn parse_raw_string__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_regex(pos, 1)
    }

    fn parse_raw_string__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::RawString>> {
        let span_start = pos;
        let mut result = cst::RawString::new(Span::unknown());
        if let Some(item0) = self.parse_raw_string__alt0__item0(pos) {
            pos = item0.pos;
            result.append_value(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_raw_string(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::RawString>>> {
        if let Some(alt0) = self.parse_raw_string__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_literal(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Literal>>> {
        apply(self, 10u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_literal, Self::parse_literal)
    }

    fn parse_literal__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_regex(pos, 2)
    }

    fn parse_literal__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Literal>> {
        let span_start = pos;
        let mut result = cst::Literal::new(Span::unknown());
        if let Some(item0) = self.parse_literal__alt0__item0(pos) {
            pos = item0.pos;
            result.append_value(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_literal(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Literal>>> {
        if let Some(alt0) = self.parse_literal__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse__trivia(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Trivia>>> {
        apply(self, 11u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse__trivia, Self::parse__trivia)
    }

    fn parse__trivia__alt0__item0__alts__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::LineComment>>> {
        self.apply__parse_line_comment(pos)
    }

    fn parse__trivia__alt0__item0__alts__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Trivia>> {
        let span_start = pos;
        let mut result = cst::Trivia::new(Span::unknown());
        if let Some(item0) = self.parse__trivia__alt0__item0__alts__alt0__item0(pos) {
            pos = item0.pos;
            result.append_line_comment(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse__trivia__alt0__item0__alts__alt1__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::LineComment>>> {
        self.apply__parse_line_comment(pos)
    }

    fn parse__trivia__alt0__item0__alts__alt1(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Trivia>> {
        let span_start = pos;
        let mut result = cst::Trivia::new(Span::unknown());
        if let Some(item0) = self.parse__trivia__alt0__item0__alts__alt1__item0(pos) {
            pos = item0.pos;
            result.append_line_comment(item0.result);
        }
        if let Some(ws) = self.consume_regex(pos, 3) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::TriviaChild::Span(ws.result));
            }
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse__trivia__alt0__item0__alts__alt2__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::BlockComment>>> {
        self.apply__parse_block_comment(pos)
    }

    fn parse__trivia__alt0__item0__alts__alt2(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Trivia>> {
        let span_start = pos;
        let mut result = cst::Trivia::new(Span::unknown());
        if let Some(item0) = self.parse__trivia__alt0__item0__alts__alt2__item0(pos) {
            pos = item0.pos;
            result.append_block_comment(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse__trivia__alt0__item0__alts(&mut self, pos: i64) -> Option<ApplyResult<cst::Trivia>> {
        if let Some(r) = self.parse__trivia__alt0__item0__alts__alt0(pos) {
            return Some(r);
        }
        if let Some(r) = self.parse__trivia__alt0__item0__alts__alt1(pos) {
            return Some(r);
        }
        if let Some(r) = self.parse__trivia__alt0__item0__alts__alt2(pos) {
            return Some(r);
        }
        None
    }

    fn parse__trivia__alt0__item0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Trivia>> {
        let span_start = pos;
        let mut result = cst::Trivia::new(Span::unknown());
        while let Some(one_result) = {
            self.parse__trivia__alt0__item0__alts(pos)
        } {
            pos = one_result.pos;
            result.extend_children(&one_result.result);
        }
        if pos == span_start {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse__trivia__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Trivia>> {
        let span_start = pos;
        let mut result = cst::Trivia::new(Span::unknown());
        if let Some(item0) = self.parse__trivia__alt0__item0(pos) {
            pos = item0.pos;
            result.extend_children(&item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse__trivia(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Trivia>>> {
        if let Some(alt0) = self.parse__trivia__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_line_comment(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::LineComment>>> {
        apply(self, 12u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_line_comment, Self::parse_line_comment)
    }

    fn parse_line_comment__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "//")
    }

    fn parse_line_comment__alt0__item1(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_regex(pos, 4)
    }

    fn parse_line_comment__alt0__item2(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "\u{0a}")
    }

    fn parse_line_comment__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::LineComment>> {
        let span_start = pos;
        let mut result = cst::LineComment::new(Span::unknown());
        if let Some(item0) = self.parse_line_comment__alt0__item0(pos) {
            pos = item0.pos;
            result.append_prefix(item0.result);
        } else {
            return None;
        }
        if let Some(item1) = self.parse_line_comment__alt0__item1(pos) {
            pos = item1.pos;
            result.append_content(item1.result);
        } else {
            return None;
        }
        if let Some(item2) = self.parse_line_comment__alt0__item2(pos) {
            pos = item2.pos;
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_line_comment(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::LineComment>>> {
        if let Some(alt0) = self.parse_line_comment__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_block_comment(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::BlockComment>>> {
        apply(self, 13u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_block_comment, Self::parse_block_comment)
    }

    fn parse_block_comment__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "/*")
    }

    fn parse_block_comment__alt0__item1(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_regex(pos, 5)
    }

    fn parse_block_comment__alt0__item2(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_regex(pos, 6)
    }

    fn parse_block_comment__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::BlockComment>> {
        let span_start = pos;
        let mut result = cst::BlockComment::new(Span::unknown());
        if let Some(item0) = self.parse_block_comment__alt0__item0(pos) {
            pos = item0.pos;
            result.append_start(item0.result);
        } else {
            return None;
        }
        if let Some(item1) = self.parse_block_comment__alt0__item1(pos) {
            pos = item1.pos;
            result.append_content(item1.result);
        } else {
            return None;
        }
        if let Some(item2) = self.parse_block_comment__alt0__item2(pos) {
            pos = item2.pos;
            result.append_end(item2.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_block_comment(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::BlockComment>>> {
        if let Some(alt0) = self.parse_block_comment__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

}
#[cfg(test)]
mod generated_regex_tests {
    #[test]
    fn all_regex_patterns_compile() {
        for pat in super::REGEX_PATTERNS.iter() {
            if let Err(e) = fltk_parser_core::regex::Regex::new(pat) {
                panic!("grammar regex {pat:?} is not supported by the regex crate: {e}");
            }
        }
    }
}
