//! Generated by fltk gen-rust-parser from `fltk/fegen/test_data/collision_fixture.fltkg`. Do not edit.
//! **Stack depth note**: this parser is recursive-descent. Rule-application depth is
//! bounded by `max_depth` (default `fltk_parser_core::DEFAULT_MAX_DEPTH`, configurable
//! via `Parser::set_max_depth`). Exceeding it fails the parse with
//! `Parser::depth_exceeded()` set (Python bindings raise `RecursionError`) rather than
//! overflowing the native stack. **The default limit is sized for an ~8 MiB stack and
//! ~5-7 native frames per rule application.** Callers on smaller thread stacks (Rust
//! spawned threads use 2 MiB; async-runtime worker threads vary) or with grammars
//! that have deep per-rule call structure must lower `max_depth` proportionally or
//! size the stack accordingly. Check `depth_exceeded()` after parsing; a result
//! produced with the flag set must be discarded.
// Allow double-underscore names used in generated parse function paths.
#![allow(non_snake_case)]

use std::sync::OnceLock;
use fltk_parser_core::regex_automata::meta::Regex;

use fltk_cst_core::{Shared, SourceText, Span};
use fltk_parser_core::{apply, ApplyResult, Cache, ErrorTracker, PackratState, TerminalSource};

use super::collision_cst as cst;

pub const RULE_NAMES: [&str; 6] = ["root", "name", "parser", "apply_result", "item", "_trivia"];

const REGEX_PATTERNS: [&str; 2] = ["[a-z_]+", "[\\s]+"];
static REGEX_CELLS: [OnceLock<Regex>; 2] = [OnceLock::new(), OnceLock::new()];

fn regex_at(idx: usize) -> &'static Regex {
    REGEX_CELLS[idx].get_or_init(|| {
        Regex::new(REGEX_PATTERNS[idx])
            .unwrap_or_else(|e| panic!("invalid regex pattern {:?}: {e}", REGEX_PATTERNS[idx]))
    })
}

pub struct Parser {
    terminals: TerminalSource,
    packrat: PackratState,
    error_tracker: ErrorTracker,
    capture_trivia: bool,
    cache__parse_root: Cache<Shared<cst::Root>>,
    cache__parse_name: Cache<Shared<cst::Name>>,
    cache__parse_parser: Cache<Shared<cst::Parser>>,
    cache__parse_apply_result: Cache<Shared<cst::ApplyResult>>,
    cache__parse_item: Cache<Shared<cst::Item>>,
    cache__parse__trivia: Cache<Shared<cst::Trivia>>,
}

impl Parser {
    pub fn new(text: &str, filename: Option<&str>, capture_trivia: bool) -> Self {
        Self::from_source_text(SourceText::from_str(text, filename), capture_trivia)
    }

    pub fn from_source_text(source: SourceText, capture_trivia: bool) -> Self {
        let terminals = TerminalSource::from_source_text(source);
        Self {
            terminals,
            packrat: PackratState::default(),
            error_tracker: ErrorTracker::default(),
            capture_trivia,
            cache__parse_root: Cache::new(),
            cache__parse_name: Cache::new(),
            cache__parse_parser: Cache::new(),
            cache__parse_apply_result: Cache::new(),
            cache__parse_item: Cache::new(),
            cache__parse__trivia: Cache::new(),
        }
    }

    pub fn terminals(&self) -> &TerminalSource { &self.terminals }
    pub fn capture_trivia(&self) -> bool { self.capture_trivia }
    pub fn rule_names(&self) -> &'static [&'static str] { &RULE_NAMES }

    /// Return a human-readable parse error message.
    ///
    /// If `depth_exceeded()` is true, returns a depth-limit diagnostic instead of
    /// the normal longest-match error — the error tracker state is unreliable when
    /// depth was exceeded.
    pub fn error_message(&self) -> String {
        if self.packrat.depth_exceeded() {
            return format!("parse aborted: depth limit exceeded (max_depth = {})", self.packrat.max_depth());
        }
        fltk_parser_core::format_error_message(&self.error_tracker, &self.terminals, &RULE_NAMES)
    }

    pub fn error_position(&self) -> Option<i64> {
        (self.error_tracker.longest_parse_len >= 0).then_some(self.error_tracker.longest_parse_len)
    }

    /// Set the maximum rule-application depth before the parse fails with the
    /// depth-exceeded flag. Call before parsing.
    /// Default: `fltk_parser_core::DEFAULT_MAX_DEPTH`.
    pub fn set_max_depth(&mut self, max_depth: u32) { self.packrat.set_max_depth(max_depth); }

    /// Return the current maximum rule-application depth limit.
    pub fn max_depth(&self) -> u32 { self.packrat.max_depth() }

    /// Return true if the depth limit was exceeded during parsing.
    ///
    /// When true, the parse result (even if `Some`) must be discarded — it may be
    /// a partial or wrong parse. This instance is spent; construct a fresh `Parser`.
    pub fn depth_exceeded(&self) -> bool { self.packrat.depth_exceeded() }

    fn consume_regex(&mut self, pos: i64, regex_idx: usize) -> Option<ApplyResult<Span>> {
        if let Some(span) = self.terminals.consume_regex(pos, regex_at(regex_idx)) {
            return Some(ApplyResult { pos: span.end(), result: span });
        }
        let rule_id = *self.packrat.invocation_stack.last()
            .expect("consume_regex called outside apply__* frame");
        self.error_tracker.fail_regex(pos, rule_id, REGEX_PATTERNS[regex_idx]);
        None
    }

    pub fn apply__parse_root(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Root>>> {
        apply(self, 0u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_root, Self::parse_root)
    }

    fn parse_root__alt0__item0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Root>> {
        let span_start = pos;
        let mut result = cst::Root::new(Span::unknown());
        while let Some(one_result) = {
            self.apply__parse_item(pos)
        } {
            if one_result.pos <= pos { break; }
            pos = one_result.pos;
            result.append_item(one_result.result);
        }
        if pos == span_start {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_root__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Root>> {
        let span_start = pos;
        let mut result = cst::Root::new(Span::unknown());
        let item0 = self.parse_root__alt0__item0(pos)?;
        pos = item0.pos;
        result.extend_children(&item0.result);
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_root(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Root>>> {
        if let Some(alt0) = self.parse_root__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_name(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Name>>> {
        apply(self, 1u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_name, Self::parse_name)
    }

    fn parse_name__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_regex(pos, 0)
    }

    fn parse_name__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Name>> {
        let span_start = pos;
        let mut result = cst::Name::new(Span::unknown());
        let item0 = self.parse_name__alt0__item0(pos)?;
        pos = item0.pos;
        result.append_value(item0.result);
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_name(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Name>>> {
        if let Some(alt0) = self.parse_name__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_parser(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Parser>>> {
        apply(self, 2u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_parser, Self::parse_parser)
    }

    fn parse_parser__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Name>>> {
        self.apply__parse_name(pos)
    }

    fn parse_parser__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Parser>> {
        let span_start = pos;
        let mut result = cst::Parser::new(Span::unknown());
        let item0 = self.parse_parser__alt0__item0(pos)?;
        pos = item0.pos;
        result.append_name(item0.result);
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_parser(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Parser>>> {
        if let Some(alt0) = self.parse_parser__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_apply_result(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::ApplyResult>>> {
        apply(self, 3u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_apply_result, Self::parse_apply_result)
    }

    fn parse_apply_result__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Name>>> {
        self.apply__parse_name(pos)
    }

    fn parse_apply_result__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::ApplyResult>> {
        let span_start = pos;
        let mut result = cst::ApplyResult::new(Span::unknown());
        let item0 = self.parse_apply_result__alt0__item0(pos)?;
        pos = item0.pos;
        result.append_name(item0.result);
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_apply_result(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::ApplyResult>>> {
        if let Some(alt0) = self.parse_apply_result__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_item(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Item>>> {
        apply(self, 4u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_item, Self::parse_item)
    }

    fn parse_item__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Parser>>> {
        self.apply__parse_parser(pos)
    }

    fn parse_item__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Item>> {
        let span_start = pos;
        let mut result = cst::Item::new(Span::unknown());
        let item0 = self.parse_item__alt0__item0(pos)?;
        pos = item0.pos;
        result.append_p(item0.result);
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_item__alt1__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::ApplyResult>>> {
        self.apply__parse_apply_result(pos)
    }

    fn parse_item__alt1(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Item>> {
        let span_start = pos;
        let mut result = cst::Item::new(Span::unknown());
        let item0 = self.parse_item__alt1__item0(pos)?;
        pos = item0.pos;
        result.append_a(item0.result);
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_item(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Item>>> {
        if let Some(alt0) = self.parse_item__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        if let Some(alt1) = self.parse_item__alt1(pos) {
            return Some(ApplyResult { pos: alt1.pos, result: Shared::new(alt1.result) });
        }
        None
    }

    pub fn apply__parse__trivia(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Trivia>>> {
        apply(self, 5u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse__trivia, Self::parse__trivia)
    }

    fn parse__trivia__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_regex(pos, 1)
    }

    fn parse__trivia__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Trivia>> {
        let span_start = pos;
        let mut result = cst::Trivia::new(Span::unknown());
        let item0 = self.parse__trivia__alt0__item0(pos)?;
        pos = item0.pos;
        result.append_content(item0.result);
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse__trivia(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Trivia>>> {
        if let Some(alt0) = self.parse__trivia__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

}
#[cfg(test)]
mod generated_regex_tests {
    #[test]
    fn all_regex_patterns_compile() {
        for pat in super::REGEX_PATTERNS.iter() {
            if let Err(e) = fltk_parser_core::regex_automata::meta::Regex::new(pat) {
                panic!("grammar regex {pat:?} is not supported by regex_automata::meta::Regex: {e}");
            }
        }
    }
}

#[cfg(feature = "python")]
mod python_bindings {
    use pyo3::exceptions::{PyRecursionError, PyValueError};
    use pyo3::prelude::*;
    use super::cst;
    use super::Parser;

    #[pyclass(frozen, name = "ApplyResult")]
    pub struct PyApplyResult {
        pos: i64,
        result: Py<PyAny>,
    }

    #[pymethods]
    impl PyApplyResult {
        #[getter]
        fn pos(&self) -> i64 { self.pos }
        #[getter]
        fn result(&self, py: Python<'_>) -> Py<PyAny> { self.result.clone_ref(py) }
    }

    /// Recursive-descent parser with a configurable rule-application depth limit.
    ///
    /// Rule-application depth is bounded by `max_depth` (default
    /// `fltk_parser_core::DEFAULT_MAX_DEPTH`). Exceeding the limit raises `RecursionError`
    /// instead of overflowing the native stack. A `Parser` instance that has raised
    /// `RecursionError` is spent; construct a fresh one.
    #[pyclass(name = "Parser")]
    pub struct PyParser {
        inner: Parser,
    }

    impl PyParser {
        fn check_pos(&self, pos: i64) -> PyResult<()> {
            let len = self.inner.terminals().len();
            if pos < 0 || pos > len {
                return Err(PyValueError::new_err(format!(
                    "pos {pos} out of range for input of length {len}"
                )));
            }
            Ok(())
        }
    }

    #[pymethods]
    impl PyParser {
        #[new]
        #[pyo3(signature = (text, filename = None, capture_trivia = false, max_depth = None))]
        fn new(text: &str, filename: Option<&str>, capture_trivia: bool, max_depth: Option<u32>) -> Self {
            let mut inner = Parser::new(text, filename, capture_trivia);
            if let Some(d) = max_depth {
                inner.set_max_depth(d);
            }
            PyParser { inner }
        }

        #[getter]
        fn capture_trivia(&self) -> bool { self.inner.capture_trivia() }

        #[getter]
        fn rule_names(&self) -> Vec<&'static str> { self.inner.rule_names().to_vec() }

        #[getter]
        fn max_depth(&self) -> u32 { self.inner.max_depth() }

        #[getter]
        fn depth_exceeded(&self) -> bool { self.inner.depth_exceeded() }

        fn error_message(&self) -> String { self.inner.error_message() }

        fn error_position(&self) -> Option<i64> { self.inner.error_position() }
        fn apply__parse_root(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_root(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyRoot::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_name(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_name(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyName::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_parser(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_parser(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyParser::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_apply_result(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_apply_result(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyApplyResult::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_item(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_item(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyItem::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse__trivia(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse__trivia(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyTrivia::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }
    }

    pub fn register_classes(module: &Bound<'_, pyo3::types::PyModule>) -> PyResult<()> {
        module.add_class::<PyApplyResult>()?;
        module.add_class::<PyParser>()?;
        Ok(())
    }
}
#[cfg(feature = "python")]
pub use python_bindings::register_classes;
