//! Generated by fltk gen-rust-parser from `fltk/fegen/test_data/rust_parser_fixture.fltkg`. Do not edit.
//! **Stack depth note**: this parser is recursive-descent. Rule-application depth is
//! bounded by `max_depth` (default `fltk_parser_core::DEFAULT_MAX_DEPTH`, configurable
//! via `Parser::set_max_depth`). Exceeding it fails the parse with
//! `Parser::depth_exceeded()` set (Python bindings raise `RecursionError`) rather than
//! overflowing the native stack. **The default limit is sized for an ~8 MiB stack and
//! ~5-7 native frames per rule application.** Callers on smaller thread stacks (Rust
//! spawned threads use 2 MiB; async-runtime worker threads vary) or with grammars
//! that have deep per-rule call structure must lower `max_depth` proportionally or
//! size the stack accordingly. Check `depth_exceeded()` after parsing; a result
//! produced with the flag set must be discarded.
// Allow double-underscore names used in generated parse function paths.
#![allow(non_snake_case)]

use std::sync::OnceLock;
use fltk_parser_core::regex::Regex;

use fltk_cst_core::{Shared, SourceText, Span};
use fltk_parser_core::{apply, ApplyResult, Cache, ErrorTracker, PackratState, TerminalSource};

use super::cst;

pub const RULE_NAMES: [&str; 21] = ["num", "name", "atom", "paren_expr", "stmt", "items", "opt_item", "zero_items", "expr", "lval", "rval", "arrow", "latin_word", "tagged", "val", "leading_ws", "grouped", "rec_via_sub", "nest", "nest_sum", "_trivia"];

const REGEX_PATTERNS: [&str; 5] = ["[0-9]+", "[a-z]+", "[À-ÿ]+", "[!@#$]+", "[\\s]+"];
static REGEX_CELLS: [OnceLock<Regex>; 5] = [OnceLock::new(), OnceLock::new(), OnceLock::new(), OnceLock::new(), OnceLock::new()];

fn regex_at(idx: usize) -> &'static Regex {
    REGEX_CELLS[idx].get_or_init(|| {
        Regex::new(REGEX_PATTERNS[idx])
            .unwrap_or_else(|e| panic!("invalid regex pattern {:?}: {e}", REGEX_PATTERNS[idx]))
    })
}

pub struct Parser {
    terminals: TerminalSource,
    packrat: PackratState,
    error_tracker: ErrorTracker,
    capture_trivia: bool,
    cache__parse_num: Cache<Shared<cst::Num>>,
    cache__parse_name: Cache<Shared<cst::Name>>,
    cache__parse_atom: Cache<Shared<cst::Atom>>,
    cache__parse_paren_expr: Cache<Shared<cst::ParenExpr>>,
    cache__parse_stmt: Cache<Shared<cst::Stmt>>,
    cache__parse_items: Cache<Shared<cst::Items>>,
    cache__parse_opt_item: Cache<Shared<cst::OptItem>>,
    cache__parse_zero_items: Cache<Shared<cst::ZeroItems>>,
    cache__parse_expr: Cache<Shared<cst::Expr>>,
    cache__parse_lval: Cache<Shared<cst::Lval>>,
    cache__parse_rval: Cache<Shared<cst::Rval>>,
    cache__parse_arrow: Cache<Shared<cst::Arrow>>,
    cache__parse_latin_word: Cache<Shared<cst::LatinWord>>,
    cache__parse_tagged: Cache<Shared<cst::Tagged>>,
    cache__parse_val: Cache<Shared<cst::Val>>,
    cache__parse_leading_ws: Cache<Shared<cst::LeadingWs>>,
    cache__parse_grouped: Cache<Shared<cst::Grouped>>,
    cache__parse_rec_via_sub: Cache<Shared<cst::RecViaSub>>,
    cache__parse_nest: Cache<Shared<cst::Nest>>,
    cache__parse_nest_sum: Cache<Shared<cst::NestSum>>,
    cache__parse__trivia: Cache<Shared<cst::Trivia>>,
}

impl Parser {
    pub fn new(text: &str, capture_trivia: bool) -> Self {
        Self::from_source_text(SourceText::from_str(text), capture_trivia)
    }

    pub fn from_source_text(source: SourceText, capture_trivia: bool) -> Self {
        let terminals = TerminalSource::from_source_text(source);
        Self {
            terminals,
            packrat: PackratState::default(),
            error_tracker: ErrorTracker::default(),
            capture_trivia,
            cache__parse_num: Cache::new(),
            cache__parse_name: Cache::new(),
            cache__parse_atom: Cache::new(),
            cache__parse_paren_expr: Cache::new(),
            cache__parse_stmt: Cache::new(),
            cache__parse_items: Cache::new(),
            cache__parse_opt_item: Cache::new(),
            cache__parse_zero_items: Cache::new(),
            cache__parse_expr: Cache::new(),
            cache__parse_lval: Cache::new(),
            cache__parse_rval: Cache::new(),
            cache__parse_arrow: Cache::new(),
            cache__parse_latin_word: Cache::new(),
            cache__parse_tagged: Cache::new(),
            cache__parse_val: Cache::new(),
            cache__parse_leading_ws: Cache::new(),
            cache__parse_grouped: Cache::new(),
            cache__parse_rec_via_sub: Cache::new(),
            cache__parse_nest: Cache::new(),
            cache__parse_nest_sum: Cache::new(),
            cache__parse__trivia: Cache::new(),
        }
    }

    pub fn terminals(&self) -> &TerminalSource { &self.terminals }
    pub fn capture_trivia(&self) -> bool { self.capture_trivia }
    pub fn rule_names(&self) -> &'static [&'static str] { &RULE_NAMES }

    /// Return a human-readable parse error message.
    ///
    /// If `depth_exceeded()` is true, returns a depth-limit diagnostic instead of
    /// the normal longest-match error — the error tracker state is unreliable when
    /// depth was exceeded.
    pub fn error_message(&self) -> String {
        if self.packrat.depth_exceeded() {
            return format!("parse aborted: depth limit exceeded (max_depth = {})", self.packrat.max_depth());
        }
        fltk_parser_core::format_error_message(&self.error_tracker, &self.terminals, &RULE_NAMES)
    }

    pub fn error_position(&self) -> Option<i64> {
        (self.error_tracker.longest_parse_len >= 0).then_some(self.error_tracker.longest_parse_len)
    }

    /// Set the maximum rule-application depth before the parse fails with the
    /// depth-exceeded flag. Call before parsing.
    /// Default: `fltk_parser_core::DEFAULT_MAX_DEPTH`.
    pub fn set_max_depth(&mut self, max_depth: u32) { self.packrat.set_max_depth(max_depth); }

    /// Return the current maximum rule-application depth limit.
    pub fn max_depth(&self) -> u32 { self.packrat.max_depth() }

    /// Return true if the depth limit was exceeded during parsing.
    ///
    /// When true, the parse result (even if `Some`) must be discarded — it may be
    /// a partial or wrong parse. This instance is spent; construct a fresh `Parser`.
    pub fn depth_exceeded(&self) -> bool { self.packrat.depth_exceeded() }

    fn consume_literal(&mut self, pos: i64, literal: &'static str) -> Option<ApplyResult<Span>> {
        if let Some(span) = self.terminals.consume_literal(pos, literal) {
            return Some(ApplyResult { pos: span.end(), result: span });
        }
        let rule_id = *self.packrat.invocation_stack.last()
            .expect("consume_literal called outside apply__* frame");
        self.error_tracker.fail_literal(pos, rule_id, literal);
        None
    }

    fn consume_regex(&mut self, pos: i64, regex_idx: usize) -> Option<ApplyResult<Span>> {
        if let Some(span) = self.terminals.consume_regex(pos, regex_at(regex_idx)) {
            return Some(ApplyResult { pos: span.end(), result: span });
        }
        let rule_id = *self.packrat.invocation_stack.last()
            .expect("consume_regex called outside apply__* frame");
        self.error_tracker.fail_regex(pos, rule_id, REGEX_PATTERNS[regex_idx]);
        None
    }

    pub fn apply__parse_num(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Num>>> {
        apply(self, 0u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_num, Self::parse_num)
    }

    fn parse_num__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_regex(pos, 0)
    }

    fn parse_num__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Num>> {
        let span_start = pos;
        let mut result = cst::Num::new(Span::unknown());
        if let Some(item0) = self.parse_num__alt0__item0(pos) {
            pos = item0.pos;
            result.append_value(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_num(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Num>>> {
        if let Some(alt0) = self.parse_num__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_name(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Name>>> {
        apply(self, 1u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_name, Self::parse_name)
    }

    fn parse_name__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_regex(pos, 1)
    }

    fn parse_name__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Name>> {
        let span_start = pos;
        let mut result = cst::Name::new(Span::unknown());
        if let Some(item0) = self.parse_name__alt0__item0(pos) {
            pos = item0.pos;
            result.append_value(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_name(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Name>>> {
        if let Some(alt0) = self.parse_name__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_atom(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Atom>>> {
        apply(self, 2u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_atom, Self::parse_atom)
    }

    fn parse_atom__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Num>>> {
        self.apply__parse_num(pos)
    }

    fn parse_atom__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Atom>> {
        let span_start = pos;
        let mut result = cst::Atom::new(Span::unknown());
        if let Some(item0) = self.parse_atom__alt0__item0(pos) {
            pos = item0.pos;
            result.append_num(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_atom__alt1__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Name>>> {
        self.apply__parse_name(pos)
    }

    fn parse_atom__alt1(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Atom>> {
        let span_start = pos;
        let mut result = cst::Atom::new(Span::unknown());
        if let Some(item0) = self.parse_atom__alt1__item0(pos) {
            pos = item0.pos;
            result.append_name(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_atom(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Atom>>> {
        if let Some(alt0) = self.parse_atom__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        if let Some(alt1) = self.parse_atom__alt1(pos) {
            return Some(ApplyResult { pos: alt1.pos, result: Shared::new(alt1.result) });
        }
        None
    }

    pub fn apply__parse_paren_expr(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::ParenExpr>>> {
        apply(self, 3u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_paren_expr, Self::parse_paren_expr)
    }

    fn parse_paren_expr__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "(")
    }

    fn parse_paren_expr__alt0__item1(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Atom>>> {
        self.apply__parse_atom(pos)
    }

    fn parse_paren_expr__alt0__item2(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, ")")
    }

    fn parse_paren_expr__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::ParenExpr>> {
        let span_start = pos;
        let mut result = cst::ParenExpr::new(Span::unknown());
        if let Some(item0) = self.parse_paren_expr__alt0__item0(pos) {
            pos = item0.pos;
        } else {
            return None;
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::ParenExprChild::Trivia(ws.result));
            }
        }
        if let Some(item1) = self.parse_paren_expr__alt0__item1(pos) {
            pos = item1.pos;
            result.append_inner(item1.result);
        } else {
            return None;
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::ParenExprChild::Trivia(ws.result));
            }
        }
        if let Some(item2) = self.parse_paren_expr__alt0__item2(pos) {
            pos = item2.pos;
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_paren_expr(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::ParenExpr>>> {
        if let Some(alt0) = self.parse_paren_expr__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_stmt(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Stmt>>> {
        apply(self, 4u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_stmt, Self::parse_stmt)
    }

    fn parse_stmt__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Atom>>> {
        self.apply__parse_atom(pos)
    }

    fn parse_stmt__alt0__item1(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "=")
    }

    fn parse_stmt__alt0__item2(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Atom>>> {
        self.apply__parse_atom(pos)
    }

    fn parse_stmt__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Stmt>> {
        let span_start = pos;
        let mut result = cst::Stmt::new(Span::unknown());
        if let Some(item0) = self.parse_stmt__alt0__item0(pos) {
            pos = item0.pos;
            result.append_lhs(item0.result);
        } else {
            return None;
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::StmtChild::Trivia(ws.result));
            }
        } else {
            return None;
        }
        if let Some(item1) = self.parse_stmt__alt0__item1(pos) {
            pos = item1.pos;
        } else {
            return None;
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::StmtChild::Trivia(ws.result));
            }
        } else {
            return None;
        }
        if let Some(item2) = self.parse_stmt__alt0__item2(pos) {
            pos = item2.pos;
            result.append_rhs(item2.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_stmt(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Stmt>>> {
        if let Some(alt0) = self.parse_stmt__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_items(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Items>>> {
        apply(self, 5u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_items, Self::parse_items)
    }

    fn parse_items__alt0__item0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Items>> {
        let span_start = pos;
        let mut result = cst::Items::new(Span::unknown());
        while let Some(one_result) = {
            self.apply__parse_atom(pos)
        } {
            pos = one_result.pos;
            result.append_item(one_result.result);
        }
        if pos == span_start {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_items__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Items>> {
        let span_start = pos;
        let mut result = cst::Items::new(Span::unknown());
        if let Some(item0) = self.parse_items__alt0__item0(pos) {
            pos = item0.pos;
            result.extend_children(&item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_items(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Items>>> {
        if let Some(alt0) = self.parse_items__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_opt_item(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::OptItem>>> {
        apply(self, 6u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_opt_item, Self::parse_opt_item)
    }

    fn parse_opt_item__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Atom>>> {
        self.apply__parse_atom(pos)
    }

    fn parse_opt_item__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::OptItem>> {
        let span_start = pos;
        let mut result = cst::OptItem::new(Span::unknown());
        if let Some(item0) = self.parse_opt_item__alt0__item0(pos) {
            pos = item0.pos;
            result.append_item(item0.result);
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_opt_item(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::OptItem>>> {
        if let Some(alt0) = self.parse_opt_item__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_zero_items(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::ZeroItems>>> {
        apply(self, 7u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_zero_items, Self::parse_zero_items)
    }

    fn parse_zero_items__alt0__item0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::ZeroItems>> {
        let span_start = pos;
        let mut result = cst::ZeroItems::new(Span::unknown());
        while let Some(one_result) = {
            self.apply__parse_atom(pos)
        } {
            pos = one_result.pos;
            result.append_item(one_result.result);
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_zero_items__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::ZeroItems>> {
        let span_start = pos;
        let mut result = cst::ZeroItems::new(Span::unknown());
        if let Some(item0) = self.parse_zero_items__alt0__item0(pos) {
            pos = item0.pos;
            result.extend_children(&item0.result);
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_zero_items(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::ZeroItems>>> {
        if let Some(alt0) = self.parse_zero_items__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_expr(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Expr>>> {
        apply(self, 8u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_expr, Self::parse_expr)
    }

    fn parse_expr__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Expr>>> {
        self.apply__parse_expr(pos)
    }

    fn parse_expr__alt0__item1(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "+")
    }

    fn parse_expr__alt0__item2(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Atom>>> {
        self.apply__parse_atom(pos)
    }

    fn parse_expr__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Expr>> {
        let span_start = pos;
        let mut result = cst::Expr::new(Span::unknown());
        if let Some(item0) = self.parse_expr__alt0__item0(pos) {
            pos = item0.pos;
            result.append_lhs(item0.result);
        } else {
            return None;
        }
        if let Some(item1) = self.parse_expr__alt0__item1(pos) {
            pos = item1.pos;
        } else {
            return None;
        }
        if let Some(item2) = self.parse_expr__alt0__item2(pos) {
            pos = item2.pos;
            result.append_rhs(item2.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_expr__alt1__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Atom>>> {
        self.apply__parse_atom(pos)
    }

    fn parse_expr__alt1(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Expr>> {
        let span_start = pos;
        let mut result = cst::Expr::new(Span::unknown());
        if let Some(item0) = self.parse_expr__alt1__item0(pos) {
            pos = item0.pos;
            result.append_atom(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_expr(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Expr>>> {
        if let Some(alt0) = self.parse_expr__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        if let Some(alt1) = self.parse_expr__alt1(pos) {
            return Some(ApplyResult { pos: alt1.pos, result: Shared::new(alt1.result) });
        }
        None
    }

    pub fn apply__parse_lval(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Lval>>> {
        apply(self, 9u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_lval, Self::parse_lval)
    }

    fn parse_lval__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Rval>>> {
        self.apply__parse_rval(pos)
    }

    fn parse_lval__alt0__item1(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "!")
    }

    fn parse_lval__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Lval>> {
        let span_start = pos;
        let mut result = cst::Lval::new(Span::unknown());
        if let Some(item0) = self.parse_lval__alt0__item0(pos) {
            pos = item0.pos;
            result.append_inner(item0.result);
        } else {
            return None;
        }
        if let Some(item1) = self.parse_lval__alt0__item1(pos) {
            pos = item1.pos;
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_lval__alt1__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Name>>> {
        self.apply__parse_name(pos)
    }

    fn parse_lval__alt1(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Lval>> {
        let span_start = pos;
        let mut result = cst::Lval::new(Span::unknown());
        if let Some(item0) = self.parse_lval__alt1__item0(pos) {
            pos = item0.pos;
            result.append_base(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_lval(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Lval>>> {
        if let Some(alt0) = self.parse_lval__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        if let Some(alt1) = self.parse_lval__alt1(pos) {
            return Some(ApplyResult { pos: alt1.pos, result: Shared::new(alt1.result) });
        }
        None
    }

    pub fn apply__parse_rval(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Rval>>> {
        apply(self, 10u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_rval, Self::parse_rval)
    }

    fn parse_rval__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Lval>>> {
        self.apply__parse_lval(pos)
    }

    fn parse_rval__alt0__item1(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "?")
    }

    fn parse_rval__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Rval>> {
        let span_start = pos;
        let mut result = cst::Rval::new(Span::unknown());
        if let Some(item0) = self.parse_rval__alt0__item0(pos) {
            pos = item0.pos;
            result.append_inner(item0.result);
        } else {
            return None;
        }
        if let Some(item1) = self.parse_rval__alt0__item1(pos) {
            pos = item1.pos;
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_rval__alt1__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Num>>> {
        self.apply__parse_num(pos)
    }

    fn parse_rval__alt1(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Rval>> {
        let span_start = pos;
        let mut result = cst::Rval::new(Span::unknown());
        if let Some(item0) = self.parse_rval__alt1__item0(pos) {
            pos = item0.pos;
            result.append_base(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_rval(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Rval>>> {
        if let Some(alt0) = self.parse_rval__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        if let Some(alt1) = self.parse_rval__alt1(pos) {
            return Some(ApplyResult { pos: alt1.pos, result: Shared::new(alt1.result) });
        }
        None
    }

    pub fn apply__parse_arrow(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Arrow>>> {
        apply(self, 11u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_arrow, Self::parse_arrow)
    }

    fn parse_arrow__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "→")
    }

    fn parse_arrow__alt0__item1(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Name>>> {
        self.apply__parse_name(pos)
    }

    fn parse_arrow__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Arrow>> {
        let span_start = pos;
        let mut result = cst::Arrow::new(Span::unknown());
        if let Some(item0) = self.parse_arrow__alt0__item0(pos) {
            pos = item0.pos;
        } else {
            return None;
        }
        if let Some(item1) = self.parse_arrow__alt0__item1(pos) {
            pos = item1.pos;
            result.append_target(item1.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_arrow(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Arrow>>> {
        if let Some(alt0) = self.parse_arrow__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_latin_word(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::LatinWord>>> {
        apply(self, 12u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_latin_word, Self::parse_latin_word)
    }

    fn parse_latin_word__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_regex(pos, 2)
    }

    fn parse_latin_word__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::LatinWord>> {
        let span_start = pos;
        let mut result = cst::LatinWord::new(Span::unknown());
        if let Some(item0) = self.parse_latin_word__alt0__item0(pos) {
            pos = item0.pos;
            result.append_value(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_latin_word(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::LatinWord>>> {
        if let Some(alt0) = self.parse_latin_word__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_tagged(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Tagged>>> {
        apply(self, 13u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_tagged, Self::parse_tagged)
    }

    fn parse_tagged__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "tag")
    }

    fn parse_tagged__alt0__item1(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_regex(pos, 1)
    }

    fn parse_tagged__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Tagged>> {
        let span_start = pos;
        let mut result = cst::Tagged::new(Span::unknown());
        if let Some(item0) = self.parse_tagged__alt0__item0(pos) {
            pos = item0.pos;
            result.push_child(None, cst::TaggedChild::Span(item0.result));
        } else {
            return None;
        }
        if let Some(item1) = self.parse_tagged__alt0__item1(pos) {
            pos = item1.pos;
            result.append_value(item1.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_tagged(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Tagged>>> {
        if let Some(alt0) = self.parse_tagged__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_val(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Val>>> {
        apply(self, 14u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_val, Self::parse_val)
    }

    fn parse_val__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Num>>> {
        self.apply__parse_num(pos)
    }

    fn parse_val__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Val>> {
        let span_start = pos;
        let mut result = cst::Val::new(Span::unknown());
        if let Some(item0) = self.parse_val__alt0__item0(pos) {
            pos = item0.pos;
            result.append_item(cst::ValChild::Num(item0.result));
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_val__alt1__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Name>>> {
        self.apply__parse_name(pos)
    }

    fn parse_val__alt1(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Val>> {
        let span_start = pos;
        let mut result = cst::Val::new(Span::unknown());
        if let Some(item0) = self.parse_val__alt1__item0(pos) {
            pos = item0.pos;
            result.append_item(cst::ValChild::Name(item0.result));
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_val__alt2__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_regex(pos, 3)
    }

    fn parse_val__alt2(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Val>> {
        let span_start = pos;
        let mut result = cst::Val::new(Span::unknown());
        if let Some(item0) = self.parse_val__alt2__item0(pos) {
            pos = item0.pos;
            result.append_item(cst::ValChild::Span(item0.result));
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_val(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Val>>> {
        if let Some(alt0) = self.parse_val__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        if let Some(alt1) = self.parse_val__alt1(pos) {
            return Some(ApplyResult { pos: alt1.pos, result: Shared::new(alt1.result) });
        }
        if let Some(alt2) = self.parse_val__alt2(pos) {
            return Some(ApplyResult { pos: alt2.pos, result: Shared::new(alt2.result) });
        }
        None
    }

    pub fn apply__parse_leading_ws(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::LeadingWs>>> {
        apply(self, 15u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_leading_ws, Self::parse_leading_ws)
    }

    fn parse_leading_ws__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Num>>> {
        self.apply__parse_num(pos)
    }

    fn parse_leading_ws__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::LeadingWs>> {
        let span_start = pos;
        let mut result = cst::LeadingWs::new(Span::unknown());
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::LeadingWsChild::Trivia(ws.result));
            }
        }
        if let Some(item0) = self.parse_leading_ws__alt0__item0(pos) {
            pos = item0.pos;
            result.append_num(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_leading_ws(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::LeadingWs>>> {
        if let Some(alt0) = self.parse_leading_ws__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_grouped(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Grouped>>> {
        apply(self, 16u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_grouped, Self::parse_grouped)
    }

    fn parse_grouped__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "(")
    }

    fn parse_grouped__alt0__item1__alts__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Num>>> {
        self.apply__parse_num(pos)
    }

    fn parse_grouped__alt0__item1__alts__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Grouped>> {
        let span_start = pos;
        let mut result = cst::Grouped::new(Span::unknown());
        if let Some(item0) = self.parse_grouped__alt0__item1__alts__alt0__item0(pos) {
            pos = item0.pos;
            result.append_left(cst::GroupedChild::Num(item0.result));
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_grouped__alt0__item1__alts__alt1__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Name>>> {
        self.apply__parse_name(pos)
    }

    fn parse_grouped__alt0__item1__alts__alt1(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Grouped>> {
        let span_start = pos;
        let mut result = cst::Grouped::new(Span::unknown());
        if let Some(item0) = self.parse_grouped__alt0__item1__alts__alt1__item0(pos) {
            pos = item0.pos;
            result.append_left(cst::GroupedChild::Name(item0.result));
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_grouped__alt0__item1__alts(&mut self, pos: i64) -> Option<ApplyResult<cst::Grouped>> {
        if let Some(r) = self.parse_grouped__alt0__item1__alts__alt0(pos) {
            return Some(r);
        }
        if let Some(r) = self.parse_grouped__alt0__item1__alts__alt1(pos) {
            return Some(r);
        }
        None
    }

    fn parse_grouped__alt0__item1(&mut self, pos: i64) -> Option<ApplyResult<cst::Grouped>> {
        self.parse_grouped__alt0__item1__alts(pos)
    }

    fn parse_grouped__alt0__item2(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, ")")
    }

    fn parse_grouped__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Grouped>> {
        let span_start = pos;
        let mut result = cst::Grouped::new(Span::unknown());
        if let Some(item0) = self.parse_grouped__alt0__item0(pos) {
            pos = item0.pos;
        } else {
            return None;
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::GroupedChild::Trivia(ws.result));
            }
        }
        if let Some(item1) = self.parse_grouped__alt0__item1(pos) {
            pos = item1.pos;
            result.extend_children(&item1.result);
        } else {
            return None;
        }
        if let Some(ws) = self.apply__parse__trivia(pos) {
            pos = ws.pos;
            if self.capture_trivia {
                result.push_child(None, cst::GroupedChild::Trivia(ws.result));
            }
        }
        if let Some(item2) = self.parse_grouped__alt0__item2(pos) {
            pos = item2.pos;
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_grouped(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Grouped>>> {
        if let Some(alt0) = self.parse_grouped__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_rec_via_sub(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::RecViaSub>>> {
        apply(self, 17u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_rec_via_sub, Self::parse_rec_via_sub)
    }

    fn parse_rec_via_sub__alt0__item0__alts__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::RecViaSub>>> {
        self.apply__parse_rec_via_sub(pos)
    }

    fn parse_rec_via_sub__alt0__item0__alts__alt0__item1(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "+")
    }

    fn parse_rec_via_sub__alt0__item0__alts__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::RecViaSub>> {
        let span_start = pos;
        let mut result = cst::RecViaSub::new(Span::unknown());
        if let Some(item0) = self.parse_rec_via_sub__alt0__item0__alts__alt0__item0(pos) {
            pos = item0.pos;
            result.append_inner(cst::RecViaSubChild::RecViaSub(item0.result));
        } else {
            return None;
        }
        if let Some(item1) = self.parse_rec_via_sub__alt0__item0__alts__alt0__item1(pos) {
            pos = item1.pos;
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_rec_via_sub__alt0__item0__alts__alt1__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Atom>>> {
        self.apply__parse_atom(pos)
    }

    fn parse_rec_via_sub__alt0__item0__alts__alt1(&mut self, mut pos: i64) -> Option<ApplyResult<cst::RecViaSub>> {
        let span_start = pos;
        let mut result = cst::RecViaSub::new(Span::unknown());
        if let Some(item0) = self.parse_rec_via_sub__alt0__item0__alts__alt1__item0(pos) {
            pos = item0.pos;
            result.append_inner(cst::RecViaSubChild::Atom(item0.result));
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_rec_via_sub__alt0__item0__alts(&mut self, pos: i64) -> Option<ApplyResult<cst::RecViaSub>> {
        if let Some(r) = self.parse_rec_via_sub__alt0__item0__alts__alt0(pos) {
            return Some(r);
        }
        if let Some(r) = self.parse_rec_via_sub__alt0__item0__alts__alt1(pos) {
            return Some(r);
        }
        None
    }

    fn parse_rec_via_sub__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<cst::RecViaSub>> {
        self.parse_rec_via_sub__alt0__item0__alts(pos)
    }

    fn parse_rec_via_sub__alt0__item1(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Name>>> {
        self.apply__parse_name(pos)
    }

    fn parse_rec_via_sub__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::RecViaSub>> {
        let span_start = pos;
        let mut result = cst::RecViaSub::new(Span::unknown());
        if let Some(item0) = self.parse_rec_via_sub__alt0__item0(pos) {
            pos = item0.pos;
            result.extend_children(&item0.result);
        } else {
            return None;
        }
        if let Some(item1) = self.parse_rec_via_sub__alt0__item1(pos) {
            pos = item1.pos;
            result.append_suffix(item1.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_rec_via_sub(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::RecViaSub>>> {
        if let Some(alt0) = self.parse_rec_via_sub__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

    pub fn apply__parse_nest(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Nest>>> {
        apply(self, 18u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_nest, Self::parse_nest)
    }

    fn parse_nest__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "(")
    }

    fn parse_nest__alt0__item1(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Nest>>> {
        self.apply__parse_nest(pos)
    }

    fn parse_nest__alt0__item2(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, ")")
    }

    fn parse_nest__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Nest>> {
        let span_start = pos;
        let mut result = cst::Nest::new(Span::unknown());
        if let Some(item0) = self.parse_nest__alt0__item0(pos) {
            pos = item0.pos;
        } else {
            return None;
        }
        if let Some(item1) = self.parse_nest__alt0__item1(pos) {
            pos = item1.pos;
            result.append_inner(item1.result);
        } else {
            return None;
        }
        if let Some(item2) = self.parse_nest__alt0__item2(pos) {
            pos = item2.pos;
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_nest__alt1__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Num>>> {
        self.apply__parse_num(pos)
    }

    fn parse_nest__alt1(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Nest>> {
        let span_start = pos;
        let mut result = cst::Nest::new(Span::unknown());
        if let Some(item0) = self.parse_nest__alt1__item0(pos) {
            pos = item0.pos;
            result.append_leaf(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_nest(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Nest>>> {
        if let Some(alt0) = self.parse_nest__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        if let Some(alt1) = self.parse_nest__alt1(pos) {
            return Some(ApplyResult { pos: alt1.pos, result: Shared::new(alt1.result) });
        }
        None
    }

    pub fn apply__parse_nest_sum(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::NestSum>>> {
        apply(self, 19u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse_nest_sum, Self::parse_nest_sum)
    }

    fn parse_nest_sum__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::NestSum>>> {
        self.apply__parse_nest_sum(pos)
    }

    fn parse_nest_sum__alt0__item1(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_literal(pos, "+")
    }

    fn parse_nest_sum__alt0__item2(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Nest>>> {
        self.apply__parse_nest(pos)
    }

    fn parse_nest_sum__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::NestSum>> {
        let span_start = pos;
        let mut result = cst::NestSum::new(Span::unknown());
        if let Some(item0) = self.parse_nest_sum__alt0__item0(pos) {
            pos = item0.pos;
            result.append_lhs(item0.result);
        } else {
            return None;
        }
        if let Some(item1) = self.parse_nest_sum__alt0__item1(pos) {
            pos = item1.pos;
        } else {
            return None;
        }
        if let Some(item2) = self.parse_nest_sum__alt0__item2(pos) {
            pos = item2.pos;
            result.append_rhs(item2.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_nest_sum__alt1__item0(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Nest>>> {
        self.apply__parse_nest(pos)
    }

    fn parse_nest_sum__alt1(&mut self, mut pos: i64) -> Option<ApplyResult<cst::NestSum>> {
        let span_start = pos;
        let mut result = cst::NestSum::new(Span::unknown());
        if let Some(item0) = self.parse_nest_sum__alt1__item0(pos) {
            pos = item0.pos;
            result.append_first(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse_nest_sum(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::NestSum>>> {
        if let Some(alt0) = self.parse_nest_sum__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        if let Some(alt1) = self.parse_nest_sum__alt1(pos) {
            return Some(ApplyResult { pos: alt1.pos, result: Shared::new(alt1.result) });
        }
        None
    }

    pub fn apply__parse__trivia(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Trivia>>> {
        apply(self, 20u32, pos, |p| &mut p.packrat, |p| &mut p.cache__parse__trivia, Self::parse__trivia)
    }

    fn parse__trivia__alt0__item0(&mut self, pos: i64) -> Option<ApplyResult<Span>> {
        self.consume_regex(pos, 4)
    }

    fn parse__trivia__alt0(&mut self, mut pos: i64) -> Option<ApplyResult<cst::Trivia>> {
        let span_start = pos;
        let mut result = cst::Trivia::new(Span::unknown());
        if let Some(item0) = self.parse__trivia__alt0__item0(pos) {
            pos = item0.pos;
            result.append_content(item0.result);
        } else {
            return None;
        }
        result.set_span(Span::new_with_source(span_start, pos, self.terminals.source_text()));
        Some(ApplyResult { pos, result })
    }

    fn parse__trivia(&mut self, pos: i64) -> Option<ApplyResult<Shared<cst::Trivia>>> {
        if let Some(alt0) = self.parse__trivia__alt0(pos) {
            return Some(ApplyResult { pos: alt0.pos, result: Shared::new(alt0.result) });
        }
        None
    }

}
#[cfg(test)]
mod generated_regex_tests {
    #[test]
    fn all_regex_patterns_compile() {
        for pat in super::REGEX_PATTERNS.iter() {
            if let Err(e) = fltk_parser_core::regex::Regex::new(pat) {
                panic!("grammar regex {pat:?} is not supported by the regex crate: {e}");
            }
        }
    }
}

#[cfg(feature = "python")]
mod python_bindings {
    use pyo3::exceptions::{PyRecursionError, PyValueError};
    use pyo3::prelude::*;
    use super::cst;
    use super::Parser;

    #[pyclass(frozen, name = "ApplyResult")]
    pub struct PyApplyResult {
        pos: i64,
        result: PyObject,
    }

    #[pymethods]
    impl PyApplyResult {
        #[getter]
        fn pos(&self) -> i64 { self.pos }
        #[getter]
        fn result(&self, py: Python<'_>) -> PyObject { self.result.clone_ref(py) }
    }

    /// Recursive-descent parser with a configurable rule-application depth limit.
    ///
    /// Rule-application depth is bounded by `max_depth` (default
    /// `fltk_parser_core::DEFAULT_MAX_DEPTH`). Exceeding the limit raises `RecursionError`
    /// instead of overflowing the native stack. A `Parser` instance that has raised
    /// `RecursionError` is spent; construct a fresh one.
    #[pyclass(name = "Parser")]
    pub struct PyParser {
        inner: Parser,
    }

    impl PyParser {
        fn check_pos(&self, pos: i64) -> PyResult<()> {
            let len = self.inner.terminals().len();
            if pos < 0 || pos > len {
                return Err(PyValueError::new_err(format!(
                    "pos {pos} out of range for input of length {len}"
                )));
            }
            Ok(())
        }
    }

    #[pymethods]
    impl PyParser {
        #[new]
        #[pyo3(signature = (text, capture_trivia = false, max_depth = None))]
        fn new(text: &str, capture_trivia: bool, max_depth: Option<u32>) -> Self {
            let mut inner = Parser::new(text, capture_trivia);
            if let Some(d) = max_depth {
                inner.set_max_depth(d);
            }
            PyParser { inner }
        }

        #[getter]
        fn capture_trivia(&self) -> bool { self.inner.capture_trivia() }

        #[getter]
        fn rule_names(&self) -> Vec<&'static str> { self.inner.rule_names().to_vec() }

        #[getter]
        fn max_depth(&self) -> u32 { self.inner.max_depth() }

        #[getter]
        fn depth_exceeded(&self) -> bool { self.inner.depth_exceeded() }

        fn error_message(&self) -> String { self.inner.error_message() }

        fn error_position(&self) -> Option<i64> { self.inner.error_position() }
        fn apply__parse_num(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_num(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyNum::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_name(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_name(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyName::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_atom(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_atom(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyAtom::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_paren_expr(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_paren_expr(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyParenExpr::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_stmt(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_stmt(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyStmt::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_items(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_items(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyItems::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_opt_item(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_opt_item(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyOptItem::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_zero_items(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_zero_items(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyZeroItems::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_expr(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_expr(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyExpr::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_lval(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_lval(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyLval::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_rval(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_rval(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyRval::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_arrow(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_arrow(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyArrow::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_latin_word(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_latin_word(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyLatinWord::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_tagged(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_tagged(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyTagged::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_val(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_val(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyVal::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_leading_ws(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_leading_ws(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyLeadingWs::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_grouped(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_grouped(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyGrouped::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_rec_via_sub(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_rec_via_sub(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyRecViaSub::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_nest(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_nest(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyNest::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse_nest_sum(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse_nest_sum(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyNestSum::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }

        fn apply__parse__trivia(&mut self, py: Python<'_>, pos: i64) -> PyResult<Option<PyApplyResult>> {
            self.check_pos(pos)?;
            let result = self.inner.apply__parse__trivia(pos);
            if self.inner.depth_exceeded() {
                return Err(PyRecursionError::new_err(format!(
                    "parse depth limit exceeded (max_depth = {})", self.inner.max_depth())));
            }
            match result {
                Some(r) => {
                    let handle = cst::PyTrivia::to_py_canonical(py, &r.result)?;
                    Ok(Some(PyApplyResult { pos: r.pos, result: handle.into_any() }))
                }
                None => Ok(None),
            }
        }
    }

    pub fn register_classes(module: &Bound<'_, PyModule>) -> PyResult<()> {
        module.add_class::<PyApplyResult>()?;
        module.add_class::<PyParser>()?;
        Ok(())
    }
}
#[cfg(feature = "python")]
pub use python_bindings::register_classes;
